### ISSUE TITLE
[Kafka] How should errors be dealt with when using input bindings in order to reliably consume messages?

### ISSUE THREAD

**Issue by gunniwho** [dapr/components-contrib#1006]
I'm looking at using the Kafka input binding for one of my projects at work. While I was playing around with it I realized that I would loose messages if my app experienced an error while handling the request from the dapr sidecar. I tried to return an error status code back to dapr and I also tried to just kill the app, hoping it would pick up that same message again once the pod was restarted. That however was not the case and the message was lost forever. So I'm wondering how in general this concern should be dealt with while using dapr input bindings? I can't seem to find anything about this in the docs...

**Comment by yaron2** [comment]
Transfered to components-contrib.

**Comment by artursouza** [comment]
@pkedy This issue is about bringing Kafka bindings at the same level as Kafka pubsub.

**Comment by artursouza** [comment]
The original scope is about making sure errors from app does not result in an Ack in Kafka input binding. We should keep scope limited to that until the resiliency work in sidecar brings retry as a first class experience in Dapr.

**Comment by artursouza** [comment]
#955 Should include this issue, so component can be GA-ed.

**Comment by yaron2** [comment]
Fixed by https://github.com/dapr/components-contrib/pull/1696
