### ISSUE TITLE
Add GitHub workflow to create conformance test resources for infrastructure as code

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [dapr/components-contrib#1007]
## Describe the proposal
Per [feedback](https://github.com/dapr/components-contrib/pull/1001#issuecomment-876894135) in #1001, it would be useful to add a GitHub workflow that can be triggered to automate the deployment of new resources needed by the conformance test workflow. This will help the project move in the direction of infrastructure as code instead of relying on manually created and maintained cloud resources that the test automation depends on. 

As a first cut, this issue is concerned with the deployment of the existing Azure resource components in use by the conformance test workflows today, although it is desirable for other tests using cloud services to provide similar automation as they are developed.

**Comment by artursouza** [comment]
I believe this should be a new workflow that runs independently of the tests, so the tests don't need to wait for resource provisioning and can rely on existing infrastructure.
