### ISSUE TITLE
How can we invoke service method in middleware code?

### ISSUE THREAD

**Issue by li1234yun** [dapr/components-contrib#1013]
Hello!
I want to write a invoke service middleware, but I do not know how to invoke service? Maybe I just call service method by url? Is there a convenient way to achieve this?

Thanks!

**Comment by daixiang0** [comment]
https://github.com/dapr/quickstarts/tree/master/middleware may help.

**Comment by li1234yun** [comment]
> https://github.com/dapr/quickstarts/tree/master/middleware may help.

Hello, thank you for your reply.
I have seen the sample, the sample is called by url, but I want to know how can I call service methon in middleware code.

I have added your qq friends. Maybe you can add me if you like.
