### ISSUE TITLE
Change redispipe package to go-redis for state management

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#103]
## Describe the proposal

The [go-redis](https://github.com/go-redis/redis) package is a common and highly used package for interacting with Redis for Go. It's used by Redis for Pub/Sub, while the Redis State Store uses [redispipe](https://github.com/joomcode/redispipe), which favors implicit pipelining but does not support things like TLS.

I propose to standardize on `go-redis` as the package for Redis interactions in components-contrib.

**Comment by amanbha** [comment]
Closing as its tracked by https://github.com/dapr/components-contrib/issues/213
