### ISSUE TITLE
Add RabbitMQ for Pub/Sub

### ISSUE THREAD

**Issue by lukekim** [dapr/components-contrib#105]
Support RabbitMQ as a Pub/Sub component.

**Comment by yaron2** [comment]
This is for pub/sub, right? (We have a RabbitMQ binding) - I suggest removing the word bindings from the title.

**Comment by fbeltrao** [comment]
Is anyone working on this already?
If not, I would love to contribute.

**Comment by markrussinovich** [comment]
I was planning on working on it this weekend, but if you want to take this, let me know.

**Comment by fbeltrao** [comment]
If you don't mind I would like to take it. It is a good first item for me to get familiar with the project internals.

**Comment by markrussinovich** [comment]
Okay, it's yours.

**Comment by amanbha** [comment]
https://github.com/dapr/components-contrib/tree/master/pubsub/rabbitmq
