### ISSUE TITLE
Add TTL Support For Couchbase Component

### ISSUE THREAD

**Issue by Admiralkheir** [dapr/components-contrib#1056]
Adding TTL support for couchbase will be useful for couchbase users like us. We are using couchbase as a state store on prod application.

TTL supported components : [Document](https://docs.dapr.io/reference/components-reference/supported-state-stores/)
Couchbase Expiration Using With Go : [Document1](https://docs.couchbase.com/go-sdk/1.6/document-operations.html#creatingdocuments) [Document2](https://docs.couchbase.com/go-sdk/current/howtos/kv-operations.html#cas)

**Comment by sedat-eyuboglu** [comment]
+1
CB is dependent component as state backend in our prod apps. And whenever we need ttl, we have to bypass dapr's BB and use native CB sdk. It is an unwanted case for us.

**Comment by sedat-eyuboglu** [comment]
> 
> 
> Adding TTL support for couchbase will be useful for couchbase users like us. We are using couchbase as a state store on prod application.
> 
> TTL supported components : [Document](https://docs.dapr.io/reference/components-reference/supported-state-stores/)
> Couchbase Expiration Using With Go : [Document1](https://docs.couchbase.com/go-sdk/1.6/document-operations.html#creatingdocuments) [Document2](https://docs.couchbase.com/go-sdk/current/howtos/kv-operations.html#cas)

Which dapr SDK do you use?

**Comment by Admiralkheir** [comment]
> 
> 
> > Adding TTL support for couchbase will be useful for couchbase users like us. We are using couchbase as a state store on prod application.
> > TTL supported components : [Document](https://docs.dapr.io/reference/components-reference/supported-state-stores/)
> > Couchbase Expiration Using With Go : [Document1](https://docs.couchbase.com/go-sdk/1.6/document-operations.html#creatingdocuments) [Document2](https://docs.couchbase.com/go-sdk/current/howtos/kv-operations.html#cas)
> 
> Which dapr SDK do you use?

We are using Dapr.AspNetCore Version="1.0.0"

**Comment by Admiralkheir** [comment]
Hi @yaron2 , Can you activate this issue again?
