### ISSUE TITLE
Update S3 binding

### ISSUE THREAD

**Issue by fjvela** [dapr/components-contrib#1080]
## Describe the feature
Update S3 binding:

- update create operation: support upload files in base64 (https://docs.dapr.io/reference/components-reference/supported-bindings/s3/#upload-a-file doesn't work), return location and version id 
- add get operation
- add delete operation
- add list operation

## Release Note

RELEASE NOTE:
- **UPDATE** S3 binding. Create operation: support upload files in base64, return location and version id 
- **ADD**  S3 binding: get operation
- **ADD**  S3 binding: delete operation
- **ADD**  S3 binding: list operation

**Comment by CodeMonkeyLeet** [comment]
@tanvigour @artursouza Target of opportunity for v1.4 release?

**Comment by tanvigour** [comment]
> @tanvigour @artursouza Target of opportunity for v1.4 release?

looks like there's already a PR for this, so yeah we can add it to 1.4

**Comment by tanvigour** [comment]
> > @tanvigour @artursouza Target of opportunity for v1.4 release?
> 
> looks like there's already a PR for this, so yeah we can add it to 1.4

I don't have rights to can @artursouza add it to 1.4?

**Comment by artursouza** [comment]
I made some small comments in the PR. For community contributions, we add to the milestone when it is about to be merged because we cannot predict when the PR will be merged.
