### ISSUE TITLE
SASL OAUTHBEARER support in Kafka binding

### ISSUE THREAD

**Issue by sthussey** [dapr/components-contrib#1084]
## Describe the feature
In enterprise settings, authentication - particularly federated authentication - is a requirement for shared platforms like a message queue or event stream such as Kafka. Dapr is a great tool-set for easing access to EDA, but is lacking in some enterprise-grade features like better support of federated authentication. I'm looking for interesting in adding support for federated authentication to Kafka specifically via an open-standard like OAuth2/OIDC via the SASL OAUTHBEARER protocol.

Currently the only path I see to using federated identity between Dapr and Kafka is either a custom listener in Kafka (which rules out using something like Strimzi easily) or using commercial Kafka that has LDAP for using with the SASL username/password. Since the underlying Sarama client supports OAUTHBEARER, the only addition would be generating a valid token in Dapr to pass along and correctly respond to token expiration by generating a new token. 

I could see two methods for this:
 - Make Dapr a OAuth2 client directly 
 - Allow the application to host a Dapr callback that would generate the token. This has the effect (benefit?) of allowing universal binding configuration, but allowing each client service to bring-their-own-identity.

## Release Note

RELEASE NOTE: **ADD** Support OAuth2 authentication with Kafka for pub/sub binding

**Comment by CodeMonkeyLeet** [comment]
@yaron2, any thoughts on this? Dapr has concessions for OAuth handling for service invocation via middleware, but doesn't extend to bindings. At the same time, there have been asks for more direct access to sarama supported auth scenarios (e.g. https://github.com/dapr/components-contrib/issues/349 for SSL, not OAuth) which may point to this being easier to manage on a per component basis.

**Comment by sthussey** [comment]
Just wanted to come back to this - I'd be happy to put together a PR with something in place if there is interest in merging it.

**Comment by yaron2** [comment]
@sthussey it'd be great if you can add this to the existing components. Re: general purpose, lets open a separate issue for that :)

**Comment by sthussey** [comment]
I'm working on the PR for this. First draft of code is finished, just need to take time to setup an integration environment to test it.

https://github.com/sthussey/components-contrib/tree/feat/kafka-oidc-support

**Comment by sthussey** [comment]
PR #1229 is still in progress.

**Comment by yaron2** [comment]
Reopened
