### ISSUE TITLE
Kafka endpoint for EventHub only works for bindings and not for pubsub

### ISSUE THREAD

**Issue by denniszielke** [dapr/components-contrib#1085]
## Expected Behavior

I created an EventHub namespace with Kafka support, created an eventhub.
When creating a kafka pubsub component I would expect it to load successfully.

## Actual Behavior

I am getting the following error message during startup

`FATA[0006] process component pubsub-important error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)  app_id=message-creator-node instance=box scope=dapr.runtime type=log ver=1.3.0`

```
If I change the same component to a kafka binding it loads successfully
INFO[0000] successful init for output binding binding-important (bindings.kafka/v1)  app_id=message-creator-node instance=box scope=dapr.runtime type=log ver=1.3.0
INFO[0001] successful init for input binding binding-important (bindings.kafka/v1)  app_id=message-creator-node instance=box scope=dapr.runtime type=log ver=1.3.0
INFO[0001] component loaded. name: binding-important, type: bindings.kafka/v1  app_id=message-creator-node instance=box scope=dapr.runtime type=log ver=1.3.0
```

## Steps to Reproduce the Problem

Create EventHub namespace with Kakfa enabled. 
Create eventhub on the namespace
Create binding component

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-important
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "demoeh.servicebus.windows.net:9093"
  - name: consumerGroup
    value: '$Default'
  - name: authRequired
    value: "true"
  - name: saslUsername
    value: '$ConnectionString'
  - name: saslPassword
    value: "Endpoint=sb:/EntityPath=important"
  - name: publishTopic
    value: important
  - name: topics
    value: important
```

It should work.

When creating the same component of type pubsub.kafka dapr returns an error.

Documentation seems to suggest that TLS needs to be enabled in config.Net.TLS.Enable and config.Net.TLS.Config is set to an instance of TLS Config. Can it be that pubsub and binding for kafka are using different configuration?

## Release Note

RELEASE NOTE:

**Comment by CodeMonkeyLeet** [comment]
@denniszielke The Dapr EventsHub pubsub component is being deprecated in favor of the binding only (see https://github.com/dapr/components-contrib/issues/951) because it has numerous issues integrating with the Dapr pubsub model such as topics handling, so this issue is probably not going to get a lot of traction.

**Comment by denniszielke** [comment]
@CodeMonkeyLeet, yes I understand that the native EventHub will be deprecated, but in this case I am using the Kafka protocol head for EventHub (so dapr does not know that I am using EventHub - it is interacting with the Kafka). My understanding is that the EventHub deprecation is due to EventHub behaviour.

**Comment by denniszielke** [comment]
My guess is that this issue is related to the handling of TLS in the Kafka pubsub component.

**Comment by CodeMonkeyLeet** [comment]
@denniszielke Sorry, got my wires crossed, I see what you mean now. The kafka bindings and pubsub component configurations are indeed different, see [pubsub](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/) vs. [bindings ](https://docs.dapr.io/reference/components-reference/supported-bindings/kafka/) component configurations. 

Semantically, the Dapr pubsub components also assume particular models, such as competing consumer, which may not be an ideal way to consume events from EventHub more generally (the efficiencies of the partitioned consumer model are only accessible through the EventHubs bindings today AFAIK)

Regarding the TLS config, both the bindings and kafka components enable the TLS config though (the `updateAuthInfo` code looks like a copy-and-paste job), so that might not be it. The fatal error doesn't look related to TLS either ...

**Comment by darren-wang** [comment]
> ## Expected Behavior
> I created an EventHub namespace with Kafka support, created an eventhub. When creating a kafka pubsub component I would expect it to load successfully.
> 
> ## Actual Behavior
> I am getting the following error message during startup
> 
> `FATA[0006] process component pubsub-important error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?) app_id=message-creator-node instance=box scope=dapr.runtime type=log ver=1.3.0`
> 
> ```
> If I change the same component to a kafka binding it loads successfully
> INFO[0000] successful init for output binding binding-important (bindings.kafka/v1)  app_id=message-creator-node instance=box scope=dapr.runtime type=log ver=1.3.0
> INFO[0001] successful init for input binding binding-important (bindings.kafka/v1)  app_id=message-creator-node instance=box scope=dapr.runtime type=log ver=1.3.0
> INFO[0001] component loaded. name: binding-important, type: bindings.kafka/v1  app_id=message-creator-node instance=box scope=dapr.runtime type=log ver=1.3.0
> ```
> 
> ## Steps to Reproduce the Problem
> Create EventHub namespace with Kakfa enabled. Create eventhub on the namespace Create binding component
> 
> ```
> apiVersion: dapr.io/v1alpha1
> kind: Component
> metadata:
>   name: binding-important
> spec:
>   type: bindings.kafka
>   version: v1
>   metadata:
>   - name: brokers
>     value: "demoeh.servicebus.windows.net:9093"
>   - name: consumerGroup
>     value: '$Default'
>   - name: authRequired
>     value: "true"
>   - name: saslUsername
>     value: '$ConnectionString'
>   - name: saslPassword
>     value: "Endpoint=sb:/EntityPath=important"
>   - name: publishTopic
>     value: important
>   - name: topics
>     value: important
> ```
> 
> It should work.
> 
> When creating the same component of type pubsub.kafka dapr returns an error.
> 
> Documentation seems to suggest that TLS needs to be enabled in config.Net.TLS.Enable and config.Net.TLS.Config is set to an instance of TLS Config. Can it be that pubsub and binding for kafka are using different configuration?
> 
> ## Release Note
> RELEASE NOTE:

I met the same problem!
