### ISSUE TITLE
POD Crashes when deploying cosmos DB binding

### ISSUE THREAD

**Issue by ubhanja** [dapr/components-contrib#1092]
I have a producer deployment (yaml is attached) which is posting data to Azure service bus queue binding in DAPR. This producer works fine with Azure Service BUS binding. I created a new Cosmos DB Binding (attached is the binding Yaml). As soon as the binding is deployed in default namespace the producer pod crashes. I increased the request and limit memory but still the issue continues. If I delete the binding component for Azure Cosmos DB , POD starts running. I am able to shell into the POD and post data at 3500 port for Azure Service bus . I created a state store for COSMOS DB and it works. I am able to save the data in COSMOS DB using statestore. But for bindings it is failing. I have the POD logs and DAPR container logs attached with yaml file. Appreciate if you can provide some input on why bindings in cosmos DB is causing the POD to crash,
[daprdeploy.zip](https://github.com/dapr/components-contrib/files/7009012/daprdeploy.zip)

**Comment by CodeMonkeyLeet** [comment]
Given the errors in your pod logs:
```bash
time="2021-08-17T14:55:32.504974844Z" level=debug msg="loading component. name: ukbcosmos, type: bindings.azure.cosmosdb/v1" app_id=producer instance=producer-66f7578fd-qz6r6 scope=dapr.runtime type=log ver=1.3.0
time="2021-08-17T14:55:32.615879781Z" level=error msg="failed to init output binding ukbcosmos (bindings.azure.cosmosdb/v1): , " app_id=producer instance=producer-66f7578fd-qz6r6 scope=dapr.runtime type=log ver=1.3.0
time="2021-08-17T14:55:32.616122885Z" level=error msg="failed to init output bindings: , " app_id=producer instance=producer-66f7578fd-qz6r6 scope=dapr.runtime type=log ver=1.3.0
time="2021-08-17T14:55:32.616299288Z" level=warning msg="process component error daprd process will exited, gracefully to stop" app_id=producer instance=producer-66f7578fd-qz6r6 scope=dapr.runtime type=log ver=1.3.0
```
This suggests an issue in the configuration of your daprcosmosbindings, which are blanked out in the logs you've provided. I'd test that your cosmosdb configuration works independently first (e.g. maybe by replacing the kafka in the [bindings quickstart](https://github.com/dapr/quickstarts/tree/master/bindings) and verifying that the producer sample can start locally).

**Comment by ubhanja** [comment]
Yes that would ne helpful. If you need further details , pls ping me.

**Comment by CodeMonkeyLeet** [comment]
@ubhanja I think you misunderstood me: I've already tried this with using cosmosdb binding in a minimal environment like the quickstart, and the cosmosdb component inits successfully. I'm suggesting that you test your cosmosdb configuration similarly in an isolated setting to help debug your failure, because the failure is very early in initializing the output binding, which usually indicates an incorrect component configuration.

**Comment by ubhanja** [comment]
@CodeMonkeyLeet  can you please share your sample cosmosdb binding

**Comment by ubhanja** [comment]
@CodeMonkeyLeet  I think I got the issue. CosmosDB with DocumentDB is working fine. When I use Mongo client the binding is crashing the POD. i.e if it is  https://******.documents.azure.com:443/ it works fine. but for  https://******.mongo.azure.com:443/ it fails . Can you please confirm that COSMOS DB Binding only works for Cosmos DB Document DB

**Comment by yaron2** [comment]
> @CodeMonkeyLeet I think I got the issue. CosmosDB with DocumentDB is working fine. When I use Mongo client the binding is crashing the POD. i.e if it is https://******.documents.azure.com:443/ it works fine. but for https://******.mongo.azure.com:443/ it fails . Can you please confirm that COSMOS DB Binding only works for Cosmos Document DB

Yes, I can confirm that.
You can try using the Dapr MongoDB state store component.
