### ISSUE TITLE
Middleware bearer for multiple client apps

### ISSUE THREAD

**Issue by thanhlq** [dapr/components-contrib#1094]
Hi everybody,

I am intending to use the [bearer middleware](https://github.com/dapr/components-contrib/blob/master/middleware/http/bearer/bearer_middleware.go) for multiple client apps (for instance I have a web app & a mobile app).

So, there is a way allowing me to define mulitple CLIEND_ID / IssuerUrl ?  

Thank you very much,

**Comment by CodeMonkeyLeet** [comment]
I don't believe that the existing bearer middleware implementation supports that yet though it sounds like an useful feature enhancement to have.
