### ISSUE TITLE
Does dapr support scram-sha-512  sasl for Kafka

### ISSUE THREAD

**Issue by pandagodyyy** [dapr/components-contrib#1109]
## In what area(s)?

> /area runtime

## Ask your question here
I deployed Kafka with Strimzi , it  only support 

- Mutual TLS client authentication (on listeners with TLS enabled encryption)
- SASL SCRAM-SHA-51
- OAuth 2.0 token based authentication

https://strimzi.io/docs/operators/latest/overview.html#security-configuration-authentication_str

And out dapr support secured connecting with kafka with saslUser and saslPassword.
but I had a trail let dapr connect with kafka with SCRAM-SHA-512, 
there is error log in kafka broker 
`"Failed authentication with /100.96.0.71 (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(SASL-9093)-SASL_PLAINTEXT-8"`
there is error in dapr sidcar
```
time="2021-08-30T06:38:36.351704903Z" level=fatal msg="process component pubsub error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)" app_id=xxx instance=xxx-69fcf8cb7b-rvw8j scope=dapr.runtime type=log ver=1.3.0
Logs from 8/30/2021, 2:33:07 PM
```

by the way if I did not enable the authentication of kafka broker, they can successfully to be wired.
However when I use bitnami chart to deploy kafka with plain user name and pasword, they can successfully to be wired as well.
I am feeling dapr does not understand SCRAM-SHA-512? hope someone can confirm it?

**Comment by oscarprol** [comment]
Is it Closed on v1.6 ?

func updateAuthInfo(config *sarama.Config, saslUsername, saslPassword string) {
	config.Net.SASL.Enable = true
	config.Net.SASL.User = saslUsername
	config.Net.SASL.Password = saslPassword
	config.Net.SASL.Mechanism = **sarama.SASLTypePlaintext**
}

**Comment by yehia2amer** [comment]
Is this issue also going to add [SCRAM-SHA-256](https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_scram.html)? 
From the above code the SASL.Mechanism is hardcoded to Plaintext; it needs to be configurable in the component yaml file

**Comment by mindovermiles262** [comment]
Any updates on this? We are trying to use MSK and it only supports SHA-512.

**Comment by nupis-DanielS** [comment]
Hi,

can you implement this feature in the version 1.10 or above?

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/dapr/docs/pull/2621
- https://github.com/dapr/docs/pull/2624
- https://github.com/dapr/docs/pull/2637
- https://github.com/dapr/docs/pull/2939
- https://github.com/dapr/components-contrib/issues/1109
- https://github.com/dapr/components-contrib/pull/1856
