### ISSUE TITLE
Add GCP KMS as a secrets store

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#113]
## Describe the proposal

Add support for [GCP KMS](https://cloud.google.com/kms/) as a Secrets Store.

The means to authenticate with GCP resources can be found in other components like GCP Pub/Sub, and the way these get passed in can be inferred from the other secrets store implementations.

**Comment by anuragprafulla** [comment]
@yaron2 I would like to take this issue.

**Comment by yaron2** [comment]
> @yaron2 I would like to take this issue.

Assigned, thanks!

**Comment by anuragprafulla** [comment]
Hi @yaron2 @youngbupark , I took sometime to understand the flow and what we are trying to do here. Almost halfway through. But I am stuck at a few places and wanted to get some help on these points. 
1. How is the metadata field populated? I am thinking I can get the credentials from metadata.
2. What would be the way to test if the functionality works properly?

**Comment by youngbupark** [comment]
@anuragprafulla both question can be answered in [azure keyvault howto doc](https://github.com/dapr/docs/blob/master/howto/setup-secret-store/azure-keyvault.md). this doc is written like a tutorial. Following the doc, you can find how metadata fields are populated and how to test your implementation in local and k8s modes.

**Comment by anuragprafulla** [comment]
> 
> 
> @anuragprafulla both questions can be answered in [azure keyvault howto doc](https://github.com/dapr/docs/blob/master/howto/setup-secret-store/azure-keyvault.md). this doc is written like a tutorial. Following the doc, you can find how metadata fields are populated and how to test your implementation in standalone and k8s modes.

@yaron2 @youngbupark This linked helped a lot with my understanding. I just have a couple more questions. Please bear with me :) 
1. cloudkms supports two types of encryption symmetric and asymmetric, which one should we support? Should we support both?
2. cloudkms does not necessarily support storing secrets, it is basically useful for encryption, decryption, logging etc. So, the encrypted file could be stored either on a gcp storage or any other safe location. Would giving a path of the encrpyted file as a parameter to the decryption method make sense?

**Comment by yaron2** [comment]
> cloudkms supports two types of encryption symmetric and asymmetric, which one should we support? Should we support both?

Let's start with the symmetric encryption which is more common. We can add asymmetric down the road.

> cloudkms does not necessarily support storing secrets, it is basically useful for encryption, decryption, logging etc. So, the encrypted file could be stored either on a gcp storage or any other safe location. Would giving a path of the encrypted file as a parameter to the decryption method make sense?

A path to the GCP storage file makes sense. We just need to account for the credentials to access this file if a policy has been set to make it private.

**Comment by amanbha** [comment]
https://github.com/dapr/components-contrib/tree/master/secretstores/gcp/cloudkms
