### ISSUE TITLE
Default TTL support in Redis State Store

### ISSUE THREAD

**Issue by Weidaicheng** [dapr/components-contrib#1135]
I saw there was a PR in #1059 which provided the ability to use default TTL state store in Redis, but when I tried to use this by configuring my statestore component like this, it did work, can I ask how should I do this right, thanks in advance.

![image](https://user-images.githubusercontent.com/18458093/132941443-f482e045-a894-44ef-80ba-57c1ee426a16.png)

**Comment by Taction** [comment]
What does `it did work` actually mean? What are the expected and actual behaviors?
