### ISSUE TITLE
Create certification test for CosmosDB state store

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#1138]
After completing #1137, write an integration test for CosmosDB.

Test scenarios:

** Handle connection drop of 1 minute, a.k.a. "reconnect" - offer "pull the plug" mode in the test framework.
*** Test should perform a write operation with retry over 2 minutes and succeed, following with a GET proving the data was written. Write operation must last at least 1 minute to show that the outage was correctly injected.

** Validate multiple authentication mechanisms

** Write different data types and validate how data is persisted in the database
*** String
*** Integer
*** Float
*** Boolean
*** Byte array

** Validate data can be queried by "native" database client

Parent: #939

**Comment by shivamkm07** [comment]
# Azure Cosmos DB certification testing

This project aims to test the Azure Cosmos DB State Store component under various conditions.

## Test plan

### Basic Test using master key authentication
1. Able to create and test connection.
2. Able to do set, fetch and delete.

### Test Partition Keys
Ensure the following scenarios:
 1. In case of invalid partition key, the access fails
 2. In case of missing partition key, *key* property is used in place of it
 3. In case of correct partition key, the access succeeds

### Authentication using Azure AD
1. Save Data using GO SDK
2. Retrieve data using AAD credentials

**Comment by DeepanshuA** [comment]
Should we also add a use-case for checking one of "Best Practices for Production Use":
- Let's say, initially, there is a network issue and connection could not be established; but as initTimeout is configured for, say 2 minutes or so, it retries for Connection and as network issue is resolved now, so Connection is successful while re-attempting.
