### ISSUE TITLE
To track version of tools used

### ISSUE THREAD

**Issue by sayboras** [dapr/components-contrib#115]
## Ask your question here

Just want to check if there is any plan to track the version of tools used. Here is common approach for go module https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

**Comment by sayboras** [comment]
@yaron2 @youngbupark @shalabhms let me know what you have in mind ?

**Comment by msfussell** [comment]
This is now supported with Go modules
