### ISSUE TITLE
MySQL state store conformance test should support `first-write` tests

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [dapr/components-contrib#1162]
## Describe the proposal
The `first-write` tests test the interaction between the use of ETags and concurrency settings, so components that test `ETags` should also be updated to run the `first-write` state store conformance tests and the component should be passing them.

Follow-up to #1124.

Depends on #1123.

**Comment by berndverst** [comment]
Not sure when this happened, but it is done.
