### ISSUE TITLE
New criteria to GA components

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#1167]
## Background
There is a desire to certify as GA more components. However, aspects of the current certification requirements seem arbitrary or even insufficient. See https://docs.dapr.io/operations/components/certification-lifecycle/#certification-levels for current certification criteria for the different lifecycle stages of a Dapr component.

## Proposed change to General Availability (GA) criteria
•	~Has at least two different users using the component in production~
•	The component must have the integration tests validating functionality and resiliency
•	~A GA component has a maintainer in the Dapr community or the Dapr maintainers~
•	The component is maintained by Dapr maintainers and supported by the community 
•	~The component is well documented, tested and maintained across multiple versions of components-contrib repo~
•	The component is well-documented and tested. 
•	A maintainer will address component security, core functionality and test issues according to the Dapr support policy and issue a patch release of Dapr that includes the patched stable component

## Proposed renaming

Instead of calling these `GA components`, we should call these `stable components` since they reflect the maturity of the code and not necessarily the support model of a managed service.

## Future

In addition, there can be additional requirements for GA, such as performance tests.

**Comment by Forrest-zhao** [comment]
@artursouza, could you elaborate on the removal of "maintained across multiple versions of components-contrib repo"? IMO. keeping the maintenance of multiple versions is necessary for GA components to provide the consistent support model of a managed service.

**Comment by artursouza** [comment]
> @artursouza, could you elaborate on the removal of "maintained across multiple versions of components-contrib repo"? IMO. keeping the maintenance of multiple versions is necessary for GA components to provide the consistent support model of a managed service.

This statement is ambiguous. The current GA components only have one version but that same version is present in multiple releases of components-contrib. Having a component in multiple versions of components-contrib does not increase the quality of the component, having a consistent battery of tests does.

Anther point in this proposal, is that a Dapr component is not a managed service. It can be a Facade to a managed service, but it is not necessatily a support model. That is why this proposal suggests the use of "stable" as the proper terminology to refer to Dapr components.

**Comment by yaron2** [comment]
> but it is not necessatily a support model

I disagree @artursouza , Dapr's support model is inferred automatically here. Any decision regarding component level maturity automatically applies directly to Dapr's support model of issuing patches (P0 bugs, security fixes) and maintaining backward compatibility for a component.

**Comment by yaron2** [comment]
Also in terms of GA, as @dmitsh proposed, we can look at maturity levels of other projects. the current criteria was taken from the nearest thing to CNCF maturity level, which is [Kubernetes maturity levels](https://kubernetes.io/docs/reference/using-api/deprecation-policy/).

Kubernetes uses alpha, beta and GA which is also known as stable.

**Comment by daixiang0** [comment]
> Kubernetes uses alpha, beta and GA which is also known as stable.
I agree stable is more equal to GA in cloud native world. With my experience in Kubernetes, those levels would iterate through multiple releases to ensure upgrade.

I propose that we can mark one as GA which is mostly used and "stable" for each component, then iterate others.

**Comment by beiwei30** [comment]
> In addition, there can additional requirements for GA, such as performance tests.

Shouldn't we escalate this requirement to 'Now' instead of 'Future'? By doing this, we can make sure the "GA" components always satisfy the corresponding component API.

**Comment by artursouza** [comment]
> > In addition, there can additional requirements for GA, such as performance tests.
> 
> Shouldn't we escalate this requirement to 'Now' instead of 'Future'? By doing this, we can make sure the "GA" components always satisfy the corresponding component API.


If we set this bar now, we will not have any component marked as GA anytime soon. We can retroactive write perf tests for GA components once we decide we can have a test plan and framework to enable perf testing.

**Comment by dmitsh** [comment]
Regarding "GA vs. stable" discussion, I personally prefer the later.
IMO, “GA” has a connotation of a managed service with associated SLA, which does not apply to an open source project.

**Comment by orizohar** [comment]
> Regarding "GA vs. stable" discussion, I personally prefer the later. IMO, “GA” has a connotation of a managed service with associated SLA, which does not apply to an open source project.

I very much agree. I think "stable" is a better name in the context of Dapr components

**Comment by willtsai** [comment]
I prefer "stable" over "GA" as well for the same reasons enumerated above.

**Comment by berndverst** [comment]
I also agree that "stable" is better.

**Comment by yaron2** [comment]
There are examples in the OSS ecosystem of both - for example, Istio uses `stable` while Kubernetes uses `GA` - neither are managed services.

This topic will be discussed in the next Dapr STC meeting.

**Comment by beiwei30** [comment]
agree, I vote 'stable' too.
