### ISSUE TITLE
SQL Server state component broken for version 1.1.2

### ISSUE THREAD

**Issue by luk355** [dapr/components-contrib#1178]
We are running into following issue when upgrading from v1.0 to v1.1.2 while using `state.sqlserver` component. As recommended upgrade path by Dapr is to go through 1.1, we are stuck with the upgrade.

## Expected Behavior

Daprd sidecar will start ok for Dapr v1.1.2 with `state.sqlserver` component.

## Actual Behavior

Daprd component crashes with following stack trace:

```bash
goroutine 40 [running]:
github.com/denisenkom/go-mssqldb.passthroughConn.SetWriteDeadline(...)
        /home/runner/go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20191128021309-1d7a30a10f73/net.go:167
crypto/tls.(*Conn).SetWriteDeadline(...)
        /opt/hostedtoolcache/go/1.16.3/x64/src/crypto/tls/conn.go:150
crypto/tls.(*Conn).closeNotify(0xc0002b6e00, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.3/x64/src/crypto/tls/conn.go:1360 +0xfd
crypto/tls.(*Conn).Close(0xc0002b6e00, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.16.3/x64/src/crypto/tls/conn.go:1330 +0xd7
github.com/denisenkom/go-mssqldb.(*Conn).Close(0xc0003fc7c0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20191128021309-1d7a30a10f73/mssql.go:361 +0x3a
database/sql.(*driverConn).finalClose.func2()
        /opt/hostedtoolcache/go/1.16.3/x64/src/database/sql/sql.go:592 +0x49
database/sql.withLock(0x3bd1ea8, 0xc000a26480, 0xc000a87368)
        /opt/hostedtoolcache/go/1.16.3/x64/src/database/sql/sql.go:3294 +0x69
database/sql.(*driverConn).finalClose(0xc000a26480, 0xc000a264a0, 0x3777bd8)
        /opt/hostedtoolcache/go/1.16.3/x64/src/database/sql/sql.go:590 +0x13c
database/sql.(*DB).Close(0xc0002f49c0, 0xc0002f49c0, 0xc000a12180)
        /opt/hostedtoolcache/go/1.16.3/x64/src/database/sql/sql.go:847 +0x288
github.com/dapr/components-contrib/state/sqlserver.(*migration).executeMigrations(0xc00000e968, 0xc000a12180, 0x17, 0xc000212e40, 0x1d, 0xc000a12198, 0x15, 0xc000a121b0, 0x13, 0xc000212e60, ...)
        /home/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.1.1/state/sqlserver/migration.go:94 +0xd17
github.com/dapr/components-contrib/state/sqlserver.(*SQLServer).Init(0xc000a02100, 0xc0003fef00, 0x3, 0x4)
        /home/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.1.1/state/sqlserver/sqlserver.go:236 +0x37d
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).initState(0xc00004f680, 0xc0003e3ab0, 0x9, 0xc0003e3ac0, 0x10, 0xc0003e3ad0, 0xb, 0x0, 0x0, 0xc0003e3ae0, ...)
        /home/runner/work/dapr/dapr/pkg/runtime/runtime.go:855 +0x21d
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).doProcessOneComponent(0xc00004f680, 0x363ba45, 0x5, 0xc0003e3ab0, 0x9, 0xc0003e3ac0, 0x10, 0xc0003e3ad0, 0xb, 0x0, ...)
        /home/runner/work/dapr/dapr/pkg/runtime/runtime.go:1472 +0xb8
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).processComponentAndDependents.func1(0xc000201f80, 0xc00004f680, 0x363ba45, 0x5, 0xc000962000)
        /home/runner/work/dapr/dapr/pkg/runtime/runtime.go:1434 +0xa5
created by github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).processComponentAndDependents
        /home/runner/work/dapr/dapr/pkg/runtime/runtime.go:1433 +0x4a5
```

I believe this is caused by old version of `go-mssqldb` package referenced. The seems to be fixed in later versions of `go-mssqldb`. 

Reference to the issue: https://github.com/denisenkom/go-mssqldb/issues/639

I can see this was also fixed in later versions of Dapr, see this discussion: https://github.com/dapr/components-contrib/pull/1078/files#r689207428

The fix should therefore be pretty simple:

1) create tag/version 1.1.3 with updated version reference to github.com/denisenkom/go-mssqldb package in `go.mod`. More specifically, use version `github.com/denisenkom/go-mssqldb v0.0.0-20210411162248-d9abbec934ba` as this one is still currently used in master branch as well.

## Steps to Reproduce the Problem

1. Install Dapr v1.1.2
2. use `state-mssql` component
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: TODO
  name: state-mssql
spec:
  version: v1
  type: state.sqlserver
  metadata:
    - name: connectionString
      secretKeyRef: TODO
```
3. deploy a service with Daprd sidecar enabled

## Release Note

RELEASE NOTE:
**FIX** state.sqlserver component for v1.1

**Comment by berndverst** [comment]
@artursouza @yaron2 @msfussell any thoughts?

The SQL Server state store component is not considered GA / stable yet and certainly not in 1.0 / 1.1.2. The 1.0 -> 1.1.2 upgrade path seems to be broken for users of that component.

Should we create a 1.1.3 release to update the MSSQL library version used to fix this issue and make upgrading easier?

**Comment by artursouza** [comment]
@luk355 Can you try skipping to 1.2.2? We usually avoid skipping versions since that is not a tested upgrade path but it might be worth in your situation.

**Comment by berndverst** [comment]
@luk355 the first Dapr release that uses a different version of `github.com/denisenkom/go-mssqldb v0.0.0-20210411162248-d9abbec934ba` is actually v1.4.

We will not be creating patch releases for v1.1, v1.2 and v1.3 to update this library. I specifically addressed the issue you are encountering by upgrading the library in v1.4 forward. The SQL Server component is Alpha.

My recommendation is to disable the SQL Server state store component (and any service relying on it), complete the upgrade to v1.4 and then reenable the component and the services that depend on it.
