### ISSUE TITLE
TLS with Kafka pubsub component

### ISSUE THREAD

**Issue by neumann1990** [dapr/components-contrib#1188]
I'm trying to use the Kafka pubsub component to connect to a Kafka listener with TLS enabled. Are there any hooks to provide the dapr sidecar with a CA chain for verifying the Kafka TLS cert, similar to the `caCert` config value for the [MMQT pubsub component](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-mqtt/)?

**Comment by Taction** [comment]
I'll look into this and add tls support for it.

**Comment by yaron2** [comment]
Triaged into 1.5.

**Comment by darren-wang** [comment]
> I'll look into this and add tls support for it.

Can you have a look into my issue with kafka as pubsub backend? Thanks a lot!
https://github.com/dapr/dapr/issues/3766
