### ISSUE TITLE
Add AckWait, MaxDeliver, and MaxAckPending Properties for NATS Jetstream 

### ISSUE THREAD

**Issue by Admiralkheir** [dapr/components-contrib#1191]
We need these properties for using JetStream. We are using Nats Streaming now but wanted to change it with JetStream

AckWait: Ack Wait is the time in nanoseconds that the server will wait for an ack for any individual message. If an ack is not received in time, the message will be delivered.

MaxDeliver: The maximum number of times a specific message will be delivered. Applies to any message that is re-sent due to ack policy.

MaxAckPending: The maximum number of messages without an acknowledgment that can be outstanding, once this limit is reached message delivery will be suspended. It cannot be used with AckNone ack policy.

[Document](https://docs.nats.io/jetstream/concepts/consumers#flowcontrol)
[Example Usage](https://github.com/nats-io/nats.go#jetstream-basic-usage)

**Comment by Admiralkheir** [comment]
Of course I would, but I don't have much experience in go language, I usually develop applications on the .net side.

**Comment by yaron2** [comment]
Reopened

**Comment by Admiralkheir** [comment]
Hello, we want to switch to use JetStream instead of Nats streaming(Cause of end of support), which we currently use in our applications, but the equivalents of ackwait(AckWait) and maxinflight(MaxAckPending) values ​​on the nats streaming component are not available in the jetstream component. These properties are essential to our transition. Thanks

**Comment by Admiralkheir** [comment]
Reopened

**Comment by Admiralkheir** [comment]
looks like done with #2179
