### ISSUE TITLE
Add Query StateStore API implementation for Redis StateStore

### ISSUE THREAD

**Issue by dmitsh** [dapr/components-contrib#1211]
## Describe the feature
Per https://github.com/dapr/dapr/issues/3662, we have added Query StateStore API and implemented it for ModgoDB and CosmosDB (https://github.com/dapr/components-contrib/pull/1153)

We need to implement this API for Redis StateStore

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Reopened.

**Comment by yaron2** [comment]
@dmitsh are you planning to work on this for 1.6?

**Comment by dmitsh** [comment]
> @dmitsh are you planning to work on this for 1.6?

wasn't planning. @manojrupireddy, are you still interested in pursuing this task?

**Comment by dmitsh** [comment]
Natively, Redis only offers primary key access. However, with the help of two modules, it is possible to store and query JSON documents:

- RedisJSON allows to store and manipulate values as JSON objects (https://oss.redis.com/redisjson/)
- RediSearch enables secondary indexing and searching capability (https://oss.redis.com/redisearch/).

The current Redis component implementation does not require any additional modules, and stores the values as raw data.

The use of the aforementioned modules allows querying the state, but it comes with a price:
1. RediSearch requires setting the JSON object schema prior to querying
2. RedisJSON stores data in a special fashion.

This will be incompatible with the current implementation. One way to address this issue is to develop an alternative Redis component that supports JSON structures. The new component will require presence of RedisJSON and RediSearch, and will allow setting the object schemas.

To make the new Redis component to support other formats, we would need to introduce optional content type to the State Store API. If the content type equals to `application/json`, the component will store the value as JSON object. Otherwise the value will be stored as raw data.

In the future, the component could support additional formats.

This is a very high-level description of the proposed design.
Please comment if you have any comments and suggestions.
After gathering the feedback, I'm intended to propose more detailed design.

**Comment by artursouza** [comment]
This starts to feel like a different implementation of the redis state store component.

**Comment by dmitsh** [comment]
> This starts to feel like a different implementation of the redis state store component.

it can be the same component, but there should be an agreement that if JSON content type is declared, the underlying Redis service should include RedisJSON and RediSearch modules.

**Comment by pkedy** [comment]
One thing to consider is that if the users are getting their Redis from a managed cloud offering (e.g. AWS ElastiCache for Redis), does that offering have the required modules @dmitsh mentioned installed. Given this features relies heavily on the modules being active/installed, it could limit the value that could come from this feature. Would users not shift to a Document DB style database when they have this usecase?
