### ISSUE TITLE
cron binding currently calls all copies of a service

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1249]
Currently, it will cause repeated execution. Can a service be called only once，Similar to competing consumers pattern?

**Comment by daixiang0** [comment]
What do all copies of service mean? A HA kafka? Please share more details to help us understand.

**Comment by saber-wang** [comment]
@daixiang0 
cron 
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: daprdemocron
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 20s" # valid cron schedule
  - name: route
    value: /daprdemo/api/v1/Remote/cron
```

Deploy 2 replicas of a service, observe the log output and find that each replica is called once every 20s ，The expectation is to call only one replica every 20s 

yml:
```
version: '3'
services:
  daprdemo:
    image: daprdemo:v1
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - PORT=5000
    ports:
      - "5000:5000"
  daprdemo-dapr:
    image: "daprio/daprd:1.4.3"
    network_mode: "service:daprdemo"
    command: ["./daprd",
      "-app-id", "daprdemo",
      "-app-port", "5000",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      #"-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/.dapr/components/:/components"
      - "./DaprDemo/DaprDemo.Host/localfilesecret.json/:/localfilesecret.json"
     # - "./dapr/configuration/:/configuration"
    depends_on:
      - daprdemo
  daprdemo1:
    image: daprdemo:v1
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - PORT=5000
    ports:
      - "5001:5000"
  daprdemo1-dapr:
    image: "daprio/daprd:1.4.3"
    network_mode: "service:daprdemo1"
    command: ["./daprd",
      "-app-id", "daprdemo",
      "-app-port", "5000",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      #"-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/.dapr/components/:/components"
      - "./DaprDemo/DaprDemo.Host/localfilesecret.json/:/localfilesecret.json"
     # - "./dapr/configuration/:/configuration"
    depends_on:
      - daprdemo1  
  dapr-placement:
    image: "daprio/dapr:1.4.3"
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

```

logs:
![image](https://user-images.githubusercontent.com/45062099/139774431-16a2cce3-b7a5-42f0-b74a-1703ad7dcd41.png)


![image](https://user-images.githubusercontent.com/45062099/139774484-7815198c-39da-4ab8-9062-57c70674525f.png)


Deploying 2 pods on k8s is the same

**Comment by CodeMonkeyLeet** [comment]
@saber-wang there seem to be a couple of misconceptions here:

- The [cron binding](https://docs.dapr.io/reference/components-reference/supported-bindings/cron/) does not take a `route` parameter.
- There is no backing service to the cron binding. It runs local to the dapr sidecar, so scaling out your app also scales out the number of cron triggers.

As mentioned, if you would like to use a competing consumer pattern for handling an event based on a cron trigger, you should:

1. Create a separate singleton service that publishes a trigger message using the cron binding.
2. Update your app that is being scaled using replicas to subscribe to the same topic with the same consumer ID (e.g. using [Dapr pubsub](https://docs.dapr.io/reference/components-reference/supported-pubsub/)) to handle the trigger message. That should produce the competing consumer pattern you desire.

Alternatively, if you don't want to use a pubsub broker, you can also define your replica set to behave as a virtual server by defining a [Kubernetes Service](https://kubernetes.io/docs/concepts/services-networking/service/). You can then have your singleton cron trigger app invoke the Service exposed port, which will load balance the call out to one of the replicas in the set.

**Comment by saber-wang** [comment]
@CodeMonkeyLeet  Thank you for your answers and suggestions
