### ISSUE TITLE
Enriching RabbitMQ bindings and pub/sub

### ISSUE THREAD

**Issue by fbeltrao** [dapr/components-contrib#126]
I think that RabbitMQ support needs a few improvements in order to better support production scenarios.

The following features comes to mind:

- [x] As a publisher I want to define message TTL in order to expire stale content
- [x] As a consumer I want to move messages to a dead-letter queue if the consumer fails or message expires
- [ ] As a consumer I want to ensure that my queue has a maximum capacity in order to prevent using too many resources
- [ ] As a consumer I want to be able to change RabbitMQ queue properties as part of a new deployment. Example: v1 did not define a TTL and dead-letter. In v2 we want to define them. I see 2 options to address the issue, would appreciate if others have different ideas:
  - [ ] Option A:  version exchanges and queues so that when a new version is defined it gets the version as part of the name. This approach allows running v1 and v2 side by side.
  - [ ] Option B: changes to exchange and queue properties are automatically reapplied by Dapr runtime. This approach does not allow running v1 and v2 side by side. If both versions are running simultaneous they will keep recreating the underlying queues.

Would love to hear your opinion. If this changes are accepted I can happily tackle them.

**Comment by amanbha** [comment]
@fbeltrao These improvements sounds good, would you like to create a PR for it.

**Comment by fbeltrao** [comment]
@amanbha I have a problem with time availability in the next months. If you are ok with me working slowly on this I can do it.

My advice would be to start working on an standard way to define the additional queue metadata within Dapr so that other implementations (Azure Service Bus,  Azure Storage Queue, etc.)  can follow the same pattern.

**Comment by amanbha** [comment]
@fbeltrao Thats totally fine, thanks!

**Comment by amanbha** [comment]
Thanks for the contribution @fbeltrao , we will review it soon.

**Comment by msfussell** [comment]
TTL is done.

**Comment by Taction** [comment]
I’ll pick up dead-letter queue feature.

**Comment by berndverst** [comment]
The maximum queue capacity is not a feature we currently have in any pubsub and binding components.

If this is still needed for RabbitMQ, could you please open a separate issue just for this feature request?

Separate issues for separate features help with implementation as well as letting the community find and upvote that issue.

**Comment by berndverst** [comment]
I'm closing this issue as many items have been addressed here. And to help reprioritize or give focus to any feature requests here I ask that new requests are opened for each feature.
