### ISSUE TITLE
PubSub AWS SNS SQS component - use SQS FIFO

### ISSUE THREAD

**Issue by amimimor** [dapr/components-contrib#1260]
## Describe the feature
To use exactly once message delivery guarantees with message ordering when using SQS, a user (here daprd) must choose an SQS queue of FIFO type and queue name suffixed with `.fifo` (see [AWS docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-create-queue.html)) upon the queue creation.
The ability to use SQS FIFO is currently missing from the the pubsub/aws/snssqs implementation and we'd like to add this capability to daprd.

## Release Note

RELEASE NOTE:

**Comment by mhozhda-agiliway** [comment]
Already created an issue a few days ago: https://github.com/dapr/components-contrib/issues/1205
