### ISSUE TITLE
 the Route of subscription API does not work on pubsub.pulsar

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1263]
time="2021-11-02T09:40:16+08:00" level=info msg="Connecting to broker" remote_addr="pulsar://ip:prot"
time="2021-11-02T09:40:16+08:00" level=info msg="TCP connection established" local_addr="ip:prot" remote_addr="ip:prot"
time="2021-11-02T09:40:16+08:00" level=info msg="Connection is ready" local_addr="ip:prot" remote_addr="pulsar://ip:prot
time="2021-11-02T09:40:16+08:00" level=info msg="Connecting to broker" remote_addr="pulsar://ip:prot"
time="2021-11-02T09:40:16+08:00" level=info msg="TCP connection established" local_addr="ip:prot" remote_addr="pulsar://ip:prot"
time="2021-11-02T09:40:16+08:00" level=info msg="Connection is ready" local_addr="ip:prot" remote_addr="pulsar://ip:prot"
time="2021-11-02T09:40:16+08:00" level=info msg="Connected consumer" name=xtbnd subscription=daprdemo topic="persistent://public/default/DaprDemoEvent"
time="2021-11-02T09:40:16+08:00" level=info msg="Created consumer" name=xtbnd subscription=daprdemo topic="persistent://public/default/DaprDemoEvent"

......

time="2021-11-02T09:40:39+08:00" level=info msg="Created producer" cnx="ip:prot -> ip:prot" producer_name=pulsar-mini-6-164004 topic="persistent://public/default/DaprDemoEvent"
time="2021-11-02T09:40:39.5137062+08:00" level=debug msg="Processing Pulsar message persistent://public/default/DaprDemoEvent/&pulsar.messageID{ledgerID:377, entryID:1, batchIdx:0, partitionIdx:0, tracker:(*pulsar.ackTracker)(nil), consumer:(*pulsar.partitionConsumer)(0xc000901860)}" app_id=daprdemo instance=Yoga-14s scope=dapr.contrib type=log ver=1.4.3
time="2021-11-02T09:40:39.5142207+08:00" level=debug msg="no matching route for event df5176a9-7856-4f94-8566-306f040eae6e in pubsub pubsub and topic persistent://public/default/DaprDemoEvent; skipping" app_id=daprdemo instance=Yoga-14s scope=dapr.runtime type=log ver=1.4.3

![image](https://user-images.githubusercontent.com/45062099/139773460-4b2fd16c-e3b3-493d-9ded-66eb132566cb.png)

**Comment by CodeMonkeyLeet** [comment]
@saber-wang This looks like an issue with your publisher config that is using the topic `persistent://public/default/DaprDemoEvent` and not the `DaprDemoEvent` topic configured by your subscriber.

**Comment by saber-wang** [comment]
@CodeMonkeyLeet But when I changed pulsar to redis, everything was normal, and it was clear that `persistent://public/default/DaprDemoEvent` was created and subscribed in the log.

**Comment by Taction** [comment]
@saber-wang Thanks for reporting this.
It seems that pulsar has formated the topic into its own form. When publishing msg to dapr, we should use the original topic instead of using the topic get from msg.
Or we can document that to instruct users to define the topic following the pulsar's rule(define `persistent://public/default/DaprDemoEvent` instead of `DaprDemoEvent ` when using pulsar), but this may break the consistency of behavior between components.

Anyone who is familiar with this can go ahead. Otherwise, I will look into it this weekend.

**Comment by saber-wang** [comment]
@Taction Make a suggestion,can pulsar support more metadata? For example, support for setting up tenants and namespaces

**Comment by Taction** [comment]
Can you list the metadata you want or suggest? It's best to have a link to the official documentation.

**Comment by saber-wang** [comment]
@Taction `https://pulsar.apache.org/docs/en/concepts-multi-tenancy/`  Tenants and Namespaces

**Comment by daixiang0** [comment]
I think Tenants and Namespaces are useful, are you interested in adding them? @saber-wang

**Comment by saber-wang** [comment]
@daixiang0 Sorry, I’m not very familiar with GO
