### ISSUE TITLE
Support configuring broker version in Kafka bindings component

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [dapr/components-contrib#1277]
## Describe the feature
Per https://github.com/dapr/dapr/issues/3806 for Kafka pubsub, the Kafka bindings component hardcodes the Kafka version the component expects the broker to be using, which can unnecessarily restrict compatibility in an end user's environment.

Given https://github.com/dapr/components-contrib/pull/1275, it would be good for Kafka bindings to support the `Version` metadata as well for parity. This may be a lower priority for Kafka bindings because it hardcodes to `v1_0_0_0` unlike pubsub (it supports a wider range of Kafka versions as that supports v1 and up, whereas pubsub was using v2 and up.)

## Release Note

RELEASE NOTE: **ADD** Kafka version configuration to Kafka bindings

**Comment by daixiang0** [comment]
Does it mean Dapr need to maintain multi-version of Kafka?

**Comment by CodeMonkeyLeet** [comment]
@daixiang0 what you mean? Dapr itself is agnostic to the Kafka versions as far as I can tell, it's primarily a feature that the sarama lib the Kafka components in Dapr rely on that expose the ability to configure the client to be compatible with downlevel versions of the Kafka brokers. The change is simply for the Dapr Kafka binding to expose the configuration option that sarama already provides.

If Dapr runtime features depend on a specific version of Kafka, that's not documented anywhere currently, so it's an unknown unknown, and should be verified on implementation of this.

**Comment by daixiang0** [comment]
Oh, I get it, thanks for your careful explain.

**Comment by yaron2** [comment]
@light-pan can you please comment `/assign` here? it's so you get the credit in the 1.7 release :)
