### ISSUE TITLE
Azure Auth Tests: Refactor use of `MSI_ENDPOINT` and make related tests run sequentially

### ISSUE THREAD

**Issue by berndverst** [dapr/components-contrib#1307]
This is a work item to investigate how to make the MSI / Azure Managed Identity tests pass without use of the `MSI_ENDPOINT` environment variable.

If this cannot be removed the tests should be run in sequence at least.

This was originally introduced in https://github.com/dapr/components-contrib/pull/1132, then reverted in https://github.com/dapr/components-contrib/pull/1291, then reintroduced in https://github.com/dapr/components-contrib/pull/1290

This change is required for the MSI auth tests to pass with newer versions of the ADAL and Autorest libraries.

**Comment by berndverst** [comment]
cc @ItalyPaleAle

**Comment by ItalyPaleAle** [comment]
I've done some digging into the code of `azure/go-autorest/autorest/adal`

Looks like the environmental variables `MSI_ENDPOINT` and `MSI_SECRET` are used by the SDK to determine the environment the app is running in and which is the endpoint of the MSI. In this case, with `MSI_ENDPOINT` only set, the SDK thinks it's running on CloudShell.

Sadly the current SDK doesn't seem to have an option to pass the same information without using environmental variables.

I am not familiar enough with the tests to know if making the SDK think we're running in CloudShell is needed or not. But assuming it's needed for the tests, then there doesn't seem to be a different way to set that.

**Comment by ItalyPaleAle** [comment]
👋 bot
