### ISSUE TITLE
Mongodb authentication will fail, in case of databasename other than 'admin'

### ISSUE THREAD

**Issue by mjtansin** [dapr/components-contrib#1311]
## Expected Behavior

We could set DatabaseName to an name other then 'admin'.
We could set authentication database name.
For mongodb, we should set `--authenticationDatabase`, but there's no such key provided in state.mongo component.  
## Actual Behavior
If databaseName is not 'admin', authentication will fail.
`time="2021-11-18T07:55:17.339768961Z" level=fatal msg="process component chatstore error: error in connecting to mongodb, host: 10.110.100.193:29002 error: connection() error occured during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AuthenticationFailed) Authentication failed." app_id=chatroom instance=chatroom-5b7c88c9c9-sb5f9 scope=dapr.runtime type=log ver=1.4.3`

If database name is not 'damin', authencation will fail, because we don't set authentication database name(--authenticationDatabase). But, there's no such entry in the component manifest.

## Steps to Reproduce the Problem

1. Create a mongodb component, set databaseName 'xxx', while 'xxx' is not 'admin'.
2. Apply that component in k8s.
## Release Note

Add a new key 'auchenticationDatabase' to mongodb component.

RELEASE NOTE:

**Comment by Taction** [comment]
Thanks for reporting this. Would you be interested in submitting a PR to fix this?

**Comment by mjtansin** [comment]
I viewed the code, and found the way to slove this problem by adding key 'params'  and value '?authSource=admin'. So, it's not a bug. It's better to update [mongo state store](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-mongodb/).

**Comment by yaron2** [comment]
Hey @Taction, please contact me on Discord: my user is yaron2 :)

**Comment by Taction** [comment]
> Hey @Taction, please contact me on Discord: my user is yaron2 :)

@yaron2 I can't send you a message directly, I have sent you a friend request. My user is Taction.

**Comment by shivamkm07** [comment]
@yaron2 As @mjtansin said, the issue can be resolved by adding the key 'params' and value '?authSource=xxx', where 'xxx' is the authenticationDatabase. So should this issue be closed?

 [mongo state store](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-mongodb/) docs needs to be updated with 'params' key, will do that.

**Comment by shivamkm07** [comment]
Also, I see [mongo-driver](https://github.com/mongodb/mongo-go-driver/blob/40c0e70826f57cf9d942045a014367d9b3c94251/x/mongo/driver/connstring/connstring.go#L380) client for mongodb uses `databaseName` as default value for `authenticationDatabase`. If `databaseName` isn't specified, then it will use `admin` as default value. However specifying the `authSource` in params will override the default values.

**Comment by shivamkm07** [comment]
@artursouza thoughts?

**Comment by artursouza** [comment]
@shivamkm07 I think the docs update seems to be the right thing here. Thanks.

**Comment by yaron2** [comment]
Closed via https://github.com/dapr/docs/pull/2262.
