### ISSUE TITLE
Cosmosdb impl returns nil for Get request when length of items is 0

### ISSUE THREAD

**Issue by LMWF** [dapr/components-contrib#132]
## Expected Behavior

dapr panics when using the state store is cosmosdb and the app is an actor.  The reason is because the cosmosdb components implementation returns a nil response from Get() when the length of returned items is 0.

## Actual Behavior

```
== DAPR == time="2019-11-19T16:44:10-08:00" level=info msg="actors: placement order received: update"
== DAPR == time="2019-11-19T16:44:10-08:00" level=info msg="actors: placement tables updated"
== DAPR == time="2019-11-19T16:44:10-08:00" level=info msg="actors: placement order received: unlock"
== DAPR == panic: runtime error: invalid memory address or nil pointer dereference
== DAPR == [signal 0xc0000005 code=0x0 addr=0x8 pc=0x9e72c5]
== DAPR ==
== DAPR == goroutine 119 [running]:
== DAPR == github.com/dapr/dapr/pkg/actors.(*actorsRuntime).getRemindersForActorType(0xc00053f320, 0xc0003661c0, 0x9, 0xc000563d00, 0x0, 0x0, 0x0, 0x0)
== DAPR ==      D:/a/dapr/dapr/pkg/actors/actors.go:978 +0x165
== DAPR == github.com/dapr/dapr/pkg/actors.(*actorsRuntime).evaluateReminders(0xc00053f320)
== DAPR ==      D:/a/dapr/dapr/pkg/actors/actors.go:600 +0x16b
== DAPR == created by github.com/dapr/dapr/pkg/actors.(*actorsRuntime).updatePlacements
== DAPR ==      D:/a/dapr/dapr/pkg/actors/actors.go:526 +0x466
```

## Steps to Reproduce the Problem

- init dapr
- overwrite components\redis.yaml with a cosmosdb config
- From  \dotnet-sdk\samples\Actor\DemoActor
```
$ dapr run --port 3500 --app-id demo_actor --app-port 5000 dotnet run --log-level debug
```

**Comment by yaron2** [comment]
CosmosDB is not an actor supported state store because it's not transactional.

**Comment by yaron2** [comment]
Only Redis and MongoDB are supported for actors.

**Comment by LMWF** [comment]
Yes I realize that, but I should've clarified above.  I was using it to repro https://github.com/dapr/dapr/issues/515.

It should not be failing a statestore.Get() though when the the len of items is 0.  That is still a problem which I'm fixing.

**Comment by LMWF** [comment]
> Only Redis and MongoDB are supported for actors.

Changed title a bit so someone reading it doesn't get the wrong idea.
