### ISSUE TITLE
Storage bindings data property as base64?

### ISSUE THREAD

**Issue by Inx51** [dapr/components-contrib#1331]
How come that the storage components (at least localstorage) handles the data as a json property with the data as a base64?
```
{
"operation":"create",
"data":"{base64}" <-- why this?
}
```
From my knowledge base64 increases the total size of data by around 33%, so a file of 10Mb will as base64 get increased to 13.3Mb.
A very large file of 1Gb would end up as 1.3Gb over the "wire", thats 300Mb of "wasted" bandwidth and CPU calc.
Why not simply use a more "REST-like" approach?

POST http://localhost:{dapr-port}/v1.0/bindings/{storage-component-name} = "operation":"create"
body as bytes

POST http://localhost:{dapr-port}/v1.0/bindings/{storage-component-name}/{fileName} = "operation":"create"
body as bytes

GET http://localhost:{dapr-port}/v1.0/bindings/{storage-component-name} = "operation":"list"

GET http://localhost:{dapr-port}/v1.0/bindings/{storage-component-name}/{fileName} = "operation":"get"

DELETE http://localhost:{dapr-port}/v1.0/bindings/{storage-component-name}/{fileName} = "operation":"delete"

This way you wouldnt have to stress the CPU with encoding bytes to a base64, and also put less stress over the "wire".

**Comment by rainfd** [comment]
Firstly, dapr only support json-schmea spec. Other components follow the same rule. Change the binding schmea for the specific component is not a good idea.
Secondly, base64 format is more safety. You can see some detail in this answer [Why do we use Base64?](https://stackoverflow.com/a/3538079/5509717)
