### ISSUE TITLE
Panic on azure blob storage state store

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#1351]
## Expected Behavior

Invalid Azure storage account name does not cause a panic and gives proper error message.

## Actual Behavior

Providing an invalid Azure storage account name to Azure storage state store causes panic.

![image](https://user-images.githubusercontent.com/130954/144105602-7f5ca996-75b2-49f8-af7d-ae46edc3f463.png)

## Steps to Reproduce the Problem

Use azure blob storage state store with an invalid account name

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
@Gehhilfe can you please comment here with `/assign`? Thanks!
