### ISSUE TITLE
mqtt metadata is not enough

### ISSUE THREAD

**Issue by dream2zz** [dapr/components-contrib#1367]
https://github.com/dapr/components-contrib/blob/cac03dbe874f6aee9148dc3002b734b8ea5d9c4f/bindings/mqtt/metadata.go#L8

there is need other field, just like  username,password , etc...  Reference: [ClientOptions](https://github.com/eclipse/paho.mqtt.golang/blob/77d851e09af4fbb4ab43624c033683e6070579b6/options.go#L61).

**Comment by daixiang0** [comment]
@Dream2zz are you willing to post a PR?
