### ISSUE TITLE
RabbitMQ: channel not initialized, even if channel exists

### ISSUE THREAD

**Issue by WhoAteDaCake** [dapr/components-contrib#1371]
## Expected Behavior
Dapr to send messages, since channel exists

## Actual Behavior

Dapr complains about. 
error in subscriber for scraper-scraper in ensureSubscription: channel not initialized"

## Steps to Reproduce the Problem

I'm not quite sure? It started happening since I've updated to 1.5.1

![logs](https://user-images.githubusercontent.com/16735813/145417059-c83b7213-0df3-4248-a2e9-d38b96582417.png)
![queue](https://user-images.githubusercontent.com/16735813/145417066-d6ebef6e-800a-4f0f-90fa-ee6646746bec.png)
![exchange](https://user-images.githubusercontent.com/16735813/145417074-ab674ea1-7253-47ee-a7db-63f3560d336c.png)

## Release Note

RELEASE NOTE:

**Comment by dmitsh** [comment]
@WhoAteDaCake , could you provide instructions on how to reproduce this issue?

**Comment by WhoAteDaCake** [comment]
Sorry, but I couldn't catch the exact scenario. I'll try to replicate over the weekend. It started happening as soon as I updated from 1.3.1 -> 1.5.1. We reverted back now and the issue has stopped

**Comment by dmitsh** [comment]
@WhoAteDaCake , I have a fix for #1372.
Could you try it with your test case by changing `daprd` image from `daprio/daprd:1.5.1` to `dmitsh/daprd:dev-rmq-linux-amd64` ?

**Comment by WhoAteDaCake** [comment]
It seems to be working as expected now. Thank you for your work @dmitsh

**Comment by andreatosato** [comment]
This not resolve my problem.

I create this branch repository: https://github.com/andreatosato/dapr-cloudchampion/tree/rabbitmq-error
```
time="2021-12-14T21:22:11.8985009Z" level=error msg="rabbitmq pub/sub: error in subscriber for cloudchampion-web-orderstatus in ensureSubscription: channel not initialized" app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

time="2021-12-14T21:22:11.8985535Z" level=warning msg="rabbitmq pub/sub: subscriber is reconnecting in 3s ..." app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

time="2021-12-14T21:22:14.9033483Z" level=info msg="rabbitmq pub/sub: connectionCount: current=0 reference=0" app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

time="2021-12-14T21:22:14.9135839Z" level=info msg="rabbitmq pub/sub: connected with connectionCount=1" app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

time="2021-12-14T21:22:14.9270754Z" level=info msg="rabbitmq pub/sub: declaring queue 'cloudchampion-web-orderstatus'" app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

time="2021-12-14T21:22:14.9488794Z" level=info msg="rabbitmq pub/sub: binding queue 'cloudchampion-web-orderstatus' to exchange 'orderstatus'" app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

time="2021-12-14T21:22:14.9622449Z" level=info msg="rabbitmq pub/sub: subscribe to topic/queue 'orderprocessed/cloudchampion-web-orderprocessed'" app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

time="2021-12-14T21:22:15.0300956Z" level=info msg="rabbitmq pub/sub: declaring queue 'cloudchampion-web-orderprocessed'" app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

time="2021-12-14T21:22:15.0657686Z" level=info msg="rabbitmq pub/sub: binding queue 'cloudchampion-web-orderprocessed' to exchange 'orderprocessed'" app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

time="2021-12-14T21:22:15.0776415Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 40594.8337ms" app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.runtime type=log ver=edge
```

/cc @dmitsh

**Comment by yaron2** [comment]
Reopened for now.

cc @artursouza

**Comment by dmitsh** [comment]
@andreatosato , could you elaborate what is the problem? From the log I can see that your application has connected to rabbitmq pub/sub.

**Comment by andreatosato** [comment]
When application start, DAPR must create topic on rabbit.
Then this is the error:

```
rabbitmq pub/sub: error in subscriber for cloudchampion-web-orderstatus in ensureSubscription: channel not initialized" app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge
```

**Comment by dmitsh** [comment]
> time="2021-12-14T21:22:11.8985535Z" level=warning msg="rabbitmq pub/sub: subscriber is reconnecting in 3s ..." app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

Right, but after that the component is reconnected:
time="2021-12-14T21:22:11.8985535Z" level=warning msg="rabbitmq pub/sub: subscriber is reconnecting in 3s ..." app_id=cloudchampion-web instance=c821022bbc95 scope=dapr.contrib type=log ver=edge

Does your application work as expected?

**Comment by andreatosato** [comment]
My sample don't work fine, this is my error application:
```
 Dapr.DaprException: Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
       ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="error when publish to topic orderstatus in pubsub pubsub: channel not initialized")
```

**Comment by dmitsh** [comment]
could you provide the steps to reproduce the error?

**Comment by andreatosato** [comment]
I create 3 topic in my sample.
I have clean rabbit (empty configuration, no exchange, no queue, no topic).

When start application for the first time, Dapr raise error.


In my sample, run docker compose, start web application.
I have only index page. 
Insert number, than text and click button... Application crash

**Comment by dmitsh** [comment]
could you be more specific with the steps?

**Comment by andreatosato** [comment]
From visual studio 2022:
- run docker compose
- open web container on index
- compile form
- - number
- - text
- - click button

Error appear

**Comment by andreatosato** [comment]
docker-compose  -f "C:\Users\AndreaTosato\Source\Repos\dapr-cloudchampion\docker-compose.yml" -f "C:\Users\AndreaTosato\Source\Repos\dapr-cloudchampion\docker-compose.override.yml" -f "C:\Users\AndreaTosato\Source\Repos\dapr-cloudchampion\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose2803362638168428963 --ansi never up -d --build --remove-orphans


This is command generated from VS 2022

**Comment by dmitsh** [comment]
> docker-compose -f "C:\Users\AndreaTosato\Source\Repos\dapr-cloudchampion\docker-compose.yml" -f "C:\Users\AndreaTosato\Source\Repos\dapr-cloudchampion\docker-compose.override.yml" -f "C:\Users\AndreaTosato\Source\Repos\dapr-cloudchampion\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose2803362638168428963 --ansi never up -d --build --remove-orphans

This command starts docker containers, but does not trigger the application flow.
Do you have to run your application on Windows? Is there a way to isolate the issue and reproduce it in a platform-agnostic way?

**Comment by dmitsh** [comment]
I think I found it. Could you try this image: `dmitsh/daprd:dev-rmq1-linux-amd64` ?

**Comment by andreatosato** [comment]
Works now!
Thanks @dmitsh 

Can you release dapr 1.5.2 this change?

**Comment by dmitsh** [comment]
> Can you release dapr 1.5.2 this change?

Most likely it will be released in 1.6 next month.

**Comment by yaron2** [comment]
> Works now! Thanks @dmitsh
> 
> Can you release dapr 1.5.2 this change?

@dmitsh is correct, this will go into 1.6.

**Comment by Hsuwen** [comment]
I also encountered this problem. It is easy to reproduce it, such as restart or replace rabbitMQ, and there is a high probability of the above error occurring in applications with subscriptions.
