### ISSUE TITLE
proposal: nameresolution add report API

### ISSUE THREAD

**Issue by 1046102779** [dapr/components-contrib#1398]
We need to enhance the capabilities of nameresolution. When nameresolution's ResolveID  method obtains the address of the Runtime service, if access to this address fails or times out, it should actively report to the nameresolution that the service address is unhealthy or unavailable.

```golang
+ // ReportRequest report unhealthy runtime server
+ type ReportRequest struct {
+         ID        string
+         Namespace string
+         Address   string
+         Port      int
+         Metadata  map[string]string
+ }
+ 

// Resolver is the interface of name resolver.
type Resolver interface {
        // Init initializes name resolver.
        Init(metadata Metadata) error
        // ResolveID resolves name to address.
        ResolveID(req ResolveRequest) (string, error)
+      // Report report unhealthy runtime server
+      Report(req ReportRequest) error
}
```

**Comment by 1046102779** [comment]
At the same time, we should support multiple name service instances, because all component instances of component-contribs have addressing features, so they can be provided to them, such as binding.http...

**Comment by daixiang0** [comment]
How users use Report API? If any error, it would return an error from `ResolveID`.

**Comment by 1046102779** [comment]
> How users use Report API? If any error, it would return an error from `ResolveID`.

Yes.  The Dapr Runtime took the initiative to inform namesolution of the call result, and let nameresolution process the failed request IP according to its own strategy

**Comment by daixiang0** [comment]
So Report API is used by Namesolution? Is it a common function for Namesolution?

**Comment by 1046102779** [comment]
> 

Yes. Nameresolution can start the fuse mechanism according to the reporting situation of  micrologic server, and Dapr Runtime can actively report, which can enhance the health status of micrologic server.

**Comment by daixiang0** [comment]
If so, sound like a good feature.

/cc @yaron2 @artursouza I accept it, WDYT?

@1046102779 are you interested in adding it?

**Comment by 1046102779** [comment]
> 
hah, of course. I'am a Dapr member.
