### ISSUE TITLE
Implement StateStore for the OCI ObjectStorage Service

### ISSUE THREAD

**Issue by lucasjellema** [dapr/components-contrib#1400]
## Describe the proposal
The OCI Object Storage Service is a cloud service on Oracle Cloud Infrastructure, very similar in nature to AWS S3 and Azure BlobStorage. This services support creating, retrieving, deleting objects that represent state. It has concurrency control through ETags. I believe that especially for Daprized applications running on OCI – either on OKE, the OCI container engine for Kubernetes or on a compute instance – it can be of value to leverage ObjectStorage as the state store. It is cheap, easily accessible and can easily be integrated into many technologies from within the OCI cloud as well as from elsewhere. 

I have described the implementation of a Dapr State Store component based on OCI Object Storage in an [article on Medium](https://lucasjellema.medium.com/composing-dapr-custom-state-store-component-for-oracle-cloud-object-storage-a4c2feb15b3). I  will shortly submit a PR with the implementation of this component.

The contribution will allow Dapr application operators to configure state store components backed by OCI Object Storage.

**Comment by yaron2** [comment]
Thanks @lucasjellema this will be a welcomed addition to Dapr and the very first Oracle Cloud component.

**Comment by yaron2** [comment]
Closed via https://github.com/dapr/components-contrib/pull/1401.
