### ISSUE TITLE
Add support to S3 based state store

### ISSUE THREAD

**Issue by israelevi-code** [dapr/components-contrib#1413]
i think it would be great if  a statestore that based on S3 API will be implemented - i would like to use minIO in my cluster and S3 protocol is anyway widely used.
In addition the state store API does not support streaming and i think that for large blobs its a must

Thanks

**Comment by daixiang0** [comment]
> In addition the state store API does not support streaming and i think that for large blobs its a must

Could you share more about this case? The size of the state data should not be big I think, is it a real case for you?

**Comment by israelevi-code** [comment]
The thing is that dapr doesn’t have different abstraction for in-memory store ( we are using redis via dapr API for storing session state data which is small ) vs persistent stores ( Mongo for documents and MinIO for blobs).
Blobs in our system are neural networks models that might take hundreds of MB’s each. A train server save those models inside minIO and the key is passed to the runtime services that use it for serving.
It would be nice if we would be able to use dapr API also for loading those models at runtime
