### ISSUE TITLE
Dapr RabbitMQ binding failing

### ISSUE THREAD

**Issue by skmaingi** [dapr/components-contrib#1431]
## Expected Behavior

Invoke microservice using RabbitMQ binding without failure.

## Actual Behavior

RabbitMQ Binding is failing when the system remains idle for several hours leading to RabbitMQ - Dapr connection getting closed.

RabbitMQ Log:

```
2022-01-06 10:48:55.460 [warning] <0.5618.44> closing AMQP connection <0.5618.44> (10.42.0.132:39128 -> 10.42.0.227:5672, vhost: '/', user: 'dapr'):

client unexpectedly closed TCP connection
.
.
.
2022-01-06 10:48:55.461 [info] <0.17915.47> Closing all channels from connection '10.42.0.132:39130 -> 10.42.0.227:5672' because it has been closed

2022-01-06 10:48:55.461 [info] <0.17917.47> Closing all channels from connection '10.42.0.132:32814 -> 10.42.0.227:5672' because it has been closed
```
[rabbitmq log.txt](https://github.com/dapr/components-contrib/files/7841577/rabbitmq.log.txt)

## Steps to Reproduce the Problem

1. Deploy dapr v1.4.3-1.5.0 on k8s cluster
```
helm repo add dapr https://dapr.github.io/helm-charts/
helm repo update
helm install dapr dapr/dapr \
--version=1.5 \
--namespace dapr-system \
--create-namespace \
--wait
```
2. Deploy RabbitMQ on k8s
3. Deploy RabbitMQ binding component on k8s cluster
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name:test-api
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
    - name: queueName
      value: myqueue
    - name: host
      secretKeyRef:
        name: rabbitmq-secret
        key: HOST
    - name: durable
      value: true
    - name: deleteWhenUnused
      value: false
    - name: prefetchCount
      value: 0
```
3. Deploy daprized microservice created using Fast API framework on k8s
_main.py_
```
import os
import json
from typing import List, Optional
from fastapi import FastAPI, Request, Response
from pydantic import BaseModel

app = FastAPI()

class Topic(BaseModel):
    title: str
    author: str

@app.api_route("/test-api", methods=['OPTIONS'], status_code=200)
def test_api_binding():
    return {'success': True}

@app.post(path="/test-api", status_code=200)
def perform_task(topic: Topic):
    # Method to perform task for a topic
    # :return: json
    print(f"Request to perform task for topic {topic.title}", flush=True)
    return {'success': True}
```
Docker CMD: `uvicorn main:app`
4. Trigger the microservice using binding
```
from dapr.clients import DaprClient

with DaprClient() as d:
    resp = d.invoke_binding(name='test-api', operation='create', data='{"title":"Test","author":"Dev"}')
```
5. Let the system remain idle for over 24 hours
6. Try to trigger the microservice again using binding

## Release Note

RELEASE NOTE: **FIX** RabbitMQ - Dapr Connection Bug.

**Comment by dmitsh** [comment]
@skmaingi, I was able to deploy the setup. Is there a way to decrease the duration of the test cycle?

**Comment by dmitsh** [comment]
@skmaingi, I could not to reproduce the issue after 24 hours.

My k8s cluster runs in AKS, and I'm using Bitnami's char to deploy RabbitMQ:
```
helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo

helm install dapr-demo azure-marketplace/rabbitmq ...
```

The main difference is that I'm running the latest dapr code, and not v1.5.
The new dapr release v1.6 is expected in the upcoming weeks.
In the meantime, could you try my custom image `docker.io/dmitsh/dapr:dev-linux-amd64` and see whether you could reproduce the issue in your environment?

**Comment by skmaingi** [comment]
> @skmaingi, I was able to deploy the setup. Is there a way to decrease the duration of the test cycle?

Hi @dmitsh,. We have tasks that will run for over 24 hours i.e. perform_task(topic: Topic). When those tasks run, the system could remain idle for hours waiting for other requests to process

**Comment by skmaingi** [comment]
> @skmaingi, I could not to reproduce the issue after 24 hours.
> 
> My k8s cluster runs in AKS, and I'm using Bitnami's char to deploy RabbitMQ:
> 
> ```
> helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo
> 
> helm install dapr-demo azure-marketplace/rabbitmq ...
> ```
> 
> The main difference is that I'm running the latest dapr code, and not v1.5. The new dapr release v1.6 is expected in the upcoming weeks. In the meantime, could you try my custom image `docker.io/dmitsh/dapr:dev-linux-amd64` and see whether you could reproduce the issue in your environment?

Thank you @dmitsh. I will test with your custom image

**Comment by skmaingi** [comment]
@dmitsh could this issue be related to this https://github.com/dapr/dapr/issues/2301
There is a timeout error we get for tasks that take several hours or days to complete.
```
2022-01-06 10:49:01.089 [info] <0.18126.47> connection <0.18126.47> (10.42.0.134:33468 -> 10.42.0.227:5672): user 'dapr' authenticated and granted access to vhost '/'
2022-01-06 11:19:03.607 [warning] <0.18136.47> Consumer ctag-/daprd-3 on channel 1 has timed out waiting for delivery acknowledgement. Timeout used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more
2022-01-06 11:19:03.608 [error] <0.18136.47> Channel error on connection <0.18126.47> (10.42.0.134:33468 -> 10.42.0.227:5672, vhost: '/', user: 'dapr'), channel 1:
operation none caused a channel exception precondition_failed: delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more
```

**Comment by dmitsh** [comment]
@skmaingi, I deployed Dapr v1.5.0 but still could not reproduce the error in my setup.
I suspect that closing the channel happens in rabbitmq container independently of Dapr.

How do you deploy rabbitmq service? What version?

Regarding dapr/dapr#2301 I'm not sure this is the case. IIUC, you are sending data to rabbitmq, which is output binding functionality.

**Comment by skmaingi** [comment]
@dmitsh 
RabbitMQ deployment
 ```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install rabbitmq -f values.yaml bitnami/rabbitmq -n <namespace>
```
values.yaml
```
auth:
  username: <USERNAME>
  password: <PASSWORD>
  erlangCookie: <COOKIE>
persistence:
  enabled: false
replicaCount: 1
extraConfiguration: |-
  log.file.level = debug
  max_message_size = 512000000
```

**Comment by dmitsh** [comment]
@skmaingi, I checked the binding code and confirmed that dapr does not close any channels. So I'm pretty convinced the closure of the channel happens outside dapr.

Where do you run your k8s cluster, on site or in the cloud?
If you are using AKS, please try Bitnami's version of RabbitMQ for AKS:
```
helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo
helm install dapr-demo azure-marketplace/rabbitmq ...
```
I also checked parameters of my rabbitmq deployment and found one difference, compared to yours:
```
persistence:
  enabled: true
```

**Comment by skmaingi** [comment]
Thank you @dmitsh 
I noticed timeout exception in RabbitMQ logs after binding request. 
```
2022-01-06 10:49:01.089 [info] <0.18126.47> connection <0.18126.47> (10.42.0.134:33468 -> 10.42.0.227:5672): user 'dapr' authenticated and granted access to vhost '/'
2022-01-06 11:19:03.607 [warning] <0.18136.47> Consumer ctag-/daprd-3 on channel 1 has timed out waiting for delivery acknowledgement. Timeout used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more
2022-01-06 11:19:03.608 [error] <0.18136.47> Channel error on connection <0.18126.47> (10.42.0.134:33468 -> 10.42.0.227:5672, vhost: '/', user: 'dapr'), channel 1:
operation none caused a channel exception precondition_failed: delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more
```

**Comment by skmaingi** [comment]
@dmitsh You are right "I suspect that closing the channel happens in rabbitmq container independently of Dapr."

I read this from RabbitMQ [consumers link]( https://www.rabbitmq.com/consumers.html)

"Delivery Acknowledgement Timeout

In modern RabbitMQ versions, a timeout is enforced on consumer delivery acknowledgement. This helps detect buggy (stuck) consumers that never acknowledge deliveries. Such consumers can affect node's on disk data compaction and potentially drive nodes out of disk space.

If a consumer does not ack its delivery for more than the timeout value (30 minutes by default), its channel will be closed with a PRECONDITION_FAILED channel exception. The error will be logged by the node that the consumer was connected to."

**Comment by dmitsh** [comment]
Thank you for confirming, @skmaingi . Do you require any further assistance?

**Comment by skmaingi** [comment]
@dmitsh currently no. I made some updates to test consumer timeout. 
Thank you very much for your support and assistance in troubleshooting the issue.
