### ISSUE TITLE
After using redis as pubsub, the message will not be deleted after being processed by the subscriber

### ISSUE THREAD

**Issue by zhenlei520** [dapr/components-contrib#1436]
After dapr uses redis as pubsub, after the message is processed by the subscriber, the message will be processed by the ACK mechanism, but the processed message is not deleted. This lacks the function of deleting the message that has been consumed. Currently, it only supports setting maxlen to ensure the total length of the Stream, but doing so will waste space. It is recommended to increase the parameters to control the consumed messages will be automatically deleted after a certain period of time

https://github.com/dapr/components-contrib/blob/3c28fee80f1cbf7c37df2854836cc3bc8660f9e3/pubsub/redis/redis.go#L246-L267

**Comment by zhenlei520** [comment]
After the message is processed, the ACK mechanism will be used to prevent repeated consumption, but it does not delete the processed message. I hope to add a function that the message will be deleted after a certain period of time after consumption, or provide a message to be deleted after a certain period of time. Option to delete immediately after consumer consumes

**Comment by Taction** [comment]
When multiple services subscribe to the same topic, it can be difficult to determine an appropriate time to delete messages. In particular, it is difficult to determine whether messages should be deleted when one of these services is down. What do you think?

Redis pubsub has a `maxLenApprox` metadata defined maximum number of items inside a stream, does this meet your needs? You can refer to here: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/#spec-metadata-fields

**Comment by zhenlei520** [comment]
> When multiple services subscribe to the same topic, it can be difficult to determine an appropriate time to delete messages. In particular, it is difficult to determine whether messages should be deleted when one of these services is down. What do you think?
> 
> Redis pubsub has a `maxLenApprox` metadata defined maximum number of items inside a stream, does this meet your needs? You can refer to here: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/#spec-metadata-fields

When multiple services subscribe to the same topic, if some services are not started, redis does not know that there are still services that are not executed, and after the message is acked, when the previously unstarted service is restarted, the message that has been acked is still acked. Will it be redelivered?

**Comment by Taction** [comment]
Services with deferent `consumerID `(defaults to appid if not set) are independent when consuming messages. So if `multiple services` have different appid, messages will be redelivered.

**Comment by Taction** [comment]
@zhenlei520 You can refer to here for more details: https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#consumer-groups-and-competing-consumers-pattern

**Comment by zhenlei520** [comment]
Yes, what you said makes sense, but if you specify maxLenApprox, when the accumulation exceeds the number, it will also be deleted without delivery.

I checked the introduction of Streams in the redis documentation, and I think this is caused by the problem of redis. If redis can provide a function of binding a consumer group to a message, it will be fine. Bind the consumer group to the message when the system starts. When all consumer groups in the message are acked, it is the best way to stay for a certain period of time before being deleted.
