### ISSUE TITLE
Hashicorp vault secret path is fixed, not configurable. Request a feature to enable configurable secrets engine.

### ISSUE THREAD

**Issue by tarrantro** [dapr/components-contrib#1439]
## Describe the feature

Now, dapr hashicorp secretstore is hardcoded secret engine(secret). So the secretstore can only access keyvault path named after secret/xxx. If I have a vault path like kv2/xxx/xxx. I will not be able to use this secretstore. 

code: csecretstores/hashicorp/vault/vault.go, 180
	vaultSecretPathAddr := fmt.Sprintf("%s/v1/secret/data/%s/%s?version=0", v.vaultAddress, v.vaultKVPrefix, secret)

business value. In many companies that using HSV, they will have multiple path that is not based on secret/xxx. might be kv2/depart1, kv2/depart2, kv3/depart3....you can't use fixed secret engine because that will not allow flexibility.

## Release Note

RELEASE NOTE:

**Comment by Taction** [comment]
Thanks for reporting this. In fact, there is a related pr #842. Added engine path metadata.

**Comment by tarrantro** [comment]
Thanks for the reply, I checked the PR and seems it will add vaultEnginePath in new HSV component for engine path. Just want to know when will it be release? Do we have schedule?












Original



From:"Taction"< ***@***.*** &gt;;

Date:2022/1/16 9:56

To:"dapr/components-contrib"< ***@***.*** &gt;;

CC:"290535018"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [dapr/components-contrib] Hashicorp vault secret path is fixed,not configurable. Request a feature to enable configurable secrets engine.(Issue #1439)







Thanks for reporting this. In fact, there is a related pr #842. Added engine path metadata.

&amp;mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Taction** [comment]
@tarrantro will be merged in the next release version v1.7.

**Comment by Taction** [comment]
Close since the related pr has been merged.
