### ISSUE TITLE
No option to configure which IP type to listen on for mDNS

### ISSUE THREAD

**Issue by jjcollinge** [dapr/components-contrib#1468]
## Expected Behavior
User's can configure which IP type (IPv4/IPv6) they want Dapr to listen on for mDNS discovery. This should default to both as is done today using the zeroconf default but have an option to exclude either type.

## Actual Behavior
Only supports listening on both, this causes issues if no interface is available.

## Release Note

RELEASE NOTE: ADD Configuration to set which interface type mDNS listens on.

**Comment by jjcollinge** [comment]
Uploading initial report for context
![image](https://user-images.githubusercontent.com/7241190/152123784-20cd325a-2644-443e-ba42-925f4fc2e934.png)

**Comment by jjcollinge** [comment]
Looking into this more, the initial log when registering is expected as this behaviour was introduced in [this change](https://github.com/grandcat/zeroconf/commit/be8fc7be298c73e239ec340e0fd6a0499a077ce9#diff-366e46a40f6f60b4f7614eb0976bb51820364bf5ca6ccc4787eb49d7bdbef3e6). However, when trying to resolve a service we currently use the default zeroconf value which is to use IPv4 and IPv6 which will fatally error if no IPv6 interface is available.

One option would be to add MDNS config that a user can use to disable either ipv4 or ipv6 but not both. This is straight forward enough for service resolution. On the service registration front we have 2 options. Leave the current default logic that registers a service on any interfaces it finds on the host machine (this leads to that log message when either IPv4 or IPv6 is not available) but will still work. Or in Dapr we fetch all the interfaces from the kernel, iterate through them and filter out interfaces without IPv4 or IPv6 addresses based on the provided MDNS configuration. In addition, we'd need to account for the MDNS configuration conflicting with the actual available interfaces. If a user disables IPv4 to listen on IPv6 but the kernel doesn't have an interface with an IPv6 address then we'll have to crash.
We could avoid this by simply not allowing the user any MDNS config and just checking upfront whether IPv4 or IPv6 is available and then registering and resolving based on that. This option should be much simpler but is a lot less flexible. 
@yaron2 WDYT?

**Comment by mukundansundar** [comment]
@jjcollinge Thanks for looking into this. Based on the code in zeroConf, there is a possibility of specifying which IP type to use on resolver creation. Similarly I think we can specify which IP to use during service registration also. 

The main difference that I see between option 1 and 2 is that 2 chooses the interface if its there and uses it without any user intervention, whereas option 1 provides the user a choice to disable one of the IP types. I believe that providing the option for the user to configure while keeping existing behaviour intact is better. 

In this case I would suggest option 1b. 
- Leave existing logic for registration and resolver creation as such if no config is provided from the user. (Preserving existing use behaviour).
- Add a config `disableIPv6` to disable IPv6 alone and have IPv4 as the default "always on" interface to listen for.
- Change logic in code such that during registration and resolver creation, the disabled interfaces are filtered out. 

/cc @yaron2 @berndverst @artursouza thoughts?
