### ISSUE TITLE
process component vault error: couldn't create client using config: couldn't read system certs: crypto/x509: system root pool is not available on Windows

### ISSUE THREAD

**Issue by pravinparab** [dapr/components-contrib#1469]
Hi Team,

We are trying to configure Hashicorp Vault component in Dapr. Following is the configuration of vault.yaml file.
We are getting **process component vault error: couldn't create client using config: couldn't read system certs: crypto/x509: system root pool is not available on Windows** error msg while running dapr side car service.
Let us know if any changes required.

=====================================================================================

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: http://127.0.0.1:8200
  - name: skipVerify
    value: true
  - name: vaultToken # Required if vaultTokenMountPath not provided. Token value.
    value : "s.qgtgKVzPgrQc9NRs1wKuPX0K"
  - name: vaultKVPrefix # Optional. Default: "dapr"
    value : "cred"
  - name: vaultKVUsePrefix # Optional. default: "true"
    value: "true"

**Comment by Taction** [comment]
This is because the vault component will always load the tls configuration whether it is used or not. I have created pr #842 which fixes this issue, if `skipVerify` is true the tls config will not be loaded.

Can we consider merging this pr in v1.7? /cc @artursouza

**Comment by yaron2** [comment]
> This is because the vault component will always load the tls configuration whether it is used or not. I have created pr #842 which fixes this issue, if `skipVerify` is true the tls config will not be loaded.
> 
> Can we consider merging this pr in v1.7? /cc @artursouza

Sure, we can merge this in 1.7. I left a docs question on the PR.

**Comment by artursouza** [comment]
See my comments in the PR. We also would need to add vault to conformance tests for secret store. This will help make sure we don't break existing users.

**Comment by Taction** [comment]
Sorry for the late reply as I was on vacation. I created another issue #1485 to track this. Besides vault needs init as well as save the test data to it, I have viewed the conformance tests code and have not found a proper place(or any examples) to do these before running the test code, any suggestions about it?

> See my comments in the PR. We also would need to add vault to conformance tests for secret store. This will help make sure we don't break existing users.

**Comment by Taction** [comment]
This can be Closed since the related pr has been merged.

**Comment by berndverst** [comment]
closed by https://github.com/dapr/components-contrib/pull/842
