### ISSUE TITLE
Close method on Resolver interface

### ISSUE THREAD

**Issue by jjcollinge** [dapr/components-contrib#1472]
## Ask your question here
I'm not sure if there's already been discussions around this topic (I can't find any) - is there any reason we cannot add a `Close()` method to the [`resolver`](https://github.com/dapr/components-contrib/blob/8297fc929bc602156eb19daf76c2282c4bbf268a/nameresolution/nameresolution.go#L17) interface to allow any components that use stateful services to unregister? This would allow Consul and mDNS to shutdown correctly without leaving orphaned services. The change would be additive (non-breaking) so was wondering if anyone else had looked into this and found a good reason not to add this?

**Comment by daixiang0** [comment]
Agree to add it.

**Comment by mukundansundar** [comment]
Agree to this. 

@dapr/maintainers-components-contrib 
Labels to add: P1 size:xs good-first-issue area/runtime/nameresolution triaged/resolved

**Comment by jjcollinge** [comment]
I'm happy to implement this @mukundansundar - could you please assign me so I can track it.

**Comment by mukundansundar** [comment]
@jjcollinge please use `/assign` to assign yourself to the issue.

**Comment by mukundansundar** [comment]
not-stale

**Comment by berndverst** [comment]
Not marking this as "good first issue" because it also requires updating the dapr/dapr, and coordinating the changes is cumbersome.

**Comment by ItalyPaleAle** [comment]
@berndverst We don't necessarily need to update the interface for this. It can be implemented as an optional `Close() error` method.

The runtime is already checking, upon termination, if components implement `io.Closer` (e.g. `Close() error`), and if they do, it invokes them:

https://github.com/dapr/dapr/blob/ccce9e451a4b96d1d21a7688196ee7aa89654d6f/pkg/runtime/runtime.go#L2652-L2660

**Comment by berndverst** [comment]
> @berndverst We don't necessarily need to update the interface for this. It can be implemented as an optional `Close() error` method.
> 
> The runtime is already checking, upon termination, if components implement `io.Closer` (e.g. `Close() error`), and if they do, it invokes them:
> 
> https://github.com/dapr/dapr/blob/ccce9e451a4b96d1d21a7688196ee7aa89654d6f/pkg/runtime/runtime.go#L2652-L2660

That works.

**Comment by ItalyPaleAle** [comment]
I think this issue can be closed.

mDNS already implements the Close() method that disposes of resources.

Consul doesn't, but if that's needed, IMHO that's an issue specific to the component and not about the general interface for the resolvers. So should be a separate issue...

**Comment by artursouza** [comment]
It was done a while ago, marked as closed and moved to 1.10 since @ItalyPaleAle suggested that might be the correct timeline for that change.
