### ISSUE TITLE
Update darabonba-openapi for meeting compliance requirements

### ISSUE THREAD

**Issue by shubham1172** [dapr/components-contrib#1477]
**Problem**

https://github.com/alibabacloud-go/darabonba-openapi currently uses https://github.com/alibabacloud-go/alibabacloud-gateway-spi which is unlicensed. There is an active PR in the repository to add an Apache license, https://github.com/alibabacloud-go/alibabacloud-gateway-spi/pull/1

**To do**
- track updating `alibabacloud-gateway-spi` in `darabonba-openapi`
- update the `darabonba-openapi` version in this repository

Ref https://github.com/dapr/dapr/issues/4158

**Comment by yaron2** [comment]
@beiwei can you help eith

**Comment by yaron2** [comment]
@beiwei30 can you help getting this PR merged? https://github.com/alibabacloud-go/alibabacloud-gateway-spi/pull/1

**Comment by shubham1172** [comment]
Hi @beiwei30, can you please have a look at https://github.com/alibabacloud-go/alibabacloud-gateway-spi/pull/1?

**Comment by shubham1172** [comment]
External PRs
- https://github.com/alibabacloud-go/alibabacloud-gateway-spi/pull/2
- https://github.com/alibabacloud-go/darabonba-openapi/pull/2
