### ISSUE TITLE
Streaming support for object storage bindings (S3, Blob Storage, GCP Buckets)

### ISSUE THREAD

**Issue by kamilzzz** [dapr/components-contrib#1487]
As I can see, right now bindings for object storages support either writing a text as a blob or any blob data by encoding it as `base64`.
The same goes for reading where we can read either a plain value of a blob or `base64` encoded value.

In both cases whole file/blob has to be read into memory and then it can be uploaded (in case of writing) or processed (in case of reading).

Are there any plans to support streaming for object storage bindings so we don't have to keep whole blobs in memory?

**Comment by israelevi-code** [comment]
Totally agree , also regarding S3 , can the binding be more general to any S3 API provider (like minIO) and not just AWS?
