### ISSUE TITLE
Add support to partition keys in supported components when publishing

### ISSUE THREAD

**Issue by fbeltrao** [dapr/components-contrib#149]
EventHubs and Kafka (maybe others) have the option to define a partition key when publishing an event. By defining a partition key producer can ensure event ordering for related items (i.e. events from user '123' end up in same partition).

Proposal:
- Using optional "partitionKey" in output binding/publisher metadata to define a value. This would handle scenarios where the key is a string. Scenarios where the partition key is another type wouldn't be supported.

Would be glad to jump into it, if you feel it is a good addition.

**Comment by artursouza** [comment]
Hi. There is a broader discussion on redesigning the PubSub API for dapr. This is one of the new features. Please, include this in the discussion and close this as duplicate. I see that you are part of that discussion too.

Reference: https://github.com/dapr/dapr/issues/843

**Comment by fbeltrao** [comment]
Moving discussion to dapr/dapr#843

**Comment by artursouza** [comment]
BTW, Maybe you can tackle this as part of item number 3 in dapr/dapr#843. It will create a way for the publisher to add optional special fields that Dapr will understand. One of them is PartitionKey, another one is MessageID and more to come.
