### ISSUE TITLE
statestore query API: remove 'value' prefix from the key names in query JSON

### ISSUE THREAD

**Issue by dmitsh** [dapr/components-contrib#1490]
I propose a minor change in the syntax of the query JSON format.
This will eliminate unnecessary ambiguity.

Here is an example of the current query JSON object:
 ``` json
{
  "filter": {
    "IN": { "value.person.org": [ "Dev Ops", "Hardware" ] }
  }
}
```

This query returns all entries with jsonPath `.person.org` equals to `Dev Ops` or `Hardware`.
Notice that `value` prefix in the filter of the query JSON is not part of the original user object, which looks like that:
```json
{
  "person": {
    "org": "Dev Ops",
    "id": 1036
  },
  "city": "Seattle",
  "state": "WA"
}
```

IMO, it is not straightforward for a user to include `value` prefix in the jsonPath when they compose a query.
Therefore I would suggest dropping this prefix.
 
That would change the example above to:
```json
{
  "filter": {
    "IN": { ".person.org": [ "Dev Ops", "Hardware" ] }
  }
}
```
https://github.com/dapr/docs/issues/2191

**Comment by berndverst** [comment]
I strongly support this proposal.

If we proceed with this, please coordinate change of SDK E2E tests prior to the runtime release which will include this change.

**Comment by msfussell** [comment]
I like this approach, but why do you need to keep the "." in front of person? can it be this?

{
  "filter": {
    "IN": { "person.org": [ "Dev Ops", "Hardware" ] }
  }
}

**Comment by dmitsh** [comment]
> I like this approach, but why do you need to keep the "." in front of person? can it be this?
> 
> { "filter": { "IN": { "person.org": [ "Dev Ops", "Hardware" ] } } }

I've been following JSON path format, which seems appropriate when querying JSON objects.
