### ISSUE TITLE
can supports rabbitmq pubsub set exchangekind?

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1502]
Currently, exchangekind is fixed as fanout https://github.com/dapr/components-contrib/blob/7fdebda09b7177dca38137744b9240ed3b223885/pubsub/rabbitmq/rabbitmq.go#L33

Hope to support `exchangekind = topic` and event name as routing key
I see a similar merge request, but it has been closed  #573

**Comment by yaron2** [comment]
This is currently not possible. The PR above was closed due to the author being unresponsive. Would you like to open a PR for this? You can use the code in that PR that refers to the exchange metadata.

**Comment by Taction** [comment]
@saber-wang Currently, when using rabbitmq, an exchange will be created for every topic. What are you want is multiple topics to use the same exchange and use the topic to be the routing key? If this is the case, maybe you can try https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-route-messages/

**Comment by Taction** [comment]
`exchangekind` can be supported. Just a small change, the routing key needs to be set from metadata. For example, app with config:
```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order_pub_sub
spec:
  topic: B
  route: /B
  pubsubname: pubsub
  metadata:
    routingKey: keya
``` 

and if client send messages by 
```
client.PublishEvent(context.Background(), "pubsub", "B", []byte("this is a message"), dapr.PublishEventWithMetadata(map[string]string{"routingKey": "keya"}))
```
these messages will be received by the app. While these messages with another routing key will not be received by the app: 
```
client.PublishEvent(context.Background(), "pubsub", "B", []byte("this is a message"), dapr.PublishEventWithMetadata(map[string]string{"routingKey": "keyb"}))
```

And this is not a breaking change, the default behavior will act as before.

**Comment by yaron2** [comment]
Thanks for fixing this @Taction. If docs changes are needed, please make sure to submit a PR to the docs repo.

**Comment by Taction** [comment]
Sure, PR has been submitted to the docs repo.
