### ISSUE TITLE
[question] can I contribute a Publish component about dis to this repo

### ISSUE THREAD

**Issue by Shoothzj** [dapr/components-contrib#1504]
Hello, dapr community, can I contribute a Publish component about dis to this repo pubsub? It can allow applications to produce message to Huawei Cloud dis.
About Huawei Cloud Dis:  https://www.huaweicloud.com/en-us/product/dis.html

**Comment by yaron2** [comment]
Yes, that'll be a welcome addition.

**Comment by yaron2** [comment]
@Shoothzj are you working on this?

**Comment by Shoothzj** [comment]
@yaron2 yes, I am working on this, I was blocked for waitting huawei-dis go client feature.

**Comment by Shoothzj** [comment]
https://github.com/huaweicloud/huaweicloud-sdk-go-v3/issues/51
