### ISSUE TITLE
[Proposal][Vote-required] Removal of Postmark binding

### ISSUE THREAD

**Issue by shubham1172** [dapr/components-contrib#1510]
## Description

This proposal is to vote for removing the Postmark binding from components-contrib.

|Name| Type| Status| Component version| Introduced in|
|--|--|--|--|--|
|Postmark| Output| Alpha| v1| 1.0|

https://docs.dapr.io/reference/components-reference/supported-bindings/

### Background

Per https://github.com/dapr/dapr/issues/4158, we found that the current postmark library https://github.com/keighl/postmark is non-compliant due to its non-standard license, and the last activity on that repo was in 2019. 

Postmark has no official go library and the listed [community libraries](https://postmarkapp.com/developer/integration/community-libraries#google-go) are not maintained.

There is another fork on https://github.com/keighl/postmark, https://github.com/mrz1836/postmark, which is actively maintained, has a standard MIT license, but is not popular (in terms of stars/forks). Given that it's not officially listed as a community library too, this alternate seems unfit (see discussions on #1484, related: #1474).

Please vote with 👍or 👎on this issue for casting your vote, and please let me know in comments if you have any other suggestions.

**Comment by yaron2** [comment]
Based on your comment here https://github.com/dapr/components-contrib/pull/1484#issuecomment-1039830139, @shubham1172 , I don't see any valid reason to remove the binding, since there is a path forward with a library that meets CNCF expectations.

**Comment by yaron2** [comment]
> Yes @yaron2, while that is true, @berndverst suggested that while the fork meets CNCF requirements, it's neither a popular one and nor is listed as a community library by Postmark. It might be a risk for maintainers. Thoughts?

The term "popular" in this context is highly subjective without clear value, and as such, in this case, hardly a good criteria item for the removal. As a maintainer, what's important for me in terms of de-risking a library is seeing that the package is actively maintained (ie. commits within past 12 months) and has a correct license in place.

Based on this latest info, I will not support removal of the binding. You can re-open the closed PR that updates the binding package, or if you cannot do so, please let me know and I'll submit a PR. Thanks for looking into this!

**Comment by artursouza** [comment]
Based on Yaron's insights. I vote not to remove this component. We should change the dependency instead.

**Comment by shubham1172** [comment]
Closing this issue in favor of replacing the library. I will reopen my PR.
