### ISSUE TITLE
consul load balancer 

### ISSUE THREAD

**Issue by lysilver** [dapr/components-contrib#1513]
Dapr registers with Consul. After the same appid, one service takes the place of the first service

## Expected Behavior

load balancer

## Actual Behavior

Dapr registers with Consul. After the same appid, one service takes the place of the first service  #1199

dapr version 1.5

```
return &consul.AgentServiceRegistration{
		Name:    appID,
		Address: host,
		Port:    appPortInt,
		Checks:  cfg.Checks,
		Tags:    cfg.Tags,
		Meta:    cfg.Meta,
	}, nil
```

**Comment by geffzhang** [comment]
The same problem was found
