### ISSUE TITLE
Add transactional capabilities to cloud-based state stores: CosmosDB

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#152]
## Describe the proposal

In order to support actors in Azure, AWS and GCP environments, we need to enable transactional capabilities for the cloud-native state stores.

Related to https://github.com/orgs/dapr/projects/12

**Comment by anuragprafulla** [comment]
@yaron2 Can I give this a try?

**Comment by yaron2** [comment]
> @yaron2 I would like to take this up!

But of course. Starting with CosmosDB will be best. It needs to support multi operation transactions, meaning update/deletes in the same transaction.

It's ok to do it with stored procedures.

**Comment by amanbha** [comment]
@anuragprafulla Given that the issue is little old, so just checking if you are planning to pick it up

**Comment by msfussell** [comment]
This is to add other transactional state stores that can be used by  Actors. Today only Redis and Mongo DB are supported and ideally we need a cloud state store in each public cloud.
