### ISSUE TITLE
[Azure][Track 2 SDK] Migrate Azure Blob Storage Binding

### ISSUE THREAD

**Issue by berndverst** [dapr/components-contrib#1530]
Migrate Azure Blob Storage Binding to SDK github.com/Azure/azure-sdk-for-go/sdk/storage/azblob

**Comment by berndverst** [comment]
Latest status on this:

Not currently possible due to
- [ ] https://github.com/Azure/azure-sdk-for-go/issues/17152
- [ ] https://github.com/Azure/azure-sdk-for-go/issues/17061
- [ ] https://github.com/Azure/azure-sdk-for-go/issues/16679

**Comment by ItalyPaleAle** [comment]
Current blocker: https://github.com/Azure/azure-sdk-for-go/issues/17850
