### ISSUE TITLE
add certification tests for Redis

### ISSUE THREAD

**Issue by dmitsh** [dapr/components-contrib#1534]
This is a follow-up on https://github.com/dapr/components-contrib/pull/1488.

- create certification tests for Redis
- include tests for querying of JSON objects.

**Comment by artursouza** [comment]
Moving this to 1.8 milestone.

**Comment by artursouza** [comment]
Please, compare to MongoDB test plan.

**Comment by DeepanshuA** [comment]
Test Plan:

-Basic Test for CRUD operations:
	1. Able to create and test connection.
	2. Able to do set, fetch, update and delete.
	3. Negative test to fetch record with wrong values.
	4. Negative test to insert a record withput manadatory fields.
	5. Insert record with Out of Order mandatory fields.

-Test save or update data with differert TTL settings:
	1. TTL not expiring
	2. TTL not a valid number

- Use Redis as actor state store
- SQL injection tests
- Component must retry / reconnect when server or network errors are encountered

**Comment by mukundansundar** [comment]
@artursouza @berndverst @yaron2 Can you take a look at this?

**Comment by artursouza** [comment]
LGTM. Please, provide more detail on the test for transaction.
