### ISSUE TITLE
redis output binding only support "create" operation?

### ISSUE THREAD

**Issue by haobiaosheng** [dapr/components-contrib#1536]
I am follow this guide:https://docs.dapr.io/reference/components-reference/supported-bindings/redis/,
in this page, I found that, redis output binding only support create operation, and if a dapr app with redis output binding, and exec the create operation, how the dapr app to get the redis content after insert the redis key ? Do use the redis library to query the keys?I seems a litter strange，create the redis key with the redis output binding using the create operation, and app no need to use the redis library in their logic code, but when to get the redis key,app needs to use redis library to query?

**Comment by darren-wang** [comment]
that's true.

i THINK that's why it is the BINDING component instead of the STATE component.

**Comment by haobiaosheng** [comment]
> that's true.
> 
> i THINK that's why it is the BINDING component instead of the STATE component.

I am sorry, I don't understand yet
