### ISSUE TITLE
How to set connection pool properties for state.mongo?

### ISSUE THREAD

**Issue by darren-wang** [dapr/components-contrib#1543]
state.redis provides pool properties like `poolSize` and so on:

https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/

However, there is no whre to configure state.mongo:

https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-mongodb/

I found commit :

https://github.com/dapr/components-contrib/pull/216/commits/2c890d30b58018913c477c2a966d92b39e367892

seems using `params` to pass addtional params but it's not recorded in state.mongo's  official doc above.

So, should `params` be add to the available fields to state.mongo and should it be used to confiure connection pool related properties?

**Comment by Taction** [comment]
@darren-wang `params` is not used for setting the connection pool. state.mongo component's metadata can be extended to support connection pool settings, are you interested in submitting a pr for this?

**Comment by darren-wang** [comment]
> @darren-wang `params` is not used for setting the connection pool. state.mongo component's metadata can be extended to support connection pool settings, are you interested in submitting a pr for this?

I think metadata is session scoped and is not really appropriote for setting connection pools, the best way should be like state.redis to provide extended connection pool fields.

**Comment by Taction** [comment]
I am referring to component level metadata, the state.redis's `poolSize` is also under component level metadata. And I have had a quick view about MongoDB client, its connection pool config can be set by `SetMaxPoolSize` and `SetMinPoolSize` (https://github.com/mongodb/mongo-go-driver/blob/master/mongo/options/clientoptions.go#L578), Is that what you want?

**Comment by darren-wang** [comment]
@Taction I red the source code of mongo-driver-go and state.mongo component, found that `params` field of state.mongo can be used to set pool options like this:

```
  - name: params
    value: "?maxpoolsize=10&minpoolsize=5"
```

the args string in `params` filed will be concat to the uri of mongo, and it will pass pool options.
