### ISSUE TITLE
[Proposal] Remove Alibaba nacos binding

### ISSUE THREAD

**Issue by shubham1172** [dapr/components-contrib#1548]
# Proposal

Dapr introduced the Alibaba Nacos binding with #814 in v1.2 which was then reverted back in the endgame with https://github.com/dapr/dapr/pull/3212, after a performance regression https://github.com/dapr/dapr/issues/2479.

Today, the binding code still exists but it was never shipped in our API - it was removed from daprd.

Recently, we also found out compliance issues with nacos v1 which can be solved by upgrading it (as with #1547).

**Comment by yaron2** [comment]
I have to say I don't understand the purpose of the vote here, but regardless, if the compliance issue can be solved AND we can verify there's no performance regression anymore, why remove it?

**Comment by yaron2** [comment]
@shubham1172 I edited the title of the issue because a vote is not required by any means to make this decision.

**Comment by shubham1172** [comment]
> I have to say I don't understand the purpose of the vote here, but regardless, if the compliance issue can be solved AND we can verify there's no performance regression anymore, why remove it?

It never went to production and no one is using it. We could have received community feedback on IF they are willing to keep Nacos binding? Let me create another issue for verifying the perf. regression and close the upgrade with #1547. Thanks!

**Comment by yaron2** [comment]
> > I have to say I don't understand the purpose of the vote here, but regardless, if the compliance issue can be solved AND we can verify there's no performance regression anymore, why remove it?
> 
> It never went to production and no one is using it. We could have received community feedback on IF they are willing to keep Nacos binding? Let me create another issue for verifying the perf. regression and close the upgrade with #1547. Thanks!

> It never went to production

Is that a reason for it to *never* go into production? By that logic, one shouldn't ever write a component because it didn't go to production yet ;)

> and no one is using it

No one can use it if it's not actually in the code.

>  Let me create another issue for verifying the perf

That would be amazing, thank you!
