### ISSUE TITLE
Multiple included headers with space aren't available in input.request.headers

### ISSUE THREAD

**Issue by ben-kotvis** [dapr/components-contrib#1557]
According to the docs,  one should be allowed to use multiple headers in the "inlcudedHeaders" metadata input.  For example:

`    
 - name: includedHeaders
    value: "x-my-custom-header, x-jwt-header"
`

When providing multiple headers I was only able to get the first header if there was a space between the header names.  However, if a space was not between the end of a header name and the comma it provided the second header in the input.request.headers.  So "x-my-custom-header, x-jwt-header" doesn't provide x-jwt-header but ""x-my-custom-header,x-jwt-header" does.

## Actual Behavior
I expect to be able to follow the documentation and get as many headers as I need with a space between the comma and the next header name.

## Steps to Reproduce the Problem

Follow the instructions for more than one header and try to get the value of the second header if there is a space between the comma and the next header name.

**Comment by addjuarez** [comment]
#1610 fixed by this pr
