### ISSUE TITLE
Kafka pubsub not working with Dapr 1.6

### ISSUE THREAD

**Issue by yangfan0902** [dapr/components-contrib#1569]
background: I curl my kafka in my pod and get (56) Recv failure: Connection reset by peer

run kafka pubsub with Dapr1.5 everything is ok
run kafka pubsub with Dapr1.6, I get this error from sidcar: 
![image](https://user-images.githubusercontent.com/42598769/157854196-df2be653-9186-400c-b088-ad233715b8d8.png)

this is my pubsub component
apiVersion: dapr.io/v1alpha1
kind: Component
metadata
  name: kafka-pubsub
  namespace: op
spec:
  metadata:
    - name: brokers
      value: '10.8.9.180:9092'
    - name: consumerGroup
      value: group1
    - name: clientID
      value: my-dapr-app-id
    - name: authType
      value: none
    - name: maxMessageBytes
      value: 1024
    - name: consumeRetryInterval
      value: 200ms
  type: pubsub.kafka
  version: v1

**Comment by Taction** [comment]
@yangfan0902 please have a try about adding this to your component yaml:
```
  - name: disableTls
    value: "true"
```

If this issue still appears, can you provide your Kafka server logs?

**Comment by yangfan0902** [comment]
> @yangfan0902 please have a try about adding this to your component yaml:
> 
> ```
>   - name: disableTls
>     value: "true"
> ```
> 
> If this issue still appears, can you provide your Kafka server logs?

it works, thank you very much
