### ISSUE TITLE
MongoDB state store returns saved JSON array uncorrectly

### ISSUE THREAD

**Issue by nupis-DanielS** [dapr/components-contrib#1570]
## In what area(s)?

 /area runtime

 /area docs

## What version of Dapr?

1.5.x and above

## Expected Behavior

When retrieving a JSON array from the state store the structure should be the same as it was saved. The output was correct till version 1.4.x. The expected behaviour would be the same as in the current documentation.

` wget http://localhost:3500/v1.0/state/state-store/planet --header='Content-Type:application/json'`

Example:
`[{
	"name": "Tatooine"
}, {
	"name": "Alderaan"
}]`

## Actual Behavior

The retrieved data is structured as follows:
`[
	[{
		"Key": "name",
		"Value": "Tatooine"
	}],
	[{
		"Key": "name",
		"Value": "Alderaan"
	}]
]`

## Steps to Reproduce the Problem

Enable a MongoDB State Store

Save state:
`wget  http://localhost:3500/v1.0/state/state-store --header='Content-Type:application/json' --post-data '[{"key": "planet","value": [{"name": "Tatooine"}, {"name": "Alderaan"}]}]'`

Get state:
`wget http://localhost:3500/v1.0/state/state-store/planet --header='Content-Type:application/json'
`

**Comment by yaron2** [comment]
> Hi.
> 
> Are there any news on this topic or should i move the issue to the components-contrib project?

Issue moved.

**Comment by yaron2** [comment]
@nupis-DanielS this should be now fixed in 1.7, can you please confirm that's the case?

**Comment by nupis-DanielS** [comment]
Hi, it works like charm with 1.7.

Thanks
