### ISSUE TITLE
Azure Functions as output binding

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#1573]
## Describe the proposal

Create a new binding component that will trigger a function in Azure Functions

**Comment by yaron2** [comment]
Can't this be done with an HTTP binding?

**Comment by berndverst** [comment]
Exactly. You'd just use the HTTP binding to call Azure Functions (can have a private API key as query string param).

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=in-process%2Cfunctionsv2&pivots=programming-language-csharp

I do not think this component is necessary.

Thoughts @artursouza ?

**Comment by artursouza** [comment]
What about the different auth solutions for Azure? That would need a component to support those, right?

**Comment by artursouza** [comment]
Also, could we enable the call without requiring a webhook if we use the Azure SDK?

**Comment by yaron2** [comment]
> Also, could we enable the call without requiring a webhook if we use the Azure SDK?

You can't invoke functions using an SDK, the HTTP endpoint is the only way, and auth is defined on the endpoint.

**Comment by ItalyPaleAle** [comment]
At this point, Azure Functions can only be invoked with a Webhook that (when not anonymous) uses auth via a shared secret. I don't believe there's support for AAD auth (unless that gets implemented as part of the Function code by the user).

However, that would be a good thing to ask the Functions team. There's certainly value in exploring stronger auth for Functions.

**Comment by berndverst** [comment]
Closing this issue as there is nothing that can be implemented.

**Comment by ItalyPaleAle** [comment]
@berndverst releated proposal: https://github.com/dapr/proposals/pull/16
