### ISSUE TITLE
Add application-applied security component

### ISSUE THREAD

**Issue by fanfanbj** [dapr/components-contrib#1587]
## Describe the feature

This component looks like "security mecha" to our applications. We expect all applications run as unprivileged mode. In default, applications have no right to access files or execute commands in the host. When applications need to access files or execute commands in the host, applications use this component to help restrict and access files or execute commands in the host. This kind of component can help mitigate the security impact of bugs or unexpected/malicious behaviors in applications.

Based on investigation, we can leverage seccomp-bpf/Landlock LSM to implement this component. We can use this component in the following senario. For example，when the application operates files or directories in the host，it will call this component to help restrict according to added rules. This component will create landlocked process，and make action for the application's operation. if action is accept, the application will execute the operation，otherwise, the application's operation will be denied.

The benefit of this component is unprivileged applications can  access files or execute commands in the host，and with dapr architecture, the application use REST and GRPC protocol, which is language neutral programming. Tradition LSM programming needs privileged right and uses C or C++ language.

![image](https://user-images.githubusercontent.com/5186033/159164470-7934270c-75b2-480b-a722-9bc114bea762.png)

## Release Note

RELEASE NOTE:

**Comment by daixiang0** [comment]
something cross https://github.com/falcosecurity/falco

**Comment by daixiang0** [comment]
Security is always important, not sure it need to be done at Dapr side, maybe in security container like Kata.

/cc @yaron2 @artursouza

**Comment by fanfanbj** [comment]
@daixiang0 Thanks. Falco is for container runtime security, which can as independent component to detect and alert on any behavior that involves making Linux system calls. This issue has a proposal to integrate security behavior into Dapr architecture.
