### ISSUE TITLE
Query API: CosmosDB does not support non-string values in query

### ISSUE THREAD

**Issue by dmitsh** [dapr/components-contrib#1588]
The current cosmosDB package `github.com/a8m/documentdb` does not support non-string values in the query.
See https://github.com/a8m/documentdb/blob/master/query.go#L5

However, non-string values work fine when querying cosmosDB directly from the Data Explorer.

Possible solution:
1. replacing https://github.com/a8m with another (Microsoft?) SDK
2. fixing github.com/a8m/documentdb

**Comment by shubham1172** [comment]
Given that there is no official SDK or even an unofficial popular SDK, I would propose going with (2).

Some time back [MSFT recommended another SDK ](https://docs.microsoft.com/en-us/answers/questions/45184/cosmos-sql-api-support-for-golang.html), [vippsas/go-cosmosdb](https://github.com/vippsas/go-cosmosdb), but it does not have commits since 2 years.

**Comment by shubham1172** [comment]
This is not officially listed as a "Preview" yet, but this looks like it https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/data/azcosmos

**Comment by berndverst** [comment]
Please see this tracking issue @shubham1172 #1526

**Comment by shubham1172** [comment]
Can we close this issue?

**Comment by mukundansundar** [comment]
@shubham1172 Why was this issue closed ? This is still an issue with cosmosdb unless there was a fix done to the dependent library and updated in go.mod in contrib ....

**Comment by shubham1172** [comment]
@mukundansundar isn't there another issue to track the same? This was an enhancement issue to change the cosmos DB library, and #1526 already tracks it.

**Comment by mukundansundar** [comment]
@shubham1172 That is for tracking the sdk update ... but checking if non-string values work is not a priority for that issue imo.
I think this should be kept open.

**Comment by shubham1172** [comment]
Sure, let's open it and label it as a bug then?

**Comment by mukundansundar** [comment]
reopening this and labelling as bug

**Comment by berndverst** [comment]
In v1.9 we upgraded to the new Azure SDK, so this likely is not a problem anymore. However, it has also been discussed that Query API will not leave Alpha state.

Instead we will be introducing a DocumentStore building block. Cosmos DB itself will eventually exist as a DocumentStore and a proper Query API will be implemented there.

Closing this as probably fixed already / wontfix.
