### ISSUE TITLE
Are there plans to expand the functionality of the Kafka bindings?

### ISSUE THREAD

**Issue by gunniwho** [dapr/components-contrib#159]
## Ask your question here
Specifically, I'm interested in being able to specify the partition no or at least a message key when invoking a Kafka output binding and also to get the log position when consuming a Kafka input binding. Are there any plans to support this in the near future?

**Comment by msfussell** [comment]
@gunniwho - Yes, this is valid. Would you like to do a contribution with a PR for a proposal?
