### ISSUE TITLE
Implement a new state store component for the Huawei DCS

### ISSUE THREAD

**Issue by jasonlica** [dapr/components-contrib#1596]
## Describe the proposal

Add Huawei DCS as a state store component.

The [Distributed Caching Service (DCS)](https://www.huaweicloud.com/en-us/product/dcs.html) is a Huawei's cloud version of Redis. It is an online, distributed, in-memory cache service compatible with Redis on Huawei Cloud infrastructure, which is reliable, scalable, usable out of the box, and easy to manage, meeting your requirements for high read/write performance and fast data access.

See [Huawei DCS User Guide](https://support.huaweicloud.com/en-us/productdesc-dcs/dcs-pd-200713001.html) for reference.

There will be a PR submission for this component implementation shortly.

**Comment by yaron2** [comment]
If this is compatible with Redis, won't the existing Redis state store work with it?

**Comment by jasonlica** [comment]
Actually, it needs to provide access to Huawei DCS specific metadata fields. Therefore, the implementation will be a wrapper of the existing Redis state store.

**Comment by berndverst** [comment]
As mentioned in your PR @jasonlica https://github.com/dapr/components-contrib/pull/1628

If you just want to simply rename the metadata fields this is better handled in documentation.

It would be very confusing as a maintainer having to inform Huawei DCS users every time we modify the Redis component. It is better if Huawei DCS users directly use the Redis component if this is possible.

**Comment by jasonlica** [comment]
See the discussion in the PR #1628. thanks.
