### ISSUE TITLE
Azure ServiceBus Queue output binding

### ISSUE THREAD

**Issue by AndreasM009** [dapr/components-contrib#160]
Is output binding for Azure ServiceBus already supported? 
I tried the following to write some messages to the queue

``` C#
var daprport = 3500
var daprUrl = $"http://localhost:{daprport}/v1.0/bindings/message-queue";
var msg = new Message
                {
                    Text = "Hello World"
                };
var client = new HttpClient();
var data = JsonConvert.SerializeObject(msg);
var result = await client.PostAsync(daprUrl, new StringContent(data));

```

The message is written to the queue but cannot be received with input binding. When I try to create a message with ServiceBusExplorer, the message is received in the input binding.

**Comment by yaron2** [comment]
Do you see any error messages in the Dapr logs?

Also, try to start Dapr with debug log level.
If using the CLI, add `--log-level debug` to the command, before the args to start your app.

**Comment by AndreasM009** [comment]
I do not see any error messages in Dapr logs.
I deployed my app to AKS, how can I set the log level there?

**Comment by AndreasM009** [comment]
It seems that log-level is set to debug in the dapr sidecar. Messages are sent to ServiceBus queue but the message body is always empty.

**Comment by AndreasM009** [comment]
I think I figured out why it didn't work after I looked at the code of the Azure ServiceBus Queue bindings. In my message producer code I posted the json payload in a wrong structure to daprd. The json structure must look like the following:
``` JSON
{
  "data": {<your data goes here>},
  "metadata":  { <additional key value data >}
}
```  
I adjusted my code like this:
```C#
var msg = new Message
{
  Text = "Hello World"
};

var payload = new
{
  data = msg
};
```
And used CamelCasePropertyNamesContractResolver :
```C#
var client = new HttpClient();
var data = JsonConvert.SerializeObject(payload, new JsonSerializerSettings { ContractResolver = new 
    CamelCasePropertyNamesContractResolver() });
var result = await client.PostAsync(daprUrl, new StringContent(data, Encoding.UTF8, 
  "application/json"));
```

**Comment by yaron2** [comment]
Yeah, I was just about to write that. The output binding endpoint expects this payload. It's mentioned in the docs and shown in the samples.

**Comment by AndreasM009** [comment]
Thx @yaron2 I missed that :-) But now I have a better knowledge about how dapr's code is structured :-)
I wrote an example about the producer consumer pattern and how it can be implemented with dapr bindings and how the consumer can be scaled out by using keda. That made my day today.

**Comment by yaron2** [comment]
That's great! Can you share the repo for it so we can share it on Twitter/community call?

**Comment by AndreasM009** [comment]
Yes, of course :-) Give me some time to finish the documentation. I have already started, you can check it out [here](https://github.com/AndreasM009/dapr-keda-azsbqueue)

**Comment by yaron2** [comment]
Closing as resolved
