### ISSUE TITLE
pubsub: How to subscribe to rabbitmq's dead letter queue?

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1600]
Rabbitmq supports dead letter queues, but what about subscriptions?

**Comment by Taction** [comment]
Currently, it is not supported. Besides, there is a design for PubSub's DeadLetter Topic: dapr/dapr#2217.

**Comment by CMarcher-Ahuora** [comment]
@yaron2 Could you comment on whether this is still not possible? I'd prefer to use a RabbitMQ native DLQ, but I am personally having trouble setting up a subscription to a DLQ (set up by the RMQ component with `enableDeadletter`), and so I wonder if I'm wasting my time
