### ISSUE TITLE
RabbitMQ message acking does not work

### ISSUE THREAD

**Issue by vslepakov** [dapr/components-contrib#161]
## Expected Behavior

RabbitMQ messages are correctly acknowledged

## Actual Behavior

acking a messages using this code

`  res.status(200).send();
`

causes a channel error and processing stops

RabbitMQ exception: 

`Channel error on connection. operation basic.ack caused a channel exception precondition_failed: unknown delivery tag 1`

## Steps to Reproduce the Problem

Just use RabbitMQ binding and try consume messages

**Comment by yaron2** [comment]
Thanks for reporting, will investigate.
