### ISSUE TITLE
Kafka binding not retrying

### ISSUE THREAD

**Issue by trumhemcut** [dapr/components-contrib#163]
## Ask your question here
I use Helm to deploy the whole system including Kafka, Azure Functions and my services. The problem is that Kafka takes long time to bring it up while my services are very lightweight it's up much faster than Kafka and its Dapr sidecar saying that:
```
time="2019-12-26T12:19:48Z" level=warning msg="failed to init output binding bindings.kafka: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"
time="2019-12-26T12:19:53Z" level=warning msg="failed to init input binding bindings.kafka: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"
```
That logs makes sense since Kafka has not been up yet, but then when Kafka is up. The binding component is still not available to work with Kafka that time. I have to delete manually the pod (includes Dapr sidecar) to get it created again and after that it can connect Kafka and everything starts working well.
I'm wondering if we should apply Retry pattern here (or I'm not aware if any) so that it can listen & try if Kafka is fully up to work with?

**Comment by yaron2** [comment]
Normally you would install Kafka and make sure it's set up in your cluster *before* deploying your apps.

Once Kafka is running in your cluster after the initial setup, Dapr will connect to the brokers immediately.

**Comment by trumhemcut** [comment]
Thanks @yaron2 , that's ok, I'll update the Helm accordingly so that it can adapt Dapr sidecar's behavior. Just wondering in distributed systems, some services are unavailable at some points of time (e.g. Kafka is not available) is just a usual thing, even at sometimes we can't control its availability such as it comes from third-party services, then it would not break our Dapr sidecar in this case I think.

**Comment by msfussell** [comment]
@yaron2. Do our retry patterns apply to all bindings in general, or is this specific per binding?
