### ISSUE TITLE
No update of Azure Service Topic / Subscription metadata

### ISSUE THREAD

**Issue by ToonVanhoutte** [dapr/components-contrib#164]
## Expected Behavior

I have a running application, that uses the Service Bus pub sub component.  The first time I run the application, the topic did not exist yet and the component creates the topic and subscription, taking into account the configured metadata (e.g. maxDeliveryCount).  

Afterwards, I stopped the application and changed some of the Service Bus metadata (e.g. maxDeliveryCount).  I would expect that on each initialization the Service Bus topic / queue would be updated, if it exists already.

## Actual Behavior

There is no update of the existing subscription.

## Steps to Reproduce the Problem

- Have an empty ASB namespace
- Configure the ASB pub/sub component with maxDeliveryCount set to 5
- Start a Dapr application that contains that component and is configured for a topic subscription
- Notice that a topic and subscription gets automatically created
- Stop the Dapr application
- Update the component description and set maxDeliveryCount to 6
- Start the Dapr application again
- Notice that the max delivery count in ASB remains 5 and does not get updated

**Comment by jjcollinge** [comment]
Thanks for the issue, @yaron2 would reconciling properties such as this be desirable?

**Comment by yaron2** [comment]
My gut feeling tells me that such reconciliation shouldn't happen, but I need to research it a bit more @jjcollinge

**Comment by msfussell** [comment]
@jjcollinge @yaron2  - Any update here on updating the Azure Service Bus Topic when then component meta data is updated?

**Comment by jjcollinge** [comment]
No I left this as is given @yaron2 comment above - metadata is set on creation and not updated if changed. Is this something you’d want to see?
