### ISSUE TITLE
Add in-memory state store

### ISSUE THREAD

**Issue by skyao** [dapr/components-contrib#1657]
## Describe the feature

We need an in-memory state store to support performance test as described here :  https://github.com/dapr/dapr/issues/4506

The first version of this  in-memory state can be simple without any advanced feature like etag, transactional. 

## Release Note

RELEASE NOTE: **ADD** in-momery state store in Dapr for test.

**Comment by mukundansundar** [comment]
related to #1326

**Comment by skyao** [comment]
@mukundansundar please help to add a "do-not-merge" label on this PR.

I will use this PR code for my perf test of state temporarily before the exist PR merged.

**Comment by mukundansundar** [comment]
> @mukundansundar please help to add a "do-not-merge" label on this PR.
> 
> I will use this PR code for my perf test of state temporarily before the exist PR merged.

@skyao Which exact PR do you want me to add the label to?

**Comment by skyao** [comment]
@mukundansundar  https://github.com/dapr/components-contrib/pull/1326    please mark this PR as not-merge.

**Comment by skyao** [comment]
Close this issue, I will work with seaflood in another PR: https://github.com/dapr/components-contrib/pull/1326
