### ISSUE TITLE
Support Firestore (native mode) in state management

### ISSUE THREAD

**Issue by davidshen84** [dapr/components-contrib#1666]
## Describe the proposal

GCP Firestore has two modes, the legacy Datastore mode and the new Firebase mode (aka the native mode). GCP does not allow projects to switch between the two modes and the native mode is the preferred one for new projects. Currently, Dapr state store only supports GCP Firestore [Datastore mode][1]. I think Dapr state store should also support Firestore in native mode.

[1]: https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-firestore/

**Comment by yaron2** [comment]
@moonchanyong any chance you can pick up this work for 1.8?

**Comment by yaron2** [comment]
ping @moonchanyong
