### ISSUE TITLE
Documentation / samples for additional consistency levels with Cosmos Db

### ISSUE THREAD

**Issue by sowsan** [dapr/components-contrib#167]
## Provide samples and documentation on how to support additional consistency levels within Dapr for Cosmos Db

https://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels

**Comment by msfussell** [comment]
@sowsan - Dapr provides concurrency and consistency flags. Are there scenarios that you cannot do with these Dapr settings? Can you provide some details here?
