### ISSUE TITLE
[pubsub-pulsar] Add metadata property to configure BatchingMaxSize in Pulsar

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1671]
Publishing failed
```
time="2022-04-15T01:52:07Z" level=error msg="[unable to add message to batch]" producerID=8 producer_name=pulsar-cluster-zk-3-2988 properties="map[]" size=270636 topic="persistent://public/default/testEvent"
time="2022-04-15T01:52:07.670125177Z" level=debug msg="rpc error: code = Internal desc = error when publish to topic testEvent in pubsub pubsub: message add to batch failed: AddToBatchFailed" app_id=test instance=test-1.2.65-5f89f79776-bkpxf scope=dapr.runtime.grpc.api type=log ver=1.7.0
```

**Comment by berndverst** [comment]
Seems related to https://github.com/dapr/components-contrib/issues/1659 which is fixed by PR https://github.com/dapr/components-contrib/pull/1661/files

We will be releasing Dapr 1.7.1 shortly for an unrelated reason and will include this fix there.

**Comment by saber-wang** [comment]
@berndverst  https://github.com/apache/pulsar-client-go/blob/7773d27562cec30687879dc7ce240e0a02ec7a42/pulsar/producer.go#L146

BatchingMaxSize specifies the maximum number of bytes permitted in a batch. (default 128 KB) ,the message is greater than 128, so sending failed. should add parameters to support setting this value

**Comment by shubham1172** [comment]
@saber-wang can you please also update the issue title to reflect the same, e.g. "Add metadata property to configure BatchingMaxSize in Pulsar". Please feel free to take a stab at this issue.
