### ISSUE TITLE
Certification tests for Azure Blob Storage Statestore

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/components-contrib#1678]
## Description

Implement certification test for Statestore - Azure Blob Storage

**Comment by pravinpushkar** [comment]
Ping @berndverst

**Comment by tanvigour** [comment]
## Test Plan Draft

Basic Test for existing container for CRUD operations:
1. Able to create and test connection.
2. Able to do set, fetch, delete.

 Basic Test for non-existing container for CRUD operations:
1. Able to create and test connection.
2. Able to do set, fetch, delete data.
3. Delete the table

Test for authentication using AAD
1. Save Data using Go SDK 
2. Retrieve data by using AAD credentials

**Comment by artursouza** [comment]
We also need to validate reconnection. The component should not require a restart to recover from a connection outage from the service.
