### ISSUE TITLE
Certification tests for Azure Blob Storage Bindings 

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/components-contrib#1679]
## Description

Create certification test for Binding - Azure Blob Storage

**Comment by pravinpushkar** [comment]
ping @berndverst

**Comment by tanvigour** [comment]
@berndverst , @artursouza 

This tests seem to be present already: https://github.com/dapr/components-contrib/blob/master/tests/certification/bindings/azure/blobstorage/blobstorage_test.go

Shouldn't this issue be closed?

**Comment by berndverst** [comment]
Yes I created this certification test originally and it is fine as is. There is no need to check for reconnection given this is a connectionless protocol (REST).

We don't have to track the Track 2 SDK migration as part of this. That's something which we will have to do eventually.

I am not sure why we forgot to update the docs to call this component stable.

**Comment by berndverst** [comment]
@artursouza I think this component became a stable candidate in v1.6 but we simply forgot to say that it was stable in 1.7.

**Comment by berndverst** [comment]
Was resolved in early January: https://github.com/dapr/components-contrib/issues/1679

**Comment by berndverst** [comment]
@pravinpushkar this issue you opened here was a duplicate of https://github.com/dapr/components-contrib/issues/956 -- hence this confusion here.

**Comment by berndverst** [comment]
Docs:
https://github.com/dapr/docs/pull/2659
https://github.com/dapr/docs/pull/2658
