### ISSUE TITLE
Cassandra Set() method does INSERT only, doesn't check ETag

### ISSUE THREAD

**Issue by Haishi2016** [dapr/components-contrib#170]
Shouldn't it use UPDATE to update existing row?
Delete doesn't check ETag, either.

**Comment by yaron2** [comment]
Cassandra inserts are updates.

https://stackoverflow.com/questions/28350630/when-are-rows-overwritten-in-cassandra

Closing this

**Comment by yaron2** [comment]
You can open a separate issue for the etag
