### ISSUE TITLE
in-memory state component doesn' have the feature of state query

### ISSUE THREAD

**Issue by seeflood** [dapr/components-contrib#1705]
Now the implementation of in memory state #1326 has most of the state feature including etag, transactional, expire. 
Yet state query is not not included since there is no requirement for this feature.

I create this issue to track it.
Help wanted!

**Comment by berndverst** [comment]
Query API will not graduate to stable in state store.

We will be introducing a DocumentStore API, and only DocumenStore components will have a Query API in the future.

I will close this issue so that nobody spends their time and effort pursuing this implementation. Thanks.
