### ISSUE TITLE
AuthType must be preceded by three spaces for kafka-pubsub

### ISSUE THREAD

**Issue by sunday866** [dapr/components-contrib#1722]

**Comment by sunday866** [comment]
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "192.168.10.145:9092"
    - name: clientID
      value: "my-dapr-app-id"
    - name: authRequired
      value: "false"
   - name: authType
      value: "none"

**Comment by shubham1172** [comment]
@sunday866 which file is this?

**Comment by sunday866** [comment]
pubsubkafka.yml in .dapr\components

**Comment by shubham1172** [comment]
The default pubsub is redis, so this is something you must have copied from somewhere. So, you need to fix the indentation and use it. Does that answer your question?
