### ISSUE TITLE
Binding: Add HTTP Stream Support

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/components-contrib#1732]
## Describe the feature

Would like to request support for HTTP Streams, which is like WebSockets or other PubSub systems, HTTP allows to keep an open connection where chunks can be sent from a server towards a client. 

However, when creating such a client code must be written to support this streaming scenario

[Example Server](https://www.loginradius.com/blog/engineering/guest-post/http-streaming-with-nodejs-and-fetch-api/)
[Example Client](https://www.loginradius.com/blog/engineering/guest-post/http-streaming-with-nodejs-and-fetch-api/#consume-a-streaming-api-from-a-webapp)

This request comes as increasingly more IoT devices are switching towards the HTTP Streaming API approach and where I believe Dapr can bring a benefit of not having to write the abstraction layer for it. Next to the IoT space, this can also be useful in Web APIs and others.

## Release Note

RELEASE NOTE: **ADD** HTTP Streaming Support

**Comment by ItalyPaleAle** [comment]
Hi @XavierGeerinck, just so I'm clear, are you asking about the ability to maintain a persistent HTTP connection from a client to Dapr so messages can be over HTTP as streams (WebSockets or long-polling?).

We do not recommend to have client applications connecting to the Dapr runtime directly. The Dapr runtime (daprd) is meant to be used as a "sidecar", and all connections should be in the same network (localhost, and in Kubernetes, in the same pod). The Dapr runtime is not designed to receive connections from clients over an unstable network and/or with high latency.

In your case, perhaps you should consider creating an application that your IoT clients connect to, and that application interacts with daprd?

**Comment by ItalyPaleAle** [comment]
Gotcha. This sounds like it should be its own input binding component. The problem I see is that Dapr tries to adhere to existing standards, and I'm not aware of any standard for this kind of streams today that we should consider supporting.

**Comment by XavierGeerinck** [comment]
It's part of the HTTP/2 Standard :) 

https://datatracker.ietf.org/doc/html/rfc7540#page-15

**Comment by ItalyPaleAle** [comment]
Yes, for sure the transport protocol is, but the data protocol (ie. how the data is formatted in the messages) - are you aware of a standard for that?

**Comment by XavierGeerinck** [comment]
it's more of an open standard indeed, but I guess we could offer the implementation for Bytes and JSON? Seeing that the latter is most frequently used in Streaming APIs and the first allows for custom implementations by the users?

**Comment by ItalyPaleAle** [comment]
But Dapr needs to have a higher-level format. For example, if we get messages formatted as JSON, the messages need to contain a “topic” or “queue”. They need to have a specific format for passing metadata, etc.

For example, some other components use HTTP for transporting data, but they all have some data protocols on top that define what format the data is in.

Of course we could always create our own format, but I would prefer if we could rely on industry-standard ones.

**Comment by XavierGeerinck** [comment]
I am not following perfectly of what you mean here (might be missing something), so a stream is coming in JSON by JSON message with a line carriage return as the dividers.

Dapr picks these up and sends them to the connected clients no?

What format do you specifically mean then? Since in this case it's a fetch operation which will accept the default fetch arguments (e.g. headers, ...)

**Comment by ItalyPaleAle** [comment]
We try to develop components based on data formats more than transport standards. We are not going to define our own formats and say "your JSON message needs to be formatted this way, have these keys, and you must pass those headers", as that format wouldn't be standard.

A popular data format protocol for events is CloudEvents, which is implemented by some Dapr pubsub components already: https://cloudevents.io/

CloudEvents does have a specification for a HTTP protocol binding, but it is limited to HTTP1.1 and does not support streaming: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/bindings/http-protocol-binding.md

**Comment by XavierGeerinck** [comment]
Honestly I am still not following, how does this need a standard? The data format is defined by the stream returning JSON events in this case. Dapr acts as a "relay" in this case, giving the user the freedom of not having to implement the technology needed to connect to the stream.
