### ISSUE TITLE
[pubsub][pulsar]Instead of directly using consumerid as the subscriptionname, the subscriptionname should be generated together with appid

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1742]
## Describe the feature

https://github.com/dapr/components-contrib/blob/47e95c9a47151b17212a9bb59eda46ee4401ad94/pubsub/pulsar/pulsar.go#L268-L273
Here, the consumerid is directly used as the subscriptionname. What I want is to combine it with the appid.
If the consumerid is directly used as the subscriptionname, all apps will have the same subscriptionname

Function similar to rabbitmq https://github.com/dapr/components-contrib/blob/47e95c9a47151b17212a9bb59eda46ee4401ad94/pubsub/rabbitmq/rabbitmq.go#L256

This will provide different subscription names when using the same appid in multiple environments

**Comment by shubham1172** [comment]
Can you please explain a little more?

**Comment by saber-wang** [comment]
@shubham1172  Here, the consumerid is directly used as the subscriptionname. What I want is to combine it with the appid.

If the consumerid is directly used as the subscriptionname, all apps will have the same subscriptionname

**Comment by shubham1172** [comment]
Got it - can you update the issue title to reflect the same please?

**Comment by artursouza** [comment]
Today, we support `{uuid}` and `{podName}` to be used in the consumerId metadata. You can use `{podName}` along with a statefulset, so the pod's name is sticky.

**Comment by artursouza** [comment]
We can also add `{appId}` as a new special tag in metadata parsing.

**Comment by yaron2** [comment]
> We can also add `{appId}` as a new special tag in metadata parsing.

App ID is the default value that gets passed in as consumerID. How will this be different?
