### ISSUE TITLE
[pubsub]Publish support data isolation

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1745]
## Describe the feature

When multiple namespaces use the same message component, currently we can use consumerid to group message makers, but there is no way to isolate the publisher.

In this case, the published message will be subscribed by all namespaces.
can `publishid` be added to isolate data? For example, publish = p1, topic = test. The topic generated in the final message component is p1.test?

**Comment by ItalyPaleAle** [comment]
The reason for consumerID is that some services only allow one connection per consumer (with a different consumerID). In your case, would it be possible to just set the topic to `p1.test`?

**Comment by yaron2** [comment]
Dapr has the concept of a namespace for both Kubernetes and Self Hosted Mode. We could add an opt-in feature for namespace isolation which will append the namespace to the consumer ID. Thoughts @ItalyPaleAle?

**Comment by ItalyPaleAle** [comment]
Makes sense to me

**Comment by ItalyPaleAle** [comment]
Just to be clear, what @yaron2 was referring to was including (as an option) the namespace, such as these: https://docs.dapr.io/operations/components/component-scopes/#namespaces

Would that work for you?

If not, could you please provide some more context to help understand your requirements?

**Comment by saber-wang** [comment]
@ItalyPaleAle  I think I can solve this problem through the feature of message queue. For example, when redis is used, specify a DB for each namespace
