### ISSUE TITLE
AWS SNS/SQS pubsub is incorrectly named `pubsub.snssqs`

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#1753]
The component for PubSub for AWS SNS/SQS needs to be imported as `pubsub.snssqs`. However, based on the formatting used for other cloud providers' components, this should have been `pubsub.aws.snssqs`.

`pubsub.snssqs` is used  in the runtime ( https://github.com/dapr/dapr/blob/master/cmd/daprd/main.go#L331-L333 ) and in the docs.

However, `pubsub.aws.snssqs` is used in the config test file ( https://github.com/dapr/components-contrib/blob/master/tests/config/pubsub/aws/snssqs/pubsub.yml#L7 )

However, I am aware that this is likely a breaking change.

## Expected Behavior

Component should be referenced via `pubsub.aws.snssqs`

## Actual Behavior

Component is referenced via `pubsub.snssqs`

**Comment by yaron2** [comment]
In dapr/dapr we can add support for an alias to the component registry loader, so something like `WithAlias("pubsub.aws.snssqs")`.

**Comment by ItalyPaleAle** [comment]
Yes, that would work. We could preserve `pubsub.snssqs` for backwards-compatibility while changing the official identifier to `.aws`

**Comment by ItalyPaleAle** [comment]
Will be fixed by https://github.com/dapr/dapr/pull/4665
