### ISSUE TITLE
Adding certification tests for environment variables/local file for secrets store

### ISSUE THREAD

**Issue by amulyavarote** [dapr/components-contrib#1761]
Environment Variables:
-  Verify the secret is fetched from the environment variable
    - Create component spec.
    - Run dapr application with component.
    - Ensure that the secret fetched is same as secret stored in the env variable.

Local File:
- Verify the secret is fetched from the local file.
    - Create a component spec with the json file link where the secret is stored. 
    - Run dapr application with component.
    - Ensure that the secret fetched is same as secret stored in the json file.

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
@amulyavarote For the file based store, check the working for the `nestedSeparator` field also where it can be changed from `:` to something else.

**Comment by mukundansundar** [comment]
@cmendible Assigned this issue to you based on PR that you created.
