### ISSUE TITLE
Dapr invoke binding with Event Hub publishes multiple messages

### ISSUE THREAD

**Issue by arkakk93** [dapr/components-contrib#1764]
**Description**
For each event that I publish using Azure Event Hub binding, there are several events that get published to the event hub. 
The service is deployed on AKS cluster

**Using following to publish:**
await this.daprClient.InvokeBindingAsync("componentName", "create", object, new Dictionary<string, string> { { "partitionKey", "someId"} });

**Details**
_Component Used_

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: componentName
  namespace: <namespace>
spec:
  type: bindings.azure.eventhubs
  version: v1
  metadata:
  \- name: connectionString      # Azure EventHubs connection string
    secretKeyRef:
      name: keyName
      key: keyName
  \- name: consumerGroup
    value: consumerGroup
 \- name: storageAccountName    # Azure Storage Account Name
    value: "storageAccountName"
  \- name: storageAccountKey     # Azure Storage Account Key
    secretKeyRef:
      name: storageAccountKey
      key: storageAccountKey
  \- name: storageContainerName  # Azure Storage Container Name
    value: "storageContainerName"
auth:
  secretStore: keyvaultsecretstore
  
Also this component is used by another service to subscribe to this event hub.
Reason for using binding and not Pub/Sub component here: Based on issue that mentions pub/sub component is being re-written.

SDK version being used: Dapr.AspNetCore - Version="1.3.0"
Dapr version on AKS cluster: 1.4.3

**Comment by robeving** [comment]
I'm still seeing this issue

**Comment by berndverst** [comment]
> I'm still seeing this issue

@robeving are you seeing this with 1.8.0-rc.3 by chance? (That was released just a few days ago)

**Comment by robeving** [comment]
Can confirm that this issue still seems present in 1.8 - have received double data in our eventhub

**Comment by i-am-shodan** [comment]
still broken

**Comment by AceHack** [comment]
Is this still an issue?
