### ISSUE TITLE
Cron route metadata property

### ISSUE THREAD

**Issue by rafgithub** [dapr/components-contrib#1769]
## Cron binding route
Please, add the ability to specify route property in metadata component configuration. In this way, we can specify a complex endpoint (i.e.: api/v1/foo/cron) instead of the name

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
See here: https://docs.dapr.io/developing-applications/building-blocks/bindings/howto-triggers/#specifying-a-custom-route.
