### ISSUE TITLE
OAuth 2.0 Bearer Token support for Twitter binding

### ISSUE THREAD

**Issue by shubham1172** [dapr/components-contrib#1774]
## Describe the feature
The Twitter API supports app-only authentication with OAuth2.0 Bearer Token requests. It does not involve any users. See the documentation here: https://developer.twitter.com/en/docs/authentication/oauth-2-0

The Twitter client used by Dapr already supports it: https://github.com/dghubble/go-twitter

```go
import (
    "github.com/dghubble/go-twitter/twitter"
    "golang.org/x/oauth2"
    "golang.org/x/oauth2/clientcredentials"
)

// oauth2 configures a client that uses app credentials to keep a fresh token
config := &clientcredentials.Config{
    ClientID:     "consumerKey",
    ClientSecret: "consumerSecret",
    TokenURL:     "https://api.twitter.com/oauth2/token",
}
// http.Client will automatically authorize Requests
httpClient := config.Client(oauth2.NoContext)

// Twitter client
client := twitter.NewClient(httpClient)
```

For the Twitter binding, we can introduce a new metadata: `authType`, which can be `oauth1` or `oauth2`. 

- `oauth1` requires: `consumerKey`, `consumerSecret`, `accessToken`, and `accessSecret`.
- `oauth2` requires: `consumerKey`, `consumerSecret`

## Release Note

RELEASE NOTE: **ADD** OAuth 2.0 support for Twitter binding

**Comment by berndverst** [comment]
At this point this should not be worked on:

By default all Twitter apps are APIv2 apps now, and our existing binding is not compatible.
As part of #2283 a completely different SDK will need to be used.

**Comment by shubham1172** [comment]
Agreed, closing in favor of #2283
