### ISSUE TITLE
Support RedPanda

### ISSUE THREAD

**Issue by eburnette** [dapr/components-contrib#1777]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

RedPanda, like Pulsar, is compatible with Kafka but has improved performance and other features. This is a request to support RedPanda as a first-class pub/sub broker alongside Kafka and Pulsar.

## Release Note

RELEASE NOTE: **ADD** Added support for RedPanda.

**Comment by yaron2** [comment]
Moved to correct repository.

@eburnette if RedPanda is compatible with Kafka, why isn't it possible to use the existing Kafka components to talk to RedPanda?

**Comment by eburnette** [comment]
I'm not sure how compatible it is, and I'm sure there will be some settings unique to RedPanda.
