### ISSUE TITLE
AWS SQS/SNS submit more than 20 statement in access policy

### ISSUE THREAD

**Issue by xingrux** [dapr/components-contrib#1780]
## Expected Behavior

A service should be able to subscribe to more than 20 topic without submitting more than statement in access policy to sqs.
The maximum limit for attaching a managed policy to an IAM role or user is 20 in AWS.

## Actual Behavior
When a service is subscribed to more than 20 topics, the following error is shown, saying that more than 20 statement were found in the submitted policy, which over the limit of aws.
```

time="2022-06-08T13:40:54.607042655Z" level=error msg="error setting sns-sqs subscription policy: error setting queue subscription policy: OverLimit: 21 statements were found in the submitted policy, max allowed is 20\n\tstatus code: 403, request id: 17f49068-d8e9-5e78-8bd6-cb7271cf4bda" app_id=xxxxx instance=xxxxx scope=dapr.contrib type=log ver=1.6.0
time="2022-06-08T13:40:54.607155617Z" level=error msg="failed to subscribe to topic xxx-topic: error setting sns-sqs subscription policy: error setting queue subscription policy: OverLimit: 21 statements were found in the submitted policy, max allowed is 20\n\tstatus code: 403, request id: 17f49068-d8e9-5e78-8bd6-cb7271cf4bda" app_id=xxxxx instance=xxxx scope=dapr.runtime type=log ver=1.6.0
```

## Steps to Reproduce the Problem

Create a test app that subscribes to more than 20 topics. Run the app with AWS SQS/SNS component configured for pubsub. check that if every sns topic has its access policy created

## Possible solution
instead of adding a access policy for each sns topic, we can use [condition set operator  ](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html) and add sns arns to a single  `aws:SourceArn` array like the following
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "sns.amazonaws.com"
      },
      "Action": "sqs:SendMessage",
      "Resource": "<SQS>",
      "Condition": {
        "ForAnyValue:ArnEquals": {
          "aws:SourceArn": [
....
          ]
        }
      }
    }
  ]
}`
## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Thanks for reporting. Would you be able to submit a PR that fixes this?
