### ISSUE TITLE
RabbitMQ: What dead letter topic are failed messages sent to?

### ISSUE THREAD

**Issue by msfussell** [dapr/components-contrib#1781]
## Ask your question here
In the reference docs there is a "`enableDeadLetter`" boolean property on the RabbitMQ component, but in turning this to `true`, what is the name of the dead letter topic that this is sent to? How is this message forwarding configured?
https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-rabbitmq/

**Comment by Taction** [comment]
In rabbitmq, the message of topic `a` will be sent to `${consumerID}-a`(In most cases consumerID is app-id), and its dead letter will be sent to `dlq-${consumerID}-a`. And it can not be subscribed by any topic for now, users need to handle these messages manually.
Besides, in favor of dapr/dapr#4399, using and subscribing to a dead letter topic is possible.
