### ISSUE TITLE
State Store - CosmosDB: not able to utilize Partition Keys and thus failing to save state each time

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/components-contrib#1794]
When trying to perform a `state save` for CosmosDB, I get the following:

```
== APP == {
== APP ==   errorCode: 'ERR_STATE_SAVE',
== APP ==   message: `failed saving state in state store state-azure-cosmosdb: BadRequest, Message: {"Errors":["PartitionKey extracted from document doesn't match the one specified in the header. Learn more: https:\\/\\/aka.ms\\/CosmosDB\\/sql\\/errors\\/wrong-pk-value"]}\r\n` +
== APP ==     'ActivityId: e4e66f05-527f-4721-9bb4-f9f33b64c652, Request URI: /apps/c77b35bd-68fd-461d-b0b9-b3acc6647408/services/95a2f10a-4191-41f6-b6d1-b8a5a8baa34d/partitions/29ebe2d4-f08c-4eb1-8fad-24f853fa6b16/replicas/132971751152842865p/, RequestStats: \r\n' +

```

As read in the [Docs](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-azure-cosmosdb/#partition-keys), I should be able to add "metadata" which specify the "partitionKey" which is as well confirmed in the [code #1](https://github.com/dapr/components-contrib/blob/4727ea8b33c26e7d6f5316021e4eb31fb93f2124/state/azure/cosmosdb/cosmosdb.go#L99) and [code #2](https://github.com/dapr/components-contrib/blob/4727ea8b33c26e7d6f5316021e4eb31fb93f2124/state/azure/cosmosdb/cosmosdb.go#L629) but still this issue occurs.

Am I doing something wrong?

The request I am performing (I tried writing the partition key in a different format to see if that would work, but nothing worked):

```javascript
    const itemRes = await fetch(`http://localhost:3500/v1.0/state/my-cosmosdb`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify([
        {
          key: "test",
          value: {
            test: "hello-world",
            "/partitionKey": 2083,
            "partitionKey": 2083,
            "partitionkey": 2083,
            "/partitionID": 2083,
            "partitionID": 2083,
            "partitionid": 2083
          },
          metadata: {
            partitionKey: "partitionID"
          }
        }
      ])
    })
```

Configured Portal

![image](https://user-images.githubusercontent.com/591282/174455349-e2aa814a-48a1-4a18-a5ef-6f026bc9e80d.png)

**Comment by shubham1172** [comment]
Have you tried?
```ts
   const itemRes = await fetch(`http://localhost:3500/v1.0/state/my-cosmosdb`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify([
        {
          key: "test",
          value: {
            test: "hello-world"
          },
          metadata: {
            partitionKey: "/partitionID" // this is the important part
          }
        }
      ])
    })
```

**Comment by berndverst** [comment]
The partition key must be the same as the partition key you configured when creating the table in Cosmos DB. You cannot dynamically change the partition key.

Also, this must be the partitionKey path - e.g. `/myfieldname` -- this is what CosmosDB will show in the portal for the partition Key also.
