### ISSUE TITLE
Azure service bus message bus throws timeout error after being idle ( and stops working)

### ISSUE THREAD

**Issue by MohsenMahdieh** [dapr/components-contrib#180]
## Expected Behavior

Using Azure service bus as Dapr message bus provider, it should not stop working after being idle as it throws exception 

## Actual Behavior

Using Azure service bus as Dapr message bus provider, it stops working after being idle for sometime 

## Steps to Reproduce the Problem

- configure Dapr to use azure service bus as message bus by replacing default redis message bus in components folder -  running in stand alone mode - steps to configure can be found [here](https://github.com/dapr/docs/blob/v0.3.0/howto/setup-pub-sub-message-broker/setup-azure-servicebus.md)
- run the service to make sure the connection is properly made
- let it be idle by not sending any message to subscription/topic for at least an hour without any message  
- you would see the following message in Dapr output **DAPR == time="2020-01-08T07:30:14+11:00" level=error msg="azure service bus error: error receiving from topic 'topic name', context canceled"**

**Comment by jjcollinge** [comment]
Thanks for raising the issue, I’ll have a look into this and report back ASAP

**Comment by MohsenMahdieh** [comment]
> Thanks for raising the issue, I’ll have a look into this and report back ASAP

Hey mate @jjcollinge any update on this?

**Comment by jjcollinge** [comment]
Hey, sorry been busy today but hopefully have time tomorrow to investigate.

**Comment by jjcollinge** [comment]
Just trying to repro, I've followed your steps but haven't seen the error reported (yet) after ~2 hours. Did you have any additional configuration set aside from your connection string? If you can repro, it'd be good to get debug logs by setting `--log-level debug` when running the dapr command. When you saw the message did dapr continue to work and did the pubsub continue to work i.e. it was just a log message but you could still perform pubsub?

The error message `error receiving from topic 'topic name'` looks suspicious too - given topic = `topic name`. I'll keep having having a look.

**Comment by jjcollinge** [comment]
It finally repro'd so I can answer my own questions now.

Debug logs below:
```
== DAPR == 2020-01-10 11:32:55.760164 I | redis: connection to localhost:6379 broken (localAddr: 127.0.0.1:38760, remAddr: 127.0.0.1:6379): redispipe.io error: {address: localhost:6379}, cause: read tcp 127.0.0.1:38760->127.0.0.1:6379: i/o timeout
== DAPR == 2020-01-10 11:32:55.760199 I | redis: connecting to localhost:6379
== DAPR == time="2020-01-10T11:32:55Z" level=error msg="azure service bus error: error receiving from topic C, context canceled"
== DAPR == 2020-01-10 11:32:55.782714 I | redis: connected to localhost:6379 (localAddr: 127.0.0.1:38808, remAddr: 127.0.0.1:6379)
== DAPR == time="2020-01-10T11:33:55Z" level=error msg="azure service bus error: error receiving from topic A, context canceled"
```
The `dapr` process does continue but the pubsub stops working.
Will look into this more.

**Comment by MohsenMahdieh** [comment]
Thanks @jjcollinge for that. Now as you say, I remember that it was happening while my machine was going to sleep.
Would be great if we can have an update on that.

**Comment by jjcollinge** [comment]
@MohsenMahdieh I've pushed a PR (#186 ) that appeared to fix the issue during my tests - the component will still logs errors but it should recover once the network becomes available again. It'd be great if you could please test this for me?

**Comment by MohsenMahdieh** [comment]
> @MohsenMahdieh I've pushed a PR (#186 ) that appeared to fix the issue during my tests - the component will still logs errors but it should recover once the network becomes available again. It'd be great if you could please test this for me?

@jjcollinge I am using dapr cli and I dont have dapr dev setup on my mahcine.. Would it be possible to build the docker image so I can use it instead of setting up dapr dev on my machine..

**Comment by jjcollinge** [comment]
@MohsenMahdieh AFAIK in standalone mode the CLI only uses the docker container to run the placement service and uses the local `daprd` binary to run the Dapr sidecar(s). In case you have a setup that works around this I've pushed the image to Docker Hub @ `dotjson/dapr:azsb-reconnect`. Note, the dapr CLI also [hard codes the dapr image name](https://github.com/dapr/cli/blob/aa5d68e2c6b013b219fdc6082abe97743a8ef60c/pkg/standalone/standalone.go#L40) (but again, think this is just for the placement service) - may need to raise an issue to make this overridable or just use docker commands directly. I'm not sure what OS you are on but I've [uploaded a zip containing the binaries built for Linux AMD64](https://gofile.io/?c=Bq4znT) (md5sum: 216c3fdafae07770695242a3749fca3e) in case you want to use those. I don't think Dapr has cross compilation currently setup to build the Windows/MacOS bins on Linux so haven't got those.

**Comment by yaron2** [comment]
> @MohsenMahdieh AFAIK in standalone mode the CLI only uses the docker container to run the placement service and uses the local `daprd` binary to run the Dapr sidecar(s). In case you have a setup that works around this I've pushed the image to Docker Hub @ `dotjson/dapr:azsb-reconnect`. Note, the dapr CLI also [hard codes the dapr image name](https://github.com/dapr/cli/blob/aa5d68e2c6b013b219fdc6082abe97743a8ef60c/pkg/standalone/standalone.go#L40) (but again, think this is just for the placement service) - may need to raise an issue to make this overridable or just use docker commands directly. I'm not sure what OS you are on but I've [uploaded a zip containing the binaries built for Linux AMD64](https://gofile.io/?c=Bq4znT) (md5sum: 216c3fdafae07770695242a3749fca3e) in case you want to use those. I don't think Dapr has cross compilation currently setup to build the Windows/MacOS bins on Linux so haven't got those.

Dapr builds for Mac/Linux/Windows with `make build`

**Comment by jjcollinge** [comment]
Ah yes I had a typo in `GOOS=windows GOARCH=amd64 make build`, fixed it and it does cross compile - thanks @yaron2. @MohsenMahdieh bins for Mac/Linux/Windows are available [here](https://gofile.io/?c=sDTwag) (md5sum: 74355f5ec4eeed1b9b8e96ad2ac06f91)

**Comment by yaron2** [comment]
> Ah yes I had a typo in `GOOS=windows GOARCH=amd64 make build`, fixed it and it does cross compile - thanks @yaron2. @MohsenMahdieh bins for Mac/Linux/Windows are available [here](https://gofile.io/?c=sDTwag) (md5sum: 74355f5ec4eeed1b9b8e96ad2ac06f91)

Did you remember to change go.mod in Dapr to point to your local version of contrib and then build it?

**Comment by jjcollinge** [comment]
yes

**Comment by yaron2** [comment]
> yes

Awesome :)

**Comment by MohsenMahdieh** [comment]
> Ah yes I had a typo in `GOOS=windows GOARCH=amd64 make build`, fixed it and it does cross compile - thanks @yaron2. @MohsenMahdieh bins for Mac/Linux/Windows are available [here](https://gofile.io/?c=sDTwag) (md5sum: 74355f5ec4eeed1b9b8e96ad2ac06f91)

@jjcollinge I downloaded it and was going to give it a go but I had a production issue and had to work on that. @yaron2 is it available as I can see you closed the issue?!

**Comment by yaron2** [comment]
> > Ah yes I had a typo in `GOOS=windows GOARCH=amd64 make build`, fixed it and it does cross compile - thanks @yaron2. @MohsenMahdieh bins for Mac/Linux/Windows are available [here](https://gofile.io/?c=sDTwag) (md5sum: 74355f5ec4eeed1b9b8e96ad2ac06f91)
> 
> @jjcollinge I downloaded it and was going to give it a go but I had a production issue and had to work on that. @yaron2 is it available as I can see you closed the issue?!

It was closed automatically when we merged a fix for it, yes.
It will go out in the upcoming version.

**Comment by MohsenMahdieh** [comment]
> > > Ah yes I had a typo in `GOOS=windows GOARCH=amd64 make build`, fixed it and it does cross compile - thanks @yaron2. @MohsenMahdieh bins for Mac/Linux/Windows are available [here](https://gofile.io/?c=sDTwag) (md5sum: 74355f5ec4eeed1b9b8e96ad2ac06f91)
> > 
> > 
> > @jjcollinge I downloaded it and was going to give it a go but I had a production issue and had to work on that. @yaron2 is it available as I can see you closed the issue?!
> 
> It was closed automatically when we merged a fix for it, yes.
> It will go out in the upcoming version.

Ok mate, any idea when the next release rolling out?
