### ISSUE TITLE
[pubsub][pulsar]When a message fails to be processed, subsequent messages will be blocked.

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1813]
## Expected Behavior

Skip the failed messages or put the failed messages in the dead letter queue and continue consuming other messages.

## Actual Behavior

Subsequent messages will be blocked in the pulsar.
![image](https://user-images.githubusercontent.com/45062099/175275750-a4933bc5-db7d-4315-811b-cd48f3f12c61.png)

**Comment by saber-wang** [comment]
https://github.com/dapr/components-contrib/blob/8f04d5d15dd6601c4eaebc77f1bb74c0a817b7d1/pubsub/pulsar/pulsar.go#L313-L325

Is `retry.NotifyRecover` called every time a failure occurs?
Is there a mechanism to call `Nack(message)` to notify pulsar that the message processing fails after the last retry.

**Comment by saber-wang** [comment]
https://github.com/dapr/dapr/issues/2217  Can this proposal be used to solve this problem?

**Comment by ItalyPaleAle** [comment]
I believe #1798 should fix this issue too

**Comment by saber-wang** [comment]
@ItalyPaleAle  I saw that the `Nack` call was added, which should solve this problem.

I have a question about where the `Nack` message is when there is no dead letter queue? Is the message discarded or continues to exist in the queue?

**Comment by ItalyPaleAle** [comment]
If there's no DLQ, messages that fail are added back to the queue and will be sent back to your applications _eventually_ (after the delay you can configure with that PR). If you have multiple instances of the same app, another instance may receive the message the next time.

Note: Pulsar doesn't offer a way to track how many times a message has been Nack'd, so it will be retried "indefinitely". Your application is responsible in that case for tracking how many times a message was attempted and discard (by returning no error) ones that can't be processed.

**Comment by saber-wang** [comment]
@ItalyPaleAle  Thank you for your answer
