### ISSUE TITLE
Eventhub Component in beta and not stable

### ISSUE THREAD

**Issue by ivanthelad** [dapr/components-contrib#1844]
Hi, 
Reviewing the supported pubsub components I see the Azure Eventhubs component is beta state. 
https://docs.dapr.io/reference/components-reference/supported-pubsub/

I was wondering if anyone should shed light on what aspect of the [stable](https://docs.dapr.io/operations/components/certification-lifecycle/#certification-tests) requirements are not met by the component

**Comment by greenie-msft** [comment]
@artursouza, @berndverst - Can you provide specifics on what is needed to flip this component from beta to stable?

Also, this question might come up for more components. Should we consider adding current status of component and the needed criteria for a component to move to the next state - example: conformance/cert tests, docs, etc?

**Comment by Radhikabollineni** [comment]
With 1.8 release, EventHubs can be announced as stable candidate, as per the criteria defined here: https://docs.dapr.io/operations/components/certification-lifecycle/#stable ;  the component has certifications tests as noted here https://github.com/dapr/components-contrib/tree/master/tests/certification/pubsub/azure/eventhubs;  
Also carrying the good documentation on its usage.  @berndverst - being the maintainer of the Repo to confirm.

**Comment by robeving** [comment]
Stable for reading (maybe) maybe but not for writing

https://github.com/dapr/components-contrib/issues/1764
and
https://github.com/dapr/components-contrib/issues/1598

**Comment by i-am-shodan** [comment]
still broken
