### ISSUE TITLE
Azure ServiceBus Binding error (cannot unmarshal string into Go struct field) - Dapr 1.8 RC

### ISSUE THREAD

**Issue by iamluso** [dapr/components-contrib#1845]
## Expected Behavior
We'd like to configure some new properties added in Dapr 1.8 RC for Azure ServiceBus Queues so that we can increase the messages processing pace:

- name: maxActiveMessages # Optional
  value: 10
 - name: maxConcurrentHandlers # Optional
 value: 1

## Actual Behavior
When adding the below parameters to the component YAML:
- name: maxActiveMessages
  value: 10
 - name: maxConcurrentHandlers
 value: 1

We receive the following error when the pod is starting:
{"app_id":"job","instance":"job-6f867c57cc-xs296","level":"fatal","msg":"process component <component> error: json: cannot unmarshal string into Go struct field serviceBusQueuesMetadata.maxActiveMessages of type int","scope":"dapr.runtime","time":"2022-07-04T12:56:23.30122603Z","type":"log","ver":"1.8.0-rc.5"}

## Steps to Reproduce the Problem

- Add the following config to the component YAML
  - name: maxActiveMessages # Optional
    value: 10
   - name: maxConcurrentHandlers # Optional
   value: 1

- Deploy and start the pod.

**Comment by yaron2** [comment]
Possible release blocker.

cc @ItalyPaleAle @artursouza

**Comment by ItalyPaleAle** [comment]
Thanks for the report. I will take a look at this tomorrow.

**Comment by ItalyPaleAle** [comment]
This is now fixed in release-1.8. a new RC is coming out shortly. Thanks again for reporting this and to @cmendible for fixing it :)
