### ISSUE TITLE
bindings.azure.blobstorage{ grpc: received message larger than max (13981148 vs. 4194304) }

### ISSUE THREAD

**Issue by kou-h** [dapr/components-contrib#1853]
Hello, I have this problem here. How can I solve it. thank you
![image](https://user-images.githubusercontent.com/70868445/177471645-d6709e5a-29f5-4935-af3c-97f200f3e329.png)

**Comment by ItalyPaleAle** [comment]
What operation are you executing?

**Comment by kou-h** [comment]
> What operation are you executing?

Hello, I'm trying to use bindings azure. blobstorage.  This error occurs when uploading files of more than 10MB

**Comment by ItalyPaleAle** [comment]
What we suspected is correct then. As @yaron2  said, you need to enable support for larger bodies.

That flag must be passed to the dapr CLI: https://docs.dapr.io/operations/configuration/increase-request-size/

**Comment by kou-h** [comment]
@ItalyPaleAle @yaron2 
By setting this flag, a large file was successfully uploaded. thank.
However, received message exceeded the maximum configured message size Which flag does this need to be set through?

**Comment by yaron2** [comment]
> @ItalyPaleAle @yaron2 By setting this flag, a large file was successfully uploaded. thank. However, received message exceeded the maximum configured message size Which flag does this need to be set through?

This setting should probably be set on your app, as Dapr tries to deliver the file over HTTP/gRPC

**Comment by kou-h** [comment]
@yaron2 
Thank you for your reply. Now I am using the dapr SDK for Net.
It seems that the attribute of response size is not set. Do I need to contact the dapr SDK for Net author?
https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/DaprClientGrpc.cs#L207
