### ISSUE TITLE
[pubsub][pulsar]Support pulsar+ssl:// URL format

### ISSUE THREAD

**Issue by Kyle2123** [dapr/components-contrib#1860]
## Describe the feature
Currently the pulsar pubsub component expects the Pulsar url to be in one of three formats:
- pulsar://
- http://
- https://

Please add support for the pulsar+ssl:// format to allow for connections to production Pulsar clusters that are configured to use TLS.

https://github.com/dapr/components-contrib/blob/3821c001315dfd2c24f8e1c6bdd19dd1ff21475d/pubsub/pulsar/pulsar.go#L49

https://github.com/dapr/components-contrib/blob/3821c001315dfd2c24f8e1c6bdd19dd1ff21475d/pubsub/pulsar/pulsar.go#L164-L167

**Comment by ItalyPaleAle** [comment]
Hey @Kyle2123  thanks for opening this issue! Would you be able to submit a PR for this?
