### ISSUE TITLE
Azure Service Bus binding fails to receive message

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#1865]
## Expected Behavior

Azure Service Bus binding continues to receive messages regardless of up time.

## Actual Behavior

After a "long" time, Azure Service Bus bindings stops receiving messages and sidecar must be restarted.

## Steps to Reproduce the Problem

Runs input binding for Azure Service Bus over a "long" period of time.

## Release Note

RELEASE NOTE:  **FIX** issue where Azure Service Bus binding would not receive messages after some time.

**Comment by ItalyPaleAle** [comment]
Can you please ask the user:

- What protocol does Dapr use to communicate with the app? HTTP or gRPC?
- Are they setting `app-max-concurrency`?

**Comment by mdaquel** [comment]
@ItalyPaleAle we've been experiencing the same behavior. Using gRPC protocol & no `app-max-concurrency` settings. Dapr runtime `1.8.2`.

**Comment by ItalyPaleAle** [comment]
@mdaquel Thanks for the report. How long before the issue appears, and is there anything "noteworthy" that happens before the issue appears?

**Comment by mdaquel** [comment]
@ItalyPaleAle in our case we've noticed that the issue happened when the input binding queue had not received any messages even for about 10 minutes.  After that period messages will start to bank up in that queue until we rollout restart the pods that receive events from that binding.  btw we're pretty early on our Dapr journey. This could be unrelated to this particular issue which a simple binding spec config tweak would resolve. Either way please feel free to advise. We'd be glad to hear your though & thanks heaps, cheers!

**Comment by ItalyPaleAle** [comment]
@mdaquel Just to confirm: you do not have any message published for 10 mins, or you just notice that this is frozen because you don't see messages for 10 mins?

Do you see anything relevant in the logs?

Are you able to run Dapr with log level "debug" (https://docs.dapr.io/operations/troubleshooting/logs-troubleshooting/) to see if the logs include anything useful please?

I will investigate further next week, but anything you can share would be very helpful.

**Comment by mdaquel** [comment]
@ItalyPaleAle we don't technically publish messages directly into the queue. The messages were produce externally/triggered from our Azure event grid events from our Azure storage account for any blob created & deleted.

Unfortunately we don't see anything specific or relevant in the logs for both the app & Daprd pod.

Yes we can run Dapr with log level debug and let you know as soon as possible.

That would be great if you can investigate further next week. We appreciate it, again thanks heaps!

**Comment by ItalyPaleAle** [comment]
@mdaquel I was able to confirm the issue and reproduce it.

In short, in case of certain errors (such as if the network is dropped for a prolonged amount of time) a lock was not released and this was causing ASB to hang. This impacts both the Azure Service Bus Queue binding and Azure Service Bus pubsub components, as that code is shared.

I will have a fix ready shortly.

**Comment by ItalyPaleAle** [comment]
@mdaquel  FYI discussed this with @berndverst  and @yaron2  and we will release Dapr 1.8.4 as a hotfix

**Comment by mdaquel** [comment]
@ItalyPaleAle, @berndverst and @yaron2  much appreciated. Amazing turn around time addressing this issue. Thank you so much!
