### ISSUE TITLE
Enable middleware with authorization policies against JWT tokens

### ISSUE THREAD

**Issue by mkosieradzki** [dapr/components-contrib#189]
As we have different authentication middlewares which results in acquring and validating JWT tokens, I believe it would be a good idea to provide a framework to write authorization policies against JWT tokens.

_This proposal assumes that middleware pipelines will be configurable based on path filters._

Related: #187, #155  

Example policies:
1. Array-based claim (like `group` or `role`) contains specific value.
2. Literal claim equals to string (eg. `sub`, `name` or `iss`).
3. Space separated claims (like `scope`) contains a specific value.

To be able to implement this we need a way to pass the parsed token down the stream alternatively we can look again at the `Authorization` header and parse JWT without performing any signature validation.

**Comment by RichiCoder1** [comment]
I'm interested in this, specifically `iss` and `scope`. Might be up for implementing too.

Is there currently a way to pass state between middleware? Would this be possible extending metadata?

**Comment by msfussell** [comment]
@mkosieradzki Does this PR https://github.com/dapr/components-contrib/pull/188 close this issue also?

**Comment by mkosieradzki** [comment]
@msfussell Unfortunately, not. #188 handles only the authentication part, but there is no place to do the authorization logic today.

**Comment by jjcollinge** [comment]
An example of parsing JWT in Go for authorization that we could build on for a middleware https://github.com/benc-uk/dapr-store/blob/master/pkg/auth/auth.go cc: @benc-uk

**Comment by benc-uk** [comment]
I'd like to turn this into a JWT validation middleware component. For some reason I thought there was one already (or at least a PR) but I went looking and couldn't find it.

It's kinda a classic use case for this sort of middleware.

Major thing to consider is how users specify which routes/URLs to secure, as in my experience you might want your API to expose a mix of open and secured routes

**Comment by benc-uk** [comment]
I'd like to turn this into a JWT validation middleware component. For some reason I thought there was one already (or at least a PR) but I went looking and couldn't find it.

It's kinda a classic use case for this sort of middleware.

Major thing to consider is how users specify which routes/URLs to secure, as in my experience you might want your API to expose a mix of open and secured routes

**Comment by mkosieradzki** [comment]
#188 does JWT validation

**Comment by jjcollinge** [comment]
Ah I searched and missed this too - either way we can look to extend it to add the authorization / claims parsing part. This may require changes to the middleware pipeline too.

**Comment by mkosieradzki** [comment]
My bad. Should have used JWT keyword in the description.

**Comment by benc-uk** [comment]
I knew I saw a PR somewhere! 🤔🙂

**Comment by msfussell** [comment]
@mkosieradzki @jjcollinge Looks like the PR is merged, however there are no docs on how to use this. 
Can you create a  PR for a Howto doc that can be included with the middleware section on how to use this JWT token?

**Comment by jjcollinge** [comment]
I think we may be able to use the request context to pass the JWT downstream - although this is unstructured so I’ll need to do some tests. Then we can start with some standard OIDC scope/claims handling and build from there. Will update once I’ve tried it  out.

**Comment by RichiCoder1** [comment]
@jjcollinge Looking forward to that! Agreed on policy language. For anything beyond that, some sort of integration with OPA ala https://github.com/dapr/dapr/issues/1350 would probably be preferred.

**Comment by jjcollinge** [comment]
I put a quick (and probably inaccurate) diagram together to try to make sure we're all on the same page. I guess open questions are, is the best abstraction to have different authorization middlewares i.e. `authz_opa`, `authz_basic`, etc. that can be assembled into a pipeline (with this PR https://github.com/dapr/dapr/pull/1557 we could use selectors). Or do we provide an interface such as `Authorize(token)` to the existing bearer middleware that can be configured. I'll continue to experiment with the separate middleware idea and see how it looks.
![oauth2](https://user-images.githubusercontent.com/7241190/83006581-5be3e300-a00a-11ea-95f3-e841430f7189.png)

**Comment by RichiCoder1** [comment]
That looks awesome! I think just a generic middleware would great, as I could imagine there might be cases where you want to terminate a request before it even gets to the authz middleware. So you might want to make policy decisions on both ends.

One helpful thing would likely be to added some sort of context dictionary so the OAuth/Bearer Middleware could make the token/parsed claims available somewhere without having to specialize the pipeline. That general seems to work well afai seen.

**Comment by RichiCoder1** [comment]
Also, if we allow pre & post OPA, and ensured that OPA policies [could manipulate things like headers](https://github.com/open-policy-agent/opa-istio-plugin#example-policy-with-object-response), you could potentially do custom token logic but still use the generic Bearer middleware for example. That may be a contrived case though.
