### ISSUE TITLE
Azure Service Bus Component: Metadata

### ISSUE THREAD

**Issue by clemensv** [dapr/components-contrib#1893]
https://github.com/dapr/components-contrib/blob/801297c724e9d55d55b3288b9b123c000a231df6/bindings/azure/servicebusqueues/servicebusqueues.go#L258

If the Service Bus integration is meant to be interoperable with message senders that aren't built with DAPR and possibly including such that talk to Service Bus directly using a generic AMQP client, which ought to be a goal, it needs to surface all potentially relevant metadata to the consumer, which includes all application properties and surely all of the fixed AMQP message properties. There's cherry-picking of three built-in properties here, notably excluding the "content-type" that's key to understand what "Body" is and the application properties are completely dropped.

**Comment by wesselkranenborg** [comment]
This is indeed what we are also facing. Our downstream service publishes messages with ApplicationProperties but we have no way to get these using the service bus queue dapr binding (that I am aware of). So I think this issue is stil relevant and not stale.

**Comment by opinionmachine** [comment]
Yea, how do you deal with OpenTelemetry if you've binned ApplicationProperties? I call shenanigans. 

Please open up access to System or ApplicationProperties, if not through headers, invent a payload that you can opt to receive from the sidecar that contains all the things you need to properly handle tracing and other application properties. It's bad enough you skated over Baggage that could have been used to forward important dimensions for the telemetry that could help enormously with observabililty across the estate. Binning Application Properties as well is a last straw.
