### ISSUE TITLE
Azure Service Bus: Application Properties maintained?

### ISSUE THREAD

**Issue by clemensv** [dapr/components-contrib#1894]
https://github.com/dapr/components-contrib/blob/801297c724e9d55d55b3288b9b123c000a231df6/pubsub/azure/servicebus/message.go#L76

I don't see the application-properties section of a service bus message getting mapped. Is that information dropped if the topic is being populated by a non-DAPR producer?

**Comment by berndverst** [comment]
No it's not part of 1.9.0. Our bot closed it for being stale. This hasn't been worked on yet.

It's probably the same as the dapr/dapr issue you mentioned in Discord.

I'll reopen and add it to the 1.10 milestone for now.

Any details you can provide would be great.

Most likely the data you seek would need to be sent via the Binding Request Metadata Dictionary.

**Comment by berndverst** [comment]
Unclear whether this is still an issue - and we didn't see this issue for the 1.10 release as it had auto-closed.
