### ISSUE TITLE
Service Bus/Event Hubs/Rabbit PubSub abstraction model issues

### ISSUE THREAD

**Issue by clemensv** [dapr/components-contrib#1895]
https://github.com/dapr/components-contrib/blob/801297c724e9d55d55b3288b9b123c000a231df6/pubsub/azure/servicebus/servicebus.go#L71

While the issue I raise here is with the PubSub abstration in general, I am anchoring it on the Service Bus implementation of the interface, because it's more straightforward to discuss a concrete example.

The abstraction squishes three distinct concerns into a single interface: publishing, subscribing, and consuming. 

Outside of trivial use-cases inside of a single application/service, those are very different operations with very different required permissions and required capabilities. A publisher is often not permitted to receive from the channel it sends to, because those channels are often shared across multiple publishers with distinct identities. A consumer is often not authorized to manipulate the pubsub engine rules to set up their own subscriber relationship. The act of "subscribing" often entails a configuration of the pubsub engine inside of the broker with particular filtering rules, and the subscribing party may quite well not be the consumer but an orchestrator. 

Multiple consumer instances may need to share a single subscription on a pubsub stream -- for different reasons. In one case, consumers need to share a subscription to collaboratively consume a single stream in parallel and without overlap. In another case, consumers share a subscription to consumer and handle jobs competitively. That is the key difference between and event stream and a queue-style subscription on a pubsub broker. Yet, the implementations for Service Bus and Event Hubs differ vastly even in terms of semantics and control of what the "subscribe" abstraction means. 

The Event Hubs implementation appears to sidesteps creating a separate subscription  (a "consumer group") on "subscribe" by having the consumer group name in config and then creating that CG on need. "Subscribe" is then apperantrly merely adding a new reader to that CG, but that does not match the semantics of "subscribe". "Subscribe" on Event Hubs is the act of creating a new consumer group and providing an initial offset positon from where that consumer group starts reading.  

The Service Bus implementation doesn't appear to allow for sharing a subscription; it insists on creating a new one for each consumer.  Here, again, the act of subscribing is squished into the path of creating a consumption relationship, but disregards that the pubsub engine has rules and filters that execute on the server side and need to be configured, and where the act of configuration (=routing) may quite well happen as a control action on the application.

The "subscribe request metadata" escape hatch that exists for subscriptions breaks the promise of "write once, configure anywhere".  The RabbitMQ implementation sneaks a ["routingKey"](https://github.com/dapr/components-contrib/blob/801297c724e9d55d55b3288b9b123c000a231df6/pubsub/rabbitmq/rabbitmq.go#L189) through the subscriber interface, which doesn't make sense for configuring the same code on top of the Service Bus provider. if the Service Bus provider did the same and smuggled a SQL rule in the SB dialect through the same interface, a RabbitMQ implementation would not be able to deal with it. 

While "subscribe" varies, the "consume" operation would largely be the same for both brokers, but squishing "subscribe" and "consume" into one operation makes it difficult to build code that is using features of the underlying brokers and remains interoperable.

I assume that the MQTT subscribe request implementation "cheats" silently here, because the topic path that is provided with the request presumably does permit MQTT topic wildcards, which would not work on a different broker's addressing model.

My suggestion for evolution of this interface is to cleanly separate the flow path interfaces (publish, consume) and the control path interface (subscribe). 

For "consume" there should be a separation of queue-style paths where the application threads might compete for messages and get explicit control of server-side settlement (accept, release, reject) and a variation where the applications handle streams and control read offsets and client-side checkpoints as it is common with event stream engines. The current abstraction pretends that Kafka and RabbitMQ are functionally similar and that is clearly not the case. 

I do recognize that there is a challenge with splitting subscribing and consuming is that there are cases where the protocol itself mixes the subscribe/consumer concerns and subscriptions are scoped to the lifetime of a receiver session, most prominently in MQTT. In AMQP, there is also the ability to create a receive link with a source filter (Apache Qpid JMS uses that for message selectors against queues and volatile topics), which is functionally equivalent. So there might indeed be a separate control interface for subscriptions that manifest durably and are sharable and an interface more closely aligned with consuming that can manage subscriptions scoped to this client. 

JMS has such a conceptual split between durable and volatile subscriptions, even though I would not recommend concrete shape of JMS.

As I see the abstraction and some of the implementations today, the abstraction keeps customers too far away from broker feature details while, at the same time, being leaky such that using particular request metadata elements or even tropic paths with inadvertently bolt an app to a particular protocol/product, sabotaging the goal of the abstraction.

**Comment by sadgit** [comment]
Separate subscriptions for multiple parallel consumers is a fundamental part of the reactive model.

The mapping of a near-unlimited number of multiple handlers to a given topic should be part of the basic design.
