### ISSUE TITLE
[Proposal] Blob Storage as State Store

### ISSUE THREAD

**Issue by aloneguid** [dapr/components-contrib#191]
## Describe the proposal

Blob storage is currently supported as output bindings (S3, Azure etc.) however I can see scenarios when blob storage would be extremely useful for state stores as well. 

First, considering the availability of tools, it's much easier to view blob storage compared to say Dynamo DB.

Second, blob storage is extremely cheap for low traffic scenarios. I'm not quite sure whether blob storage is actually cheaper for high traffic as well.

Blob storage is a key-value storage too - key is blob name, value is blob content. One can attach key-value metadata for a blob as well. Optimistic concurrency is supported via ETags (for instance in Azure Blob Storage).

**Comment by msfussell** [comment]
@aloneguid - are you interested in adding Azure Blob Storage as a state store?

**Comment by ksivamuthu** [comment]
I'm interested to do if it is free to take.

**Comment by aloneguid** [comment]
@msfussell I'm happy for @ksivamuthu to do it, I'm not too active for a next month or so. Looking forward to contribute to some other component soon.

**Comment by youngbupark** [comment]
@ksivamuthu Can you please create docs as well ?

**Comment by youngbupark** [comment]
@ksivamuthu please follow [this doc style](https://github.com/dapr/docs/tree/master/contributing#contributing-to-how-tos) when you create the howto.
