### ISSUE TITLE
Add certification tests for Azure Cosmos DB State store

### ISSUE THREAD

**Issue by amulyavarote** [dapr/components-contrib#1912]
The Azure Cosmos DB State store requires certification tests to be created.

Conformance tests are already present.

Release Note

RELEASE NOTE: ADD Certification tests for Azure Cosmos DB State store

**Comment by amulyavarote** [comment]
Azure Cosmos DB State Store Certification

The purpose of this module is to provide tests that certify the Azure Cosmos DB State Store as a stable component.

Certification Tests:

Azure Cosmos DB State Store Certification

The purpose of this module is to provide tests that certify the Azure Cosmos DB State Store as a stable component.

Certification Tests

- Verify the authentication with Azure Active Directory.
    - Create component spec.
    - Run dapr application with component.
    - Ensure the authentication is successful.
- Verify the authentication with master key.
    - Create component spec.
    - Run dapr application with component.
    - Ensure the authentication is successful.
- Verify invalid partition key specified.
    - Create component spec.
    - Run dapr application with component.
    - Ensure the invalid partition key fails.
- Verify missing partition key.
    - Create component spec.
    - Run dapr application with component.
    - Ensure the missing partition key fails. 
- Verify missing id from the document.
    - Create component spec.
    - Run dapr application with component.
    - Ensure the missing id fails. 
- Verify the connection is established to DB.
    - Create component spec.
    - Run dapr application with component.
    - Ensure that you have access to the DB and connection to the DB is established.
- Verify set, fetch, update and delete operations are performed.
    - Create component spec.
    - Run dapr application with component.
    - Ensure that the operations are performed.
- Verify negative test to fetch record with key, that is not present
    - Create component spec.
    - Run dapr application with component.
    - Ensure that the operation fails.

**Comment by rabollin** [comment]
@amulyavarote  - https://github.com/dapr/components-contrib/issues/1138 is similar to this current work and is in works by 
shivamkm07.  Please and avoid redundant efforts here.

**Comment by amulyavarote** [comment]
Closing this because this is a duplicate issue.
