### ISSUE TITLE
Proposal: Rate Limiting Middleware

### ISSUE THREAD

**Issue by jjcollinge** [dapr/components-contrib#192]
## Proposal: Rate Limiting Middleware
Add a middleware that can throttle the rate of requests.

Potential rate limiters to leverage:

- https://godoc.org/golang.org/x/time/rate
- https://github.com/juju/ratelimit
- https://github.com/uber-go/ratelimit

We'd probably want to support 2 modes of operation, one that throws a 429 and expects the user to retry and one that blocks until a token is available.

**Comment by yaron2** [comment]
Dapr supports rate limiting:
https://github.com/dapr/docs/blob/master/howto/control-concurrency/README.md

However it's interesting to move that logic into a middleware.

**Comment by yaron2** [comment]
Ok, so the above rate limits the user app, I gather this is to rate limit Dapr?

**Comment by jjcollinge** [comment]
Sorry, I completely missed the existing rate limiting - I just did a quick search and didn't find anything so proposed this 🤦‍♂️. If you think having a middleware option is of value then we can pursue this a bit more - if not feel free to close this!

**Comment by jjcollinge** [comment]
Although looking at the existing control I think the middleware could be used to compliment or extend it. Like you say the middleware would allow you to throttle requests coming into Dapr. We could look to isolate it to just Dapr ingress and then you could use concurrency controls to control appplication ingress. Or something to that effect.

**Comment by jjcollinge** [comment]
A bug in Dapr https://github.com/dapr/dapr/issues/948 made me think the middleware behaved differently to how I expected, once that's been fixed the middleware will only be invoked once per client call. Therefore we can use this to throttle client and app calls into Dapr. Whereas the existing concurrency control is just Dapr calling the app. Hope that makes sense.
