### ISSUE TITLE
Hashicorp Vault secret store as Stable

### ISSUE THREAD

**Issue by tmacam** [dapr/components-contrib#1926]
* The [HashiCorp Vault Secret Store Component] requires certification tests to be created.
* Add conformance tests if not present.

[HashiCorp Vault Secret Store Component]: https://docs.dapr.io/reference/components-reference/supported-secret-stores/hashicorp-vault/

**Comment by berndverst** [comment]
This is incomplete.

The Hashicorp Vault Certification tests created by @tmacam and merged by @artursouza are incomplete and don't cover most metadata options at this time. Hence this task was not complete yet.

**Comment by berndverst** [comment]
Given this is incomplete, I think we should mark the component as Beta for now @artursouza @tmacam. It will be stable once we complete the remaining certification test scenarios.

**Comment by tmacam** [comment]
I will send a PR later this week with the remaining tests,
