### ISSUE TITLE
Cron Binding - Does it have a load balancing option?

### ISSUE THREAD

**Issue by MotaOcimar** [dapr/components-contrib#1927]
I did some tests with the Cron Binding and noticed that each instance of my application in Kubernetes is triggered by that binding.
However, I'm afraid this will cause multiple unnecessary actions as a result (eg multiple requests to a third application).
I would like to know if it is possible to load balace the Cron Binding calls, similarly to what happens with the service invocation.

I also take the opportunity to ask if this also applies to the other Input Bindings, that is, is a trigger sent to each instance or to a single one?

**Comment by sarsharma** [comment]
@MotaOcimar 
This might help : https://github.com/dapr/components-contrib/issues/1249#issuecomment-959799552

**Comment by markheath** [comment]
It would be nice if this was available as an option for the Dapr cron binding (or maybe an additional binding that ) as that's how the Timer trigger in Azure Functions works, and in most cases that's what's wanted. I seem to remember that Azure Functions used blob leases to achieve that, and I guess the Dapr distributed lock building block could be used to achieve a similar result.
