### ISSUE TITLE
Installing Custom Daprd into Kubernetes

### ISSUE THREAD

**Issue by charlesATswin** [dapr/components-contrib#1952]
Hello,

I have been working through the guide [here](https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md) for developing a new Dapr component. At step 6 it talks about replacing the `daprd` binary; this is not in `~/.dapr/bin` as shown. I concluded that this is due to the fact I am running Dapr on Minikube at the moment and therefore there are no local files, is this right? If so, I presume I need to change the image being used to deploy the Dapr sidecar? Is this right? If so which images should I be building and overriding in my K8s? 

Any help would be greatly appreciated.

**Comment by Mellonta** [comment]
I'm running into the same issue. Did you manage to do it?
