### ISSUE TITLE
amqp:link:detach-forced error messages from pubsub.azure.eventhubs components

### ISSUE THREAD

**Issue by skylaro** [dapr/components-contrib#1969]
## Expected Behavior

Azure container apps should properly run and scale without periodic exception messages occurring.

## Actual Behavior

Azure container apps unexpectedly shutting down and scaling in.

## Steps to Reproduce the Problem

Irreproducible. Issue is periodic and is currently affecting all container apps under a particular azure container app environment resource.

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
This should be fixed by https://github.com/dapr/components-contrib/pull/1783 (issue https://github.com/dapr/components-contrib/issues/1612) from Dapr 1.8.0.

Please try with Dapr 1.8.4 (the latest 1.8.X release)

**Comment by ItalyPaleAle** [comment]
Could you please provide some more insights on what the error that you're experiencing is?

Also, Azure Container Apps should start seeing Dapr 1.8 in the next days at this point, if it's not completely rolled out already.

**Comment by skylaro** [comment]
@ItalyPaleAle, the customer is using the pubsub.azure.eventhubs component on several azure container apps and is seeing very unexpected scaling behavior, which we think could be due to the amqp errors picked up in the logs. I'll confirm when our 1.8 rollout will occur and confirm if that fixes the scaling issues.

**Comment by ItalyPaleAle** [comment]
Rollout of Dapr 1.8.x is now complete in Container Apps.

Please also do share any log message you have. We will need those to investigate the issue.

**Comment by berndverst** [comment]
Closing this due to lack of further info. Likely fixed by 1.8 release. Reopen as necessary.
