### ISSUE TITLE
AWS SQS/SNS Pubsub as Stable

### ISSUE THREAD

**Issue by mcandeia** [dapr/components-contrib#1971]
- The [AWS SQS/SNS Pubsub](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-aws-snssqs/) requires certification tests to be created.
- Add conformance tests if not present.
- TODO - Complete the list of items here to get this component to stable

**Comment by mukundansundar** [comment]
todo

**Comment by olitomlinson** [comment]
+1 for this
