### ISSUE TITLE
Define a common metadata object across components

### ISSUE THREAD

**Issue by mcandeia** [dapr/components-contrib#1990]
## Describe the proposal

The structs for the components metadata are being redefined in each component. This is good because it allows components to have different metadata, but on the other hand it does not allow components share a common structure to define common abstractions, such as the component name that is only supported by the bindings metadata.

This will be used soon, for creating pluggable components connections [see related issue](https://github.com/dapr/dapr/issues/4925#issuecomment-1222719786).

See the current state of the components' metadata here:

1. [Bindings](https://github.com/dapr/components-contrib/blob/master/bindings/metadata.go)
2. [PubSub](https://github.com/dapr/components-contrib/blob/master/pubsub/metadata.go)
3. [State Store](https://github.com/dapr/components-contrib/blob/master/state/metadata.go)
4. [Secret Stores](https://github.com/dapr/components-contrib/blob/master/secretstores/metadata.go)
5. [Name Resolution](https://github.com/dapr/components-contrib/blob/master/nameresolution/metadata.go)
6. [Configuration](https://github.com/dapr/components-contrib/blob/master/configuration/metadata.go)
7. [Middleware](https://github.com/dapr/components-contrib/blob/master/middleware/metadata.go)

This issue proposes to create a common metadata structure across components, including `Properties` and the `Name` of the Component

```golang
type BaseMetadata struct {
        Name string
	Properties map[string]string `json:"properties"`
}
```

All components metadata will embed the `BaseMetadata` having yet the possibility of extending the metadata with the component-specific fields.

The dapr runtime should add the name of the component when initializing the component.

### Considered alternatives:

[Change factory method](https://github.com/dapr/dapr/blob/master/pkg/components/bindings/registry.go#L36) to receive the component name - It generates a higher overhead than just create a common metadata object - and brings less advantages

**Comment by berndverst** [comment]
LGTM

**Comment by mcandeia** [comment]
I decided to take another approach for this issue, but first, let's go to the facts,

## The problem

The PR changed the way we instantiate the metadata object for all components, so, instead of having

```golang
metadata := bindings.Metadata { Properties ... }
```

We're going to have

```golang
metadata := bindings.Metadata { Base: metadata.Base { Properties... } }
```

> Notice that the properties still being accessible via metadata.Properties

I managed to change all 4xx occurrences on the entire code-base to rewrite the way it's being instantiated.

However, because our certification tests run against the current components-contrib repository - and pinned dapr runtime, breaking changes becomes harder to do, in the sense of when you have to change something here that's already being used inside dapr/dapr you're enforced to keep backwards compatibility - it shouldn't, given that the dapr/dapr [has pinned](https://github.com/dapr/dapr/blob/master/go.mod#L11) the components-contrib version. 

In fact, the dapr runtime will not break if we do commit breaking changes here as long as the components-contrib remain pinned there. The source of the problem comes from [here](https://github.com/dapr/components-contrib/blob/master/tests/certification/go.mod#L7) + [here](https://github.com/dapr/components-contrib/blob/master/tests/certification/go.mod#L130), so the dapr runtime from certification tests will use the indirect components-contrib dependency version from the local code base, which is actually good for test purposes - testing against the current repository changes.

So, all the certification tests have broken because they can't properly instantiate the metadata object.

Since this problem is out of context of the initial proposal I think this should be discussed in another issue.

This leads us to the following options:

## Alternatives

### Remove the `Properties` attr from the base metadata and keep only the `Name` attr

The new base metadata will look like:

```golang
package metadata
type Base struct {
    Name string
}
```

Sadly, the `Properties` is the only one that's actually shared across components.

### Temp Methods/Structs
Another option is actually creating a New Init Method and a New Metadata object that will co-exist with the current one. This change is really huge (touches in many points) and also require 2 PRs here and 2 PRs on the runtime side


```golang

type MetadataTemp struct { // for each component
}

func InitTemp(metadata MetadataTemp) // for each component
``` 

### Run certification tests against dapr/dapr modified branch

For that we have to take the following steps,

1. open a branch in dapr/dapr pointing to a modified version of components-contrib that contains the breaking changes
2. Get it reviewed and approved
3. Go to the components-contrib and point the certification tests to the dapr/dapr branch version
4. Get the certification tests approved
5. Merge the components-contrib version
6. Merge the dapr/dapr version pointing to the master version of the components-contrib (now in master)
7. Open a brand new components-contrib PR and change the certification module to point to the master version of dapr/dapr


For a small window of time we will have the certification tests pointing out to a branch version of dapr/dapr, but it seems reasonable.

**Comment by berndverst** [comment]
> However, because our certification tests run against the current components-contrib repository - and pinned dapr runtime, breaking changes becomes harder to do, in the sense of when you have to change something here that's already being used for dapr runtime you're enforced to keep backwards compatibility - it shouldn't, given that the dapr runtime [has pinned](https://github.com/dapr/dapr/blob/master/go.mod#L11) the components-contrib version.

Incorrect. This is by design so that any change checked into contrib can be evaluated against certification tests on PR. The Dapr runtime does not need to be updated for this unless a new API is introduced / API is modified, or a new component is registered.

We must keep the local replace of contrib. This is a hard requirement.

**Comment by berndverst** [comment]
Thanks for putting together these options.

I think we should go with the **temporary branch / fork of dapr/dapr** which we will only import in `tests/certification` within contrib.

After your change lands in dapr/dapr master we can then update the certification tests to the real `dapr/dapr` again.
