### ISSUE TITLE
[redis Configuration]After the dapr is started, the newly added key cannot be subscribed

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1999]
## Expected Behavior

If do not specify a key, you can subscribe to the newly added configuration item.

## Actual Behavior

Cannot subscribe to the newly added configuration item

## Steps to Reproduce the Problem

1. Do not specify key subscription configuration
```
using var client = new DaprClientBuilder().Build();
var _configurationResponse = await client.SubscribeConfiguration("configuration",new List<string>());
 await foreach (var items in _configurationResponse.Source.WithCancellation(cancellationToken))
     {
        _logger.LogInformation("{@items}", items);
     }
```
2. Add a key that does not exist in redis
3. Observation log (no output)

**Comment by berndverst** [comment]
Sounds like whenever a key is not found there should be an attempt to refresh the list of known keys.

Which configuration store is this? Redis? This problem will be specific to the configuration store. (We have multiple configuration stores now)

**Comment by saber-wang** [comment]
@berndverst  Yes, the current test is redis.

**Comment by pravinpushkar** [comment]
Related issue is here in runtime - https://github.com/dapr/dapr/issues/5183
IMO the problem is in current impln for subscribe all in runtime. The solution may span both runtime and specific components.
