### ISSUE TITLE
How to use Dapr SignalR Output Binding?

### ISSUE THREAD

**Issue by MotaOcimar** [dapr/components-contrib#2012]
It's not clear to me how to use Dapr's SignalR output Binding.

If I understand correctly, SignalR works with communication between three parties:
- A server, which will provide functions to be called by clients, as well as being able to call functions from connected clients;
- Clients, which can call server functions, as well as provide functions to be called by the server;
- A Hub, which will manage connections.

I also understood that for a client to connect to the hub, [it must first connect to the server, which will do the redirection](https://stackoverflow.com/questions/50930551/how-do-i-pass-the-accesskey-value-to-an-azure-signalr-server-in-c).

Since Dapr connects directly to the Hub, I assume it is the server, right?

And if so, how do I connect a client to it?

**Comment by berndverst** [comment]
Take a look at this issue which my provide some information:
https://github.com/dapr/components-contrib/issues/147

And maybe this part of the docs is helpful: https://docs.dapr.io/reference/components-reference/supported-bindings/signalr/#additional-information

Beyond that I cannot provide any further assistance as I am not familiar with SignalR. Maybe @yaron2 can help here.

**Comment by MotaOcimar** [comment]
@chenkennt, I saw that you answered the [StackOverflow question](https://stackoverflow.com/questions/50930551/how-do-i-pass-the-accesskey-value-to-an-azure-signalr-server-in-c). Can you help me?

**Comment by chenkennt** [comment]
In order to SignalR service, client needs to first do a negotiate with server to get the url of the service and access token. Dapr SignalR binding doesn't have a built-in support for this, so you need to implement it by yourself. You can refer to this doc about how to expose a negotiate endpoint manually:
https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-reference-data-plane-rest-api#implement-negotiate-endpoint

Also seems Dapr SignalR binding only supports output binding so you can only use it send messages to clients but cannot receive messages from client. You can do it by yourself by implement webhook to receive messages. Checkout this doc for details:
https://docs.microsoft.com/en-us/azure/azure-signalr/concept-upstream

**Comment by chenkennt** [comment]
Here is a code snippet that shows how to do the negotiate and send message using Dapr binding (using node.js and express). Hope it helps.

```js
import { DaprClient } from '@dapr/dapr';
import express from 'express';
import jwt from 'jsonwebtoken';

const client = new DaprClient(process.env.DAPR_HOST || 'http://localhost', process.env.DAPR_HTTP_PORT || '3500');
const hub = 'chat';
const connectionString = '<your-connection-string>';
let app = express();
app.get('/send', (req, res) => {
  client.binding.send('signalr', 'create', {
    Target: 'foo',
    Arguments: ['bar']
  });
  res.send('done');
}).post('/chat/negotiate', (req, res) => {
  let endpoint = /Endpoint=(.*?);/.exec(connectionString)[1];
  let accessKey = /AccessKey=(.*?);/.exec(connectionString)[1];
  let url = `${endpoint}/client/?hub=${hub}`;
  let token = jwt.sign({ aud: url }, accessKey, { expiresIn: 3600 });
  res.json({ url: url, accessToken: token });
});
app.listen(5000, () => console.log('server started'));
```

Then call `/send` the send the message and use the following code in browser to receive it:
```js
let connection = new signalR.HubConnectionBuilder()
  withUrl('/chat')
  build();
connection.on('foo', message => console.log(message));
connection.start();
```

**Comment by MotaOcimar** [comment]
Thank you very much @chenkennt!!!
It was exactly what I was looking for.

**Comment by MotaOcimar** [comment]
@chenkennt one more question:
How can I get the user id on the server?
That same user id that goes in [the "user" field of "metadata"](https://docs.dapr.io/reference/components-reference/supported-bindings/signalr/#additional-information)

**Comment by MotaOcimar** [comment]
A general question now:
It would be useful to have some Dapr API to help with SignalR negotiation.
Is this something that might fit within the scope of Dapr?

**Comment by berndverst** [comment]
> A general question now: It would be useful to have some Dapr API to help with SignalR negotiation. Is this something that might fit within the scope of Dapr?

No this does not make sense in Dapr. Dapr provides APIs that are not integration / implementation specific and can be used with a variety of components / integrations.

If you can think of an entirely new component abstraction (building block) with a set of APIs that would apply to multiple integrations, feel free to create a proposal for that in the Dapr/Dapr repo.

**Comment by chenkennt** [comment]
User ID can be set in the `sub` claim when generating the token:

```js
let token = jwt.sign({ aud: url, sub: '<user-id>' }, accessKey, { expiresIn: 3600 });
res.json({ url: url, accessToken: token });
```
