### ISSUE TITLE
Apache Pulsar pubsub as Stable

### ISSUE THREAD

**Issue by addjuarez** [dapr/components-contrib#2013]
The Pulsar pubsub requires certification tests to be created.
Add conformance tests if not present.

**Comment by berndverst** [comment]
@addjuarez please rename this issue to "Stable certification for Apache Pulsar in Pubsub" or something like that.

Right now this issue sounds like the component is stable but missing tests. However, the component is Alpha.

**Comment by artursouza** [comment]
Is there any test for message redelivery in cert tests or are all that covered in conformance?

**Comment by addjuarez** [comment]
Yes I will make sure all properties are at least used add a test validating them. I also do not see retry tests in conformance. I will add one in the Certification tests.
