### ISSUE TITLE
Query API: Set filters when Unmarshalling Query struct

### ISSUE THREAD

**Issue by mcandeia** [dapr/components-contrib#2037]
## Describe the proposal

The default [query unmarshal](https://github.com/dapr/components-contrib/blob/master/state/query/query.go#L98) doesn't set the Filters field as it does for the others fields - sort and page.

It's not a problem for any of our current state component since filters has only been used for building the `Filter` [interface](https://github.com/dapr/components-contrib/blob/master/state/query/query.go#L45),

However if a component needs to send this data serialized as JSON this would become a problem, which is probably not the case for any of the components made within that repository.

This proposal is just a way to make it easier to serialize filters as JSON for components that need to resend them (i.e. pluggable components). Another option would be to reverse engineer the filters, but given that this modification is small enough to have no problem, I believe it would be easier to set the field.

**Comment by berndverst** [comment]
Feel free to open a PR @mcandeia - just make sure it doesn't break any conformance or certification tests. If it does, you may need to update some components' Query API implementation.
