### ISSUE TITLE
Proposal: Conformance test

### ISSUE THREAD

**Issue by youngbupark** [dapr/components-contrib#204]
# Overview

Conformance test in component-contrib determines whether component implementation complies with the requirements of Dapr specification to guarantee the consistency of components.

# Purpose

* Standardize tests for component to enable the consistency with the below aspects:
   - Performance
   - Function & Behavior
   - Robustness
* Remove dapr/dapr repo dependency while developing new component

# Proposed conformance test process

Contributors use their own environments or cloud resources while developing component-contrib. It is difficult and insecure to share their dev environments and secrets to access their own resources. Therefore, contributors need to test new component with conformance test tools on their development machines.

1. Implement new component
2. Create metadata yaml, that includes connection info, and credentials for new component
3. Run conformance test tool using make
```
go test ./tests/... --component.type=statestore --component.name=new_statestore
```
4. Repeat step 3 until conformance tests are passed
5. Remove Credentials in metadata yaml
6. Create the pull request to add generated test reports into conformance test report repo
7. Create the pull request to add new component to component-contrib

Component contributors can develop new component without Dapr and test and validate components consistently and effectively, improving robustness and functional correctness in Dapr. Contributors will neither write integration tests for new component nor clone Dapr for the validation, which will improve the productivity. 

# Conformance test tooling

Conformance test will leverage built-in go test. Conformance test contributor (or maintainers) will pre-create conformance test cases which will be used for all components. Component contributors will use the pre-created test sets rather than their own test code even if they need to write minimal validation code for bindings.

* /tests/conformance/[component_type]/ 
   - This includes comformance test framework and common test sets for performance, function, and robustness
   - Owners: Conformance test contributors or maintainers
* /tests/custom/[component_type]/[component]/
   - This includes custom validation code such as input/output bindings e.g. state doesn’t require this custom code because it provides get/set methods in state interface.
   - Owners: Component contributors
* /tests/config/[component_type]/[component]/
   - This includes metadata config yaml for testing. Component contributors should remove the credentials before submitting the code.
   - Owners: Component contributors
* /tests/results
  - Once component contributors run the conformance test, conformance test framework will generate test report. Component contributors need to submit this test report as well

# Action items

* Design conformance test framework/tools
* Define test cases for each component type
#404

**Comment by youngbupark** [comment]
@yaron2 @amanbha @Haishi2016 @artursouza @LMWF @shalabhms / I know we have not planned it but we need this to enable the consistency across components in a standardized way in the long term. Please review it and leave some feedbacks. 

cc/ @msfussell @lukekim

**Comment by youngbupark** [comment]
@abhirockzz @sayboras @jjcollinge Can you please review this proposal and leave any feedbacks and comments?

**Comment by jjcollinge** [comment]
This would be a very welcome addition. I’ve only had a quick scan but it sounds reasonable, I’ll have a more thorough read later this week. One initial thought is what the plan would be to keep the tests in sync with Dapr? Would this just be manually managed as part of dapr PRs or is there a better way?

**Comment by youngbupark** [comment]
> ... One initial thought is what the plan would be to keep the tests in sync with Dapr? Would this just be manually managed as part of dapr PRs or is there a better way?

Maybe we set up new workflow to clone dapr/dapr and enable new component in dapr. Then build the testable binaries. Or we can set up CI which will create PR against dapr/dapr repo by using github rest api with the latest component-contrib whenever component-contrib PR is merged. but it looks like this is out of scope of this proposal :) You can create new proposal.

**Comment by LMWF** [comment]
lgtm - yes we need a method to validate components.

**Comment by abhirockzz** [comment]
This would be really helpful!

**Comment by amanbha** [comment]
Thanks @youngbupark  This would be good for the repo, one thing to note is that perf characteristics of each component would be different so the tests should allow for an acceptable deviation in perf measurement.

**Comment by artursouza** [comment]
LGTM

**Comment by yaron2** [comment]
> Thanks @youngbupark This would be good for the repo, one thing to note is that perf characteristics of each component would be different so the tests should allow for an acceptable deviation in perf measurement.

This.

**Comment by youngbupark** [comment]
> Thanks @youngbupark This would be good for the repo, one thing to note is that perf characteristics of each component would be different so the tests should allow for an acceptable deviation in perf measurement.

Yes we should allow acceptable range for the performance. In the beginning, we may have to allow large range in the test and learn from customer's test results to decide the proper range.

**Comment by jjcollinge** [comment]
@youngbupark - just flagging this proposal again as I think this is required before 1.0. I will do a quick prototype of the above proposal later this week and then we can review if we think it's the right pattern.

**Comment by youngbupark** [comment]
> @youngbupark - just flagging this proposal again as I think this is required before 1.0. I will do a quick prototype of the above proposal later this week and then we can review if we think it's the right pattern.

Fantastic!  I think you can start state component first as a prototype :) Thanks for taking this.

**Comment by jjcollinge** [comment]
I'll probably have to push this to next week but will still take a crack at it. Seems sensible to start with the state api, thanks!

**Comment by mukundansundar** [comment]
closing this issue since it is handled by https://github.com/dapr/components-contrib/issues/405
