### ISSUE TITLE
Secret components should advertise Multiple Key-Values support 

### ISSUE THREAD

**Issue by tmacam** [dapr/components-contrib#2047]
## Describe the feature

In the [Secret API Documentation](https://docs.dapr.io/reference/api/secrets_api/#response-body) it is stated:

> If a secret store has support for multiple keys in a secret, a JSON payload is returned with the key names as fields and their respective values.
>
> In case of a secret store that only has name/value semantics, a JSON payload is returned with the name of the secret as the field and the value of the secret as the value.

There are two classes of secret stores but there isn't a way to tell them apart at run-time. This limits the ability of conformance tests to verify the behavior of secret stores supporting multiple keys.

The proposal is to, similarly to what is done with State Stores, have Secret Stores "advertise" the _features_ they support (implement `getFeatures`). This particular feature could be named `MULTI_VALUED` to match the configuration flag on [Local File Secret Store] or something more verbose but technically accurate like `MULTIPLE_KEY_VALUES_PER_SECRET`. Stores not advertising such flag would be assumed to be single valued by default or, another option, they could be required to expose a `SINGLE_VALUED` feature.

This would also help documenting expected secret store behavior so a table like https://v1-2.docs.dapr.io/reference/components-reference/supported-state-stores/ could be produced.

(Interestingly [Local File Secret Store] is a secret store that can support both modes of operation depending on the value of its `multiValued ` configuration flag.)

## Release Note

RELEASE NOTE: **ADD** Secret Stores advertise supported features.

[Environment Variable Secret Store]: https://docs.dapr.io/reference/components-reference/supported-secret-stores/envvar-secret-store/
[Local File Secret Store]: https://docs.dapr.io/reference/components-reference/supported-secret-stores/file-secret-store/

**Comment by berndverst** [comment]
I support this. Also I like the longer feature key you suggested "MULTIPLE_KEY_VALUES_PER_SECRET"

**Comment by tmacam** [comment]
Should this block #1926 or should conformance and certification be done with the current model?

**Comment by artursouza** [comment]
I support his.

**Comment by berndverst** [comment]
@artursouza personally this is P2 -- the reason being that Keyvault and File are the only secret stores that support multiple keys and we have fairly good tests for keyvault.

**Comment by berndverst** [comment]
@tmacam this does not block https://github.com/dapr/components-contrib/issues/1926. The certification test can proceed.

**Comment by mcandeia** [comment]
I don't know if is my lack of knowledge, but it seems to me that the problem is that our secret store is not uniform, therefore, not predictable.

The problem here is to "flatten" the keys when the secret store supports json, if assuming consistent behavior doesn't solve the problem?

For example:

Always return JSON when supporting JSON and return plain-text when not supporting JSON? + specifying content type (same as statestore)

Or if the idea is to always support json let it be

key: value

or

key: {
     prop: value
}

Am I missing something?

**Comment by tmacam** [comment]
I agree with @mcandeia: secrets interface is odd. If we checked out how most of the secret stores interfaces are defined we would reach a `getSecret(secretName) -> secretValueAsRawBytes` API. 

Our interface, however is such that even for a secret store that only supports a single value per secret, we are still wrapping the response in a map such as `getSecret(secretName) -> { secretName: secretValue}`. Great that we can model more complicated secret stores this way but it seems an unnecessary complication for the most common and frequent usages.

Somethings tells that at this point this decision of returning a Map is grandfathered and we can't revisit it but I would really like to listen to what others think.
