### ISSUE TITLE
Cron binding as Stable

### ISSUE THREAD

**Issue by sarsharma** [dapr/components-contrib#2056]
* The [Cron Binding](https://docs.dapr.io/reference/components-reference/supported-bindings/cron/) requires certification tests to be created.
* Add conformance tests if not present.

**Comment by mukundansundar** [comment]
👋

**Comment by nyemade-uversky** [comment]
@berndverst would you be able to double check on this and mark this as closed if the changes look good?

**Comment by DeepanshuA** [comment]
Docs issue for change from Input/Output Binding to Input only Binding: https://github.com/dapr/docs/pull/2971

**Comment by DeepanshuA** [comment]
> Docs PR for change from Input/Output Binding to Input only Binding: [dapr/docs#2971](https://github.com/dapr/docs/pull/2971)

**Comment by berndverst** [comment]
This issue would have auto-closed if PR 2191 had not said "see 2056" but instead "fixes 2056" or "closes 2056".
