### ISSUE TITLE
Azure configstore component cannot get a key using connection string

### ISSUE THREAD

**Issue by maXA1m** [dapr/components-contrib#2062]
## Expected Behavior

Should work without errors, authorize, and get requested key.

## Actual Behavior

Fails with internal exception:

Status(StatusCode="Internal", Detail="fail to get [KEYNAME] from Configuration store service-configstore: GET <https://cfgstore.azconfig.io/kv/KEYNAME>

RESPONSE 401: 401 Unauthorized
ERROR CODE UNAVAILABLE

Response contained no body

## Steps to Reproduce the Problem

1. Setup configstore yaml file and set valid connection string to appConfigConnectionString setting.
2. Try to access configuration using AddDaprConfigurationStore extension method from .NET SDK, specify List that contains key name to "keys" parameter.
3. An exception will be thrown.

You can find MS documentation link below and check how to authorize properly, or ensure you are using Azure Go lang libs in the right way:
https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-key-value

## Release Note

RELEASE NOTE:

**Comment by maXA1m** [comment]
Component metadata file:
`apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: service-configstore
  namespace: service
spec:
  type: configuration.azure.appconfig
  version: v1
  metadata:
  # WARN: can't set both appConfigHost and appConfigConnectionString fields in metadata
  #- name: appConfigHost
  #  value: https://cfgstore.azconfig.io
  - name: appConfigConnectionString
    value: "Endpoint=https://cfgstore.azconfig.io;Id=someid;Secret=secret"
  # - name: maxRetries
  #   value: <int>
  # - name: maxRetryDelay
  #   value: <int>
  # - name: retryDelay
  #   value: <int>`

**Comment by cmendible** [comment]
This one is caused by this filter:

https://github.com/dapr/components-contrib/blob/2b5650c2faa41f0a8d82862583497103776be49f/configuration/azure/appconfig/appconfig.go#L176

Current implementation only returns values for keys with label == `*`

**Comment by maXA1m** [comment]
Do you plan to extend it with ability to pass label as `IReadOnlyDictionary<string, string>? metadata`?

**Comment by shubham1172** [comment]
@berndverst this seems to be the PR https://github.com/dapr/components-contrib/pull/2064, can you please assign the issue to cmendible?
