### ISSUE TITLE
Add support for operations like "DELETE" and "GET" for Redis output binding

### ISSUE THREAD

**Issue by yash-nisar** [dapr/components-contrib#2068]
## Describe the feature

Currently, Redis only supports the [`CREATE` operation](https://github.com/dapr/components-contrib/blob/master/bindings/redis/redis.go#L75). We can perhaps add the following additional operations for Output Bindings as well:

`DELETE` operation: https://redis.io/commands/del/
`GET` operation: https://redis.io/commands/get/

Following this, the certification tests and docs should be updated as well.

## Release Note

RELEASE NOTE: **ADD** New feature in Dapr.

**Comment by wxbty** [comment]
#2094 did this, maybe it should be separated from the rocketmq issue
