### ISSUE TITLE
Tracing Exporter: Azure Monitor/AppInsights

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/components-contrib#207]
## Describe the proposal

The current proposal of integrating Dapr tracing with Azure Monitor
- is no an easy task, with a lot of manual work and [without any official guidance](https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/azure-monitor.md#setup-the-local-forwarder)
- is based on [Local Forwarder](https://github.com/microsoft/ApplicationInsights-LocalForwarder) which is ["not supported and the repo is being archived"](https://github.com/microsoft/ApplicationInsights-LocalForwarder/issues/37#issuecomment-528697085)

Would be great to have a native tracing exporter for Azure Monitor the same way as it exists for Zipkin.

**Comment by youngbupark** [comment]
Linking to https://github.com/dapr/dapr/issues/1080

- Dapr Observability work items : https://github.com/dapr/dapr/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fobservability

**Comment by youngbupark** [comment]
Cross link : https://github.com/dapr/dapr/issues/1050

**Comment by youngbupark** [comment]
Moving this to 0.6.0 release

**Comment by youngbupark** [comment]
@RicardoNiepel  We found some issues to use opentelemetry-agent. Meanwhile, I pushed localforwarder image to docker hub and improved the docs - https://github.com/dapr/docs/pull/440 (still in review)

The instruction will be more descriptive.

**Comment by youngbupark** [comment]
@RicardoNiepel  Please review [this doc](https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/azure-monitor.md).

To simplify the onboarding process, 
1) Push dapr-localforwarder image to daprio docker image
2) Make [doc](https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/azure-monitor.md) more descriptive.
3) We are tracking [the separated issue](https://github.com/dapr/docs/issues/384) to switch local forwarder to opentelemetry collector

cc/ @artursouza
