### ISSUE TITLE
Unable to access azure key vault with managed identity using Dapr

### ISSUE THREAD

**Issue by nelson-b** [dapr/components-contrib#2079]
**Prerequisite completed:**

1. Installed dapr engine in local machine(docker desktop)
2. Able to install dapr binaries.
3. Able to run the dapr engine.
4. Added spec type: secretstores.azure.keyvault yaml configuration to connect the azure key vault.
5. Able to run and view dapr dashboard.

**YAML file:**

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "kv-tchstn-dev-uks"

Challenges 
-	Getting unauthorized error while trying to access azure key vault by using dapr(dapr api used: http://localhost:3500/v1.0/secrets/kv-tchstn-dev-uks/appcs-id-Primary)

**Comment by berndverst** [comment]
Managed identity is only available if running Dapr in services with managed identity support. This is something that you must enable explicitly. You also need to give your managed identity the appropriate Azure Key Vault Secrets Reader role for the correct scope.
