### ISSUE TITLE
[Azure Event Hub] Cloud Events not available from PubSubs such as Azure Event Hubs

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/components-contrib#2095]
## Expected Behavior

Cloud Event Properties are not being passed from the PubSub. I expect that when I have an item on Azure Event Hub in Cloud Events spec (e.g. by creating an Azure Digital Twin to Event Hub endpoint that publishes in that format - https://learn.microsoft.com/en-us/azure/digital-twins/concepts-event-notifications#digital-twin-change-notifications) that I can receive the Cloud Events properties in Dapr its PubSub processing.

Below an example of such an Event Hub can be found when debugging it Event Hub -> Logic Apps 

```json
{
  "ContentData": "eyAiaGVsbG8iOiAid29ybGQiIH0=",
  "Properties": {
    "cloudEvents:id": "4a1d713c-76b3-494f-aaaa-eb125d741945",
    "cloudEvents:source": "adt6864821e.api.weu.digitaltwins.azure.net",
    "cloudEvents:specversion": "1.0",
    "cloudEvents:type": "Microsoft.DigitalTwins.Twin.Update",
    "cloudEvents:time": "2022-09-19T15:36:54.8479470Z",
    "cloudEvents:subject": "my-subject-id",
    "cloudEvents:traceparent": "00-46ce8eb246bd27f4addfb96b5e8fd6a9-f478498c016a1670-01",
    "CorrelationId": "16e09088-497e-4370-b3f5-1cf77d463b21",
    "ContentType": "application/json",
    "x-opt-sequence-number": 3,
    "x-opt-offset": "4688",
    "x-opt-enqueued-time": "2022-09-19T15:36:55.042Z"
  },
  "SystemProperties": {
    "EnqueuedTimeUtc": "2022-09-19T15:36:55.042Z",
    "Offset": "4688",
    "PartitionKey": null,
    "SequenceNumber": 3
  }
}
```

## Actual Behavior

The `Properties` objecties is not being passed and `cloudEvents:*` are missing. This might be related to #755

## Steps to Reproduce the Problem

1. Set up Azure Digital Twins to Event Hub
2. Monitor events from the Event Hub through a Dapr SDK
3. See missing cloudEvent properties

## Release Note

RELEASE NOTE: **FIX** Azure Event Hub cloudEvent Properties parsing

**Comment by mukundansundar** [comment]
Related to https://github.com/dapr/dapr/issues/3642

**Comment by XavierGeerinck** [comment]
Thanks! Closing in favor of that one
