### ISSUE TITLE
Azure EventHubs Binding checkpointing & KEDA usage

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/components-contrib#210]
## Describe the proposal

As I can see the Azure EventHubs Binding is currently not doing any checkpointing of the messages received, is this correct?

> https://github.com/Azure/azure-event-hubs-go#event-processor-host

Should this be part of the binding to make sure to not losse any messages?

In addition, KEDA only supports Azure Event Hub scaler based on checkpoints from Azure Blob Storage. It uses this information for calculating the diff and decidinign for scaling Up/down.

> https://keda.sh/scalers/azure-event-hub/

This should be another reason for adding checkpointing to the Azure EventHubs Binding.

**Comment by yaron2** [comment]
Hey @RicardoNiepel, this is already tracked here: https://github.com/dapr/components-contrib/issues/154

Looks like a good candidate for 0.5

**Comment by RicardoNiepel** [comment]
Perfect - it should be tested afterwards if the KEDA Event Hub scaler can handle the written checkpoint file from Golang.
Inside the documentation it currently says
> "scaling only Event Hub applications written in C#, Java, Python or created with Azure Function"
> https://keda.sh/scalers/azure-event-hub/

If not, a custom ```CheckpointPersister``` will be needed, otherwise it doesn't make sence to use Event Hub binding in Dapr, if it is not scalable.

**Comment by yaron2** [comment]
> Perfect - it should be tested afterwards if the KEDA Event Hub scaler can handle the written checkpoint file from Golang.
> Inside the documentation it currently says
> 
> > "scaling only Event Hub applications written in C#, Java, Python or created with Azure Function"
> > https://keda.sh/scalers/azure-event-hub/
> 
> If not, a custom `CheckpointPersister` will be needed, otherwise it doesn't make sence to use Event Hub binding in Dapr, if it is not scalable.

KEDA is not the only way to scale event hub consumers. Also, the Prometheus KEDA scaler can be used for this.

**Comment by yaron2** [comment]
Specifically, according to the EH scaler docs, matters are even worse: you can only scale an Azure Function with it.

**Comment by RicardoNiepel** [comment]
I have taken a look into the source code - the language doesn't matter - it just important that the checkpoint files are in a specific format in an Azure storage account - and the EventHostProcessors from C#, Java, Python and Azure Function in general are following these.

I can test in the next weeks.

Regarding autoscaler possibilties: I was just mentioning KEDA because it's mentioned inside the Dapr documentation.

**Comment by yaron2** [comment]
Can you check for the Event Hubs Go SDK?

**Comment by RicardoNiepel** [comment]
This is exactly what I will do, using the Go EventProcessorHost

**Comment by RicardoNiepel** [comment]
#253 enabled to test this.

If successful I will add an Event Hub section to [Autoscaling a Dapr app with KEDA](https://github.com/dapr/docs/tree/master/howto/autoscale-with-keda).

**Comment by msfussell** [comment]
@RicardoNiepel - Can this issue now be closed  and can you also update the Event Hub section to Autoscaling a Dapr app with KEDA documentation?
