### ISSUE TITLE
EventHubs components to use Azure SDK for Go ("Track 2 SDK")

### ISSUE THREAD

**Issue by berndverst** [dapr/components-contrib#2101]
The EventHubs components should be refactored to use the Azure SDK for Go (Track 2 SDK)

https://github.com/Azure/azure-sdk-for-go/tree/sdk/messaging/azeventhubs/v0.2.0

(Check for a newer version when working on this issue)

As part of this issue support for AAD auth should be added - see #1103.

**Comment by berndverst** [comment]
Consider adding https://github.com/dapr/components-contrib/issues/2176 (Websocket connection support) with the new SDK.

**Comment by berndverst** [comment]
Ping @ItalyPaleAle  :)

**Comment by ItalyPaleAle** [comment]
It's on my TODO for next week!
