### ISSUE TITLE
Conformance tests to include scenarios for pagination in Query API

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#2128]
## Describe the proposal

Current conformance tests could not catch a regression in cosmosdb state store but E2E tests did. The pagination scenarios covered in E2E tests are not covered in conformance tests.

Fix for regression: https://github.com/dapr/components-contrib/pull/2127
E2E test failing due to this regression: https://github.com/dapr/dapr/actions/runs/3114077163/jobs/5049874057

<img width="542" alt="image" src="https://user-images.githubusercontent.com/130954/192052443-fa2d82e3-3cf7-4961-b470-77917a9b562a.png">

**Comment by berndverst** [comment]
I think we should table this and consider this for Document Store instead.
