### ISSUE TITLE
Support Redis with SSL, e.g. for Azure Managed Redis Cache

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/components-contrib#213]
## Describe the proposal

Currently Azure Managed Redis Cache is only supported, if ["SSL only" is deactivated](https://github.com/dapr/docs/blob/master/howto/setup-state-store/setup-redis.md#creating-an-azure-managed-redis-cache) and a non-SSL connection will be used.

Would be great if it is possible to use also a SSL connection.

**Comment by yaron2** [comment]
I just opened an issue to track it, but will close it in favor of this one. #214

**Comment by yaron2** [comment]
Today the Redis state store is using https://github.com/joomcode/redispipe which does not support TLS client options.

I propose to move to https://github.com/go-redis/redis/ which supports TLS client options.

**Comment by youngbupark** [comment]
@yaron2 shouldn't we ship this change in 0.4.0? 

cc/ @msfussell @artursouza

**Comment by yaron2** [comment]
> @yaron2 shouldn't we ship this change in 0.4.0?
> 
> cc/ @msfussell @artursouza

No, this can wait for 0.5/0.6.

**Comment by msfussell** [comment]
Yes, we can hold off on this for a while and review all the the asks for the next release.

**Comment by RicardoNiepel** [comment]
@pruthvidhodda are you already working on this? Can I help somehow?

**Comment by pruthvidhodda** [comment]
Already working on this, will reach out if I need help. Thanks for offering though.

**Comment by RicardoNiepel** [comment]
@pruthvidhodda @yaron2 Please reopen.

See below what is still open:
- [ ] Enable TLS at [Redis Binding Component](https://github.com/dapr/components-contrib/blob/master/bindings/redis/redis.go)
  - [ ] Document it [here](https://github.com/dapr/docs/blob/master/reference/specs/bindings/redis.md)
- [X] Enable TLS at [Redis State Store Component](https://github.com/dapr/components-contrib/blob/master/state/redis/redis.go)
  - [ ] Document it [here](https://github.com/dapr/docs/blob/master/howto/setup-state-store/setup-redis.md#configuration)
- [X] Enable TLS at [Redis PubSub Component](https://github.com/dapr/components-contrib/blob/master/pubsub/redis/redis.go)
  - [ ] Document it [here](https://github.com/dapr/docs/blob/master/howto/setup-pub-sub-message-broker/setup-redis.md#configuration)

**Comment by youngbupark** [comment]
@yaron2 @amanbha We may not have a time to complete `Enable TLS at Redis Binding Component` in this milestone. If this is urgent, then we can release another minor version. otherwise, we should postpone it to 0.7.0

cc/ @shalabhms @pruthvidhodda

**Comment by amanbha** [comment]
@RicardoNiepel  We will open a new issue for Redis binding. When the issue was open, it wasn't clear on where the changes are needed, May be I am missing something, but I did not see the checklist you pasted above in the issue earlier.
Support for Redis binding will be added in next release.

**Comment by amanbha** [comment]
I have created https://github.com/dapr/cli/issues/305 to track binding changes.
