### ISSUE TITLE
Binding SOAP

### ISSUE THREAD

**Issue by BartNetJS** [dapr/components-contrib#2131]
I don't see a binding for SOAP.
What is the best approach?

Contributing a SOAP binding? 
But my team doesn't have a Go developer and the SOAP experience is from a few years ago.
So writing a SOAP binding seems tricky.

Or writing a proxy to translate SOAP into REST and vice versa?
[Core WCF](https://github.com/CoreWCF/CoreWCF) seems the way to go.

Any suggestion, blogs, tips are welcome

**Comment by berndverst** [comment]
Two options:

1) Contributing a new SOAP binding (output binding). This must be written in Go.
It seems this is a promising Go library that could be used as a foundation: https://github.com/tiaguinho/gosoap

2) "Pluggable Components" which are Dapr components that live outside of the Dapr runtime binary and communicate with the Runtime. This allows writing of Dapr components in a variety of languages, including Dot Net.
The Dot Net SDK isn't complete yet but you can see the work in progress here: https://github.com/dapr-sandbox/components-dotnet-sdk/tree/genesis

One advantage of creating your own pluggable component is that you can modify the component independently of Dapr runtime releases, so you can use the component much sooner.

Please see the upcoming Dapr 1.9.0 release notes for more details on pluggable components. There will also be a blogpost following with details on this.
