### ISSUE TITLE
Upgrade devcontainer to Go's version to 1.19

### ISSUE THREAD

**Issue by tmacam** [dapr/components-contrib#2142]
## Expected Behavior

Opening a CodeSpace of a container in VS Code as defined by [component-contrib devcontainer](https://github.com/dapr/components-contrib/blob/da366088e4eb244894807ad2dc1bde9fc92c35a6/.devcontainer/devcontainer.json) should provide an environment using Go (and all its dependencies) version 1.19, as this is the version targeted for the upcoming Dapr 1.9 release.

## Actual Behavior

The image currently in use by components-contrib is `ghcr.io/dapr/dapr-dev:0.1.8`, which is tracking Dapr 1.8 and Go 1.18. But [component-contrib] approval workflows are already using/requiring Go 1.19 (running `go mod tidy -compat=1.19` etc)

## Steps to Reproduce the Problem

1. Open a Codespace with the current HEAD of [components-contrib]
2. Run `go mod tidy -compat=1.19`
3. See the above command fail complaining it can only mod tidy against 1.18

## Release Note

RELEASE NOTE: **UPDATE** devcontainer's Go version to 1.19.

[components-contrib]: https://github.com/dapr/components-contrib

**Comment by tmacam** [comment]
I agree that there is work on dapr/dapr to be done but creating a new image in dapr/dapr won't fix this issue here.

**Comment by berndverst** [comment]
All I'm saying is that we have done this several times before and it's just part of the release process to also bump the devcontainer images. The work to bump the Go version only needs to be done in dapr/dapr, and contrib gets it for free.

We can decide in the future whether we should bump the devcontainer mid release whenever we bump the Go version - that's perhaps the real question here!

For tracking purposes I do think this belongs in dapr/dapr but it doesn't matter.
