### ISSUE TITLE
[PubSub Jetstream]: New topics added to stream are not being subscribed to

### ISSUE THREAD

**Issue by NickLarsenNZ** [dapr/components-contrib#2145]
## Expected Behavior

Given a subscription on a topic which is not yet added to a stream, once a subject is added to a stream, the Jetstream component should start subscribing to messages.

## Actual Behavior

The component throws an error and never seems to try again, meaning the processes have to be restarted.

## Steps to Reproduce the Problem

1. Set the application to subscribe to the pubsub on a new topic (eg: `another.topic`) that is not yet part of the stream.
2. Start daprd:
   ```log
   time="2022-09-30T20:20:30.137617Z" level=error msg="error occurred while beginning pubsub for component failed to subscribe to topic another.topic: nats: no stream matches subject: %!s(MISSING)" app_id=job-scheduler instance=3508bbcf56b4 scope=dapr.runtime type=log ver=edge
   ```
4. Add the topic to the stream:
   ```sh
   nats str edit --subjects=$original_subs,another.topic
   ```
5. Notice no messages will be processed until after dapr (and the application) are restarted.

Now that I write this out, I wonder if this is actually controller by `daprd` itself?

## Release Note

RELEASE NOTE:

**Comment by Jarema** [comment]
This error comes from NATS Client that fails to create a consumer for the given stream matching stream by subject.

NATS supports your case, but instead one has to crate a consumer by binding to the stream name, not it's subject.
I will take a look if that can be easily fixed.

**Comment by Jarema** [comment]
One note: it will not work if you want to filter stream subject while subscribing (creating a consumer).
This will work only if you want to get all messages for a given stream.

**Comment by NickLarsenNZ** [comment]
> This error comes from NATS Client that fails to create a consumer for the given stream matching stream by subject.

@Jarema , yes. Shouldn't Dapr periodically try again?

I don't think a person should have to restart dapr (and in some cases they might not know to, for example, if a separate team is managing the NATS configuration - even if through gitops)

**Comment by Jarema** [comment]
@NickLarsenNZ 

Having a stream `data`
with filter subjects (topics) `objects`

and a subscription (consumer) to a stream having `events` subject(topic) is an error and missconfig. Keep in mind that NATS Consumer is actually a server side state to which user/library hooks up.

adding a subscription (consumer) to a stream `events` without specyfing not yet added subject filter should work. It will start receiving messages immediately after the stream is edited and the first messages appear. Dapr does not have to do anything here.

The above cases should be possible to do in Dapr and will be when #2161 is implemented.

In case of config happening elsewhere:
Im part of the NATS team, not the Dapr team, so I can't speak for them, but I would expect that calling Subscription to not existing stream/stream without that subject should return the error and let the user decide if he/she/she wants to retry.

Disclaimer: I'm just getting accustomed myself to the Dapr API, so I might be wrong 🙂

**Comment by NickLarsenNZ** [comment]
Ah OK, I think I understand. So what Dapr would still call a Topic to subscribe to will really be a stream in NATS.

I'll take a look at that issue, as I'd like to understand if the stream has to map to a single subject, or if Dapr can handle it covering many subjects.

Thanks for your reply @Jarema
