### ISSUE TITLE
Redis Config Store: Can Not fetch configurations from HashSets

### ISSUE THREAD

**Issue by DeepanshuA** [dapr/components-contrib#2156]
## Describe the feature

If I have multiple microservices, for which I want to store configurations in redis as config store, then I may want to use different hashsets for different microservices / different use cases.
That means that I should be able to fetch key-values from a particular hashset / all hashsets.
But, currently it doesn't seem to be possible in case of redis as configuration store, which doesn't seem to cater to hashsets as of now.

## Release Note

RELEASE NOTE:

**Comment by pravinpushkar** [comment]
@DeepanshuA It seems related to this - https://github.com/dapr/components-contrib/issues/2000 ?

**Comment by DeepanshuA** [comment]
> @DeepanshuA It seems related to this - #2000 ?

yeah @pravinpushkar, As per comment https://github.com/dapr/components-contrib/issues/2000#issuecomment-1270134200, it seems that #2000 is also targeting same. If that is the understanding, I can close this issue. WDYT?

**Comment by pravinpushkar** [comment]
> > @DeepanshuA It seems related to this - #2000 ?
> 
> yeah @pravinpushkar, As per comment https://github.com/dapr/components-contrib/issues/2000#issuecomment-1270134200, it seems that #2000 is also targeting same. If that is the understanding, I can close this issue. WDYT?

Yeah.. I also think we can close this one.
