### ISSUE TITLE
Upgrade google secret manager client to latest

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/components-contrib#2166]
## Description

This issues is to upgrade google secret manager client to latest.

## Release Note

RELEASE NOTE: **UPDATE**  Upgrade google secret manager go client to use 1.7.0 or latest

**Comment by berndverst** [comment]
You do not need to create an issue if you plan to immediately submit a PR for the same issue. Especially for dependency upgrades there is little point in opening a dedicated issue.

**Comment by pravinpushkar** [comment]
Closing this as deps got upgraded by another PR.

**Comment by berndverst** [comment]
Yup - I updated all packages in contrib.
