### ISSUE TITLE
Pub Sub Polling interval for Kafka

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/components-contrib#2173]
The subscriber polls to get the messages from subscription topic in kafka. The interval at which request is made to get the new message is not configurable as of now. Making this parameter configurable will help in tuning the  application for performance needs.

@pravinpushkar

**Comment by yaron2** [comment]
Moving to correct repo.

**Comment by ctoomey** [comment]
There's a huge number of configuration settings for kafka [consumers](https://kafka.apache.org/documentation/#consumerconfigs) and [producers](https://kafka.apache.org/documentation/#producerconfigs). E.g. a couple more that we use are `partition.assignment.strategy` and `client.dns.lookup`.

Ideally all these settings should be configurable, instead of just a very limited fixed subset of them.

**Comment by rabollin** [comment]
Currently Pub-sub configurations are handled by sarama library[https://pkg.go.dev/github.com/shopify/sarama] and there is not much scope for the App developers to edit the configurations. I think extending the implementation to allow configuration edits may help.

**Comment by berndverst** [comment]
> Currently Pub-sub configurations are handled by sarama library - https://pkg.go.dev/github.com/shopify/sarama and there is not much scope for the App developers to edit the configurations. I think extending the implementation to allow configuration edits may help.

Allowing all configuration options becomes impossible to maintain and test for. We will want to add the minimum necessary options users actually need.

Dapr isn't intended to be a passthrough client that allows configuring every single setting.

**Comment by ctoomey** [comment]
It'd be REALLY hard to decide which subset of config. settings should be supported and which should not, as they all are important in different situations. If the goal is to support developers moving from kafka-specific clients that support all config. settings (which it should be), I'd suggest allowing and passing through all config. settings. Suggest having them in a separate section in the config. file vs. having them mixed in with the dapr config. settings.

**Comment by berndverst** [comment]
If there is a way to pass through the settings the best we can probably do is providing a single metadata field which would be a comma separated list of key value pairs. And you'd have to refer to the Sarama library to get a list of supported settings. We will not separately document the supported options, but we can probably link to it from the docs.

Still I do not know whether this is possible.

By the way, as a maintainer of the components I do not think that the goal is for those to replace the use of native clients for advanced use cases / configuration scenario. Dapr is an abstraction and you always lose some ability to customize things with each abstraction.

**Comment by rabollin** [comment]
/ keep-alive

**Comment by rabollin** [comment]
/ keep-alive

**Comment by rahulp4** [comment]
We need to have provision to tune the kafka parameters. There are many configurable options provided by sarama library, but only few options are available via dapr. Kafka is critical piece in our architecture and based on the load, message size we will need to tune these params as per needs. Hence requesting to provide configurable parameters to subscribers/publishers. While the dapr can continue to keep the defaults as it is today, however consumers should be able to override them.

Below is params from library which can be made configurable

c.Producer.MaxMessageBytes = 1000000
c.Producer.Timeout = 10 * time.Second
c.Producer.Partitioner = NewHashPartitioner
c.Producer.Retry.Max = 3
c.Producer.Retry.Backoff = 100 * time.Millisecond
c.Producer.Return.Errors = true
c.Producer.CompressionLevel = CompressionLevelDefault
c.Producer.Transaction.Timeout = 1 * time.Minute
c.Producer.Transaction.Retry.Max = 50
c.Producer.Transaction.Retry.Backoff = 100 * time.Millisecond

 
c.Consumer.Fetch.Min = 1
c.Consumer.Fetch.Default = 1024 * 1024
c.Consumer.Retry.Backoff = 2 * time.Second
c.Consumer.MaxWaitTime = 500 * time.Millisecond
c.Consumer.MaxProcessingTime = 100 * time.Millisecond
c.Consumer.Return.Errors = false
c.Consumer.Offsets.AutoCommit.Enable = true
c.Consumer.Offsets.AutoCommit.Interval = 1 * time.Second
c.Consumer.Offsets.Initial = OffsetNewest
c.Consumer.Offsets.Retry.Max = 3

 

c.Consumer.Group.Session.Timeout = 10 * time.Second
c.Consumer.Group.Heartbeat.Interval = 3 * time.Second
c.Consumer.Group.Rebalance.GroupStrategies = []BalanceStrategy{BalanceStrategyRange}
c.Consumer.Group.Rebalance.Timeout = 60 * time.Second
c.Consumer.Group.Rebalance.Retry.Max = 4
c.Consumer.Group.Rebalance.Retry.Backoff = 2 * time.Second
c.Consumer.Group.ResetInvalidOffsets = true
c.ChannelBufferSize = 256

**Comment by rahulpoddar-fyndna** [comment]
We need to have provision to tune the kafka parameters. There are many configurable options provided by sarama library, but only few options are available via dapr. Kafka is critical piece in our architecture and based on the load, message size we will need to tune these params as per needs. Hence requesting to provide configurable parameters to subscribers/publishers. While the dapr can continue to keep the defaults as it is today, however consumers should be able to override them.

Below is params from library which can be made configurable

c.Producer.MaxMessageBytes = 1000000
c.Producer.Timeout = 10 * time.Second
c.Producer.Partitioner = NewHashPartitioner
c.Producer.Retry.Max = 3
c.Producer.Retry.Backoff = 100 * time.Millisecond
c.Producer.Return.Errors = true
c.Producer.CompressionLevel = CompressionLevelDefault
c.Producer.Transaction.Timeout = 1 * time.Minute
c.Producer.Transaction.Retry.Max = 50
c.Producer.Transaction.Retry.Backoff = 100 * time.Millisecond
c.Consumer.Fetch.Min = 1

c.Consumer.Fetch.Default = 1024 * 1024
c.Consumer.Retry.Backoff = 2 * time.Second
c.Consumer.MaxWaitTime = 500 * time.Millisecond
c.Consumer.MaxProcessingTime = 100 * time.Millisecond
c.Consumer.Return.Errors = false
c.Consumer.Offsets.AutoCommit.Enable = true
c.Consumer.Offsets.AutoCommit.Interval = 1 * time.Second
c.Consumer.Offsets.Initial = OffsetNewest
c.Consumer.Offsets.Retry.Max = 3
c.Consumer.Group.Session.Timeout = 10 * time.Second
c.Consumer.Group.Heartbeat.Interval = 3 * time.Second
c.Consumer.Group.Rebalance.GroupStrategies = []BalanceStrategy{BalanceStrategyRange}
c.Consumer.Group.Rebalance.Timeout = 60 * time.Second
c.Consumer.Group.Rebalance.Retry.Max = 4
c.Consumer.Group.Rebalance.Retry.Backoff = 2 * time.Second
c.Consumer.Group.ResetInvalidOffsets = true
c.ChannelBufferSize = 256
