### ISSUE TITLE
Query empty label on Azure App Configuration component

### ISSUE THREAD

**Issue by adiazcan** [dapr/components-contrib#2199]
## Expected Behavior

We want to load configuration from Azure App Configuration from differents labels using the metadata param for filtering. The requirement is to load all key-values without label or label = null and all key-values from an expecific label, for example 'PRO'. 

## Actual Behavior

Different unexpected behavior:

- When label filter is equal to "%00", we did'nt recieve any kv. 
- When label filter is equal to "%00,PRO", we recieved the kv from PRO but not for empty label. 
- When label filter is equal to "*,PRO", we recieved a bad request "Invalid request parameter 'label'" when the application run

According from the [Azure App Configuration Rest API](https://learn.microsoft.com/en-us/azure/azure-app-configuration/rest-api-key-value#supported-filters) documentation: 

- label is omitted or label=* --> Matches any label 
- label=%00 --> Matches KV without label

## Steps to Reproduce the Problem

`
    var config = await daprClient.GetConfiguration("configstore", 
        new List<string>() { }, 
        new Dictionary<string, string>() { { "label", "*,INT" } }
    );
`
`
    var config = await daprClient.GetConfiguration("configstore", 
        new List<string>() { }, 
        new Dictionary<string, string>() { { "label", "%00,INT"} }
    );
`

**Sample data from Azure App Configuration**
![image](https://user-images.githubusercontent.com/6652046/196510819-7274be24-7beb-4451-b128-0fdf2e32aa77.png)

**Comment by cmendible** [comment]
@adiazcan can you please run the following curl commands and check if you get the expected results?

``` bash
curl -v -G -d 'metadata.label=%00' http://localhost:<dapr http port>/v1.0-alpha1/configuration/azconfig
curl -v -G -d 'metadata.label=%00,PRO' http://localhost:<dapr http port>/v1.0-alpha1/configuration/azconfig
```

For the last use case I think the bad request comes from the fact that the `*` matches any label and therefore there is no need to also set the PRO label.

**Comment by adiazcan** [comment]
@cmendible yes, querying the component like this I get the expected results.

so now, maybe the problem is at the c# sdk?

**Comment by adiazcan** [comment]
@cmendible yes, querying the component like this I get the expected results.

and now, maybe the problem is on the c# sdk?

**Comment by cmendible** [comment]
@adiazcan please try the following to match KV without label and KV with the INT label :

```` csharp
var config = await daprClient.GetConfiguration("configstore", new List<string>() { }, new Dictionary<string, string>() { { "label", "\u0000,INT"} } );
```
