### ISSUE TITLE
[PubSub Jetstream] Support deduplication

### ISSUE THREAD

**Issue by NickLarsenNZ** [dapr/components-contrib#2200]
## Describe the feature

This follows on from a discussion that begins before my message on [discord].

Dapr Docs suggest that you get deduplication for free when using CloudEvents, or at least doesn't make it clear when that feature is available or not:

> Dapr uses CloudEvents to provide additional context to the event payload, enabling features like:
>
> - Tracing
> - **Deduplication by message Id**
> - Content-type for proper deserialization of event data
>
> _source: <https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-cloudevents/>_

Based on the NATS documentation, deduplication is based on a header called [`Nats-Msg-Id`]. I have searched the component code and don't see this being added (taking it from the CloudEvents [`id`] and [`source`]? fields).

https://github.com/dapr/components-contrib/blob/94f62c489ddb258169d6ddee15f3d9c0ab72707e/pubsub/jetstream/jetstream.go#L90-L95

It looks to me like we should be using the [`MsgId`] function (which is documented to be used for deduplication).

```go
 func (js *jetstreamPubSub) Publish(req *pubsub.PublishRequest) error {
	msgId := pubopt.MsgId("foo:6") // todo: replace with source and event ID.

 	js.l.Debugf("Publishing topic %v with data: %v and msgId: %v", req.Topic, req.Data, msgId)
 	_, err := js.jsc.Publish(req.Topic, req.Data, msgId) 
  
 	return err 
 } 
```

For completeness, an alternative way is to use the [`PublishMsg`] function with a [`Msg`] containing the [`Header`] instead?

## Release Note

RELEASE NOTE:

[`Nats-Msg-Id`]: https://docs.nats.io/using-nats/developer/develop_jetstream/model_deep_dive#message-deduplication
[`id`]: https://github.com/alanconway/cloudevents-spec/blob/master/spec.md#id
[`source`]: https://github.com/alanconway/cloudevents-spec/blob/master/spec.md#source
[discord]: https://discord.com/channels/778680217417809931/901141467840524289/1032252979681706114
[PubOpt]: https://pkg.go.dev/github.com/nats-io/nats.go#PubOpt
[`PublishMsg`]: https://pkg.go.dev/github.com/nats-io/nats.go#JetStream
[`Msg`]: https://pkg.go.dev/github.com/nats-io/nats.go#Msg
[`MsgId`]: https://pkg.go.dev/github.com/nats-io/nats.go#MsgId
[`Header`]: https://pkg.go.dev/github.com/nats-io/nats.go#Header

**Comment by NickLarsenNZ** [comment]
It looks like the event `source` might not be needed, and the event `id` should be unique enough.

Here is how the Azure EventHub Component does it:

https://github.com/dapr/components-contrib/blob/94f62c489ddb258169d6ddee15f3d9c0ab72707e/pubsub/azure/eventhubs/eventhubs.go#L123-L126

**Comment by NickLarsenNZ** [comment]
I can't see where the CloudEvent `id` would come from. Would dapr be putting in the `Metadata` field, or do we need to try an deserialize `Data` and extract the `id` contained?

https://github.com/dapr/components-contrib/blob/94f62c489ddb258169d6ddee15f3d9c0ab72707e/pubsub/requests.go#L16-L23

**Comment by NickLarsenNZ** [comment]
In any case, the metadata should probably also be getting converted to Headers, which necessitates using [`PublishMsg`](https://pkg.go.dev/github.com/nats-io/nats.go#JetStream).

I'll leave that out, and this comment can be converted to a new issue if it sounds appropriate.

**Comment by Jarema** [comment]
thanks @NickLarsenNZ for investigating!

I agree that metadata should be converted into headers.

That will not fix the deduplication, unless `Nats-Msg-Id` is one of them.

@berndverst is an assumption that 
```
// MessageIDMetadataKey defines the metadata key for the message id.
MessageIDMetadataKey = "MessageId" // read, write.
```
is a proper key to transform into NATS-specific header and should work for CloudEvents API?

**Comment by NickLarsenNZ** [comment]
@Jarema @berndverst, I notice that the `req.Metadata` map is empty when I log it out (in my local version):

```
DEBU[0009] Request Metadata: map[]                       app_id=nodeapp instance=pathogen scope=dapr.contrib type=log ver=edge
```

So I guess Dapr isn't putting anything in there by default.

`req.Data` has the `id` that we should be using here (after converting the decimal bytes to ASCII):

```json
{
   "data":{
      "hello":"world"
   },
   "datacontenttype":"application/json",
   "id":"92996fcb-6f8d-4b05-a0cc-57fb68515424",
   "pubsubname":"jetstream-test",
   "source":"nodeapp",
   "specversion":"1.0",
   "topic":"topic-a",
   "traceid":"00-0a9aadf0e9d947d04de044a301c28b4c-58d2ba7e9eee835d-00",
   "traceparent":"00-0a9aadf0e9d947d04de044a301c28b4c-58d2ba7e9eee835d-00",
   "tracestate":"",
   "type":"com.dapr.event.sent"
}
```

It appears the req.Metadata is just for the developer to add additional data to the payload: https://docs.dapr.io/reference/api/pubsub_api/#metadata.

So I think we must extract the ID from the `req.Data`.

**Comment by berndverst** [comment]
Yes `req.metadata` is a standard field of headers / grpc metadata. This is not what you should be using.

Unless you specify the raw event type explicitly Dapr publishes events as cloud events - the cloud event envelope is managed by Dapr, and Dapr generates the ID for the cloud event, unless you explicitly send a cloud event (with content type "application/cloudevents+json"). Whether you send pubsub data as cloud event or not, it will be stored as cloud event. And in either case you can still pass through your own tracing information.

As you discovered, everything you need should be in the `req.data` which represents a binary representation of the cloud event.

https://github.com/dapr/dapr/blob/032581dfd736b8927e8f8ebee360c9888dd9a80f/pkg/runtime/pubsub/cloudevents.go#L23-L41

https://github.com/dapr/components-contrib/blob/master/pubsub/envelope.go#L129
