### ISSUE TITLE
Dapr Bot Enhancements

### ISSUE THREAD

**Issue by shubham1172** [dapr/components-contrib#2209]
Dapr Bot should support the following actions. When an issue is labelled with:

1. `docs-needed`, create a new issue in Docs repo.
1. `new-component`, create 
    1. Dapr issue to register the component
    1. Docs issue for the component

Note, labels can be only added by approver/maintainer, so this does not require any authorization checks from our hard-coded list.

**Comment by mukundansundar** [comment]
I agree the creation of issues.
For registering the component I am thinking if we can automate PR creation. Only the creation ... it still will go through the normal review process.

**Comment by shubham1172** [comment]
🤖👋🏻
