### ISSUE TITLE
tests/certification: unit tests panic.

### ISSUE THREAD

**Issue by 1046102779** [dapr/components-contrib#2210]
> github.com/dapr/components-contrib/tests/certification/state/redis
> go test -v ./...

![image](https://user-images.githubusercontent.com/20457624/197207022-f57940c4-dfad-48a8-bd7d-1b23d6aaaf94.png)

Now `go-sdk` repo and `dapr` repo have two independent `pbs`: [dapr proto](https://github.com/dapr/dapr/tree/master/pkg/proto) and [go-sdk](https://github.com/dapr/go-sdk/tree/main/dapr/proto), of which the pb of `go-sdk` is copied from the `dapr` repo to reduce the dependence on the main dapr repo. But I found that this brought new problems.
   
In general, we do not refer to the two packages `dapr` and `go-sdk` at the same time, but I found this behavior in the `components-contrib` repo, which caused proto to be initialized when it was imported in runtime. Register twice resulted in panic.

Relate issue&PR:

https://github.com/dapr/dapr/pull/4923
https://github.com/dapr/dapr/issues/4920

Maybe we need init a new module in dapr repo, and named proto module :`github.com/dapr/dapr/proto` or `github.com/dapr/dapr/pkg/proto`.

@ItalyPaleAle @berndverst @yaron2 @daixiang0 .

**Comment by Taction** [comment]
+1. Encountered the same issue when adding certification tests. https://github.com/dapr/components-contrib/actions/runs/3302503973/jobs/5449407539

**Comment by 1046102779** [comment]
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```shell
Starting with v1.26.0 of the google.golang.org/protobuf module, a hard error will be reported when a Go program starts up that has multiple conflicting protobuf names linked into it. While it is preferable that the source of the conflict be fixed, the fatal error can be immediately worked around in one of two ways:

At compile time. The default behavior for handling conflicts can be specified at compile time with a linker-initialized variable: go build -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn"

At program execution. The behavior for handling conflicts when executing a particular Go binary can be set with an environment variable: GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn ./main
```

Although the panic caused by repeated registration can be prevented by setting the above parameter value, it is hoped that the `Dapr` standard api can be independent into a module. The smallest impact is the direct use of `dapr/dapr/pkg/proto` mentioned by @ItalyPaleAle [comment#1197414356](https://github.com/dapr/dapr/pull/4923#issuecomment-1197414356) before: `go mod init`

**Comment by daixiang0** [comment]
> https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
> 
> ```shell
> Starting with v1.26.0 of the google.golang.org/protobuf module, a hard error will be reported when a Go program starts up that has multiple conflicting protobuf names linked into it. While it is preferable that the source of the conflict be fixed, the fatal error can be immediately worked around in one of two ways:
> 
> At compile time. The default behavior for handling conflicts can be specified at compile time with a linker-initialized variable: go build -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn"
> 
> At program execution. The behavior for handling conflicts when executing a particular Go binary can be set with an environment variable: GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn ./main
> ```
> 
> Although the panic caused by repeated registration can be prevented by setting the above parameter value, it is hoped that the `Dapr` standard api can be independent into a module. The smallest impact is the direct use of `dapr/dapr/pkg/proto` mentioned by @ItalyPaleAle [comment#1197414356](https://github.com/dapr/dapr/pull/4923#issuecomment-1197414356) before: `go mod init`

It worth create an issue in dapr core repo since it impacts a lot.

**Comment by 1046102779** [comment]
> > https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
> > ```shell
> > Starting with v1.26.0 of the google.golang.org/protobuf module, a hard error will be reported when a Go program starts up that has multiple conflicting protobuf names linked into it. While it is preferable that the source of the conflict be fixed, the fatal error can be immediately worked around in one of two ways:
> > 
> > At compile time. The default behavior for handling conflicts can be specified at compile time with a linker-initialized variable: go build -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn"
> > 
> > At program execution. The behavior for handling conflicts when executing a particular Go binary can be set with an environment variable: GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn ./main
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Although the panic caused by repeated registration can be prevented by setting the above parameter value, it is hoped that the `Dapr` standard api can be independent into a module. The smallest impact is the direct use of `dapr/dapr/pkg/proto` mentioned by @ItalyPaleAle [comment#1197414356](https://github.com/dapr/dapr/pull/4923#issuecomment-1197414356) before: `go mod init`
> 
> It worth create an issue in dapr core repo since it impacts a lot.

OK, I organize the information, and then create an issue in the core repo `dapr/dapr`.

**Comment by berndverst** [comment]
This is unavoidable here because of decisions made in the go-sdk and dapr runtime.

I agree that an issue in dapr/dapr would be good.
