### ISSUE TITLE
PR 2113 removed code to pass kafka record headers to subscribers 

### ISSUE THREAD

**Issue by ctoomey** [dapr/components-contrib#2212]
## Expected Behavior

Kafka pubsub subscribers should be passed kafka record headers, in addition to the record value (payload) and topic name.

## Actual Behavior

In v1.9.0, the behavior is correct and the headers are passed. PR #2113 seems to have accidentally removed the code that passed the headers as you can see [this diff](https://github.com/dapr/components-contrib/commit/8500da577c0cbd14165d88b5ce8c8b290a28eaf4#diff-eb5563b3cfb22a216e7f790227dc667222a9988cedc45ec4608d8c1a79a55aaeL181).

## Steps to Reproduce the Problem

Using dapr 1.9.0, subscribe to a kafka topic  and in your callback handler, examine the HTTP request headers and notice they contain the kafka record headers. Using some dapr build post #2113 and notice the HTTP request headers no longer contain the kafka record headers.

## Release Note

RELEASE NOTE: **FIX** Restore passing of kafka record headers to kafka pubsub subscribers

**Comment by berndverst** [comment]
@DeepanshuA can you please look into this since the PR in question was your PR?

**Comment by ctoomey** [comment]
> @ctoomey so this is only broken in the master branch (nightly releases) correct? In the hotfix releases we wouldn't have included this commit.

@berndverst yes it's broken on the master branch, but I'm not able to comment on where else if any it might also be broken.

**Comment by berndverst** [comment]
I was just wondering whether you are running 1.9.3 by now. But if it worked in 1.9.0 it will be fine in 1.9.3.

**Comment by DeepanshuA** [comment]
> @DeepanshuA can you please look into this since the PR in question was your PR?

yeah, looking into it now

**Comment by DeepanshuA** [comment]
@ctoomey thanks for raising this and letting us know the issue that has occurred.

I have raised #2281 for this.

**Comment by ctoomey** [comment]
> @ctoomey thanks for raising this and letting us know the issue that has occurred.
> 
> I have raised #2281 for this.

Thanks @DeepanshuA

**Comment by yaron2** [comment]
Closed via https://github.com/dapr/components-contrib/pull/2281
