### ISSUE TITLE
Add bulk subscribe support to Azure Event Hubs

### ISSUE THREAD

**Issue by shubham1172** [dapr/components-contrib#2221]
## Describe the proposal

This issue is to add the bulk subscribe feature to Azure Event Hubs. See https://github.com/Azure/azure-sdk-for-go/issues/19276. This needs track 2 migration to be completed first.

Prerequisite: #2101 
Related to: dapr/dapr#2218

**Comment by shubham1172** [comment]
Can we please re-open this and pin the issue? /cc @mukundansundar

**Comment by oising** [comment]
Please reopen. Without "bulk" support for subscription (which would map to batchSize I guess on the underlying eventhubclient), this component will be a poor substitute for the EH input binding component. Also, there needs to be some intelligent derivation (or direct configurability) of the checkpointing frequency. Without control of both batching and checkpointing, this component will always be massively inferior to the binding, or the raw SDK itself, in terms of performance.

**Comment by rabollin** [comment]
@mukundansundar -Please tag this issue to 1.12

**Comment by mukundansundar** [comment]
@berndverst @ItalyPaleAle Please tag this to be in 1.12 ...
