### ISSUE TITLE
MQTT Missing Resubscribe on Reconnect

### ISSUE THREAD

**Issue by thielepaul** [dapr/components-contrib#2229]
## Expected Behavior

When I restart my mqtt-broker, the dapr sidecar should reconnect, resubscribe and the receive messsages again

## Actual Behavior

The sidecar does reconnect but not resubscribe

## Steps to Reproduce the Problem

* subscribe with dapr to mqtt broker
* restart mqtt broker

## Release Note

RELEASE NOTE:

## Possible Solution

As proposed in the upstream issue (https://github.com/eclipse/paho.mqtt.golang/issues/22), we could put the subscribe call in the `onConnect` handler this should fix the issue.

**Comment by thielepaul** [comment]
@ItalyPaleAle you helped me with mqtt issues before, it would be awesome if you can take a look into it :)

**Comment by thielepaul** [comment]
any news about this? For us this issue is unfortunately a blocker...

**Comment by ItalyPaleAle** [comment]
I think we can get this fixed in 1.10, coming out in January/February.

We may be able to get the fix pushed to master before EOM, if you want to use a nightly build (could be buggy)

**Comment by thielepaul** [comment]
awesome! thanks for your efforts towards improving mqtt support in dapr!

**Comment by berndverst** [comment]
We are making a lot of changes in nightly builds at the moment, so using those could certainly be risky. But the 1.10 release will be good.

**Comment by ItalyPaleAle** [comment]
#2350 should fix this
