### ISSUE TITLE
RabbitMQ PubSub: Wrong content-type handling

### ISSUE THREAD

**Issue by zivfuture** [dapr/components-contrib#2238]
I am trying to sent a event by pubsub component.  (mq is rabbitmq)
Event sent by this code(netcore SDK 1.9.0):
![image](https://user-images.githubusercontent.com/49356505/198822300-63c92b54-03f9-4f3b-9d04-a3cd4afb5d16.png)

and event sent successful with wrong content-type:
![image](https://user-images.githubusercontent.com/49356505/198822383-0b25ff9f-ef5d-49f7-a6da-904cac043f72.png)

The donet sdk will check the content-type to identify whether it is clould event:
![image](https://user-images.githubusercontent.com/49356505/198822580-38a95084-c516-44bf-ae94-d0661715e2a5.png)
![image](https://user-images.githubusercontent.com/49356505/198822600-f0d54d28-25ee-4749-8217-b29beb012551.png)

and  the dapr pubsub component was hard code content-type to "text/plain" :
https://github.com/dapr/components-contrib/blob/master/pubsub/rabbitmq/rabbitmq.go#L194

and the issue [879](https://github.com/dapr/components-contrib/issues/879) mentioned this

so  the subscribe end point alway throw this error:
bad news is subscribe  endpoint got an error:
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-bf24d29056b340a20f334166b88c8793-18596679de91203d-01",
    "errors": {
        "$": [
            "The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0."
        ],
        "client": [
            "The client field is required."
        ]
    }
}
```

**Comment by Taction** [comment]
@zivfuture Thanks for submitting this issue, can I know why you close this issue?
