### ISSUE TITLE
[Bindings] PostgreSQL bindings

### ISSUE THREAD

**Issue by youngbupark** [dapr/components-contrib#224]
## Describe the proposal

This is to create PostgreSQL input/output bindings

**Comment by msfussell** [comment]
@youngbupark - Is someone from Azure Global team working on this? If so, can you assign this issue to them?

**Comment by youngbupark** [comment]
> @youngbupark - Is someone from Azure Global team working on this? If so, can you assign this issue to them?

no this is not their scope. they are working only on state store. I think we can close it for now. Right now, no requests from the customers.
