### ISSUE TITLE
[StateStore] PostgreSQL statestore

### ISSUE THREAD

**Issue by youngbupark** [dapr/components-contrib#225]
## Describe the proposal

This is to create PostgreSQL statestore

**Comment by youngbupark** [comment]
@brooke-hamilton will work on this issue.

**Comment by youngbupark** [comment]
@brooke-hamilton Can you please update the progress?

**Comment by brooke-hamilton** [comment]
Thanks for checking - I'm ready to submit a PR for review and feedback.

Apart from submitting the review PR, remaining work includes implementing the TransactionalStore interface, consistency flags, benchmark tests, and likely some renaming of things internal to the package.

**Comment by yaron2** [comment]
> Thanks for checking - I'm ready to submit a PR for review and feedback.
> 
> Apart from submitting the review PR, remaining work includes implementing the TransactionalStore interface, consistency flags, benchmark tests, and likely some renaming of things internal to the package.

Thanks, submitting the PR as soon as possible would be great :)

**Comment by youngbupark** [comment]
@brooke-hamilton Thanks for the update. I moved this issue to 0.9.0 milestone. 

cc/ @yaron2 @amanbha @msfussell @orizohar

**Comment by orizohar** [comment]
@brooke-hamilton - Thanks for this contribution. On top of this PR, can you please add a PR for the docs repo that provides guidance on using this component here https://github.com/dapr/docs/tree/master/howto/setup-state-store ?
There is a template for these howtos you can find here https://github.com/dapr/docs/blob/master/contributing/howto-template.md

**Comment by orizohar** [comment]
@brooke-hamilton - are you opening a PR on the docs repo for the "how to" for this?
We'd really want to get this into 0.9 and code freeze is end of this week 7/10/2020

**Comment by brooke-hamilton** [comment]
> @brooke-hamilton - are you opening a PR on the docs repo for the "how to" for this?
> We'd really want to get this into 0.9 and code freeze is end of this week 7/10/2020

@orizohar, I will submit the PR today. Thanks for the pointer on the date.

**Comment by brooke-hamilton** [comment]
@orizohar, the PR for documentation is here: https://github.com/dapr/docs/pull/675
