### ISSUE TITLE
pubsub rabbitmq broker how to not bind multiple routingKey

### ISSUE THREAD

**Issue by CCC598** [dapr/components-contrib#2256]
My App /dapr/subscribe response

````json
[
  {
    "topic": "topics",
    "pubsubName": "pubsub-rabbitmq",
    "route": "PubSub/WeatherForecast",
    "metadata": {
      "routingKey": "DaprWebApp.WeatherForecast, DaprWebApp"
    }
  }
]
````

RabbitMQ Exchanges
![image](https://user-images.githubusercontent.com/38395086/199934831-8379a95a-317d-453d-96ad-cd3588974f2d.png)

But i want to use raw routing key `DaprWebApp.WeatherForecast, DaprWebApp` , how to do it, thanks :)

**Comment by saber-wang** [comment]
You cannot delete the bound 'key', but you can add a new key, that is``
Example: "routingKey": "DaprWebApp.WeatherForecast, DaprWebApp,"
Note the last comma

**Comment by Taction** [comment]
The comma is used as a separator in `routingKey` metadata, in this way multiple routing keys can be defined.  Can you remove the`,` from your routing key or look into if you can use this component without routing key.

Also, if needed we can add a `routingKeySeparator` metadata which defaults to the comma to let users define the separator for `routingKey`.
