### ISSUE TITLE
Optimize Bulk Publish API component response

### ISSUE THREAD

**Issue by shubham1172** [dapr/components-contrib#2260]
## Describe the feature

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/22132944/200475828-9bdbd4c5-a6db-465c-b4b9-73c1f1fe3b7e.png">

With issue https://github.com/dapr/dapr/issues/5368, the API response for bulk publish, (II), has been updated to only return failed entries from the bulk. 

This issue is to optimize the data contract between the component and the runtime, (I).

## Current

<table>
<tr>
<th>Broker to runtime</th>
<th>Runtime to public</th>
</tr>
<tr>
<td>
<pre lang="json">
{
  "statuses": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", "status": "SUCCESS"},
    {"entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002", "status": "SUCCESS"},
  ]
}
</pre>
</td>
<td>
204 no content
</td>
</tr>
<tr>
<td>
<pre lang="json">
{
  "statuses": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", "status": "FAIL", "error" : "some error"},
    {"entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002", "status": "SUCCESS"},
  ]
}
</pre>
</td>
<td>
500 internal server error:
<pre lang="json">
{
  "statuses": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", "status": "FAIL", "error" : "some error"},
  ]
}
</pre>
</td>
</tr>
<tr>
<td>
<pre lang="json">
{
  "statuses": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", "status": "FAIL", "error" : "some error"},
    {"entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002", "status": "FAIL", "error" : "some other error"},
  ]
}
</pre>
</td>
<td>
500 internal server error:
<pre lang="json">
{
  "statuses": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", "status": "FAIL", "error" : "some error"},
    {"entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002", "status": "FAIL", "error" : "some other error"},
  ]
}
</pre>
</td>
</tr>
</table>

## Proposed

<table>
<tr>
<th>Broker to runtime</th>
<th>Runtime to public</th>
</tr>
<tr>
<td>
<pre lang="json">
{}
</pre>
</td>
<td>
204 no content
</td>
</tr>
<tr>
<td>
<pre lang="json">
{
  "failedEntries": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", "error":"some error"},
  ]
}
</pre>
</td>
<td>
500 internal server error:
<pre lang="json">
{
  "statuses": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", "status":"FAIL", "error":"some error"},
  ]
}
</pre>
</td>
</tr>
<tr>
<td>
<pre lang="json">
{
  "failedEntries": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", "error" : "some error"},
    {"entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002", "error" : "some other error"},
  ]
}
</pre>
</td>
<td>
500 internal server error:
<pre lang="json">
{
  "statues": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", "status":"FAIL", "error" : "some error"},
    {"entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002", "status":"FAIL", "error" : "some other error"},
  ]
}
</pre>
</td>
</tr>
</table>

## Release Note

RELEASE NOTE: **UPDATE** Bulk publish API for components

**Comment by mukundansundar** [comment]
@shubham1172 I have changed the internal struct from component to runtime to have the list as `failedEntries` and remove the status filed completely. The `error` field should be there for sure.
cc @artursouza @yaron2

**Comment by mukundansundar** [comment]
agreed with the @dapr/maintainers-dapr that the API response to users from Dapr API will be converted to `failedEntries`. Will be making the change as part of this as well

**Comment by mukundansundar** [comment]
> had an offline discussion and agreed with the @yaron2 and @artursouza that the API response to users from Dapr API will be converted to `failedEntries`. Will be making the change as part of this as well

## New Proposed Output
ERR {"some error"} - Golang `error` type
<table>
<tr>
<th>Broker to runtime</th>
<th>Runtime to public</th>
</tr>
<tr>
<td>
<pre lang="json">
{}
</pre>
</td>
<td>
204 no content
</td>
</tr>
<tr>
<td>
<pre lang="json">
{
  "failedEntries": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", "error": ERR {"some error"} },
  ]
}
</pre>
</td>
<td>
500 internal server error:
<pre lang="json">
{
  "failedEntries": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002",  "error":"some error"},
  ]
}
</pre>
</td>
</tr>
<tr>
<td>
<pre lang="json">
{
  "failedEntries": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002", ERR {"some error"} },
    {"entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002", ERR {"error" : "some other error"}},
  ]
}
</pre>
</td>
<td>
500 internal server error:
<pre lang="json">
{
  "failedEntries": [
    {"entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002",  "error" : "some error"},
    {"entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002",  "error" : "some other error"},
  ]
}
</pre>
</td>
</tr>
</table>

cc @yaron2 @artursouza @dapr/maintainers-dapr
