### ISSUE TITLE
Pubsub with NATS leafnode subscription not working

### ISSUE THREAD

**Issue by j4nsp** [dapr/components-contrib#2265]
I have configured 2 NATS servers. One of them is configured as leafnode and connected to the other one.

I have created a stream on the leafnode that contains one subject
streamname: configuration
subjectname: mytenantid.configuration

I have implemented a REST endpoint that subscribes to this subject. This subscription is working as it should. When I puplish something to the subject, I receive it in the REST callback.

In the second scenario the subscription is not working.

In this scenario I have created the stream and subject on the main NATS instance
streamname: configuration
subjectname: mytenantid.configuration

on the leafnode I created a stream that is sourced from this stream in the main instance
~ # nats s add --source configuration
`? Stream Name configuration`
`? Storage file`
`? Replication 1`
`? Retention Policy Limits`
`? Discard Policy Old`
`? Stream Messages Limit -1`
`? Total Stream Size -1`
`? Message TTL -1`
`? Max Message Size -1`
`? Duplicate tracking time window 2m0s`
`? Allow message Roll-ups No`
`? Allow message deletion Yes`
`? Allow purging subjects or the entire stream Yes`
`? Adjust source "configuration" start Yes`
`? configuration Source Start Sequence 0`
`? configuration Source UTC Time Stamp (YYYY:MM:DD HH:MM:SS) `
`? configuration Source Filter source by subject mytenantid.configuration`
`? Import "configuration" from a different JetStream domain Yes`
`? configuration Source foreign JetStream domain name cloud`
`? configuration Source foreign JetStream domain delivery prefix`

now I can publish something to the subject in the main instance and will receive it in a subscriber on the leaf node. This works perfectly fine when I am using the nats cli. But when I try to subscribe with DAPR I receive the error:

error occurred while beginning pubsub for component failed to subscribe to topic mytenantid.configuration: nats: no stream matches subject: %!s(MISSING)"

With the nats cli I can see that the stream and the subject is available on the leaf node.

component yaml is attached

 
[pubsub.txt](https://github.com/dapr/components-contrib/files/9973116/pubsub.txt)

**Comment by berndverst** [comment]
@Jarema any chance you can get someone to take a look at this? :)

**Comment by Jarema** [comment]
Sure! Will take a look.

**Comment by Jarema** [comment]
@j4nsp I guess this is about publisher not publishing to proper domain (being `cloud`).

Will look into the code.

**Comment by yaron2** [comment]
Closed via https://github.com/dapr/components-contrib/pull/2400. Thanks @Jarema
