### ISSUE TITLE
Event-Hub input binding should propagate event meta-data

### ISSUE THREAD

**Issue by chleit** [dapr/components-contrib#227]
Currently the Event-Hub input binding only propagates the data payload of an event.
AFAIK I could see this is done in the following code-snippet:

```
                        handler(&bindings.ReadResponse{
				Data: event.Data,
			})
```

I would change this to propagate the full event including all SystemProperties like "iothub-connection-device-id".

**Comment by matthieuklotz** [comment]
Hi,
We have the same use case: we need to access to metadatas of event produced by IoT Devices. But currently it is not possible.
Is someone have some news about this issue?

Regards,

**Comment by CodeMonkeyLeet** [comment]
The IoTHub SystemProperties only got added to the Azure EventHubs golang SDK in [version 3.2.0](https://github.com/Azure/azure-event-hubs-go/commit/bc2987d6d5deed48b84abd63d3bb4ab4e315c3d5), but the Dapr EventHubs pubsub and binding components currently are on the deprecated v1.3.1, so minimally Dapr needs to:

1. update the version dependency to `github.com/Azure/azure-event-hubs-go/v3`
2. expose the SystemProperties in the bindings.ReadResponse to the caller.
