### ISSUE TITLE
AWS Component Testing Infrastructure

### ISSUE THREAD

**Issue by msfussell** [dapr/components-contrib#2282]
## AWS Infrastructure
AWS Infrastructure needs to be set up for stable certification for components

## Release Note
Using the AWS supplied infrastructure account, this ensuring that AWS components are tested on AWS infra.

**Comment by berndverst** [comment]
This is a prerequisite for the AWS component certification tests (and ideally conformance tests).

A service account equivalent will need to be created and the credentials must be added to the Dapr GitHub organization by the STC.

The same service account will need to be used to run all tests, so for any future tests new permissions must be granted to this service account.

It is important not to permanently provision resources or choosing the smallest tier possible to reduce cost.

Additionally, it may be advisable to keep configurations in a AWS secret store instead - similarly to the way we keep things in Azure KeyVault. It would be better if the AWS tests do not depend on any Azure infrastructure in any way shape or form.

**Comment by ItalyPaleAle** [comment]
> Additionally, it may be advisable to keep configurations in a AWS secret store instead - similarly to the way we keep things in Azure KeyVault. It would be better if the AWS tests do not depend on any Azure infrastructure in any way shape or form.

IMHO I think it may be useful to keep all secrets in the same place. Since they're opaque, it doesn't matter if they're stored in AWS or Azure Key Vault or somewhere else... Having less places where secrets are stored makes management and access control easier.

**Comment by berndverst** [comment]
From a maintainer perspective I would like to envision a future where the Azure, AWS and other infra pieces can be managed by distinct people with distinct sets of permissions.

I still am strongly in favor of *not* mixing AWS and Azure components in the same test Workflows and not sharing any infra between these.

**Comment by addjuarez** [comment]
General AWS conformance/certification workflow

1. Set aws github secrets AWS_SECRET_KEY, AWS_ACCESS_KEY as env variables.
2. Utilize **Terraform** to deploy and manage resources needed for tests for cloud service components. Terraform Templates should be added to the repo when conformance or certifications tests are added for cloud components.
3. After the service is deployed and ready, we run the tests. Component yamls will reference the env variables for the AWS credentials
4. Clean up resources using terraform

There are github actions plugins for terraform so the only code changes needed should be inside conformance/certification workflow yaml and terraform files will be needed for cloud service components. These workflow changes could also be easily updated to support azure and gcp.

https://www.terraform.io/
https://github.com/hashicorp/setup-terraform

**Comment by ItalyPaleAle** [comment]
> Terraform

Would it be possible to do an analysis to see if Pulumi could be a better option? Although Terraform is admittedly the most widely-adopted one, I think Pulumi could have some interesting properties for us:

- Its imperative approach (vs Terraform's declarative one) could make it easier to deploy infrastructure conditionally (if...else), without conflicts (e.g. adding name prefixes when needed).
- Pulumi is available as a library for many programming languages (including Go, as well as JS and Python if we need to use scripting languages) so it could be integrated directly in our test frameworks.

**Comment by robertojrojas** [comment]
> 3. After the service is deployed and ready, we run the tests. Component yamls will reference the env variables for the AWS credentials

@addjuarez I'd like to confirm the availability of the AWS Creds as part of the Certification Test execution. The components will not be using the **_`secretstores.local.env`_** to access credentials, but instead will assume that the AWS variables (**AWS_ACCESS_KEY_ID**, **AWS_SECRET_ACCESS_KEY**) are set appropriately as part of the execution of the tests, correct?

**Comment by addjuarez** [comment]
Yes the credentials will be set as env variables during the workflow execution

**Comment by msfussell** [comment]
Issue has been completed.
