### ISSUE TITLE
Two Way SSL configuration for HTTP Binding 

### ISSUE THREAD

**Issue by vikas2k14** [dapr/components-contrib#2284]
We are using dapr HTTP binding for all the external calls in our application. Our external application needs two-way SSL for communication in one of our use cases.

I wanted to check if it's supported right now and how to configure it.

cc : @rahulopengts @akhilac1 @mukundansundar @pravinpushkar

**Comment by rabollin** [comment]
@vikas2k14  - Would you please add few more details on why mTLS will not solve the problem of 2 way SSL.

**Comment by vikas2k14** [comment]
> @vikas2k14 - Would you please add more details on why mTLS will not solve the problem of 2 way SSL.

@rabollin as discussed offline, it is an HTTP binding call that will go outside the cluster (not service-to-service invocation ); hence, I don't think dapr mTLS will handle it.


Attaching a sample diagram for the same
![SSL drawio-2](https://user-images.githubusercontent.com/37506429/207555028-eb4ae944-0064-462f-b250-7352f2731e93.png)

**Comment by pravinpushkar** [comment]
I think we will have to provide 3 options to pass `ca certificate`, `client certificate` and `client key` to the tls config option.
We can pass these options as encoded strings in the component yaml files and read the it `http.go`. This way it will work both in self hosted as well as in k8s mode.

**Comment by ItalyPaleAle** [comment]
@pravinpushkar agree with your plan.

Please consider allowing the values of those metadata properties to be either:

- a local file: first, test if there's a file at the given location
- if there's no existing file, assume it's a PEM-encoded value directly

**Comment by pravinpushkar** [comment]
> @pravinpushkar agree with your plan.
> 
> Please consider allowing the values of those metadata properties to be either:
> 
> * a local file: first, test if there's a file at the given location
> * if there's no existing file, assume it's a PEM-encoded value directly

Sure.. sounds good!
