### ISSUE TITLE
pub-sub - Support for  MQTT5 specifications

### ISSUE THREAD

**Issue by rabollin** [dapr/components-contrib#2292]
Currently DAPR pub-sub supports MQTT3.1 specification only. MQTT5(https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html) out there for some time.  For most IoT use cases, the MQTT 5 specification has become the logical choice. MQTT5 has an additional features like support for shared subscriptions, session & message expiry ..etc.

Since MQTT5 does not support backward compatibility, DAPR can support both 3.1 & 5 as parallel implementations.

**Comment by berndverst** [comment]
Maybe this is a candidate for a `v2` of the component.

Alternatively you will likely need to create something similar to my Redis PR (work in progress: https://github.com/dapr/components-contrib/pull/2228) which would mean you create an interface for MQTT and then provide two different implementations for the different MQTT versions - the implementation can be triggered based on a metadata property (though in Redis we can actually automatically detect the correct version)

Whatever we do - for code maintenance we should stay away from lots of `if version=BLA` statements.
