### ISSUE TITLE
Redis pub/sub: delete entry on successful ACK

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#2296]
With Redis pub/sub, entries aren't automatically evicted from the server after an XACK command, which can lead to an ever-growing memory usage.

We should either perform XDEL on an entry after a successful XACK automatically or opt in for it with a metadata option like `deleteEntryAfterAck: true/false`.

**Comment by berndverst** [comment]
Whoever works on this: Please base your work on top of this PR: https://github.com/dapr/components-contrib/pull/2228

Do not merge your PR until 2228 is complete. Thanks!

**Comment by ItalyPaleAle** [comment]
What happens if Dapr crashes after the XACK but before the XDEL?
Should we do a periodic garbage collection instead? (or in addition?)

**Comment by SpikeWong** [comment]
I have a question, how to make sure this message has acked by all consumer groups?
I don’t know in current situation our redis pub sub component whether has multiple consumer groups. If does, should we use some extra efforts to make sure this message has also confirmed by other consumer groups before we delete it.  As I know, currently redis hasn’t provided an api to check the message consuming progress.    
https://github.com/redis/redis/issues/8392

**Comment by yaron2** [comment]
If the Redis entry isn't scoped to a consumer group then we can't use XDEL because there isn't a way to guarantee an ACK from all consumer groups.

**Comment by SpikeWong** [comment]
> If the Redis entry isn't scoped to a consumer group then we can't use XDEL because there isn't a way to guarantee an ACK from all consumer groups.

So what do you mean entry scoped to a consumer group? Is that mean this is only one consume group that will consume the entry/topic?
Is there any api/way to get this information?

**Comment by yaron2** [comment]
Closing as there isn't an API in Redis to support getting ack info for consumer groups.
