### ISSUE TITLE
Investigate Dapr bot failures on pull request labelling 

### ISSUE THREAD

**Issue by shubham1172** [dapr/components-contrib#2332]
## Expected Behavior

Dapr bot should work when PRs are labelled, same way as it works when issues are labelled.

## Actual Behavior

It throws an error with PR labeling. Examples:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/22132944/204711507-4ba28382-4f8e-4014-b686-e73645a91bc7.png">

https://github.com/dapr/components-contrib/actions/runs/3570292159/jobs/6001130766
https://github.com/dapr/components-contrib/actions/runs/3570222569/jobs/6000993804
https://github.com/dapr/components-contrib/actions/runs/3569661221/jobs/5999831951

## Steps to Reproduce the Problem

Add a label to a PR.

## Release Note

RELEASE NOTE: **FIX** Dapr bot authorization with PR labeling

**Comment by berndverst** [comment]
@shubham1172 can we remove the trigger from the PRs after all? This workflow doesn't have access to the necessary credentials.
