### ISSUE TITLE
Kafka PubSub and Binding certification tests are flaky

### ISSUE THREAD

**Issue by sarsharma** [dapr/components-contrib#2353]
The certification tests for both Kafka pubsub and binding are failing on most runs. 
Error from the logs:
```bash 
retry.go:33: Failure: kafka: client has run out of available brokers to talk to: 3 errors occurred:
        	* dial tcp [::1]:29092: connect: connection refused
        	* dial tcp [::1]:19092: connect: connection refused
        	* dial tcp [::1]:39092: connect: connection refused
````

Trying to run the tests locally, the 3 Kafka containers are dying just after startup
Error common between all 3 Kafka containers:
```bash 
Preparing truststore
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/zookeeper/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore is complete
Looking for the right CA
No CA found. Thus exiting.
```

Looks like it is having difficulty reading certificates from the mounted volume, and due to a race condition, the certification test passes on some occasions.

**Comment by mukundansundar** [comment]
@dapr/maintainers-components-contrib I think this issue needs to be re-opened
