### ISSUE TITLE
Feature request: Add etcd components (back)

### ISSUE THREAD

**Issue by mikoskinen** [dapr/components-contrib#2360]
## Describe the feature

etcd components were removed from Dapr a year or two ago. Could these be added back?

See: https://github.com/dapr/components-contrib/issues/818

**Comment by ItalyPaleAle** [comment]
Will be fixed by #2671

**Comment by berndverst** [comment]
@taenyang please comment on this documentation issue: https://github.com/dapr/docs/issues/3269

Leave a comment `/assign`
