### ISSUE TITLE
github.com/gorilla has been archived

### ISSUE THREAD

**Issue by robertojrojas** [dapr/components-contrib#2361]
The [Gorilla Web Toolkit](https://github.com/gorilla) has been **archived**. I think it'll be a good thing to look into how this will affect the various components with dependencies to it.

**Comment by berndverst** [comment]
```
go mod why github.com/gorilla/mux
# github.com/gorilla/mux
github.com/dapr/components-contrib/middleware/http/routeralias
github.com/gorilla/mux
```

It is only used in the HTTP middleware router.

The Go SDK also uses it -- and the Go SDK itself is used in various Certification tests.
