### ISSUE TITLE
multi environment on aws sqs/sns

### ISSUE THREAD

**Issue by Sbolder** [dapr/components-contrib#2364]
## In what area(s)?

> /area runtime

## What version of Dapr?

> Runtime version: 1.9.4

## Expected Behavior
In the same aws account i have created two different eks cluster for env (dev - preprod).
With correct naming convetion dapr on start-up create:
1 sqs with two subscriber
example
sqs: event-service
sns : rn:aws:sns:eu-central-1:<account-id>:preprodEvent
sns : rn:aws:sns:eu-central-1:<account-id>:devEvent
and create correct policy to permit at sqs to send message at the correct sns

polixy expected:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "sns.amazonaws.com"
      },
      "Action": "sqs:SendMessage",
      "Resource": "arn:aws:sqs:eu-central-1:397194520445:bnpl-contracts-engine-service",
      "Condition": {
        "ArnEquals": {
          "aws:SourceArn": "arn:aws:sns:eu-central-1:397194520445:devContractEntityChangedEvent"
        }
      }
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "sns.amazonaws.com"
      },
      "Action": "sqs:SendMessage",
      "Resource": "arn:aws:sqs:eu-central-1:397194520445:bnpl-contracts-engine-service",
      "Condition": {
        "ArnEquals": {
          "aws:SourceArn": "arn:aws:sns:eu-central-1:397194520445:uatContractEntityChangedEvent"
        }
      }
    }
  ]
}
```

## Actual Behavior

Dapr create all resource correclty but the second service (subscriber) change sqs policy and overwrite the existing policy.
Unfortunatly if i reboot all services, the second services win and work done, but the first loose thei subscription and dosn't work.

the second service that startup on daprd log:
```
time="2022-12-07T10:59:14.760932156Z" level=error msg="error setting sns-sqs subscription policy: error setting queue subscription policy: InvalidAttributeValue: Invalid value for the parameter Policy.\n\tstatus code: 400, request id: 2e698073-5ee2-51b7-9a8c-dc792aa0c78c" app_id=event-service instance=event-webapi-8598984688-lqdcs scope=dapr.contrib type=log ver=1.9.4
time="2022-12-07T10:59:14.760975927Z" level=error msg="error occurred while beginning pubsub for component failed to subscribe to topic devEvent: error setting sns-sqs subscription policy: error setting queue subscription policy: InvalidAttributeValue: Invalid value for the parameter Policy.\n\tstatus code: 400, request id: 2e698073-5ee2-51b7-9a8c-dc792aa0c78c: %!s(MISSING)" app_id=event-service instance=bnpl-contracts-engine-webapi-8598984688-lqdcs scope=dapr.runtime type=log ver=1.9.4
```

policy overwrited:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "sns.amazonaws.com"
      },
      "Action": "sqs:SendMessage",
      "Resource": "arn:aws:sqs:eu-central-1:<account-id>:event-service",
      "Condition": {
        "ArnEquals": {
          ""
        }
      }
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "sns.amazonaws.com"
      },
      "Action": "sqs:SendMessage",
      "Resource": "arn:aws:sqs:eu-central-1:<account-id>:event-service",
      "Condition": {
        "ArnEquals": {
          "aws:SourceArn": "arn:aws:sns:eu-central-1:397194520445:preprodEvent"
        }
      }
    }
  ]
}
```

## Steps to Reproduce the Problem

- Create two microservices (one send event and one subscribe)
- Create two different eks cluster
- deploy microservices in each cluster
- check sqs/sns policy 

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
I think this is working as intended.

Use `disableEntityManagement`.

For creating the resources I recommend using Terraform or something similar. The goal of Dapr isn't to manage resource creation in different environments.

Here is an example terraform script you can use for inspiration>

https://github.com/dapr/components-contrib/blob/master/.github/infrastructure/terraform/conformance/pubsub/aws/snssqs/snssqs.tf

**Comment by Sbolder** [comment]
@berndverst 

ok, i have used disableEntityManagement, i have just find the workaround and i have explained it in the first comment.

I think the same bug is present in the same env if you have a situation like this:

1 writer and 2 different service that read for the same sqs in the same eks.

second reader change policy and sometimes create a conflict on policy definition and dosn't work.

Anyway the workaround with disableEntityManagement, work done, but you have to create with cloudformation or manually sqs and sns with relative subscription and policy definition.

if you think this isn't a bug, please close it, for me is fine.
