### ISSUE TITLE
Retry option for Kafka Binding

### ISSUE THREAD

**Issue by rohitshrivastava04** [dapr/components-contrib#237]
## Describe the proposal
I would suggest to add retry feature such that one can configure a retry count and after those many retries message moves to a failed topic. 
It would be also useful to do reties with delays like 5 retries every 5, 10, 15, 30, 60 minutes and then it goes to failed topic. 
Also while the message is being retried, it should continue to process further messages instead of halting at a particular offset, so that message gets processed without waiting for all retries for the previous message. This may introduce out of order processing but I think for failure scenarios it may be okay or can be controlled by configuration.

**Comment by yaron2** [comment]
@rohitshrivastava04 thanks for this, help me out with designing this.

Ideally, we would like to be able to do this for all bindings and not individually for a particular binding, if possible.

Suppose we define a `.retry` section on Dapr components that allow users to attach retry behaviors.

Dapr runtime would then retry the message according to the policy defined, and if the retry threshold is exceeded, it would *ack* the message to have been processed successfully, thus removing it from the pipe.

Would that be acceptable, or must we use some Kafka/other component specific implementation details instead?

**Comment by rohitshrivastava04** [comment]
I agree a `.retry` to all bindings would be good idea. Now it depends if we can have delays between retries, if so would it be still processing other messages? I would suggest after the retry threshold user should be able to provide a dead letter queue / topic where message should end up. 

Could you please let me know what policies are you thinking for `.retry`
