### ISSUE TITLE
Manage Local Storage binding file not found

### ISSUE THREAD

**Issue by federicocodo** [dapr/components-contrib#2374]
I started to use the [Local Storage binding](https://docs.dapr.io/reference/components-reference/supported-bindings/localstorage/) for my service application.
During my tests I notice that if I try to retrive a file that doesn't exist yet, I expect to receive a `NotFound` exception or a `BindingResponse` with the `Data` field null, instead I received an `Internal` exception just like in the image.
Would it be possible to fix to receive one of the two proposals?
Also is it possible to add in the yaml component a metadata field, time to live, for the files?

<img width="1361" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/62144863/208381853-57ac8710-7df6-401b-9240-0905159cb8e8.png">

Another bug I found during my tests is that if I get the data inside a file and then delete this, I receive an exception in which is described how my file cannot be delete because it is used by another process:

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/62144863/208442110-9daced60-5b7f-4496-8183-d80387fd7104.png">

Maybe is it cause because the file isn't close after getting the data information?

**Comment by federicocodo** [comment]
Any update to this problems?

**Comment by berndverst** [comment]
@ItalyPaleAle any quick thoughts? Maybe your PR already addressed this by chance.

**Comment by ItalyPaleAle** [comment]
@federicocodo Thanks for the report.

1. On the first issue, we can't change the returned status code sadly, nor we can return an empty data (in that case, it wouldn't be possible to distinguish whether the file doesn't exist or it exists but it's empty). However, I've changed the code so the error of the exception contains `file not found: <path>` and you can look at that.
2. On the second issue, looks like a file descriptor was not closed. Fixed

Fixes in #2449 and will be shipped with Dapr 1.10

**Comment by federicocodo** [comment]
@ItalyPaleAle Thanks a lot for the fixes, however what about the option to add in the yaml component or in the metadata field of the request class a time to live for files?

**Comment by berndverst** [comment]
> @ItalyPaleAle Thanks a lot for the fixes, however what about the option to add in the yaml component or in the metadata field of the request class a time to live for files?

I'm not in favor of that feature as a maintainer right now. That doesn't really fit the paradigm of this component. I want to avoid to introduce a separate thread for watching expiration times of files and then deleting them.

File a separate feature request for that please and we can consider it in the future.

**Comment by ItalyPaleAle** [comment]
I agree with @berndverst . However we should probably consider offering a state store for accessing local files. The TTL could be a feature of that.

**Comment by berndverst** [comment]
Let's not brainstorm that here @ItalyPaleAle.

Right now I'm not convinced that files + TTL should be combined in any form. 😅 but if there is enough demand, sure.
