### ISSUE TITLE
The setup-azure-conf-test script contains some deprecated attributes, due to which it fails after running

### ISSUE THREAD

**Issue by shivanisinghnitp** [dapr/components-contrib#2378]
## Expected Behavior

https://github.com/dapr/components-contrib/tree/master/tests/certification/pubsub/azure/eventhubs 
Referring to the above documentation, to run conformance test using azure portal, we need to run the script "setup-azure-conf-test.sh" in ".github/infrastructure/conformance/azure" and it should generate a bash rc file.

## Actual Behavior

The above script fails stating - "Could not find user with upn shivasingh@microsoft.com"

## Steps to Reproduce the Problem
Login to az cli
Go to .github/infrastructure/conformance/azure and run setup-azure-conf-test.sh script

## Fix 
The script uses "objectId" attribute, which is deprecated in "az ad user list", it needs to be changed to "id"
https://learn.microsoft.com/nb-no/cli/azure/microsoft-graph-migration

**Comment by berndverst** [comment]
What arguments are you running the script with?

**Comment by berndverst** [comment]
Glad to hear the fix I suggested worked. Using `id` instead of `objectid`.

Please make a PR against the script to replace `objectid` with `id` @shivanisinghnitp

**Comment by shivanisinghnitp** [comment]
Sure @berndverst

**Comment by ItalyPaleAle** [comment]
Will be fixed by #2453

**Comment by berndverst** [comment]
> Sure @berndverst

@ItalyPaleAle already fixed it in his PR (for something unrelated) because he ran into this as well.
