### ISSUE TITLE
Add support for AWS Dynamo DB for terraform testing infrastructure

### ISSUE THREAD

**Issue by addjuarez** [dapr/components-contrib#2402]
Add permissions and terraform files to support conformance and certification tests for Dynamo DB component

**Comment by robertojrojas** [comment]
@addjuarez  I wonder if this PR: #2384  took care of this issue. In there, I added the [Terraform](https://github.com/dapr/components-contrib/pull/2384/files#diff-a0a56f05076b6404101a62237c51ef7e1ae32e7d444feac4a0c43f4a53aa93c4), Conformance and Certification Tests for DynamoDB.

**Comment by berndverst** [comment]
Yes I think your PR addressed this @robertojrojas - assuming there were no permissions problems (which there don't appear to be).
