### ISSUE TITLE
Not able use dynamic template of SendGrid using Dapr

### ISSUE THREAD

**Issue by Harsh-U-Joshi** [dapr/components-contrib#2412]
I have created a Dynamic Template(contains dynamic fields that will be updated runtime) In Twilio SendGrid. I want to use this template directly in dapr but I am not able to find its yml configuration in Dapr documentation. I have gone through [this documentation](https://docs.dapr.io/reference/components-reference/supported-bindings/sendgrid/). Here is [link](https://docs.sendgrid.com/ui/sending-email/how-to-send-an-email-with-dynamic-templates) what I want to achieve with dapr set templateId and update dynamic fields runtime..Can you please guide me if this feature is available or else can you please let me know when this feature will be available?

**Comment by berndverst** [comment]
The binding does not support this today.

Here is the code that needs to be added to the Dapr Sendgrid Binding for this:

```go

	var templateData map[string]interface{}
	if req.Metadata["dynamicttemplatedata"] != "" {
		templateError := json.Unmarshal([]byte(req.Metadata["dynamicttemplatedata"]), &templateData)
		if templateError != nil {
			return nil, fmt.Errorf("error from SendGrid binding, dynamic template data is not valid JSON: %+v", templateError)
		}
		personalization.DynamicTemplateData = templateData
	}

	email.AddPersonalizations(personalization)
	if req.Metadata["dynamicttemplatedata"] != "" {
		email.TemplateID = req.Metadata["templateid"]
	}

```

That should work if I understand this correctly. I don't have a Twilio / Sendgrid account so I cannot test this behavior however.

**Comment by Harsh-U-Joshi** [comment]
Thanks. When will dapr support this feature??

**Comment by berndverst** [comment]
It's not a priority and a member of the community can contribute this. As an open source project we rely on code contribution from community members like yourself.

This will not be in the next release - 1.10. Maybe in the one after that if someone implements this feature.

It should be easy to do with what I provided, but I am not a twilio user and don't have an account to test with.

**Comment by yannart** [comment]
Submitted PR for the dynamic template support. Hope it can make 1.11.

**Comment by berndverst** [comment]
@yannart this will be in 1.12 - we are well beyond code freeze for 1.11 and we already cut the release branch. We also do not have documentation yet for this feature - so at this point we cannot add any features.

Please make sure you write the documentation once the 1.12 branch of the docs repo has been created (after our 1.11 release). It has to be done in the 1.12 branch.
Open this issue and leave a comment with `/assign` so the issue gets assigned to you please: https://github.com/dapr/docs/issues/3425

**Comment by yannart** [comment]
@berndverst understood for 1.12. For the doc, I have an issue and PR already: https://github.com/dapr/docs/pull/3422

**Comment by berndverst** [comment]
> @berndverst understood for 1.12. For the doc, I have an issue and PR already: [dapr/docs#3422](https://github.com/dapr/docs/pull/3422)

@yannart must have missed that. Unfortunately I cannot close the docs issue, but it should be closed by someone eventually :)
