### ISSUE TITLE
Can't connect DAPR after restart due to mDNS cache

### ISSUE THREAD

**Issue by smartnet-club** [dapr/components-contrib#2413]
if you have 2 services (A and B) and restarts A, service B can't send any message to restarted instance of A because uses cached address:
```
== APP == I20230106 05:39:38.125066 2653768 client.cpp:150] GetVersion status fail to invoke, id: license, err: failed to invoke target license after 3 retries
DEBU[0021] found mDNS IPv4 address in cache: 192.168.2.42:40093  app_id=client instance=raider scope=dapr.contrib type=log ver=1.9.5
DEBU[0021] retry count: 1, grpc call failed, ns: , addr: 192.168.2.42:40093, appid: license, err: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.2.42:40093: connect: connection refused"  app_id=client instance=raider scope=dapr.runtime.direct_messaging type=log ver=1.9.5
```
Probably you should force mDNS cache cleanup after service restart.

_Originally posted by @smartnet-club in https://github.com/dapr/dapr/issues/5699#issuecomment-1372887910_

**Comment by berndverst** [comment]
If you would like to investigate this issue, the relevant code is here: https://github.com/dapr/components-contrib/blob/master/nameresolution/mdns/mdns.go

**Comment by smartnet-club** [comment]
> If you would like to investigate this issue

Sorry, I don't have free time for this. Assign to the lead developer or put in the backlog.

**Comment by ItalyPaleAle** [comment]
In the meanwhile, a "simple" workaround is to force the Dapr sidecar to create the internal gRPC server on a fixed port (instead of a random one by default). Start Dapr with:

```sh
# Set a port here
--dapr-internal-grpc-port 50990
```

This way the value won't change across restarts and the cache won't be invalid (even if stale)

**Comment by berndverst** [comment]
Maybe this would be addressed by the following issue: https://github.com/dapr/components-contrib/issues/1472

**Comment by ItalyPaleAle** [comment]
This PR in the runtime will likely fix this issue for most users: https://github.com/dapr/dapr/pull/5914
