### ISSUE TITLE
Twilio SMS body results in double quotes in Dapr

### ISSUE THREAD

**Issue by Harsh-U-Joshi** [dapr/components-contrib#2422]
I am sending an SMS through Dapr Twilio. My SMS is sent successfully but the message body is shown in double-quotes. I am not able to configure where the error is. After searching on google I found [this](https://nation.marketo.com/t5/product-discussions/using-my-tokens-in-twilio-sms-body-results-in-double-quotes/td-p/182896)  link but I am not able to understand how to implement that solution in dapr Twilio. If you have any solution then please provide it. (Prefered Programming language is C#,.NET). I have tried it with Twilio paid version but the same issue. An image and its code snippet are added to this issue.

![Screenshot_20230109_160441](https://user-images.githubusercontent.com/48823979/211288794-5b580d06-5140-48e1-b429-34cd0d133160.png)

![Example](https://user-images.githubusercontent.com/48823979/211284995-a1e71b72-2a61-4629-a320-ecf594539ff3.jpg)

**Comment by goldytech** [comment]
Using with Dapr sidecar also shows the same behavior, the message text is still shown in double quotes


```
curl -X POST http://localhost:3500/v1.0/bindings/sms   -H "Content-Type: application/json"    -d '{         "data": "Welcome to this awesome service",         "metadata": {           "toNumber": "555-3277"

},  "operation": "create" }'

```

**Comment by dhartimakwana** [comment]
@ItalyPaleAle When this change will release?

**Comment by ItalyPaleAle** [comment]
@dhartimakwana Dapr 1.10, which should be out in early February.

in a few days you may also see it in the nightly builds of Dapr, which you can try in a dev environment (but I wouldn’t recommend them for production yet)
