### ISSUE TITLE
DAPR for Amazon MSK, Amazon DocumentDB and Amazon Elasticache

### ISSUE THREAD

**Issue by sam0410** [dapr/components-contrib#2432]
## In what area(s)?

> /area placement

> /area docs

## Describe the feature
 I know Kafka, MongoDB and Redis is supported by DAPR today. But, what will it take to integrate with AWS managed version of the three? [Amazon MSK, Amazon DocumentDB, Amazon Elasticache]?

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
I'm moving this issue to dapr/components-contrib

We definitely welcome contributions from the community to add support to more components! You can see this repo (components-contrib) for instructions on how to create a new component.

**Comment by yaron2** [comment]
@sam0410 I'm fairly certain our Kafka component works with Amazon MSK and I know our Redis component works with Elasticache.
