### ISSUE TITLE
Not able use dynamic template of SendGrid using Dapr

### ISSUE THREAD

**Issue by Harsh-U-Joshi** [dapr/components-contrib#2435]
I have created a Dynamic Template(contains dynamic fields that will be updated runtime) In Twilio SendGrid. I want to use this template directly in dapr but I am not able to find iits yml configuration in Dapr documentation. I have gone through [this documentation](https://docs.dapr.io/reference/components-reference/supported-bindings/sendgrid/). Can you please guide me if this feature is available or else can you please let me know when this feature will be available.

**Comment by berndverst** [comment]
Closing in favor of #2412
