### ISSUE TITLE
[Security] `bindings.localstorage`: disallow accessing `/var/run/secrets` by default

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#2444]
## Description

This is a potential security issue.

Using the `bindings.localstorage` binding, users can access any file mounted inside the daprd container. The folder `/var/run/secrets` is where Dapr mount secrets such as the bound token for Sentry, as well as other secrets, and it should not be accessible directly to applications.

This is potentially a breaking change, although it's very unlikely someone will have a legit reason for doing this.

## Release Note

RELEASE NOTE: **FIX** Disallow accessing `/var/run/secrets` using `bindings.localstorage` (security)

**Comment by ItalyPaleAle** [comment]
CC: @yaron2 @berndverst thoughts?

**Comment by yaron2** [comment]
LGTM, although in K8s the security boundary is (in almost all cases) the pod and not the container, so while this might help in some situations, generally users need to assume that a breach into one container is a breach into the pod. As an example, IAM roles in AWS (and I assume in Azure as well) are on a pod-basis, so any container in the pod can abuse the role and talk to AWS services that are meant to be used by a different container. Not worried about the breaking change here.

**Comment by berndverst** [comment]
I'm fine with this, but don't consider it a security issue for the same reason @yaron2 outlines.
