### ISSUE TITLE
Propagation of tracing headers in HTTP Binding component

### ISSUE THREAD

**Issue by drewby** [dapr/components-contrib#2445]
## Describe the feature

Propagation of tracing headers in HTTP Binding component in Dapr to associate traces with the correct parent span. This feature will improve traceability and aid in debugging when calling external HTTP services that provide trace data to a central collector.

There is a workaround, where the client application can add the Traceparent to the metadata in the request payload. However, this means the upstream traces will be parented to the original request to Dapr, not the Dapr request to the endpoint. 

Since a motivation for Dapr is effortless distributed tracing, this capability should be built into the HTTP binding. There may be cases where a customer does not want to propagate trace headers, so perhaps a flag in the binding configuration could be set whether to propagate headers. 

## Release Note

RELEASE NOTE: **ADD** Propagation of tracing headers in HTTP Binding component.

**Comment by msfussell** [comment]
@drewby - Can you update the docs issue for this?
