### ISSUE TITLE
For service invocation how to map a restful web api into a method

### ISSUE THREAD

**Issue by csharpknife2002** [dapr/components-contrib#248]
Assuming I have a restful api like this:
/api/v1.0/persons/{persion_id}/detail?unitsystem="Metric",

to allow another service call it via Dapr service invocation, How do I map it to a method name?

Do I have to combine all information into a simple url and all the data has to be in the body?

Thanks and best regards

**Comment by csharpknife2002** [comment]
After some try and see the source code, I find it actually support path,query parameter, but just not well documented.

**Comment by yaron2** [comment]
> After some try and see the source code, I find it actually support path,query parameter, but just not well documented.

Would be great if you could help us with docs!
