### ISSUE TITLE
SQLite state store and concurrent access by multiple Dapr instances

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#2485]
## Description

SQLite does not support concurrent writes to the database, and trying to execute multiple queries that modify the database can corrupt the DB.

Within a single Dapr instance, the component is using Go locks to ensure that no more than one operation on the database happens at the same time. This works really well to prevent issues when there's only one Dapr sidecar accessing the database.

However, if multiple Dapr sidecars are initialized with the same SQLite database, there's no protection against concurrent writes.

This could be implemented by adding a transaction around each SQL query. We could also add a metadata option to make this optional, if users developing locally don't need concurrent access to the same DB.

## Release Note

RELEASE NOTE: **ADD** Protections against concurrent access to the same SQLite database in `state.sqlite`

**Comment by berndverst** [comment]
As discussed the component should be updated to run all queries transactionally. It is also worth investigating whether there are any file locking concerns - not sure how multiple processes writing to the same SQLite database file is handled.
