### ISSUE TITLE
[Proposal] Deprecate Twitter Binding component [approved by all maintainers]

### ISSUE THREAD

**Issue by berndverst** [dapr/components-contrib#2503]
## Describe the proposal

Deprecate the Twitter binding component.

Why:

- The industry and developers are increasingly less interested in Twitter
- Twitter is planning to charge for API access beginning next week, further decreasing the usage of Twitter APIs: https://arstechnica.com/tech-policy/2023/02/cash-strapped-twitter-to-start-charging-developers-for-api-access-next-week/
- New/Current Twitter API accounts are not supported by the existing binding - for these users the component is not usable.
- Maintainer burden: Current Twitter API accounts can only use the v2 API and Dapr's Twitter component is incompatible with the v2 API. However v2 clients are incompatible with the v1 API. We would need to create a new implementation for the v2 client but also maintain the v1 client. This creates an unnecessary maintenance burden for an integration that primarily is used in demos, but not in business situations.

Benefits:
+ No need to maintain to different Twitter integrations
+ Free up memory for the Dapr sidecar

**Comment by ItalyPaleAle** [comment]
I'm in favor of this

**Comment by ItalyPaleAle** [comment]
I'm in favor of this

What version should this be deprecated in? It's not a stable component at the moment

**Comment by berndverst** [comment]
Ideally we'd start showing deprecation notices in this release and remove in 1.11. If there is too much push back we can cancel the deprecation.

**Comment by berndverst** [comment]
Thoughts @artursouza @yaron2 ?

**Comment by artursouza** [comment]
I agree to this.

**Comment by i-am-shodan** [comment]
Seems reasonable, as you say it was Alpha and with this in place we can move on as everyone knows where they stand.

**Comment by yaron2** [comment]
I support removing the component, but most of the reasons given don't justify removal:

> The industry and developers are increasingly less interested in Twitter

This is very subjective and level of interest is not a major criteria in selecting components. In 2023, Twitter still has 353M users and its APIs are commonly used in many products.

> Twitter is planning to charge for API access beginning next week, further decreasing the usage of Twitter APIs

We have many components that work with paid only tiers of the service including the major clouds, so this shouldn't be a factor.

> New/Current Twitter API accounts are not supported by the existing binding - for these users the component is not usable.

This can be solved with code just like we handle breaking changes in components like Redis. It's an Alpha component which makes it easier.

--------------------------------------------------------------

From a maintainer perspective, I agree that the binding is mostly for demos and not business scenarios. This coupled with the resource usage, maintainer burden and the component being in Alpha are enough of a reason to remove it, especially now with pluggable components that allow folks who do need this functionality to consume it, albeit with a bit more operational overhead.

**Comment by berndverst** [comment]
Yes we are only having this discussion because the component is Alpha.

While it is true that we can create a separate version of this component (see #2283 for my thoughts on that) that is additional work for which there is no bandwidth and the community hasn't stepped up to do this either. This also would represent a breaking change / behavioral change - beyond how the Redis changes worked as the API capabilities completely changed with regards to several operations.

To my knowledge the Dapr Twitter binding (alpha) component has largely been used for demos. These demos will not be viable once payment for API access is required.

To the Dapr users who used this component for real workflows today - my apologies. I do recommend using many of the available v2 Twitter SDKs. These SDKs are largely better maintained and more used in languages other than Go.

On this topic I agree that with the advent of Dapr pluggable components any community contributor may soon provide a pluggable component (process external to the sidecar) to provide Twitter functionality. This could leverage SDKs in other languages that are better maintained. So the loss of Twitter functionality may only be temporary until a community member creates a pluggable component.

In closing, it is my personal opinion that we will see a decline in Twitter API usage with the latest changes by Twitter - but that certainly isn't a decision making factor here.

**Comment by msfussell** [comment]
I would at least ask the Discord community for their opinion and see what comes back to verify the statements above.
