### ISSUE TITLE
Dapr sidecar stops consuming Azure Service Bus

### ISSUE THREAD

**Issue by arnoldpistorius** [dapr/components-contrib#2505]
## Expected Behavior

Dapr sidecar keeps consuming ASB subscription messages forever.

## Actual Behavior

Suddenly (in this case after ~6 days uptime) the sidecar stops consuming ASB subscription messages, resulting in messages piling up in the subscription. We have experienced this now the second time for two different services. The oldest item in the service bus's properties:

![image](https://user-images.githubusercontent.com/6072267/216707387-9f2cb305-0290-4d58-98be-05d0f505a467.png)

Dapr sidecar v1.9.5 logs (unfortunately info loglevel):

[dapr-log.log](https://github.com/dapr/components-contrib/files/10582686/dapr-log.log)

## Steps to Reproduce the Problem

Have a sidecar with ASB subscriptions and eventually the sidecar stops consuming the servicebus subscription (can take up several days before it occurs).

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
@arnoldpistorius could you please try with Dapr 1.9.6? I believe we should have fixed the issue then.

**Comment by arnoldpistorius** [comment]
@ItalyPaleAle We'll do that when the updated AKS extension is rolled out. Heard that it is currently in dev train and will go stable tomorrow. I'll update this ticket when the problem happens on 1.9.6+.

**Comment by arnoldpistorius** [comment]
@ItalyPaleAle had to restart a pod again today that stopped processing ASB messages. We're on 1.9.6.

**Comment by vyliniem** [comment]
We have been experiencing this same issue for some time now on different 1.9 versions. We just upgraded to 1.9.6 today so no experiences with that one yet.

Our environment is Azure AKS (standard-tier, three nodes, Kubernetes 1.24.6) with Dapr deployed in HA-mode using dapr-cli. Azure Service Bus (Standard) is the backend for dapr-pubsub.

The issue usually manifests after a pod has been running for several days. Currently the load on the cluster is very low and there can be 24+ hours between messages published, so we have not been able to accurately pinpoint when excatly daprd stops consuming the messages.

Following debug-message is repeated uninterrupted (seemingly not affected by the issue) every 20 seconds:
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"debug","msg":"No active messages require lock renewal for topic xxx","scope":"dapr.contrib","time":"2023-02-13T03:35:02.1423853Z","type":"log","ver":"1.9.5"}

These are all the log messages from daprd between last message delivered and pod-restart, except the repeating debug-message which have been filtered out.

Last succesfully delivered message:
```
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"debug","msg":"Received message: fa9b2a3c9de44192ad151c871d56ad09 current active message usage: 1/10000","scope":"dapr.contrib","time":"2023-02-12T16:46:45.1206503Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"debug","msg":"Adding message fa9b2a3c9de44192ad151c871d56ad09 with sequence number 5112 to active messages on topic xxx","scope":"dapr.contrib","time":"2023-02-12T16:46:45.1207601Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"debug","msg":"Processing received message: fa9b2a3c9de44192ad151c871d56ad09","scope":"dapr.contrib","time":"2023-02-12T16:46:45.1208027Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"debug","msg":"Calling app's handler for message fa9b2a3c9de44192ad151c871d56ad09 on topic xxx","scope":"dapr.contrib","time":"2023-02-12T16:46:45.1208996Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"debug","msg":"Completing message fa9b2a3c9de44192ad151c871d56ad09 on topic xxx","scope":"dapr.contrib","time":"2023-02-12T16:46:45.1237059Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"debug","msg":"Removing message fa9b2a3c9de44192ad151c871d56ad09 with sequence number 5112 from active messages on topic xxx","scope":"dapr.contrib","time":"2023-02-12T16:46:45.9452307Z","type":"log","ver":"1.9.5"}
```
Service consuming the message also publishes one, this warning is probably related to than one, although there is nothing in the service logs:
```
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"warning","msg":"Could not publish service bus message (nil). Retrying...: context deadline exceeded","scope":"dapr.contrib","time":"2023-02-12T16:47:45.3373890Z","type":"log","ver":"1.9.5"}
```

Then there is silence in the logs until a cert-reneval happens:
```
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"info","msg":"renewing certificate: requesting new cert and restarting gRPC server","scope":"dapr.runtime.grpc.internal","time":"2023-02-12T18:07:15.4201833Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"info","msg":"sending workload csr request to sentry","scope":"dapr.runtime.grpc.internal","time":"2023-02-12T18:07:15.4203054Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-76dd8b4889-h2dpj","level":"info","msg":"certificate signed successfully","scope":"dapr.runtime.grpc.internal","time":"2023-02-12T18:07:15.4744072Z","type":"log","ver":"1.9.5"}
```

After this there is nothing but the debug-messages noted above. From an Azure-dashboard I can see that a new message was published around 2023-02-13T02:30:00Z but not consumed until after the pod was restarted.

Pod restart:
```
{"app_id":"xxx","instance":"xxx-7976896c87-bmpmd","level":"info","msg":"starting Dapr Runtime -- version 1.9.5 -- commit f5f847eef8721d85f115729ee9efa820fe7c4cd3","scope":"dapr.runtime","time":"2023-02-13T06:55:32.0193877Z","type":"log","ver":"1.9.5"}
```

Message published earlier is consumed after restart:
```
{"app_id":"xxx","instance":"xxx-7976896c87-bmpmd","level":"debug","msg":"Received message: 12879e6ee5d046c1b51f748c0d5e5392 current active message usage: 1/10000","scope":"dapr.contrib","time":"2023-02-13T06:55:45.2537289Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-7976896c87-bmpmd","level":"debug","msg":"Adding message 12879e6ee5d046c1b51f748c0d5e5392 with sequence number 5113 to active messages on topic xxx","scope":"dapr.contrib","time":"2023-02-13T06:55:45.2540817Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-7976896c87-bmpmd","level":"debug","msg":"Processing received message: 12879e6ee5d046c1b51f748c0d5e5392","scope":"dapr.contrib","time":"2023-02-13T06:55:45.2542066Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-7976896c87-bmpmd","level":"debug","msg":"Calling app's handler for message 12879e6ee5d046c1b51f748c0d5e5392 on topic xxx","scope":"dapr.contrib","time":"2023-02-13T06:55:45.2543578Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-7976896c87-bmpmd","level":"debug","msg":"Completing message 12879e6ee5d046c1b51f748c0d5e5392 on topic xxx","scope":"dapr.contrib","time":"2023-02-13T06:55:45.2702238Z","type":"log","ver":"1.9.5"}
{"app_id":"xxx","instance":"xxx-7976896c87-bmpmd","level":"debug","msg":"Removing message 12879e6ee5d046c1b51f748c0d5e5392 with sequence number 5113 from active messages on topic xxx","scope":"dapr.contrib","time":"2023-02-13T06:55:45.4761083Z","type":"log","ver":"1.9.5"}
```

**Comment by berndverst** [comment]
In Dapr 1.10 (especially since 1.10.0-rc.7) we have further improved error handling. We therefore strongly recommend service bus users to upgrade to the 1.10 release once it is out.

**Comment by berndverst** [comment]
Now that Dapr 1.10 is out, please let us know whether this is still an issue. Note that Azure Container Apps won't see Dapr 1.10 for a bit longer.

**Comment by vyliniem** [comment]
We upgraded to Dapr 1.10 four weeks ago, and so far have not seen any more issues with message delivery/consumption.
