### ISSUE TITLE
Support Auth EXTERNAL for RabbitMQ mTLS/SSL Setups

### ISSUE THREAD

**Issue by abossard** [dapr/components-contrib#2514]
## Describe the feature
I wish for the RabbitMQ to support EXTERNAL as parameter. It means that you can configure RabbitMQ to take the Username e.g. from the Common Name of the Client certificate. This allows to have client authentication and different users without having passwords but still secure.

This is based on the EXTERNAL mechanism described here:
https://www.rabbitmq.com/access-control.html#mechanisms

And an example RabbitMQ Docker Image that uses the configuration is located here:
https://github.com/GFlisch/RabbitmqS

## Release Note

RELEASE NOTE: **ADD** Support for EXTERNAL as Auth mechanism in RabbitMQ mTLS Setups.

**Comment by berndverst** [comment]
@abossard please comment on the PR https://github.com/dapr/docs/issues/3265 to assign that to yourself. Leave a comment there with `/assign` - this is to write the documentation for your PR.
