### ISSUE TITLE
support for graphql query variables

### ISSUE THREAD

**Issue by serpentfabric** [dapr/components-contrib#2517]
i think it's important for the graphql binding to support query variables. 

currently, variables must be inlined into the query; which may be vulnerable to injection type attacks. there is no way to pass variables to a query using the existing binding as of today.

i believe parametrized queries mitigate those attacks and therefore i propose we add support for them. i think my fork contains a fairly straightforward idiomatic approach: https://github.com/dapr/components-contrib/compare/master...serpentfabric:components-contrib:feature/graphql-variable-support

**Comment by yaron2** [comment]
Thanks, feel free to open a PR.

**Comment by serpentfabric** [comment]
#2522

**Comment by serpentfabric** [comment]
so there are like zero tests for the gql binding, should i try to figure out how to add some? or does the pr seem straighforward enough that we can omit them?

disclaimer: i'm not a native golang dev so it may 'take a minute' to figure out how to test :)

**Comment by berndverst** [comment]
> so there are like zero tests for the gql binding, should i try to figure out how to add some? or does the pr seem straighforward enough that we can omit them?
> 
> disclaimer: i'm not a native golang dev so it may 'take a minute' to figure out how to test :)

@serpentfabric I added a comment on your PR for a test I'd like to see.

Essentially you set up a fake HTTP server, initialize the binding with a URL from the fake server.. then use the component and assert your fake server got the expected POST request and particular JSON payload contents.
