### ISSUE TITLE
[Proposal] OSS / cloud agnostic components should not have vendor specific naming

### ISSUE THREAD

**Issue by berndverst** [dapr/components-contrib#2518]
All open source components that are not cloud specific should not be named with a specific cloud provider.

E.g. Apache Dubbo is currently named `alicloud.dubbo` but the component is cloud agnostic. There are several other such components.

We should rename these components to standard OSS components. This means using an OSS name to instantiate the component in Dapr, and also moving the source code folder for clarity. Additionally documentation should only refer to the OSS / vendor neutral name.

For backwards compatibility we will maintain the existing vendor specific registry name as an alias.

**Comment by berndverst** [comment]
Does this sound good to you all @yaron2 @artursouza @ItalyPaleAle @msfussell ?

**Comment by berndverst** [comment]
1. Move code in contrib and rename variables as necessary.
2. Rename component name in dapr/dapr and create alias.
3. Update docs to refer to new name only.

**Comment by berndverst** [comment]
> LGTM. What are the components that would be impacted, @berndverst ?
> 
> I think one more could be Azure SQL (= SQL Server)?

Azure SQL is only a docs issue! In code and the registry name is already vendor neutral. This component is also a bit weird because the component doesn't work correctly with SQL server installation locally on Windows for example from what I recall -- but in theory that component would fall under this too - that is correct.

**Comment by yaron2** [comment]
If a component is not using a vendor SDK to interact with it then it should not be prefixed with a vendor name.

**Comment by berndverst** [comment]
> If a component is not using a vendor SDK to interact with it then it should not be prefixed with a vendor name.
> 
> 

@yaron2 exactly, but that isn't the case right now - hence this issue.

I will do the work to rename things for 1.11.

**Comment by ItalyPaleAle** [comment]
This was completed, right? @berndverst
