### ISSUE TITLE
Improve "File not Found" error for Azure BlobStorage and AWS S3 bindings

### ISSUE THREAD

**Issue by federicocodo** [dapr/components-contrib#2526]
As the previous issue (#2374) is it possible to add a similar line of code, added for LocalStorage binding, also for other storages like Azure BlobStorage, AWS S3, ecc...?
```go
if os.IsNotExist(err) {
    return nil, fmt.Errorf("file not found: %s", absPath)
}
```
Currently for Azure BlobStorage I get this error: 
![image](https://user-images.githubusercontent.com/62144863/218482695-ea8cf87f-dbf5-48e3-96fb-8689686830d0.png)
This is all because I'm running a multi-storage service and trying to manage all responses.
Thanks in advance.

**Comment by berndverst** [comment]
Sure, contributions are welcome. Please note that in Dapr 1.10 and going forward we use a completely different Azure Blob Storage SDK. So you will not be able to reproduce this exact error message there.

**Comment by artursouza** [comment]
Removing from 1.12, if anyone from the community creates a PR, we can bring it back.
