### ISSUE TITLE
Support for Apache Pulsar End-to-End Encryption (E2EE) in the PubSub Building Block

### ISSUE THREAD

**Issue by hugosmitter** [dapr/components-contrib#2531]
## Describe the feature

According to the 2020 Cost of a Data Breach Report by Ponemon Institute and IBM Security, data breaches are costing enterprises $3.86 million on average, and they’re taking an average of 280 days to discover the problem. Clearly, hackers can and already do easily identify and access both corporate and personal information when files are transmitted from device to device unless certain cybersecurity measures are put into place. End-to-end encryption (E2EE) is the easiest solution for protecting this data so it doesn’t get into the wrong hands. End-to-end encryption is the practice of encrypting data and information as it passes from device to device. The sending and receiving devices can see the original contents, but no other interceptors have the correct keys to decrypt the message. (Source: https://www.cioinsight.com/security/end-to-end-encryption/). E2EE encryption will protect data at rest.

Applications can use Pulsar end-to-end encryption (E2EE) to encrypt messages on the producer side and decrypt messages on the consumer side. You can use the public and private key pair that the application configures to perform encryption and decryption. Only the consumers with a valid key can decrypt the encrypted messages. (Source: https://pulsar.apache.org/docs/2.11.x/security-encryption/#:~:text=Applications%20can%20use%20Pulsar%20end,to%20perform%20encryption%20and%20decryption.)

This request is for optionally enabling Pulsar's E2EE support to Dapr sidecar using custom CryptoKeyReader function so the private/public key pair used to encrypt/decrypt the symmetric key used for payload encryption can be retrieved from either a Kubernetes Secret or an external secrets vault. 

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
I've added it to the `v1.11` milestone and added the `help wanted` label. Hopefully someone will pick it up.
