### ISSUE TITLE
rabbitmq pubsub - possibility of using quorum queues (instead of classic queues)

### ISSUE THREAD

**Issue by VuiDJi** [dapr/components-contrib#2544]
## Describe the feature
We want to use rabbitmq production ready cluster with 3 replicas for dapr pusub component.

For fault tolerance, we are forced to configure the replication policy for classic queues, but [rabbitmq developers recommend to avoid using classic mirrored queues](https://github.com/rabbitmq/cluster-operator/issues/666#issuecomment-826574713). They will be deprecated and removed in the future.
They think that if you care about data safety, use quorum queues instead (quorum queues don't require policies like that at all).

Please add the ability to use quorum queues, which is extremely relevant for production scenarios.

**Comment by yaron2** [comment]
Hint for implementation here: https://stackoverflow.com/questions/73670885/create-queue-quorum-rabbitmq-in-golan-by-streadway-module.

**Comment by jackycsl** [comment]
Can I work on this issue?

**Comment by yaron2** [comment]
> Can I work on this issue?

Of course.

**Comment by thevaruntiwari** [comment]
May I know when we will receive the new release integrated with this feature support.

**Comment by juanrevello** [comment]
Hi! Is there any news regarding this change? I need to create quorum queues, since rabbitmq indicates that the classic queues are to be removed. Thanks!

**Comment by ItalyPaleAle** [comment]
Done in #2816
