### ISSUE TITLE
Broken links on development guide

### ISSUE THREAD

**Issue by matzew** [dapr/components-contrib#2559]
## Expected Behavior

No broken (404) links on the https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md#validating-with-dapr-core 

## Actual Behavior

the links to the quickstarts / tutorials are broken, after the "re org" of the `quickstarts` repo

**Comment by berndverst** [comment]
Quickstarts are changing too much to maintain these links. You can pick any app - quickstart apps are just examples here. I suggest we link to the repo only, but not to any specific app.

**Comment by matzew** [comment]
Sounds good, I will tweak the doc for this, @berndverst

**Comment by matzew** [comment]
/close

this was now addressed
