### ISSUE TITLE
Create component metadata for pubsub.kafka

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#2579]
Create component metadata for pubsub.kafka, like in https://github.com/dapr/components-contrib/blob/master/state/azure/cosmosdb/metadata.yaml

**Comment by SpikeWong** [comment]
I can help with this, But I am wondering why we need this? To provide user a ready-to-use example?

**Comment by artursouza** [comment]
This can be used by platforms to present or validate metadata prior to applying them on the cluster.

**Comment by berndverst** [comment]
@SpikeWong if you need more examples, see https://github.com/dapr/components-contrib/pull/2528

You can use the 1.10 documentation to get started. However, please also double check the code -- the code is the source of truth, not the documentation. It is possible certain default values are not documented, or some metadata fields are missing etc. The YAML file should include all component metadata (for initialization of the component) found in the code.

**Comment by yaron2** [comment]
Closed via #2678
