### ISSUE TITLE
Create component metadata for secretstores.gcp.secretmanager

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#2584]
Create component metadata for secretstores.gcp.secretmanager, like in https://github.com/dapr/components-contrib/blob/master/state/azure/cosmosdb/metadata.yaml

**Comment by MregXN** [comment]
Is gcp.secretmanager the same to [GCP Firestore](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-firestore/)?

**Comment by ItalyPaleAle** [comment]
This should not have been merged until the shared auth profile for GCP is done. Re-opening so @robertojrojas can complete it

**Comment by robertojrojas** [comment]
@artursouza I believe we can close this issue as PR #2937 has been merged to master.
