### ISSUE TITLE
Create component metadata for secretstores.hashicorp.vault

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#2585]
Create component metadata for secretstores.hashicorp.vault, like in https://github.com/dapr/components-contrib/blob/master/state/azure/cosmosdb/metadata.yaml

**Comment by Kreestyan** [comment]
Hi, I was wondering if the Hashicorp secret retrieval API would allow to provide the metadata one can add to a secret in Hashicorp vault and I felt this issue was about this. Does this mean it is part of v1.11? I'm checking the v1.11 API doc but do not see any specifics about this.
