### ISSUE TITLE
Authenticate PostgreSQL components using Azure AD

### ISSUE THREAD

**Issue by sujitdmello** [dapr/components-contrib#2595]
We are able to access the configuration store from an Azure PostgreSQL database using a connection string with password. 

Subsequently, we configured the database server with AAD auth and the AKS cluster was setup with [Workload Identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview) to allow the Pods to leverage a User Assigned Managed Identity. This requires calling the [token issuer endpoint](https://learn.microsoft.com/en-us/azure/postgresql/single-server/how-to-connect-with-managed-identity) to retrieve the password for the managed identity and then setting that token as the password in the connection string that is used to access the PostgreSQL. The [configuration store binding for PostgreSQL](https://github.com/dapr/components-contrib/blob/master/configuration/postgres/postgres.go) does not do this token access, so it looks like it will have to be done by the app. 

Any thoughts on how this can be accomplished? I tried overwriting the _connectionString_ using the _GetConfigurationRequest_ class and calling _setMetadata()_ to set the connection string, but that did not seem to work. I don't see much documentation on this _setMetadata_ call - what is it used for?
  
## Components

- [X] State store: #2970
- [x] Binding: #2971
- [x] Configuration store: #2971

**Comment by ItalyPaleAle** [comment]
I was not aware that Azure Database for PostgreSQL supported Azure AD auth, thanks for sharing this.

I've taken a look at the docs: https://learn.microsoft.com/en-us/azure/postgresql/single-server/how-to-connect-with-managed-identity It looks like something that we should be able to add without too much work in Dapr 1.11.

PS: `SetMetadata` is unrelated from components' metadata: https://docs.dapr.io/reference/api/metadata_api/

**Comment by berndverst** [comment]
@sujitdmello please note that for workload identity we are still waiting for a stable SDK from the Azure SDK team with workload identity support. As such none of our AAD supported components can use workload identity. We anticipate this being complete by 1.11.

For the time being you would need to use the deprecated AAD Pod Identity extension for AKS to use regular managed identity there. Of course this only works for the Dapr components which support AAD at this time (and that does not include PostgreSQL yet - but we'll make it happen for 1.11)
