### ISSUE TITLE
Kafka Pub/Sub: CA cert authentication broken > v1.8

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#2639]
Prior to Dapr 1.8, users could authenticate to Kafka using a CA certificate (metadata field `caCert`) with `authType` set to `none`.

This is not possible in Dapr starting v1.8.

**Comment by berndverst** [comment]
Existing behavior could not be retained without breaking existing conformance tests, but as discussed we are restoring this behavior with a new auth type `certificate` which allows for certificate authentication.

**Comment by ItalyPaleAle** [comment]
Fixed in release-1.10
