### ISSUE TITLE
Zookeeper state store should return empty state if key not found

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#264]
This line: https://github.com/dapr/components-contrib/blob/fa15dfb7087d757190b25de2221a9461bd93a5ed/state/zookeeper/zk.go#L143

Should check if its an error for a missing key, and if it is return `nil, &GetResponse{}`

**Comment by halspang** [comment]
This was resolved in https://github.com/dapr/components-contrib/pull/300
