### ISSUE TITLE
Add Support for GCP Firestore Testing Infrastructure

### ISSUE THREAD

**Issue by robertojrojas** [dapr/components-contrib#2652]
## Describe the feature
The GCP Firestore Testing Infrastructure requires adding of the steps to Github actions workflow.
If any resources need to be created before the certification test is executed, these resources
can be created using [Terraform](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firestore_document) 
This is a prerequisite for [Certify GCP Firestore as Stable](https://github.com/dapr/components-contrib/issues/2460)

**Comment by berndverst** [comment]
Can you please create the tracking issue for creating the base GCP testing infrastructure? I imagine this certification test will be an extension to the base setup for GCP. We definitely don't want lots of one off code for each components - there should be some sort of shared account set up / process for all GCP components.

And then link both of your GCP components to that tracking issue as they depend on it.

Until we have the GCP account and have set up the base infrastructure we cannot proceed with this.

**Comment by robertojrojas** [comment]
@berndverst yes! that makes a lot of sense. As for the Dapr GCP Account, yeah I'm looking into that as well.

**Comment by robertojrojas** [comment]
Closing this issue as https://github.com/dapr/components-contrib/issues/2651 will take care of this.
