### ISSUE TITLE
It seems a code bug in mongo implementation

### ISSUE THREAD

**Issue by ChenTanyi** [dapr/components-contrib#2657]
## Bug Detail

It is not found in runtime. I just reading the code about implementation. So I can tell nothing about expected behavior or actual behavior.

In mongo implementation, two connection string formats is not consistent in the implementation detail. https://github.com/dapr/components-contrib/blob/4be795d812d48d455a7280f949f35fe50436a187/state/mongodb/mongodb.go#L418-L432

[connectionURIFormatWithSrvAndCredentials](https://github.com/dapr/components-contrib/blob/4be795d/state/mongodb/mongodb.go#L72) need **databaseName** and **param**, but [connectionURIFormatWithSrv](https://github.com/dapr/components-contrib/blob/4be795d/state/mongodb/mongodb.go#L69) only need **param**.

Maybe it is a bug?

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
I don't think this is a real issue.

It is used here
```
fmt.Sprintf(connectionURIFormatWithSrv, metadata.Server, metadata.Params)
```

So in the case where you want to use SRV but without authentication you can only specify the server and the params.

But if you want to use authentication you also need to specify the username, password and database.

```
return fmt.Sprintf(connectionURIFormatWithSrvAndCredentials, metadata.Username, metadata.Password, metadata.Server, metadata.DatabaseName, metadata.Params)
```

**Comment by berndverst** [comment]
So to summarize, if you need the SRV method you can do:

1. No auth - just needs server and params.
2. With auth - needs server, user, password, database name and params.

**Comment by ChenTanyi** [comment]
@berndverst It is not actual blocking issue, you can close it from your side.

I just found it inconsistent in the implementation of **server** parameter comparing with both **host** and its comment.
https://github.com/dapr/components-contrib/blob/4be795d812d48d455a7280f949f35fe50436a187/state/mongodb/mongodb.go#L62-L72

1. If it is used like **host**, it should support **database** for these two format.
2. If it acts as its comment said, it should not support **database** for these two format.

It is a little confused as sometime it support **database** and sometimes it doesn't, while **database** has nothing to do with authetication.

**Comment by berndverst** [comment]
As discussed offline, it is expected that username and password are always manually provided. This of course is not convenient.

I added an option to provide `connectionString` as a passthrough option in this PR https://github.com/dapr/components-contrib/pull/2659
