### ISSUE TITLE
GetDel support for Redis Bindings

### ISSUE THREAD

**Issue by Vishal07051999** [dapr/components-contrib#2661]
We have started using Dapr in our company and, we were trying to use it for one of our use case where we need GetDel of Redis.

Have created a implementation for the same : https://github.com/dapr/components-contrib/pull/2662

**Comment by berndverst** [comment]
Please do not start a PR immediately after creating an issue. It is best to first have some discussion as your PR (or the enhancement) might get rejected and get maintainers to voice their support on the issue.

Personally I do not see the value in `GetDel`. You can already use the `Get` operation and the `Del` operation. If necessary we can add ETAG support which we already have in other parts of Dapr.

Could you please share more about your use case in your company and why using `Get` and `Delete` operations today do not suffice?

**Comment by Vishal07051999** [comment]
GetDel help us in making keys one time retrival only even in case of consurrent program.

GetDel is a very frequesnt usecase when you need to create a Payment OTP or, Login OTP as it prevent concurrent calls from succeding as only one call gets data.

I agree using metadata with delete set as true will work and is better as it will simplify API surface area.

Will make a change in same PR.

Thanks for the suggestion.

**Comment by Vishal07051999** [comment]
Updated PR with all requested changes

**Comment by roozbehid-ic** [comment]
I am also upvoting this feature. I actually came here to check if this is supported or not. Atomicity of it, is what matters that cannot be done with two seperate API calls of GET and DEL

**Comment by berndverst** [comment]
@Vishal07051999 please assign the issue https://github.com/dapr/docs/issues/3258 to yourself to complete the documentation for your implementation.

**Comment by Vishal07051999** [comment]
Unable to assign or edit issue create.
