### ISSUE TITLE
state.sqlserver only finds database= in the connection string if it's lowercase

### ISSUE THREAD

**Issue by mattmorg55** [dapr/components-contrib#2677]
## Expected Behavior

Component would find the non-default database name using Database= or database= in the connection string.

## Actual Behavior

strings.Contains is case sensitive
```
if strings.Contains(m.store.connectionString, "database=") {
		// Schedule close of connection
		defer db.Close()
	}
	```

## Steps to Reproduce the Problem

1. Create existing database `sample`
2. Use connection string with `Database=sample`
3. A new dapr database will be created

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
Fixed by #2694
