### ISSUE TITLE
Enable the Azure Event hubs binding to be able to read/write from a single partition

### ISSUE THREAD

**Issue by msfussell** [dapr/components-contrib#268]
There are scenarios in Azure Events hubs where you need to read from a particular partition. Currently the EventHubs binding reads from all partitions and then forwards the message. 

This issue to update the binding here https://github.com/dapr/docs/blob/master/reference/specs/bindings/eventhubs.md to enable reads and write to a particular partition for an Event Hub instance.

**Comment by ksivamuthu** [comment]
@msfussell @yaron2  Can you please assign this to me, I'll work on this.

**Comment by yaron2** [comment]
Thanks!
