### ISSUE TITLE
How to create index on MongoDB state store component?

### ISSUE THREAD

**Issue by MargaretKrutikova** [dapr/components-contrib#2687]
We are transitioning from redis state store to MongoDb and we would like to know how to create indices on MongoDB. When using redis the process is extensively documented [here](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/#querying-json-objects-optional), but we can't seem to find anything related to indices in the docs on MongoDB [here](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-mongodb/). Is it possible to define indices the same way in `yaml` component spec for MongoDB or is it not supported yet?

Thanks!

**Comment by artursouza** [comment]
We will not invest more in query API for state store. It will be part of a future new API for document stores.
