### ISSUE TITLE
HTTP Output binding error message for status != 200

### ISSUE THREAD

**Issue by ManuDinicola** [dapr/components-contrib#2706]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here

Hello, 

we are using the http ouput binding  in our setup. Everything work well when httpstatuscode returning by the binding is 200. When it's an another code we lost the response message.

Exemple here are the message that we received from the output binding :

![image](https://user-images.githubusercontent.com/20815049/227452213-4416c250-0816-48bb-bd9f-36369ff8df13.png)

and here what the server really send:

![image](https://user-images.githubusercontent.com/20815049/227452528-f88a2f13-839c-4991-a188-020482624dad.png)

As you seen the message is lost somewhere. It's very annoying. 

Is there any options or it's a bug or it's intended ?

Thanks

**Comment by yaron2** [comment]
Transferred to correct repository.

Thanks for reporting @ManuDinicola

**Comment by wimvc1** [comment]
The sollution might not be that easy.
Check out this closed issue: https://github.com/dapr/components-contrib/issues/1675
The proposed solution there was this feature: https://github.com/dapr/dapr/issues/4549

**Comment by berndverst** [comment]
This is addressed in Dapr 1.10 here: https://github.com/dapr/components-contrib/pull/2321

See also https://github.com/dapr/components-contrib/issues/2758

In the HTTP output binding metadata you need to set `treatNon200AsError` to `false`.
