### ISSUE TITLE
Dapr return with empty result when using Hashicorp Vault

### ISSUE THREAD

**Issue by topolyai5** [dapr/components-contrib#2711]
## Expected Behavior

I'm using the Hashicorp Vault as vault management in EKS. I want to fetch the keys from the secret. I've followed this: https://docs.dapr.io/reference/components-reference/supported-secret-stores/hashicorp-vault/

## Actual Behavior

The `http://localhost:3500/v1.0/secrets/vault/mysecret` is returning with HTTP status 204.

## Steps to Reproduce the Problem

1. Install Hashicorp Vault in EKS (I didn't try in local K8S)
2. Create the secret: `kubectl -n vault exec -it hashicorp-vault-0 -- vault kv put -mount=secret/data mysecret newKey1=value1 key2=value2`
3. Port forwarding to the EKS pod where the vault is running (debug purposes)
4. run the dapr locally (debug purposes) `dapr run --app-id test-app --dapr-grpc-port 50001 --dapr-http-port 3500 --app-port 80`
5. GET for `http://localhost:3500/v1.0/secrets/vault/mysecret`
It will response will 204.

Vault init: `kubectl -n vault exec -it hashicorp-vault-0 -- vault secrets enable -path=secret/ kv`
DAPR config:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: http://localhost:8200 # Optional. Default: "https://127.0.0.1:8200"
    - name: vaultToken # Required if vaultTokenMountPath not provided. Token value.
      value : root-token 
    - name: vaultKVPrefix # Optional. Default: "dapr"
      value : "data"
    - name: vaultKVUsePrefix # Optional. default: "true"
      value: "false"
```

DAPR version: 1.9.6

## Release Note

RELEASE NOTE:

**Comment by topolyai5** [comment]
Additional info, I have checked the following URL from Postman and I got the result
https://github.com/dapr/components-contrib/blob/master/secretstores/hashicorp/vault/vault.go#L222
`http://localhost:8200/v1/secret/data//mysecret`
```
{
    "request_id": "9b01fc88-9274-6b53-6332-c9654f02a804",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 2764800,
    "data": {
        "key2": "value2",
        "newKey1": "value1"
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}
```

**Comment by Taction** [comment]
@topolyai5 Dapr currently supports the Vault [KV Secrets Engine version 2](https://developer.hashicorp.com/vault/docs/secrets/kv/kv-v2), which means you should set version when you init `vault secrets enable -version=2 secret`.As for your have already created a secret engine, you can run `kubectl -n vault exec -it hashicorp-vault-0 -- vault kv enable-versioning secret` to enable version 2([refer to here for more infomation](https://developer.hashicorp.com/vault/docs/commands/kv/enable-versioning)).

**Comment by topolyai5** [comment]
@Taction 
Thanks for your help, now it's working!
However I didn't find any information about what version is supported by the Dapr.

**Comment by yaron2** [comment]
@topolyai5 can you confirm again that things are working as expected? I'll then close. keeping open for now as there's chat about this on Discord.

**Comment by topolyai5** [comment]
Yes, I can. it's working as expected with the secret engine v2

**Comment by Taction** [comment]
Just FYI, The response returned by engine v1 and v2 versions are in different formats. That's why the secret is exist but gets an empty result for dapr.

**Comment by Taction** [comment]
> However I didn't find any information about what version is supported by the Dapr.

@topolyai5 Thanks for reporting this, I created a doc issue to track this and will fix the doc soon.

**Comment by ItalyPaleAle** [comment]
Closing as resolved
