### ISSUE TITLE
[azure openai] support chatgpt as binding

### ISSUE THREAD

**Issue by liu-song** [dapr/components-contrib#2716]
## Describe the feature

Using Azure's OpenAI service as an output binding for Dapr is an exciting prospect 

[GPT-4 is now available through Azure OpenAI Service](https://go.microsoft.com/fwlink/?linkid=2228136&clcid=0x409&culture=en-us&country=us)
https://azure.microsoft.com/en-us/products/cognitive-services/openai-service

**Comment by berndverst** [comment]
Unassigning this from milestones. Dapr maintainers are not working on this or considering it a priority.

If someone wants to contribute this in a PR, feel free.
