### ISSUE TITLE
Why Dapr Http Binding call is not returning response with body when http status is 400.

### ISSUE THREAD

**Issue by amit88265** [dapr/components-contrib#2758]
Scenario
When a microservice 1 is calling another microservice 2 using HTTP binding and MS2 is returning 400 with the body, but dapr is ignoring the body and returning a response with 500 status code.

How can I get the body returned by MS2?

**Comment by berndverst** [comment]
This was fixed in Dapr 1.10. You need to set the metadata property `errorIfNot2XX` to `false`.

Original PR here: https://github.com/dapr/components-contrib/pull/2321
