### ISSUE TITLE
Possible configuration problem in the pubsub rabbitmq component

### ISSUE THREAD

**Issue by arturotrenard** [dapr/components-contrib#2764]
## Expected Behavior

Hello guys I think there is a problem here if you want to change the configuration

## Actual Behavior

![image](https://user-images.githubusercontent.com/65082809/230823012-f8f99de5-e3c5-4301-8bb0-019484ef52d7.png)

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
@arturotrenard I am not sure I understand the issue. Could you help us understand please?

**Comment by ItalyPaleAle** [comment]
Thanks, we'll get this fixed

**Comment by berndverst** [comment]
Once Dapr 1.11 is out please try to reproduce this problem @arturotrenard. Hopefully the PR from @SpikeWong actually addressed the issue.

**Comment by berndverst** [comment]
@arturotrenard can you try out Dapr 1.11 RC5? https://github.com/dapr/dapr/releases/tag/v1.11.0-rc.5 to see if you can reproduce this?

**Comment by arturotrenard** [comment]
> @arturotrenard can you try out Dapr 1.11 RC5? https://github.com/dapr/dapr/releases/tag/v1.11.0-rc.5 to see if you can reproduce this?
Hi, sorry for the delay, but I don't know why I hadn't received the email. So I'll be doing tests and if I see something weird I'll write to you.
