### ISSUE TITLE
Redis Streams PubSub Message ordering

### ISSUE THREAD

**Issue by AndreasM009** [dapr/components-contrib#277]
In Redis Streams message are delivered in the order which they were created, as long as you have only one consumer within a group. Dapr fowards message to the Subscriber in a different order. After having a look at the code, dapr used goroutines to forward messages to the Subscriber asynchronously. The order cannot be guaranteed anymore. Is this done on purpose?

**Comment by jdgomeza** [comment]
In case somebody else is facing the same issue, you can set the `concurrency` metadata to 1 to get the messages in the correct order when you run a single app instance.

https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/#spec-metadata-fields
