### ISSUE TITLE
Master doesn't compile

### ISSUE THREAD

**Issue by arturotrenard** [dapr/components-contrib#2779]
Hello good, query I am generating a v2 of a component. And I'm cloning master from the component repo and master from the dapr repo and it doesn't compile. Do I have to download a specific branch to work?

![image](https://user-images.githubusercontent.com/65082809/231891607-0196cc2f-6e41-4b6e-8af5-a01fcc6b2d0b.png)

**Comment by ItalyPaleAle** [comment]
Yes, this is expected at the moment sadly. We are waiting for runtime maintainers to merge this PR: https://github.com/dapr/dapr/pull/6186

In the meanwhile, you can clone the code from my PR above and build from that, and it should work.

**Comment by arturotrenard** [comment]
thanks
