### ISSUE TITLE
RabbitMQ Pub/Sub: Add option to override queue name via subscription request metadata

### ISSUE THREAD

**Issue by Jack97** [dapr/components-contrib#2791]
## Describe the feature

Currently the queue name is generated from the `ConsumerID` and the `Topic`:

```golang
queueName := fmt.Sprintf("%s-%s", r.metadata.ConsumerID, req.Topic)
```

Consider the following example:

```golang
service := daprd.NewService(":80")

if err := service.AddTopicEventHandler(
	&common.Subscription{
		Topic:      "topic",
		Route:      "/a",
		PubsubName: "pubsub",
		Metadata: map[string]string{
			"routingKey": "a",
		},
	},
	handlerA,
); err != nil {
	return err
}

if err := service.AddTopicEventHandler(
	&common.Subscription{
		Topic:      "topic",
		Route:      "/b",
		PubsubName: "pubsub",
		Metadata: map[string]string{
			"routingKey": "b",
		},
	},
	handlerB,
); err != nil {
	return err
}

if err := service.Start(); err != nil {
	return err
}
```

With the above configuration, Dapr will declare an exchange named `topic`, and a single queue named `consumerID-notifications`. Finally, it will bind the `a` and `b` routing keys to the queue.

This is problematic, as the queue will contain both `a` and `b` messages. For each `a` message, I'm expecting to receive 100,000 `b` messages. I need to process the `a` messages very quickly, but the throughput will be greatly affected by the number of `b` messages in the queue.

As far as I'm aware, there are two existing ways to ensure two queues are declared:

1. Register two pubsub components that define unique consumer IDs, rather than depending on the app ID.
2. Separate out the event handlers into two services.

The issues with the above are:

1. I'd rather not define multiple pubsub components that are virtually the same, there are maintenance implications for doing so.
2. Separating out the event handlers into separate services complicates my deployment process.

I'd like to be able to override the queue name when setting up the subscription. It should be possible to do this by updating the [existing queue name generation logic](https://github.com/dapr/components-contrib/blob/0221ad7edff3f33cb28fa6c7e6d8dcaee44bd5fb/pubsub/rabbitmq/rabbitmq.go#L315) to something like:

```golang
queueName := req.Metadata[metadataQueueName]
if queueName == "" {
	queueName = fmt.Sprintf("%s-%s", r.metadata.ConsumerID, req.Topic)
}
```

## Release Note

RELEASE NOTE: **ADD** Option to override RabbitMQ queue name via subscription request metadata.

**Comment by Jack97** [comment]
If there's any appetite for this change, I'd be more than happy to open a merge request.

**Comment by berndverst** [comment]
Feel free to make a PR. Note that this will not make it into Dapr 1.11. So this change wouldn't be released for another 12 weeks or so.
