### ISSUE TITLE
Is it possible to define multiple scopes for a single `bindings.azure.eventgrid` component

### ISSUE THREAD

**Issue by joshwright10** [dapr/components-contrib#2797]
We have an application which needs to connect to multiple Azure Event Grid Topics using the `bindings.azure.eventgrid` component. These can all be accessed using the same `azureTenantId`, `azureClientId`, `azureClientSecret` in theory the same `subscriberEndpoint`.

However, as they have different `scope` values, it seems that we need separate Dapr components for each one of these bindings.
Is it possible to setup multiple Event Grid topic subscriptions using a single component?

**Comment by berndverst** [comment]
Not possible today. This could be considered in a future Dapr release (after 1.11)
