### ISSUE TITLE
Breaking changes in `bindings.azure.eventgrid` from Dapr 1.9.x to 1.10.5

### ISSUE THREAD

**Issue by joshwright10** [dapr/components-contrib#2813]
### Issue 1 - Sidecar listener address changed
Dapr `bindings.azure.eventgrid` component should listen on the `handshakePort` number on the path `/api/events` 

This is what we see in the logs of Dapr 1.9.0

> level=debug msg="About to start listening for Event Grid events at http://localhost:9000/api/events" app_id=myapp instance=myapp-78b65f4bb4-x757d scope=dapr.contrib type=log ver=1.9.0

### Issue 2 - Parameter Changes
Dapr `bindings.azure.eventgrid` component parameters changed name after upgrade to 1.10.5.
Expected: `tenantId`, `subscriptionId`, `clientId`, `clientSecret`.

Webhook validation handshake failed for https://dev.mycompany.com/myapp/mycomponentname/api/events. Http OPTIONS request failed with response code Unauthorized.

### Issue 1 - Sidecar listener address changed
The sidecar listener address has now changed from the route `/api/events` path, to the path taken from the `subscriberEndpoint` parameter. I would have at most expected this to just be the dapr component name, not the `subscriberEndpoint` value. Either way, these changes require updates elsewhere. In our case, we have to re-point our nginx rule.

> level=info msg="Listening for Event Grid events at http://localhost:9000/mycomponentname/api/events" app_id=myapp component="mycomponentname (bindings.azure.eventgrid/v1)" instance=myapp-7d885ddb5f-27m
jc scope=dapr.contrib type=log ver=1.10.5

As this changes the listening path, the WebHook destination fails to validate and never sets up the subscription in Azure.

### Issue 2  - Parameter Changes
Dapr `bindings.azure.eventgrid` component parameters changed now require:
Expected `azureTenantId`, `azureSubscriptionId`, `azureClientId`, `azureClientSecret`

Looking at the comments in the code, there were supposed to be aliases to allow both the old and the new parameters to work. This doesn't seem to have been implemented though.

## Steps to Reproduce the Problem

- Upgrade Dapr to 1.10.5
- Use the `bindings.azure.eventgrid` component

**Comment by ItalyPaleAle** [comment]
Hi @joshwright10 In Dapr 1.10 we had to make some breaking changes to this component due to a security vulnerability that was discovered in the component (in short, in 1.9 Dapr did not authenticate calls incoming into the endpoint for Event Grid, so anyone could have sent messages to the app - in 1.10, we validate the incoming calls using Azure AD).

We don't like making breaking changes, but these were necessary this time. Additionally please note that with beta components, like this one, breaking changes are possible, albeit rare.

## Regarding issue 1

`subscriberEndpoint` can be:

- A full URL including a path, such as `https://example.com/some/path`
  - In this case, the full path is used as-is
- A URL without path, for example `https://example.com/`
  - In this case, we append `/api/events` at the end automatically

This was done for backwards-compatibility reasons.

If you need to rewrite the URL in your proxy, make sure that you set `subscriberEndpoint` to the external URL there (e.g. `https://example.com/some/path`). We match the path, although we don't match the hostname.

## Regarding issue 2

I believe we tested with `clientId` and similar "legacy" metadata options and they should work for both the input and output binding. We use the same code as the rest of Dapr that supports aliases:

https://github.com/dapr/components-contrib/blob/a2ebc41daf03c6d76038942db0b84136d46b69b2/bindings/azure/eventgrid/eventgrid.go#324

Can you please check again, and post the exact error you see?

**Comment by berndverst** [comment]
It seems `clientSecret` at least did indeed change. I'll update this. We are finalizing a 1.10.6 hotfix (and soon the 1.11 release) so I will try to get it included there.

> Expected: tenantId, subscriptionId, clientId, clientSecret

https://github.com/dapr/components-contrib/blob/a0041cd51767d07bf194d903e7cb9d03e0b15e55/bindings/azure/eventgrid/eventgrid.go#L292-L304

and

https://github.com/dapr/components-contrib/blob/a0041cd51767d07bf194d903e7cb9d03e0b15e55/bindings/azure/eventgrid/eventgrid.go#L318-L324

**Comment by joshwright10** [comment]
Thank you for explaining @ItalyPaleAle, and yes, I understand that this is a beta component. I was just struggling to find anywhere where these changes were explained. I couldn't see anything in the release notes. 

### Regarding Issue 1
---
Our Event Grid Subscriber is an API inside Kubernetes, which has an Nginx ingress, and is only accessible via another front end gateway. 

This means that our `subscriberEndpoint` looks like `https://mywebgateway.com/dapr-eventgrid/myapplication/api/events`
1. `https://mywebgateway.com` hits the front end gateway.
2. This passes traffic onto Nginx, which uses path based routing to get to the application.
3. Nginx used to simply direct traffic to `/api/events` on the `handshakePort` and all was good.

Now that the path from `subscriberEndpoint` is being used at the Dapr level, do we have to make sure that `/dapr-eventgrid/myapplication/api/events` is an available method within the API? 

If we move this application to another Kubernetes cluster in another environment, we may not have the same path on the web gateway, and would therefore need to update the application to also have a method for that path. If this behaviour is how I have interpreted it, I'm not sure that it works well for our scenario. It would be better to have the dapr sidecar simply listen on `/api/events` like before, or allow for a custom path to be defined.

### Regarding Issue 2
@berndverst I just reused the same component and received the following in the Dapr logs:

> time="2023-04-27T13:02:28.302825346Z" level=error msg="error reading from input binding mycomponentname: failed to create or update event subscription: GET https://management.azure.com:443/subscriptions/6e664a87-16cb-4062-9360-785a2fb126d5/providers/Microsoft.Eve
ntGrid/locations/uksouth/operationsStatus/A3E47210-B344-4BBF-9B59-ED7C4F90F127\n--------------------------------------------------------------------------------\nRESPONSE 200: 200 OK\nERROR CODE: Url validation\n-----------------------------------------------------------
---------------------\n{\n  \"id\": \"https://management.azure.com/subscriptions/6e664a87-16cb-4062-9360-785a2fb126d5/providers/Microsoft.EventGrid/locations/uksouth/operationsStatus/A3E47210-B344-4BBF-9B59-ED7C4F90F127?api-version=2022-06-15\",\n  \"name\": \"a3e47210-b
344-4bbf-9b59-ed7c4f90f127\",\n  \"status\": \"Failed\",\n  \"error\": {\n    \"code\": \"Url validation\",\n    \"message\": \"Webhook validation handshake failed for https://mywebgateway.com/dapr-eventgrid/myapplication/api/events. Http OPTIONS request failed with response code Unauthorized. For troublehooting, visit https://aka.ms/esvalidationcloudevent. Activity id:20e51ac7-8807-47dc-8ddb-91a1d0a76f05, timestamp: 4/27/2023 1:02:20 PM (UTC).\"\n  }\n}\n----------------------------
----------------------------------------------------\n" app_id=myapp instance=myapp-85d569c96f-rdgcj scope=dapr.runtime type=log ver=1.10.5

Maybe this is not related to the parameter change, and is just something else...

**Comment by berndverst** [comment]
Generally we only make changes on the 1.X.0 releases - so you should always look at the release notes for say 1.10.0 and soon 1.11.0.

Here are the 1.10.0 release notes: https://github.com/dapr/dapr/releases/tag/v1.10.0

Regarding Issue 2:
Everything looks good -- You are getting a HTTP 200 -- but the **Unauthorized** error you are seeing is actually Azure trying to reach `https://mywebgateway.com/dapr-eventgrid/myapplication/api/events` (your own app endpoint) via a HTTP OPTIONS request.

So Issue 2 is actually just Issue 1!

Regarding Issue 1
Based on the error we are seeing here yes, you need to make sure `/dapr-eventgrid/myapplication/api/events` is an available method within your API.

**Comment by joshwright10** [comment]
Understood, thank you @berndverst!
