### ISSUE TITLE
Rabbitmq Pub/Sub: Quorum queues

### ISSUE THREAD

**Issue by aaguilartablada** [dapr/components-contrib#2814]
From RabbitMQ 3.8.0 we have the possibility to create quorum queues instead classic: [https://www.rabbitmq.com/quorum-queues.html](https://www.rabbitmq.com/quorum-queues.html)

It is the recommended type when deploying a RabbitMQ cluster, as it provides fault tolerance. The proposal is allowing Dapr user to tell Subscription to create a quroum queue if desired through metadata.

**Comment by berndverst** [comment]
Duplicate of https://github.com/dapr/components-contrib/issues/2544

**Comment by berndverst** [comment]
Thanks for the request here. Please move the discussion of this feature to #2544. And update your PR to refer to this issue please :)
