### ISSUE TITLE
ElasticSearch state store

### ISSUE THREAD

**Issue by abgc195** [dapr/components-contrib#2826]
## Describe the feature

May we please have elasticsearch as a state store?

I already have a use case in which I'm using elasticsearch for storing some application data for fast access and am not looking to have other tools like redis for that.
## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
State Store is a simple Key Value Store and does not supporting querying, retrieving data by anything but the primary key etc.

Are you sure this would be sufficient for your use case?

If not a binding will make more sense here - or you can wait for the future document store building block - but we have no timeline for that building block right now. At the moment this would be 6 months away or more.

**Comment by abgc195** [comment]
Ok. So there's no need to go with state store and make it generic?

**Comment by berndverst** [comment]
@abgc195 yes the downside with bindings is however is that they are not replaceable with other bindings -- there is only an fairly artificial general API, but each request is completely differently formatted in payload etc -- That's the downside of bindings.

**Comment by gedw99** [comment]
Zinc 

https://github.com/zincsearch/zincsearch

it’s golang 
It’s elastic compliant 
Store is very easy 
No IVM

this would be an excellent search state store for DAPR me thinks.

Aloe with pub sub . You can use a db and then when a record changes you can update zinc .

dapr has no CDC yet , maybe ever, so you have to construct custom code to do this workflow integration I guess

**Comment by gedw99** [comment]
Also https://docs.dapr.io/reference/components-reference/supported-state-stores/ has dbs and kv as state stores so I don’t u derarand why zinc or other search data stores can’t be part of iDAPR state stores

**Comment by abgc195** [comment]
Sorry, it looks like I completely misrepresented myself there by putting in the **not**. However, I've managed to implement my need as a **[pluggable component](https://docs.dapr.io/developing-applications/develop-components/pluggable-components/pluggable-components-overview/)** and it's working great. I got inspiration from [Creating a Dapr pluggable component for Supabase | Diagrid](https://www.diagrid.io/blog/dapr-supabase-component)
