### ISSUE TITLE
Pubsub - AWS SNS/SQS extra configuration possibilities

### ISSUE THREAD

**Issue by wimvc1** [dapr/components-contrib#2853]
This is regarding the AWS SNS/SQS pubsub component.
See current docs: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-aws-snssqs/

For starters, the component works as expected.  In our organisation we are using the `disableEntityManagement = true` because this allows us to control the IAM policy in finegrained way.
However the component decides the SNS and SQS name:
SQS resource name = consumer app-id
SNS resource name = the actual topic name

Unfortunately this clashes with our company guidelines regarding AWS naming conventions. 

## Describe the feature

My proposal (based on our own issues):

- Add a new (optional) configuration option: `sqsQueueNamePrefix`
   - This will allow the component to create (and reference) the queue with following name: {{sqsQueueNamePrefix}}-{{app_id}}
- Add a new (optional) configuration option: `snsTopicNamePrefix`
   - This will allow the component to create (and reference) the topic with following name: {{snsTopicNamePrefix}}-{{topic_name}}

This would allow:
- The developer to still use his/her desired topic names in their code
- The devops to follow his/her companies naming guidelines

Potential issues:
- This doesn't allow a suffix
- Might introduce some extra "complexity" regarding "Conforming with AWS specifications"

## Release Note

**ADD** New configuration options in AWS SNS/SQS pubsub component to allow better control over the AWS resource names

**Comment by wimvc1** [comment]
> @wimvc1 it seems like a good idea. But I do think it might make the [Subscription CRD ](https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#declarative-subscriptions) hard to build or maintain, making it more error prone if using the aforementioned prefixes, because in that file you'd need to specify a topic and optionally scopes with prefixes you're suggesting. A possible solution, but not too elegant, as I see it, is to have your enhancement but with an additional enhancement to the Subscription CRD to have an optional prefixes configuration within

Thanks for your feedback.
We are using the "_programmatic_" approach for subscribing to topics so I did indeed miss the "_declarative_" way.

To make the proposed changes clear: the prefixes only apply to the infrastructure. Inside the the application code, the developer uses the topic name he/she desires. 
I would suspect that the [Subscription CRD](https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#declarative-subscriptions) doesn't directly interact with the infrastructure layer created which was defined in the pubsub component?

**Comment by amimimor** [comment]
> I would suspect that the [Subscription CRD](https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#declarative-subscriptions) doesn't directly interact with the infrastructure layer which was defined in the pubsub component?

Sorry I didn't understand this part the above.
Also, you wrote "inside the application code" which I did understand that it would work out fine incase you introduced prefixes to the component definition as you can dynamically subscribe at runtime. 

Here are my two cents about this:
### Subscription:

Regarding the subscription CRD: the runtime (daprd) parses out that yaml if present, and calls the relevant pubsub component to `Subscribe` to the "topic" (subscriber actually polls SQS queue, not SNS topic) and internally maps the subscription to a downstream application handler endpoint to pass messages to when they arrive. 
This happens regardless of infra being provisioned or not (`disableEntityManagement` true/false).
That goes to say that the subscription CRD use case needs to be taken into consideration if you plan to template the SQS queue names using prefixes. 

### Publish:
On the other hand, if you provision everything yourself, publishing to a given named (SNS) topic is not defined anywhere and you can request to publish to a booted pubsub component with any topic name as long as it exists on the first request to publish, so in the publisher scenario you can do prefix mangling as long as your publisher app is configured with the same prefix as the suggested component.

**Comment by wimvc1** [comment]
> > I would suspect that the [Subscription CRD](https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#declarative-subscriptions) doesn't directly interact with the infrastructure layer which was defined in the pubsub component?
> 
> Here are my two cents about this:
> 
> ### Subscription:
> Regarding the subscription CRD: the runtime (daprd) parses out that yaml if present, and calls the relevant pubsub component to `Subscribe` to the "topic" (subscriber actually polls SQS queue, not SNS topic) and internally maps the subscription to a downstream application handler endpoint to pass messages to when they arrive. This happens regardless of infra being provisioned or not (`disableEntityManagement` true/false). If there is a CRD and `disableEntityManagement` is `false` then the component would indeed try to provision the SNS topic, SQS queue and their related subscription between one another. That goes to say that the subscription CRD use case needs to be taken into consideration if you plan to template the SQS queue names using prefixes.
> 
> ### Publish:
> On the other hand, if you provision everything yourself, just publishing to a given named (SNS) topic is not defined anywhere (unless there is a subscription CRD or dynamic subscription) and you can request to publish to a booted pubsub component with any topic name as long as it exists on the first request to publish, so in the publisher scenario you can do prefix mangling as long as your publisher app is configured with the same prefix as the suggested component.

Thanks for the clarification.  This leads me to believe that this proposal is feasible  without modyfing the subscription CRD implementation.

To be more precise: When checking the implementation file of SNS/SQS pubsub: https://github.com/dapr/components-contrib/blob/master/pubsub/aws/snssqs/snssqs.go
We modify the function `getOrCreateTopic` : here we will make sure that the sanitizedName starts with the prefix (when present) we defined in the component.yaml. This will make sure that the `topicArn` points to the correct SNS (regardless of disableEntityManagement true/false).

We do the same for `getOrCreateQueue` so that `queueInfo` contains the correct ARN to the queue (regardless of disableEntityManagement true/false).

These methods are used in `Subscribe` & `Publish`. So I was under the assumption that the subscription CRD actually calls the `Subscribe` method (and thus will call the correct AWS resource). But this assumption is inccorect?

**Comment by gcaracuel** [comment]
Hey!
I am interested in this issue, I think many other may face this same issue too, Could this be reopened?
