### ISSUE TITLE
Dapr support for MariaDB

### ISSUE THREAD

**Issue by dpaardenkooper** [dapr/components-contrib#2861]
Hi all,

I was just wondering if MariaDB support is coming into the supported-state-stores.
https://docs.dapr.io/reference/components-reference/supported-state-stores/

Want to use the combination together with Azure Container Apps.

Kind regards,
Dinant Paardenkooper

**Comment by berndverst** [comment]
The MySQL component supports MariaDB. This is just a documentation issue.

**Comment by ItalyPaleAle** [comment]
Fixed by https://github.com/dapr/docs/pull/3463
