### ISSUE TITLE
Templating for the DNS name resolution component

### ISSUE THREAD

**Issue by MaxSchaefer** [dapr/components-contrib#2867]
## The problem
> All nameresolution components in Dapr are resolving the app-id in their own fashion. For example, the dns component is resolving the app-id my-app to my-app-dapr.my-namespace.svc:80. A namespace and the cluster-domain of .svc is required and not configurable. [On Fly.io, our cluster-domain is .internal](https://fly.io/docs/reference/private-networking/#fly-internal-addresses). ...
https://github.com/helpwave/services/issues/164

## Describe the feature
The schema of the [DNS name resolution component](https://github.com/dapr/components-contrib/tree/master/nameresolution/dns) should be configurable. The configuration key is optional and could be called `schema_template` with a possible value of `#app_id#.internal:#port#`. In that case, `#app_id#` and `#port#` are replaced during [`ResolveID()`](https://github.com/dapr/components-contrib/blob/master/nameresolution/dns/dns.go#L39). When the configuration is not set, we should fall back to the current schema of `#app_id#-dapr.#namespace#.svc:#port#` to be backward compatible.

If discussed, I would implement this change directly.

Another solution would be to develop a new name resolution component just for templating.

## Release Note
RELEASE NOTE: **ADD** templating to the DNS name resolution component

**Comment by MaxSchaefer** [comment]
I've realized that the DNS name resolution component is not already registered in [daprd](https://github.com/dapr/dapr/tree/master/cmd/daprd/components). Is there any reason for this? The DNS name resolution component [mentions an `orchestrator`](https://github.com/dapr/components-contrib/blob/1ac92a886a7c8534a9e07c5415c84f41297aa945/nameresolution/dns/dns.go#L37). What is this orchestrator?

**Comment by MaxSchaefer** [comment]
Sounds great! I wrote the proposal/documentation with a possible implementation in mind. I have decided to use [`text/template`](https://pkg.go.dev/text/template) of go stdlib. With this approach, we can also take `ResolveRequest.Data`into account. The template should get parsed during `.Init()`.
What do you think @ItalyPaleAle about this approach?

---

__Proposal for templating inside the DNS name resolution component__
(can directly be used in the documentation as well)
## Behaviour

On `.Init()` the DNS component will parse the provided template string via [`text/template`](https://pkg.go.dev/text/template) and will cache these for further executions when an address resolution gets requested via `.ResolveID()`.
The template gets populate on a resolve request with the passed [`ResolveRequest` struct](https://github.com/dapr/components-contrib/blob/1ac92a886a7c8534a9e07c5415c84f41297aa945/nameresolution/requests.go#L20).
The [`Data map[string]string`](https://github.com/dapr/components-contrib/blob/1ac92a886a7c8534a9e07c5415c84f41297aa945/nameresolution/requests.go#L24) part of the struct can also be used inside the template.
A successful resolve request will return a populated address string of the template to the caller.

### Examples

| Template                                                   | [`ResolveRequest` struct](https://github.com/dapr/components-contrib/blob/1ac92a886a7c8534a9e07c5415c84f41297aa945/nameresolution/requests.go#L20) | Populated address           |
|------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------|
| {{.ID}}-dapr.{{.Namespace}}.svc:{{.Port}}                  | ```{ ID: "my-id", Namespace: "abc", Port: 1234, Data: {} }```                                                                                      | my-id-dapr.abc.svc:1234     |
| {{.ID}}-{{.Namespace}}.{{.Data.Region}}.internal:{{.Port}} | ```{ ID: "my-id", Namespace: "abc", Port: 1234, Data: { Region: "land" } }```                                                                      | my-id-ns.land.internal:1234 |


## Spec configuration fields

| Field                | Required |                                                                                                                Type | Details                                                                                                                                                   | Examples |
|----------------------|:--------:|------------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------|----------|
| template             | N        | `string` | The template that gets parsed and executed by [`text/template`](https://pkg.go.dev/text/template). Default to `{{.ID}}-dapr.{{.Namespace}}.svc:{{.Port}}` | `{{.ID}}-{{.Namespace}}.internal:{{.Port}}`

**Comment by MaxSchaefer** [comment]
> If the user doesn't pass a template, can we continue using the current code path?

Yes, we should do this. Do we talk about modifying the Kubernetes or DNS name resolution component? I am still not sure why the DNS component is not part of https://github.com/dapr/dapr or where the component is currently in use. Can someone elaborate on this?

**Comment by ItalyPaleAle** [comment]
The component you want to change is the Kubernetes one.
