### ISSUE TITLE
pub/sub with rabbitMQ got some error

### ISSUE THREAD

**Issue by Hsuwen** [dapr/components-contrib#2868]
### I use pub/sub with rabbitMQ-3.11 in dapr 1.10.
<img src="https://resource01-cn.cdn.yiofong.com/components.png" />

### When I update my program by ```kubectl replace -f xxx.yaml```,  the program can't running
<img src="https://resource01-cn.cdn.yiofong.com/logs.png" />
<img src="https://resource01-cn.cdn.yiofong.com/not%20ready.png" />

### I checked dapr and rabbitMQ, everything is normal.
<img src="https://resource01-cn.cdn.yiofong.com/dapr-status.png" />
<img src="https://resource01-cn.cdn.yiofong.com/rabbit.png" />

**Comment by Hsuwen** [comment]
This exception does not necessarily appear in a specific application or in applications that contain certain subscriptions.
Even in applications with multiple replicas, some replicas can start normally, while others cannot.

**Comment by Hsuwen** [comment]
There is no network restriction issue here. This is in the local area network, within the VPC, all inbound and outbound connections are open.

**Comment by Hsuwen** [comment]
When such errors occur, they can be solved temporarily by restarting rabbitMQ.

**Comment by berndverst** [comment]
The error comes from here:

https://github.com/dapr/components-contrib/blob/7ce4e4971a35bbb63c1d1cb3ff88feec1f24ecaa/pubsub/rabbitmq/rabbitmq.go#L336-L342

No idea whether this help, but this PR that was opened last week against the 1.11 release made a change to something that seems related: https://github.com/dapr/components-contrib/pull/2836

@SpikeWong do you have any idea here?

**Comment by SpikeWong** [comment]
but this user is using the version of 1.10

**Comment by SpikeWong** [comment]
I think this is related to this issue https://stackoverflow.com/questions/62792713/how-to-set-x-dead-letter-exchange-in-rabbit
> inequivalent arg 'x-dead-letter-exchange' for queue 'igSmev3-ListenerQueue' in vhost '/': received none but current is the value 'igSmev3Dlx' of type 'longstr'
That means that you have a igSmev3-ListenerQueue queue on the broker already and it is without an 'x-dead-letter-exchange' argument. Probably you have created it before with that state.
Consider to remove this queue before starting your application with already DLX provided.

**Comment by Hsuwen** [comment]
> @Hsuwen can you try out Dapr 1.10.7 to see if this occurs? Or better yet, Dapr `1.11.0-rc.5` ? There were rabbitMQ related changes in Dapr 1.11 and they might help you, so you could try this release candidate? We are planning to release Dapr 1.11 in one week.

Ok, I will follow the new version, thanks.

**Comment by SpikeWong** [comment]
![image](https://github.com/dapr/components-contrib/assets/39330606/b90cf034-6197-4dd3-8c5c-ff4c1b985d09)
@Hsuwen I think you can follow this issue https://stackoverflow.com/questions/62792713/how-to-set-x-dead-letter-exchange-in-rabbit to find out the root cause, maybe your metadata configuration has changed

**Comment by Hsuwen** [comment]
> I think this is related to this issue https://stackoverflow.com/questions/62792713/how-to-set-x-dead-letter-exchange-in-rabbit
> 
> > inequivalent arg 'x-dead-letter-exchange' for queue 'igSmev3-ListenerQueue' in vhost '/': received none but current is the value 'igSmev3Dlx' of type 'longstr'
> > That means that you have a igSmev3-ListenerQueue queue on the broker already and it is without an 'x-dead-letter-exchange' argument. Probably you have created it before with that state.
> > Consider to remove this queue before starting your application with already DLX provided.

Before asking this question, I also searched for such a description. I also tried deleting the exchange and queue that were logged, and the pod still failed to start and also reported an error. The puzzling thing is that I have not manually changed MQ before this, I have only restarted MQ and my application.
What's even more amazing is that because it can't be solved, I put the pod that can't start normally until the next day, and it actually is running, however, I didn't operate anything.

**Comment by SpikeWong** [comment]
@Hsuwen If your are still facing the same problem after upgrading, could you please provide your existing queue configuration and pubsub rabbitmq metadata
