### ISSUE TITLE
new component - Ably Output Binding

### ISSUE THREAD

**Issue by amimimor** [dapr/components-contrib#2872]
## Describe the proposal
I'd like to create a new Output Binding component that uses the [Ably](https://ably.com) platform for pushing and broadcasting messages using Ably's publish API, mostly for use cases where backend to frontend communication is needed.

I'm not affiliated with Ably whatsoever.

If we do move forward with this, I would contact Ably to provide us with API keys for conformance and certification tests which I'm sure they would comply with.

**Comment by berndverst** [comment]
Given that we have become a lot more conscious of the size of the Dapr binary we can likely only consider adding built-in components which will be utilized by a lot of users - and over time that too may change.

At this time this component should be developed as a pluggable component. See https://docs.dapr.io/developing-applications/develop-components/pluggable-components/

If a lot of users upvote this issue we can certainly revisit that conversation.

**Comment by artursouza** [comment]
Can the component use Rest or gRPC service invocation instead of an SDK?

**Comment by amimimor** [comment]
> Can the component use Rest or gRPC API instead of a client SDK?

Yes it can but since we are using our own Python Dapr HTTP-based SDK I see no real advantage to using Dapr with a pluggable component as I can implement the output binding API in a custom service (I see no difference to that compared with a pluggable component) and call it directly from our SDK (with just using a none-daprd port) as if Dapr is serving those calls and effectively passing them to a pluggable component (and saving another network hop). 
Thanks for your responses.
