### ISSUE TITLE
Support nested partition keys in cosmosdb binding

### ISSUE THREAD

**Issue by programaka** [dapr/components-contrib#288]
Cosmosdb allows you to enter a nested partition key when creating a container (collection) in the portal.

For example: /headers/salesNumber
`{
    "headers": {
        "salesNumber": "ZCW666"
    }
}`

With Dapr you can only pass a top level property as a partition key.

## Proposal
Support nested partition keys.
Mention in the documentation whether nested partition keys are supported or not.

## Dapr version
v0.5.0

**Comment by yaron2** [comment]
Thanks, that makes sense.

**Comment by ksivamuthu** [comment]
@yaron2 @youngbupark Can you please assign this to me, if it is free to take up? Thanks.

**Comment by youngbupark** [comment]
> @yaron2 @youngbupark Can you please assign this to me, if it is free to take up? Thanks.

Thanks in advance. This is yours :)
