### ISSUE TITLE
IAM auth for kafka binding

### ISSUE THREAD

**Issue by cciobanu98** [dapr/components-contrib#2882]
AWS supports IAM access for msk. From my research, I found that dapr doesn't support this auth.  

From my understanding dapr it's using sarama library to connect to the kafka. And sarama also have an issue related to this feature request (https://github.com/Shopify/sarama/issues/1985) 

In the thread there it's a suggestion to use kafka-go instead of sarama. 

Can this mechanism of auth be achievable?

**Comment by cciobanu98** [comment]
sarama have a PR open to allow implementing custom connection scenario (https://github.com/Shopify/sarama/pull/2482) it will be possible to implement in this case IAM MSK auth in dapr ?

**Comment by joaocc** [comment]
Hi. Any news on the ability to connect via IAM to a MSK on DAPR? IAM is one of the big advantages when using MSK. Thanks

**Comment by joaocc** [comment]
Thanks. @cciobanu98 are there any plans to incorporate this into DAPR, now that the library is fixed?
