### ISSUE TITLE
Support sessions when subscribing to Azure Service Bus Topic

### ISSUE THREAD

**Issue by espenaolsen** [dapr/components-contrib#289]
## In what area(s)?

/area runtime

## Describe the feature
Support the use of sessions when subscribing to an Azure Service Bus Topic

**Comment by jjcollinge** [comment]
Now that custom routes #1518 have been added I'll be able to look into adding support for sessions

**Comment by berndverst** [comment]
https://github.com/dapr/components-contrib/issues/1531
https://github.com/dapr/components-contrib/issues/1532

**Comment by yaron2** [comment]
@ItalyPaleAle do you have insights about session support with the new SDKs?

**Comment by brettveenstra** [comment]
Support for Sessions (with its FIFO behavior) would be very helpful

**Comment by berndverst** [comment]
Sample:

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/example_session_receiver_test.go

We already support attaching session IDs to pubsub messages on publish via the Dapr Request Metadata `SessionId`.

What remains is reading a list of session IDs to which to subscribe via the Subscription Metadata. For each of these a separate session receiver client must be instantiated.

**Comment by KrzysztofPajak** [comment]
It would be great if we get information about any estimated time when will be ready?

**Comment by berndverst** [comment]
With the 1.10 release in February.

**Comment by berndverst** [comment]
This feature is much more complex than I expected and I am not sure I can focus on this. I do not know Azure Service Bus particularly well, and certainly don't know what session feature is used for / how it is used.

**Comment by berndverst** [comment]
Can someone clearly explain what is needed and why? Please include all context, especially for someone who doesn't know anything about Azure Service Bus.

**Comment by berndverst** [comment]
@jjcollinge maybe you can complete this or at least offer an explanation here for someone without any background in Azure Service Bus.

**Comment by brettveenstra** [comment]
perhaps @artursouza or someone from his team could lend some direction on implementation?

the use case I'm interested in is sequenced delivery of messages to subscribers of a session id - in particular, this provides a Fan-In processing pattern

**Comment by berndverst** [comment]
@brettveenstra I am on his team. There is nobody who knows about this functionality.

**Comment by brettveenstra** [comment]
apologies @berndverst 

looking for this functionality: https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-sessions

here's a .NET SDK example: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample03_SendReceiveSessions.md

the implementation would be written for Dapr in GO correct?  that's new to me

**Comment by berndverst** [comment]
> apologies @berndverst
> 
> looking for this functionality: https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-sessions
> 
> here's a .NET SDK example: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample03_SendReceiveSessions.md
> 
> the implementation would be written for Dapr in GO correct? that's new to me

I found a Go sample too, but I don't understand what we are trying to do, how.. and what the nuances are.

I think you need to explicitly declare the sesssion IDs you want to subscribe to, would that make sense?

Maybe we can expose it like so (using programmatic subscriptions)

```json
[
  {
    "pubsubname": "pubsub",
    "topic": "newOrder",
    "route": "/orders",
    "metadata": {
      "sessionIDs": "abc123,def456,ghj789", // a comma-separate list of session IDs
    }
  },
  {
    "pubsubname": "pubsub",
    "topic": "newCustomers",
    "route": "/customers",
    "metadata": {
      "sessionIDs": "zxc123,cvb456,vbn789", // a comma-separate list of session IDs
    }
  }
]
```

**Comment by yaron2** [comment]
cc @jjcollinge

**Comment by brettveenstra** [comment]
From what I've seen with Azure's Service Bus implementation each Subscriber of a Service Bus Topic is able to require sessions independently, but once the Subscriber is setup, all messages must either supply session id or not

The .NET SDK session-aware listeners seem to include timeout behavior so that when no messages appear for a current session, it closes the connection, queries the Subscription for a list of outstanding sessions that need a listener, picks one, and starts processing messages (or at least that's the behaviors I've experienced).  Would Dapr cron binding help there?

**Comment by berndverst** [comment]
This code sample here is probably relevant: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/example_session_roundrobin_test.go

It seems it can somehow figure available sessions for a given topic.

But how many sessions should it try to read from at a given time? Reading from all sessions might starve the sidecar for resources.

And I suppose there should be some sort of timeout after which the Session Reader client is closed, so we can try reading from other sessions instead.

So maybe there is no need to manually specify session IDs.. but the behavior still really isn't clear to me.

**Comment by brettveenstra** [comment]
That could be handled similarly to Azure Functions binding: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp

notably
- maxConcurrentSessions
- sessionIdleTimeout

I'd expect that part of the Dapr component YML

**Comment by brettveenstra** [comment]
Not really expecting much to change with Dapr interaction from code, just much more from the Service Bus pubsub component

Specifically
- setup session-required Subscriptions to a Topic (only enhancement is marking the Subscription to require sessions when creating it)
- send along the session id metadata (or empty/constant value when missing) for session-required Subscriptions
- handle regularly cycling through all sessions appearing on the Subscription and posting those message payloads to the application endpoint [this sounds like the hardest part of implementation]
- provide mechanism to inspect related session id in application code (retrieve via metadata dictionary?)

Does that help with feature set?

**Comment by jjcollinge** [comment]
what @brettveenstra has outlined aligns with my thinking on this. Last time I looked into this the old SDK did not expose the needed functionality but it looks like the new sdk via the `AcceptNextSessionForSubscription` method could support this. I'll let you know ASAP if I can pick this up again for 1.10.

**Comment by jjcollinge** [comment]
I'll have a stab at implementing this next week and loop back once I know more.
