### ISSUE TITLE
Pubsub rabbitmq connection_name

### ISSUE THREAD

**Issue by gchadid** [dapr/components-contrib#2902]
Hi 

Can we set up the rabbitmq connection_name in the pubsub.rabbitmq component?

![image](https://github.com/dapr/components-contrib/assets/10290878/c3f6b9a5-bc35-4313-a5bb-dff13e5738dd)

as describe

https://www.rabbitmq.com/connections.html#client-provided-names

best regards,

**Comment by berndverst** [comment]
Whoever wants to work on this: This needs to be introduced as new metadata property and then wire up with the rabbitmq client.

Code here:
https://github.com/dapr/components-contrib/tree/master/pubsub/rabbitmq

**Comment by Taction** [comment]
/assign

Add an optional `clientName` metadata, users can set it to any value, especially `{uuid}`, `{podName}` or `{appID}` (these will be replaced by Dapr runtime to the real value).
