### ISSUE TITLE
Add config metadata for Wasm http middleware

### ISSUE THREAD

**Issue by Taction** [dapr/components-contrib#2917]
## Describe the feature
The middleware for http wasm runs in a sandbox and does not have any configuration options. 
By adding `config` metadata, the wasm program can access the defined configuration. This is useful for some use cases, such as allowing users to implement a general blocker logic and then place the features in the configuration instead of hardcoding them.

## Release Note

RELEASE NOTE: Add config metadata for Wasm http middleware

**Comment by codefromthecrypt** [comment]
> implement a general blocker logic and then place the features in the configuration instead of hardcoding them.

Sorry I don't know what this means, can you explain for my benefit what "general blocker logic" is?

Another motivation is coraza maybe. Maybe @jcchavezs can mention if https://github.com/corazawaf/coraza-http-wasm uses config or if it is compiled into the guest

**Comment by jcchavezs** [comment]
coraza-http-wasm needs to consume config, right now this is the initial structure but it might become structured https://github.com/corazawaf/coraza-http-wasm/blob/main/main_test.go#L36-L51

**Comment by jcchavezs** [comment]
what is interesting is that coraza-http-wasm needs a base FS to load files. usually we embed a FS but would be nice to support host FS. Shall we allow mounting FS through dapper?

**Comment by codefromthecrypt** [comment]
Sooner or later we need it for python libs, but maybe open a different issue with what's motivating this? e.g. static read-only, or scratch space etc? Where would the files be sourced from? Is it possible to use OCI layers instead? things like this are different than config (even if correlated), and have implementation concerns that are trickier than embedded strings.

**Comment by Taction** [comment]
> Sorry I don't know what this means, can you explain for my benefit what "general blocker logic" is?

Just for example, I have applications A and B, and some endpoints need authentication. I write a wasm middleware to do the auth, and the auth logic is only executed when the request path is in the configured list. Without config, I have to define the endpoints list in the wasm code and compile different wasm binaries for applications since they have different endpoints lists.
In this case, the auth logic may be general for a set of applications, but there may have something unique to an application that needs to be configured.

**Comment by codefromthecrypt** [comment]
thanks for the example, I wasn't sure about the term blocker but now I get it!
