### ISSUE TITLE
Azure Cognitive Services/Containerised Cognitive Services

### ISSUE THREAD

**Issue by RKapadia01** [dapr/components-contrib#2943]
## Describe the proposal
Have done some work recently with Dapr and Azure Cognitive Services (more specifically Azure Text to Speech and Speech to Text), as well as working with containerised/offline versions of these services. At the moment I'm using the relevant SDK's to interface with these services, but thinking it would be a good idea to have an Output Binding created to allow this to better interface with Dapr.

Is this something worth building as a component? If so, I'm happy to raise a PR with these features.

Thanks

**Comment by ItalyPaleAle** [comment]
Hi @RKapadia01 Yes, we would welcome a PR to add support for ACS :)
