### ISSUE TITLE
PostgreSQL state store v2

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#2956]
As we now have "v2" components, we should look into creating a v2 of the Postgres state store to address some long-standing issues:

- Do not use the xmin column for etags, but a more "traditional" column
- The implementation of the "v2" component will be 100% identical to the current CockroachDB implementation, and we can also expose it as YugabyteDB (#2529). We should be able to reuse pretty much all code, but simplify the migration code.
- We do not plan on deprecating the "v1" at present
- Tests (conformance and certification) should run for both v1 and v2

**Comment by ItalyPaleAle** [comment]
Moving this to P2 for now. Although the issues above are good reasons for a "v2", we are not sure if they're "good enough" by themselves. We may wait a bit on this to see if there's something else that comes up that could require a v2 of the component.

CC: @artursouza

**Comment by ymahajan** [comment]
1. When is this expected to be released? 
2. After this V2 change, will YugabyteDB be published as a separate state store?

**Comment by berndverst** [comment]
> 1. When is this expected to be released?
> 2. After this V2 change, will YugabyteDB be published as a separate state store?

There is no timeline. This is not one of our highest priorities right now and there are some decisions we need to carefully make as maintainers. When this is completed YugabyteDB can be added as a separate state store, but until then please wait for this issue to be closed before inquiring further.

**Comment by yaron2** [comment]
keep-alive

**Comment by olitomlinson** [comment]
Document how users can inspect the content of a value i.e. this is outlined [here](https://github.com/dapr/components-contrib/pull/3250#issuecomment-1852451951)
