### ISSUE TITLE
How to write custom component?

### ISSUE THREAD

**Issue by ddobric** [dapr/components-contrib#297]
I want to implement a custom component by following [this](https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md) guide.
Unfortunately, I feel there are many details missing in the documentation.

First of all, is it possible to write the component in any language?  This was my first confusion in the step 2 :
>  Copy component files from the reference component to your component directory

All following steps are then related to 'GO".

It would be helpful to provide a few more conceptual details in different languages (I personally prefer C#).

Thanks in advance 

RELEASE NOTE: **UPDATED** instructions mentioning custom components are written in Go lang.

**Comment by benc-uk** [comment]
As the components are imported and loaded into the main daprd (over in https://github.com/dapr/dapr) which is written in Go, this means all components have to be written in Go also

**Comment by ddobric** [comment]
Any plans to change this limitation? We have today few enterprise approved languages and platforms. Go might be ok, but it is still does not play a role in enterprises. For the case that it never becomes important part of enterprise application development, it would be reasonable to provide other options.

Independent on this, if dapr a polyglot platform, then it should also be polyglot in its core.

**Comment by jjcollinge** [comment]
@ddobric please refer to this related issue and explanation of the current limitations in the go plugin model: https://github.com/dapr/dapr/issues/739

**Comment by pkedy** [comment]
Hopefully #706 addresses at least the ambiguity of Go being used as the language for implementing components. Please reopen otherwise.
