### ISSUE TITLE
Azure App Configuration component: use Go durations instead of nanoseconds for metadata options

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#2976]
The Azure App Configuration component has [4 metadata options](https://github.com/dapr/components-contrib/blob/6d6cb2af0a3a48b256c87a4f8412be3f4d38a442/configuration/azure/appconfig/metadata.go#L22-L25) that are durations, and those are defined as integers indicating nanoseconds (1 second =1_000_000_000 nanoseconds). This is a sub-par experience for end users.

The component should be updated to use `time.Duration` for those fields. The metadata parser automatically parses that as Go durations (e.g. "5s", or "2m"), which is a much better experience for users, and more aligned with the rest of Dapr.

This is a backwards-incompatible change that can be done to this alpha component.

**Comment by msfussell** [comment]
Need to also make sure this is updated https://github.com/dapr/docs/pull/3595

**Comment by berndverst** [comment]
We should update this issue to track all configuration stores as they have the same problem - the configuration store component authors just copy and pasted from each other.
