### ISSUE TITLE
Add support for Protobufs schemas in the Apache Pulsar pubsub component (Ref. #2450 --> #2475)

### ISSUE THREAD

**Issue by hugosmitter** [dapr/components-contrib#2978]
## Describe the feature

#2475 Added AVRO and JSON schema validation support to the Apache Pulsar pubsub component based on PR #2450. This request is to add Protobuf schema validation to the Dapr pubsub component. 

See: https://pulsar.apache.org/docs/3.0.x/schema-get-started/  for details on how it's done in Apache Pulsar.

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
Fixed by #3014
