### ISSUE TITLE
TTLs not working in DynamoDB state store

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#2988]
The Dynamo DB state store supports TTLs (as documented). However, the TTL test was not enabled in the conformance tests.

When that is enabled, the TTL tests fail: https://github.com/dapr/components-contrib/actions/runs/5536918955/jobs/10105198258#step:25:31

**Comment by ItalyPaleAle** [comment]
@JoshVanL  is this something you could look into please?

**Comment by yaron2** [comment]
DynamoDB needs to be explicitly provisioned with the TTL setting enabled and the ttlAttribute matching the name used in the test, it might be that those two conditions aren't satisfied.

**Comment by ItalyPaleAle** [comment]
> DynamoDB needs to be explicitly provisioned with the TTL setting enabled and the ttlAttribute matching the name used in the test, it might be that those two conditions aren't satisfied.

Thanks for the explanation. Looks like this was the issue and by enabling TTLs in the Terraform #2987 works
