### ISSUE TITLE
Postgres State Store: Add support for cluster behind pgBouncer

### ISSUE THREAD

**Issue by danielbichuetti** [dapr/components-contrib#3002]
## Expected Behavior

I would like to use Postgres as a State Store Component when my cluster is behind pgBouncer (most production clusters are).

## Actual Behavior

If using pgBouncer, component will fail:
`initialization error occurred for pgsql-state (state.postgresql/v1): faild to acquire advisory lock: ERROR: prepared statement \"stmtcache_1\" already exists (SQLSTATE 42P05)"`

## Steps to Reproduce the Problem

Deploy a Postgres cluster behind pgBouncer, try to initialize component.

## Extra comments

There was a Discord fast discussion about this with @ItalyPaleAle and @berndverst being present.
Reference links for a similar issue and a possible solution:
https://github.com/jackc/pgx/issues/602#issuecomment-532236718 
https://dba.stackexchange.com/questions/274307/prepared-statements-with-pgbouncer

**Comment by olitomlinson** [comment]
+1 to a resolution for this. 

FYI @ostreek

**Comment by olitomlinson** [comment]
@ItalyPaleAle did you ever get a moment to take a look at this issue? Thanks :)

**Comment by berndverst** [comment]
@olitomlinson @danielbichuetti have either of you tried adding `statement_cache_mode=describe` to your connection string? That is one of the two recommended solutions. For now I suggest we go this route per the linked issue.

**Comment by berndverst** [comment]
I'm feeling generous :D opened a PR for this https://github.com/dapr/components-contrib/pull/3103

Note that this exposes the low level `queryExecMode` and it is up to you to set this to a value compatible with pgBouncer. This could be either `exec`, `simple_protocol`, or `cache_describe`.

The connection string technique I describe previously should allow you to use Dapr 1.11 already. But the PR here is likely coming out in 1.12.

**Comment by ItalyPaleAle** [comment]
Thank you very much @berndverst !
