### ISSUE TITLE
Enhance Kafka pubsub OIDC auth support to support `oauthbearer.extensions`

### ISSUE THREAD

**Issue by teachmeabhinav** [dapr/components-contrib#3008]
According to document [https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/](https://protect-us.mimecast.com/s/bL8sCzpzoxUMRQoGRu45LsH?domain=docs.dapr.io/)  for pubsub

when we set authType as **oidc** we have below properties for connecting to broker

 
- oidcTokenEndpoint

- oidcClientID

- oidcClientSecret

- oidcScopes
 

We need something to pass **"oauthbearer.extensions"** like

- oidcExtensions

 

We are currently stuck because of this issue and need urgent help.

**Comment by berndverst** [comment]
@teachmeabhinav this is an enhancement which we will try to consider for 1.12 - but it's not a bug. As a result we cannot include this in hotfix releases.

Please see the original related issue that added this support:
https://github.com/dapr/components-contrib/pull/1229

It also says to use the `client_credentials` flow as it is `the most appropriate for machine-to-machine connections.`

**Comment by berndverst** [comment]
We have not received any contributions to implement this in time for 1.12. Moving this to 1.13.

**Comment by msfussell** [comment]
@teachmeabhinav @ItalyPaleAle - Can one of you assigned yourself to the docs issue #3722.

**Comment by ItalyPaleAle** [comment]
Please don't re-open this issue since it's complete. I've assigned myself to the docs issue.
