### ISSUE TITLE
Output bindings error codes

### ISSUE THREAD

**Issue by programaka** [dapr/components-contrib#301]
It seems that Cosmos DB output binding (and other bindings) returns 500 for all errors (regardless of what was returned by Cosmos DB itself). It makes it difficult to reliably act based on the error code. For example, I want to interpret "409 Already Exists" as success, but would want to retry "429 Too Many Requests". Without code propagated, my only option is to parse the error message which is unreliable since it can change.

## Proposal
The proposal is to propagate the error code from the underlying system, or map it into a more comprehensive list of errors (not just 500, but at least a set of standard error codes).

**Comment by benc-uk** [comment]
This is a good idea, most components are wrapping downstream REST/HTTP APIs which will will return their own errors.

For the caller getting a 500 from dapr, is confusing, if they read the body and unwrap it they will mostly likely find the "real" status code, e.g. 401 or 429, but even that is down to format of error messages in the component 
The mismatch leads to confusion
