### ISSUE TITLE
Azure Blob Storage List Blobs does not return Marker 

### ISSUE THREAD

**Issue by rodyvansambeek** [dapr/components-contrib#3010]
## Expected Behavior
When using the following code on a Azure Blob storage account with more than 10 files the marker value is not returned, but always returns an empty string: 

``` C#
var bindingSettings = new { maxResults = 10 };
var bindingSettingsBytes = JsonSerializer.SerializeToUtf8Bytes(bindingSettings);
bindingRequest.Data = new ReadOnlyMemory<byte>(bindingSettingsBytes);
var response = await _daprClient.InvokeBindingAsync(bindingRequest);

response.Metadata.TryGetValue("marker", out marker);
```

I would expect the marker variable to have the marker value. 

I have tested it with a local Azurite blob storage account, but also an online Azure Blob Storage account. Both just return the first 10 results and an empty string as marker. This way we don't got any way to iterate through all pages. 

Tested the same query using the AZ CLI, to confirm that it wasn't an issue in Azure, but that returns the "nextMarker" field correctly as the last object of the result: 

```
az storage blob list --connection-string "[connstring]" -c [containername] --num-results 10 --show-next-marker
```
Will return: 
```
[
  {
     [blob 1]
  },
  {
    [blob 2]
  },
  .... (total 10 results)
  {
    "nextMarker": "e61534b1-9010-4e8e-838a-46049d01b393/54-spiderfull/property-models/18216611.json"
  }
]
```
## Actual Behavior

The marker value in the response.Metadata object is always ""

## Steps to Reproduce the Problem

Use the above code using Dapr with C# and invoke the "list" operation on the binding with a maxResults lower then the number of items in the blob storage account.

**Comment by ItalyPaleAle** [comment]
Thanks for reporting this, we'll take a look

**Comment by rodyvansambeek** [comment]
I don't think this is fixed, so needs to stay open.

**Comment by berndverst** [comment]
Dapr will always iterate through all pages and return everything. However, you can provide the marker to start from in your request if you know the marker.

https://github.com/dapr/components-contrib/blob/2cb3c1cce1de407913615aa0296cba6db34205f7/bindings/azure/blobstorage/blobstorage.go#L298-L321

It's unclear what marker we should return here, other than the provided marker which is empty if none was provided.

I don't see any issue here, but perhaps you are asking for a feature request where Dapr does not iterate through all pages, but only returns a certain number of results. In that case I could certainly understand needing the marker! @rodyvansambeek

**Comment by berndverst** [comment]
For convenience I am adding a new property `pagesTraversed` in the response metadata of the list operation. This will return the number of pages that were internally traversed.

However, I maintain that I do not see any issue with the component @rodyvansambeek 

https://github.com/dapr/components-contrib/pull/3126

**Comment by rodyvansambeek** [comment]
@berndverst Thanks for clarifying the inner workings. I will check in the next few days in the project I am working on if it does what it says when don't sending in the maxResults and wanting to retrieve more than 5000 results. I am pretty sure it returned only the first 10 results (while there were hundreds in the blob storage account) without a marker in my test setup. Will let you know as soon as possible. Will also try with a storage account with over 5000 results, to see if it then returns a marker.

**Comment by berndverst** [comment]
@rodyvansambeek if you don't mind - wait until Dapr 1.12 - or the `1.12.0-rc.2` version (if you don't mind trying out our release candidate). That will include the change I made yesterday to also show how many pages were traversed, and that will report the number of items were returned (which now can be at most **maxResults + pageSize**)

**Comment by berndverst** [comment]
@rodyvansambeek one additional comment here:

If you specify `maxResults = 10` -- that is not the page size. This actually tells the server to only return 10 results. Even if more results exist, that does not mean there will pagination for additional results beyond 10 results - the server will not actually return more results.

We do not have a way to control the page size.

**Comment by rodyvansambeek** [comment]
@berndverst That was the issue. I assumed that would be the page size, and the marker would be returned after that amount of results. I understand the inner workings now. Maybe it's a good idea to change this in the documentation because if you read the part of the data parameters on: https://docs.dapr.io/reference/components-reference/supported-bindings/blobstorage/#list-blobs 
It looks like you need to specify a maxResults and get a marker back for every page to iterate through all the results.
