### ISSUE TITLE
Dapr Binding with GCP Storage Bucket Giving Oauth2 Error

### ISSUE THREAD

**Issue by prateek-pagaria** [dapr/components-contrib#3012]
## In what area(s)?

 /area runtime

## What version of Dapr?
1.11.1

## Expected Behavior

Till dapr runtime version 1.10.7 dapr binding with gcp-storage-bucket was working. 
see the dapr version, dapr port on which service is running . 

<img width="1430" alt="Screenshot 2023-07-20 at 20 15 47" src="https://github.com/dapr/dapr/assets/108855024/77c1eb67-a654-46e5-9df3-8245a8f4d124">

Below is the response of the api to get the content from the storage bucket 
<http://localhost:3540/v1.0/bindings/gcp-storage-bucket-manager>

<img width="1440" alt="Screenshot 2023-07-20 at 20 16 25" src="https://github.com/dapr/dapr/assets/108855024/9eefc142-76fe-418d-b24e-2817bb042315">

**********************************************************************************
But After upgrading the dapr cli and dapr run time to the latest same call is throwing error

<img width="1440" alt="Screenshot 2023-07-20 at 20 20 23" src="https://github.com/dapr/dapr/assets/108855024/fe201c23-ac98-4c69-842c-ea737d1c7ba2">

Getting this error 
`{
    "errorCode": "ERR_INVOKE_OUTPUT_BINDING",
    "message": "error invoking output binding gcp-storage-bucket-manager: gcp bucketgcp bucket binding error: error downloading bucket object: Get \"https://storage.googleapis.com/imps-payment-switch/standin_eligibility_rule.json\": oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Invalid grant: account not found\"}"
}`

image attached.

<img width="1440" alt="Screenshot 2023-07-20 at 20 21 45" src="https://github.com/dapr/dapr/assets/108855024/4c71779f-71b5-42de-a51f-95d436bd6f00">

## Actual Behavior

It should also work with the latest version; I should be able to get the content of a file from storage bucket. 

## Steps to Reproduce the Problem

Start your application with dapr and give gcp  storage binding component config file while starting the application and hit the url as mentioned on the official doc: [Get object](https://docs.dapr.io/reference/components-reference/supported-bindings/gcpbucket/#get-object)

The binding file was the same for both the version referring this. 
[gcpbucket](https://docs.dapr.io/reference/components-reference/supported-bindings/gcpbucket/#component-format)

**Comment by berndverst** [comment]
cc @robertojrojas @yaron2
