### ISSUE TITLE
Question: component-metadata-bundle.json

### ISSUE THREAD

**Issue by guergabo** [dapr/components-contrib#3013]
Ref: 

## Question
Shouldn't "Azure AD: Managed identity" auth profile have at least one required field? In general, is it safe to assume all fields in an auth profile are required? 

@ItalyPaleAle

**Comment by ItalyPaleAle** [comment]
@guergabo I cannot open the link you shared https://github.com/diagridio/cloudgrid/blob/main/pkg/cloudruntime/service/resources/component-metadata-bundle.json#L416

However, no, Azure AD when using MI doesn't have any required field. It's _recommended_ to set the ClientID, but it's not _always_ required (it may be required in some environments but not all). See docs: https://docs.dapr.io/developing-applications/integrations/azure/azure-authentication/authenticating-azure/#credentials-metadata-fields

**Comment by guergabo** [comment]
Sorry, I pasted the wrong link! But, you already answered my question in the second paragraph. Thanks for the quick response!
