### ISSUE TITLE
Support Embeddings api in Azure OpenAI component

### ISSUE THREAD

**Issue by shivam-51** [dapr/components-contrib#3018]
In the current alpha stage Azure OpenAI output binding supports `completion` and `chat-completion` operations. This proposal is to add the `get-embeddings` operation based on https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#embeddings.

**Comment by shivam-51** [comment]
I am happy to pick this up once it get's accepted by the team.
cc: @ItalyPaleAle

**Comment by ItalyPaleAle** [comment]
@shivam-51 sure, go ahead and thanks!
