### ISSUE TITLE
Redis StateStore and async calls.

### ISSUE THREAD

**Issue by pamav** [dapr/components-contrib#3035]
Hi,

I used DaprClient.SaveStateASync to save the <string,string> dictionary. (Dapr is the default installation in docker)

I created a RestApi Get method with a Key parameter.(with DaprClient.GetStateAsync)
When I call the Get method with ONE user everything works fine.
When I create 100 async calls (in one console app running in Docker) I always get this error:

"Error:Dapr.DaprException: State operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
== APP ==        ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="fail to get codebookItems from state store redisstore: WRONGTYPE Operation against a key holding the wrong kind of value")
== APP ==          at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
== APP ==          --- End of inner exception stack trace ---
== APP ==          at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)"

Can you provide me where is the problem?

Thx

**Comment by ItalyPaleAle** [comment]
Hi @pamav could you please provide some code to reproduce this error? Or at least the logs from Dapr besides your application's logs?
