### ISSUE TITLE
Deprecate NATS Streaming PubSub component

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#3042]
The [NATS Streaming PubSub](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-nats-streaming/) component is currently in beta.

NATS Streaming is officially deprecated. The server does not receive security fixes as of June 2023: https://github.com/nats-io/nats-streaming-server  Maintainer instead recommend using [NATS JetStream](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-jetstream/), which Dapr already supports.

Aside from the server being deprecated, the client library we depend on is deprecated as well. This means it does not receive security fixes.

We should deprecate the component in Dapr 1.12, and decide on which version it will be officially removed from.

- [X] Docs: https://github.com/dapr/docs/pull/3666
- [X] Add warning to code: #3043

**Comment by berndverst** [comment]
Let's add a deprecation warning in 1.12 and remove in 1.14. cc @yaron2 @artursouza

**Comment by ItalyPaleAle** [comment]
Thoughts on accelerating to 1.13 since it's beta? I would like to not have a dependency in this repo that is archived. 1.14 is probably not coming for another 7-8 months so that's a long time.

**Comment by artursouza** [comment]
I am fine either way. One release seems reasonable and more than what we promise for non-stable components.
