### ISSUE TITLE
Add optional support for TTL (Time to Live) for state stores

### ISSUE THREAD

**Issue by wanton7** [dapr/components-contrib#306]
## In what area(s)?

> /area runtime

## Describe the feature

If I have example a Redis state store that I want to use as cache, having support for TTL when writing a state would be very beneficial. State stores that don't support TTL could just ignore TTL.

**Comment by denis111** [comment]
+1. Would be very useful for storing session tokens (like allow (for logged in) or deny (for logged-out) users) even for things like stateless jwt tokens for additional security.

**Comment by yaron2** [comment]
State API calls take in an optional metadata per request.

Does something like the following seem reasonable?

```
/v1.0/state/redis

[
  {
     "key": "key1",
     "value: "myVal",
     "metadata": {
         "ttl": "1d"
     }
  }
]
```

**Comment by denis111** [comment]
@yaron2 I guess it would be fine.
Right now we use Spring Boot's redis client and it has @TimeToLive annotation wich you put on long property in the class you want to save in redis, maybe something similar could be made in dapr's java sdk, if not then it's not a problem setting metadata property manually.

**Comment by berndverst** [comment]
We'll use `ttlInSeconds` in metadata, just like for PubSub

**Comment by yaron2** [comment]
Changing to P2.

**Comment by berndverst** [comment]
Just a quick note:
In addition to Redis and CosmosDB I'll be adding MongoDB and Cassandra. Maybe Couchbase if desired or I will let someone else contribute that change :)

**Comment by UmutComlekci** [comment]
With references of your Redis & Cosmos DB TTL developments, I wrote Memcached TTL support  :)

**Comment by berndverst** [comment]
Looking into this more I am not sure it makes sense to support TTL for MongoDB here. This would require a custom field (typically a date field) and an index on the entire collection specifying this field to be used for expiration.

I'd argue that collection / container / bucket level TTLs are out of scope for this change. (Perhaps they could be supported at a later time via runtime config settings.)
