### ISSUE TITLE
Consul name resolution ipv6 support

### ISSUE THREAD

**Issue by Jhoysbou** [dapr/components-contrib#3074]
## Expected Behavior
Working service to service invocation on ipv6 network

## Actual Behavior
When trying to use s2s invocation the following error occurs:
```json
{
    "errorCode": "ERR_DIRECT_INVOKE",
    "message": "fail to invoke, id: api, err: failed to invoke target api after 3 retries. Error: rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: Error while dialing: dial tcp: address 2001:db8:3333:4444:5555:6666:7777:8888:48186: too many colons in address\""
}
```

[This code](https://github.com/dapr/components-contrib/blob/master/nameresolution/consul/consul.go#L147-L153) just adds the port regardless of the protocol version:
```go
	if svc.Service.Address != "" {
		addr = svc.Service.Address + ":" + port
	} else if svc.Node.Address != "" {
		addr = svc.Node.Address + ":" + port
	} else {
		return "", fmt.Errorf("no healthy services found with AppID '%s'", req.ID)
	}
```
So for ipv6, it leads to an invalid ip. 

The address should be `[2001:db8:3333:4444:5555:6666:7777:8888]:48186`

## Steps to Reproduce the Problem
Run Consul server:
```sh
consul agent \
  -server \ 
  -data-dir=/tmp/consul \
  -bootstrap-expect=1 \
  -bind="<SERVER_IPV6_ADRESS>"
```

Run Consul client:
```sh
consul agent \
  -bind="<CLIENT_IPV6_ADDRESS>" \
  -data-dir=/tmp/consul \
  -retry-join="<SERVER_IPV6_ADRESS>"
```
Run the Consul client and the Dapr sidecar for both the caller and the called party.

The component config is as follows:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  nameResolution:
    component: "consul"
    configuration:
      selfRegister: true
```

Make a s2s invocation call
`curl http://localhost:3500/v1.0/invoke/api/method/<SOME_METHOD_NAME>`

## Release Note

RELEASE NOTE: Fixed resolution of IPv6 addresses.

**Comment by Jhoysbou** [comment]
Created a fix proposal 
https://github.com/dapr/components-contrib/pull/3075

**Comment by Jhoysbou** [comment]
@MaxSchaefer 

Hi! Could you please review this issue? I created a fix for it and checked with my network (it works fine).

I called you because I saw that you were doing something with this component before. If I'm wrong, please call someone else

**Comment by berndverst** [comment]
I'm merging your PR @Jhoysbou. If you think a PR is ready for review (tests pass etc) please don't keep it in draft mode. As a maintainer I generally ignore draft PRs.

**Comment by Jhoysbou** [comment]
Sure! Next time I do as you say
