### ISSUE TITLE
[Feature] Add Timing of Re-Deliveries When Messages Are Negatively Responded On JetStream

### ISSUE THREAD

**Issue by Admiralkheir** [dapr/components-contrib#3079]
Hi all,
We have been using nats streaming for a long time. With the end of support in Nats Streaming, we decided to switch to JetStream. With the Nats Streaming component, when we returned a negative status code on the application side, Nats Streaming was sending us a message during the AckWait time. When we use the JetStream component, even if we give the backoff parameter, it is instantly retransmitted when we return a negative status code. In cases where we return a negative status code, if this time is defined in the component, message transmission during this time will be beneficial for the listening application.

## Describe the feature
According the JetStream [doc](https://docs.nats.io/using-nats/developer/develop_jetstream/consumers#delivery-reliability);
> You can also control the timing of re-deliveries when messages are negatively acknowledged with Nak(), by passing a nakDelay() option (or using NakWithDelay()), otherwise the re-delivery attempt will happen right after the reception of the Nak by the server.

This value can be added on the component
## Release Note
RELEASE NOTE: **ADD** timing of Re-Deliveries When Messages Are Negatively Responded On JetStream

**Maintainer Edit / Notes:**
This issue is only about adding a metadata option which if set should result in the call of `NakWithDelay` instead of `Nak`. It is not about the connecting this with Dapr Resiliency policies, which is a much larger and separate effort (#1863)

**Comment by berndverst** [comment]
@Admiralkheir given that we are deprecating the NATSStreaming component in 1.12 I made sure to get this change into the 1.12 release for you! You shouldn't have to change anything if you are already setting `AckWait` in the component.

**Comment by Admiralkheir** [comment]
Ty for effort @berndverst
