### ISSUE TITLE
Azure App Config Store - Add conformance and certification tests

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/components-contrib#3086]
## Release Note

RELEASE NOTE: **ADD** Conformance and Certification tests for Azure App Config Store

**Comment by berndverst** [comment]
I will add the conformance test to make the component beta, but will leave this issue for @pravinpushkar for the certification test.

**Comment by berndverst** [comment]
@pravinpushkar PR is here - can you maybe help troubleshoot?
https://github.com/dapr/components-contrib/pull/3089
