### ISSUE TITLE
a url error in readme

### ISSUE THREAD

**Issue by xiangpingjiang** [dapr/components-contrib#3091]
## Expected Behavior

Workflow services link is ok
## Actual Behavior

[Workflow services](https://github.com/dapr/components-contrib/blob/master/workflow/README.md)   in readme not found
## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
@xiangpingjiang you are correct, the link should be changed to `https://github.com/dapr/components-contrib/blob/master/workflows/README.md`. would you like to submit a PR that fixes this?

**Comment by xiangpingjiang** [comment]
> 

done

**Comment by xiangpingjiang** [comment]
> @xiangpingjiang you are correct, the link should be changed to `https://github.com/dapr/components-contrib/blob/master/workflows/README.md`. would you like to submit a PR that fixes this?

done

**Comment by yaron2** [comment]
Thanks for your contribution
