### ISSUE TITLE
How do I register a service that starts dapr with consul in a docker environment

### ISSUE THREAD

**Issue by wxlnet** [dapr/components-contrib#3101]
In the dapr configuration file config.yml, as follows

apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec: 
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
  nameResolution:
    component: "consul"
    configuration:
      client:
        address: "localhost:8500"
      selfRegister: true

Someone big enough to help me out once and for all. Thank you。或者可以给我推荐下使用的文章或视频

**Comment by berndverst** [comment]
Maybe the details here help:
https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/#sample-configurations

If you use docker compose you also have to configure the Docker network so the Dapr and Consul can reach each other. With Docker compose usually services in containers cannot reach each other.

If you run Dapr without Docker and only run Consul in Docker, this should be much easier to test. Maybe try this first before switching to using docker compose completely.

Unfortunately I am no expert on consul. Here is a video from long ago that shows Dapr + Consul being used: https://www.youtube.com/watch?v=Cv-8e5wV44g

**Comment by wxlnet** [comment]
Thanks for the ideas and learning videos。
Currently, projects started locally in the form of command lines can be registered in docker consul, but docker services cannot be registered
[as shown in the figure](javascript:;)
![image](https://github.com/dapr/components-contrib/assets/65823238/b14c397b-32ee-40da-a0c4-868676fd9560)
![image](https://github.com/dapr/components-contrib/assets/65823238/e510dcc9-00d0-48c2-9913-d67258bf9caf)
![image](https://github.com/dapr/components-contrib/assets/65823238/75da4694-dea1-46b6-bd68-7b085416794b)

**Comment by berndverst** [comment]
Try joining our Discord server - there will be lots of people who can probably help with the setup you need.
