### ISSUE TITLE
Can not comment on Issue #3008, Proposing the Solution for it

### ISSUE THREAD

**Issue by teachmeabhinav** [dapr/components-contrib#3123]
Hi This is related the request of Enhance https://github.com/dapr/components-contrib/issues/3008. We cannot comment on the original issue so commenting over here, Team this is critical for as us our whole plan  is dependent on this, It is request please consider it as hotfix.... To expedite the process I figure out the changes as  below and it is working, Please have a look and help us to resolve it

**file : internal/component/kafka/metadata.go**
**line 17 add**
```
 "encoding/json"
```
**line 60  add** 
```
OidcExtensions        string              `mapstructure:"oidcExtensions"`
```
**line 70 add** 
```
internalExtensions    map[string]string   `mapstructure:"-"`
```
**line 183 add**
```
if m.OidcExtensions != "" {
			json.Unmarshal([]byte(m.OidcExtensions), &m.internalExtensions)
			if len(m.internalExtensions) < 1 {
				return nil, errors.New("kafka error: improper OIDC Extensions format for authType 'oidc'")
			}
		}
```
**file : internal/component/kafka/sasl_oauthbearer.go**
Replace function newOAuthTokenSource with below
```
func newOAuthTokenSource(oidcTokenEndpoint, oidcClientID, oidcClientSecret string, oidcScopes []string, extensions map[string]string) OAuthTokenSource {
	return OAuthTokenSource{TokenEndpoint: oauth2.Endpoint{TokenURL: oidcTokenEndpoint}, ClientID: oidcClientID, ClientSecret: oidcClientSecret, Scopes: oidcScopes, Extensions: extensions}
}
```
**file : internal/component/kafka/auth.go**
Replace function newOAuthTokenSource with below
```
func updateOidcAuthInfo(config *sarama.Config, metadata *KafkaMetadata) error {
	tokenProvider := newOAuthTokenSource(metadata.OidcTokenEndpoint, metadata.OidcClientID, metadata.OidcClientSecret, metadata.internalOidcScopes, metadata.internalExtensions)
	if metadata.TLSCaCert != "" {
		err := tokenProvider.addCa(metadata.TLSCaCert)
		if err != nil {
			return fmt.Errorf("kafka: error setting oauth client trusted CA: %w", err)
		}
	}
	tokenProvider.skipCaVerify = metadata.TLSSkipVerify
	config.Net.SASL.Enable = true
	config.Net.SASL.Mechanism = sarama.SASLTypeOAuth
	config.Net.SASL.TokenProvider = &tokenProvider
	return nil
}
```
**file : pubsub\kafka\metadata.yaml**
Add
```
  - name: oidcExtensions
      required: false
      description: |
        Comma-delimited list of OAuth2/OIDC extensions to request with the access token. Recommended when authType is set to oidc.
      example: '{"cluster":"kafka","poolid":"kafkapool"}'
      type: string
```

**Comment by ItalyPaleAle** [comment]
Thank you for this. I have used your proposed code changes in #3124. We'll get them merged for Dapr 1.12, crediting you.

PS: In the future, feel free to open a [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) with the code changes!
