### ISSUE TITLE
GCP Certification Tests failing

### ISSUE THREAD

**Issue by shubham1172** [dapr/components-contrib#3129]
## Expected Behavior

GCP certification tests should not fail.

## Actual Behavior

GCP (pubsub and statestore) certification tests are failing.
Example runs
- https://github.com/dapr/components-contrib/actions/runs/6143888191/job/16668226093
- https://github.com/dapr/components-contrib/actions/runs/6179322535/job/16774094695

Errors: 
```# state.gcp.firestore
error saving state: rpc error: code = Internal desc = failed saving state in state store statestore-basic: rpc error: code =
 Unauthenticated desc = transport: per-RPC creds failed due to error: oauth2/google: unable to generate access token: 
Post "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/***:generateAccessToken": oauth2/google: 
invalid response when retrieving subject token: Get "https://pipelines.actions.githubusercontent.com/": context canceled
        	Test:       	TestGCPFirestoreStorage

# pubsub.gcp.pubsub
error publishing event unto gcpps-ct-tp-exists-6143888191-1 topic: rpc error: code = Internal desc = error when publish 
to topic gcpps-ct-tp-exists-6143888191-1 in pubsub gcp-pubsub-cert-tests: rpc error: code = Unauthenticated desc = 
transport: per-RPC creds failed due to error: oauth2/google: unable to generate access token: Post 
"https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/***:generateAccessToken": oauth2/google: invalid 
response when retrieving subject token: Get "https://pipelines.actions.githubusercontent.com": context canceled
        	Test:       	publish messages to existingTopic: gcpps-ct-tp-exists-6143888191-1
```

## Steps to Reproduce the Problem

Run the stable components certification tests.

## Release Note

RELEASE NOTE: **FIX** GCP components certification tests

**Comment by berndverst** [comment]
GCP cert tests have been failing due to some oauth thing for a long time. Hoping someone from Diagrid will address it

cc @yaron2 @artursouza

**Comment by robertojrojas** [comment]
@berndverst I'll work with @elena-kolevska on this.

**Comment by elena-kolevska** [comment]
The issue was already closed automatically, but just adding a note that it was actually fixed in https://github.com/dapr/components-contrib/pull/3169
