### ISSUE TITLE
can't not regiest to consul   when dapr run on docker 

### ISSUE THREAD

**Issue by Alvin-4550** [dapr/components-contrib#3132]
## Ask your question here
 I use this config regiest  dapr to consul ,but get the wrong heartbeat  Get "http://172.21.0.3:50001/v1.0/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  nameResolution:
    component: "consul"
    configuration:
      client:
        address: "192.168.2.133:8500"
      selfRegister: true
      checks:
        - name: "Dapr Health Status"
          checkID: "daprHealth:${APP_ID}"
          interval: "15s"
          http: "http://${HOST_ADDRESS}:${DAPR_HTTP_PORT}/v1.0/healthz"
        - name: "Service Health Status"
          checkID: "serviceHealth:${APP_ID}"
          interval: "15s"
          http: "http://${HOST_ADDRESS}:${APP_PORT}/health"
      tags:
        - "dapr"
        - "v1"
        - "${OTHER_ENV_VARIABLE}"
      meta:
        DAPR_METRICS_PORT: "${DAPR_METRICS_PORT}"
        DAPR_PROFILE_PORT: "${DAPR_PROFILE_PORT}"
      daprPortMetaKey: "DAPR_PORT"        
      queryOptions:
        useCache: true
        filter: "Checks.ServiceTags contains dapr"

**Comment by berndverst** [comment]
I assume you run docker compose? If so, it's a docker network problem -- I cannot help you with the configuration. Please make sure your dapr sidecar container, the app, and the consul container can actually talk to each other on the required ports.
