### ISSUE TITLE
Is component type pubsub.azure.servicebus still supported?

### ISSUE THREAD

**Issue by adipalavra-onbe** [dapr/components-contrib#3133]
I am wondering what will happen if we are using an SDK version 1.10 or higher and we specify a component of type pubsub.azure.servicebus? From that version on, pubsub.azure.servicebus has been removed and split into two components pubsub.azure.servicebus.topics and pubsub.azure.servicebus.queues.

Is it going to use some outdated component version from a previous release and can that cause issues, or is pubsub.azure.servicebus now an alias for pubsub.azure.servicebus.topics?

**Comment by berndverst** [comment]
See here https://github.com/dapr/dapr/blob/master/cmd/daprd/components/pubsub_azure_servicebus_topics.go#L25

The old name still exists as an alias - so no worries there. For new components, please use the new name - but for the existing one nothing unexpected will happen.

**Comment by adipalavra-onbe** [comment]
Thank you for the response.
