### ISSUE TITLE
Pub/Sub retries with pod down

### ISSUE THREAD

**Issue by MatteoRigoni** [dapr/components-contrib#3136]
Ho i'm making some test with pub/sub Azure service bus with current settings:
- Topic with maxDeliveryCount tò 10
-  Resiliciency in Dapr of 9 max retries every 60 sec

I've 2 pods, the consumer and dapr sidecar.

I've theese 2 scenarios:
1) all pod down: message remain Active in service bus and Will be redelivered when restart.
2) pod Dapr down: same of point 1
3) pod consumer down: here the problem...messages Will be acquired by the sidecar and Will then finish all delivery count and deadletter.

How can i prevent this? I should put infinite retries on Resiliciency so i Will be sure that message remain enqueued until consumer's restart?

Or Is there some configuration? Basically, of consumer Is down and sidecar up, i don't want that It retries deliver message because It Will finish all possible 10 delivery count.

Thanks to all Will contribuite this.
Bye

**Comment by berndverst** [comment]
What you are looking for is the application health check feature: https://docs.dapr.io/operations/resiliency/health-checks/app-health/

When Dapr detects your app is unhealthy it will unsubscribe your app and the sidecar will not deadletter more events. When the app is healthy again it will resubscribe.

**Comment by MatteoRigoni** [comment]
Hi thanks for suggestion.
I've tried to set that flag but apparently i don't find any changes in the behaviour...in the log of container i found this:

**App health checks are a preview feature and require the AppHealthCheck feature flag to be enabled. See https://docs.dapr.io/operations/configuration/preview-features/ on how to enable preview features.**

But i don't understand what it means. From documentation i undestand that is enough set the flag "-enable-app-health-check" (i'm using k8s)

Thanks for support.

**Comment by olitomlinson** [comment]
@MatteoRigoni 

you need to configure a few other properties to ensure the App Health Checks are working as desired, please see here :

https://docs.dapr.io/operations/resiliency/health-checks/app-health/#configuring-app-health-checks
