### ISSUE TITLE
Redis:  Output Binding - Get operation does not return nil

### ISSUE THREAD

**Issue by esgraham** [dapr/components-contrib#3140]
## Output Binding Error

area runtime

## What version of Dapr?

CLI version: 1.10.0 
Runtime version: 1.10.2

## Expected Behavior

When using an Output Binding on a 'get' operation with Redis, return nil or null if the key does not exist.

## Actual Behavior

 Dapr throws an exception rather than returning nil.  The problem is that I have to look at the string message to determine if the value does not exist or if there was a network error, as the errors are very similar:

Value cannot be found error message:

== APP == io.grpc.StatusRuntimeException: INTERNAL: error invoking output binding account-database-binding: redis: nil

Redis is currently not running:

== APP == io.grpc.StatusRuntimeException: INTERNAL: error invoking output binding account-database-binding: read tcp [::1]:55697->[::1]:6377: i/o timeout

## Steps to Reproduce the Problem

1.  When running an application that uses Output Binding with Redis, call the invokebinding command with the get operation and a key value that has not been added to the Redis database.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
@esgraham if you use a simple HTTP curl command to get the value (as in, not using the SDK) what is the response status code and message you are getting?

**Comment by berndverst** [comment]
@sicoyle as maintainer of this repo I too require the full context of your conversation with @yaron2 so I know whether or not to take action myself.

**Comment by berndverst** [comment]
I cannot reproduce this in components-contrib using the Go SDK.

The issue here must be SDK or maybe only present in 1.10.2 -- it is not present in **master** or in 1.11.X / 1.12

I added the following to the Redis Binding certification test to reproduce this:

```go
invokeRequestDNE := &daprClient.InvokeBindingRequest{
	Name:      bindingName,
	Operation: string(bindings.GetOperation),
	Metadata:  map[string]string{"key": "doesnotexist"},
}
err = client.InvokeOutputBinding(ctx, invokeRequestDNE)
assert.Error(t, err)
```

**Comment by yaron2** [comment]
> @sicoyle as maintainer of this repo I too require the full context of your conversation with @yaron2 so I know whether or not to take action myself.

There is no additional context other than the issue exists

**Comment by berndverst** [comment]
@yaron2 @sicoyle I will take over this issue - I know the root cause.

There is a special `redis.nil` value returned by the redis client which we need to remap to Go's native nil.

**Comment by berndverst** [comment]
It appears I had fixed this some time ago but didn't backport it. I noticed this issue as I was developing a new feature for 1.11: https://github.com/dapr/components-contrib/pull/2654

I'll send a quick fix for 1.10.X

```go
			if err != nil {
				if err.Error() == "redis: nil" {
					return &bindings.InvokeResponse{}, nil
				}
				return nil, err
			}
```

**Comment by berndverst** [comment]
Fix here: https://github.com/dapr/components-contrib/pull/3141

**Comment by berndverst** [comment]
@yaron2 if you can approve the PR I can tag a new contrib 1.10.X tag. Maybe @sicoyle can then import that into runtime and prepare the runtime hotfix release for 1.10.X (or someone else can work on that)

**Comment by yaron2** [comment]
> @yaron2 if you can approve the PR I can tag a new contrib 1.10.X tag. Maybe @sicoyle can then import that into runtime and prepare the runtime hotfix release for 1.10.X (or someone else can work on that)

I believe we have a 1.10.x hotfix coming up for an actor issue, so we can definitely like this up.

**Comment by berndverst** [comment]
@yaron2 - https://github.com/dapr/dapr/pull/6936

**Comment by esgraham** [comment]
Thank you for fixing this issue!
