### ISSUE TITLE
Configuration component notification issues when using Postgres

### ISSUE THREAD

**Issue by danielbichuetti** [dapr/components-contrib#3167]
## Expected Behavior

When using Azure Postgres we should be able to subscribe to the TRIGGER to get configuration updates.

## Actual Behavior

Context is canceled. Subscription stopped just after subscribing.

```
d.subscribe_configuration(store_name=settings.CONFIG_STORE,
                                  keys=[_ENDPOINT_KEY],
                                  handler=endpoint_update,
                                  config_metadata={
                                      "pgNotifyChannel": "config"
                                  })
```

```
ERRO[0001] error listening to channel:%!(EXTRA *errors.errorString=context canceled)  app_id=embedder component="config (configuration.postgresql/v1)" instance=NB01A scope=dapr.contrib type=log ver=1.11.3
== APP == config configuration watcher for keys ['endpoints'] stopped.
```

## Steps to Reproduce the Problem

1. Create an Azure Postgres server
2. Create a Configuration  component using that server (table + trigger setup correctly)
3. Try to subscribe using gRPC client.

## Release Note

dapr: 1.11.3
Python SDK: 1.10

**Comment by ItalyPaleAle** [comment]
@akhilac1 @shivamkm07 As the authors of the component, could you please take a look at this?

**Comment by shivamkm07** [comment]
Hi @danielbichuetti, Can you provide more details about your setup? I tested the python-sdk configuration example https://github.com/dapr/python-sdk/tree/master/examples/configuration with postgres setup(need to modify the component file to point to postgres server) and it is working fine for me. Tested with python-sdk 1.10.0 and Dapr 1.11.3.

Can you re-verify you have setup the trigger correctly on postgres? For instruction refer this: https://docs.dapr.io/reference/components-reference/supported-configuration-stores/postgresql-configuration-store/#set-up-postgresql-as-configuration-store
> Note: There is a typo in the steps mentioned here. The function name declared in Step 3 is `configuration_event` while the name used in Step 6 is `notify_event`. It needs to refer to the same function for correct behavior. I will create a Docs PR to fix this.

**Comment by NMillard** [comment]
> ## Expected Behavior
> When using Azure Postgres we should be able to subscribe to the TRIGGER to get configuration updates.
> 
> ## Actual Behavior
> Context is canceled. Subscription stopped just after subscribing.
> 
> ```
> d.subscribe_configuration(store_name=settings.CONFIG_STORE,
>                                   keys=[_ENDPOINT_KEY],
>                                   handler=endpoint_update,
>                                   config_metadata={
>                                       "pgNotifyChannel": "config"
>                                   })
> ```
> 
> ```
> ERRO[0001] error listening to channel:%!(EXTRA *errors.errorString=context canceled)  app_id=embedder component="config (configuration.postgresql/v1)" instance=NB01A scope=dapr.contrib type=log ver=1.11.3
> == APP == config configuration watcher for keys ['endpoints'] stopped.
> ```
> 
> ## Steps to Reproduce the Problem
> 1. Create an Azure Postgres server
> 2. Create a Configuration  component using that server (table + trigger setup correctly)
> 3. Try to subscribe using gRPC client.
> 
> ## Release Note
> dapr: 1.11.3 Python SDK: 1.10

Hey, can you please share how you've set up the postgres configuration component?

**Comment by shivamkm07** [comment]
> > ## Expected Behavior
> > When using Azure Postgres we should be able to subscribe to the TRIGGER to get configuration updates.
> > ## Actual Behavior
> > Context is canceled. Subscription stopped just after subscribing.
> > ```
> > d.subscribe_configuration(store_name=settings.CONFIG_STORE,
> >                                   keys=[_ENDPOINT_KEY],
> >                                   handler=endpoint_update,
> >                                   config_metadata={
> >                                       "pgNotifyChannel": "config"
> >                                   })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > ERRO[0001] error listening to channel:%!(EXTRA *errors.errorString=context canceled)  app_id=embedder component="config (configuration.postgresql/v1)" instance=NB01A scope=dapr.contrib type=log ver=1.11.3
> > == APP == config configuration watcher for keys ['endpoints'] stopped.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Steps to Reproduce the Problem
> > 
> > 1. Create an Azure Postgres server
> > 2. Create a Configuration  component using that server (table + trigger setup correctly)
> > 3. Try to subscribe using gRPC client.
> > 
> > ## Release Note
> > dapr: 1.11.3 Python SDK: 1.10
> 
> Hey, can you please share how you've set up the postgres configuration component?

@NMillard I believe your issue is resolved right?
@danielbichuetti Can this issue be closed ?

**Comment by michalis-exus** [comment]
Was this issue resolved? Interested to know what the workaround was for the Dapr error as I'm facing a similar issue.
