### ISSUE TITLE
Improve docs for using `bindings.azure.eventgrid` Secure WebHook Event Delivery

### ISSUE THREAD

**Issue by joshwright10** [dapr/components-contrib#3172]
Following the Breaking Changes mentioned in https://github.com/dapr/components-contrib/issues/2813, I have spent the last 3 days trying to work out why Dapr and Azure would not play nicely and create my WebHook Event Subscription when upgrading from Dapr 1.9.0 to anything above 1.10.x (when the Event Grid Component changed to require Secure WebHook Event Delivery. 

The current documentation https://v1-10.docs.dapr.io/reference/components-reference/supported-bindings/eventgrid/#azure-ad-credentials is very good, but it wasn't able to get this fully working in my environment.

**My environment:**
- Kubernetes (Azure AKS)
- ingress-nginx (Helm chart 4.8.1 with Dapr Annotations)
- Dapr 1.11.4
- ASP.NET Core 6.0 API

### Issue 1 - Bad Gateway / Service Unavailable

I found myself constantly running into this issue where Azure isn't able to hit the Web Hook URL as it doesn't seem to be responding during the provisioning stage. However it responds fine when I test it manually shortly after checking the Dapr and Azure logs.
After checking on the NGINX logs, I saw that I was often getting a 503 response from the Dapr sidecar when hitting the HTTP OPTIONS port and path. 

It seems that the component is trying to create the WebHook Subscription in Azure before the Dapr sidecar is fully ready, which is why we see the HTTP 503 response.
To get around this, I simply increased the replicas in Kubernetes to ensure that there was at least one Dapr sidecar running to response.

**Dapr Sidecar Log:**
> time="2023-10-11T22:29:31.537362452Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=dapr-event-grid-test01 instance=dapr-event-grid-test01-6f645594c8-vm2pk scope=dapr.runtime.http type=log ver=1.11.4time="2023-10-11T22:29:34.551680101Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=dapr-event-grid-test01 instance=dapr-event-grid-test01-6f645594c8-vm2pk scope=dapr.runtime.http type=log ver=1.11.4time="2023-10-11T22:29:34.551722502Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=dapr-event-grid-test01 instance=dapr-event-grid-test01-6f645594c8-vm2pk scope=dapr.runtime.http type=log ver=1.11.4time="2023-10-11T22:29:38.561889738Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=dapr-event-grid-test01 instance=dapr-event-grid-test01-6f645594c8-vm2pk scope=dapr.runtime.http type=log ver=1.11.4time="2023-10-11T22:29:40.551656377Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=dapr-event-grid-test01 instance=dapr-event-grid-test01-6f645594c8-vm2pk scope=dapr.runtime.http type=log ver=1.11.4time="2023-10-11T22:29:40.551803279Z" level=debug msg="{ERR_HEALTH_NOT_READY dapr is not ready}" app_id=dapr-event-grid-test01 instance=dapr-event-grid-test01-6f645594c8-vm2pk scope=dapr.runtime.http type=log ver=1.11.4time="2023-10-11T22:29:42.07166219Z" level=error msg="error reading from input binding myapplication: failed to create or update event subscription: GET https://management.azure.com/subscriptions/13c38e4f-af2e-47c6-be0e-1a5348b735b0/providers/Microsoft.EventGrid/locations/uksouth/operationsStatus/9796D3EF-F58C-4598-B948-4A15FBF11184\n--------------------------------------------------------------------------------\nRESPONSE 200: 200 OK\nERROR CODE: Url validation\n--------------------------------------------------------------------------------\n{\n  \"id\": \"https://management.azure.com/subscriptions/13c38e4f-af2e-47c6-be0e-1a5348b735b0/providers/Microsoft.EventGrid/locations/uksouth/operationsStatus/9796D3EF-F58C-4598-B948-4A15FBF11184?api-version=2022-06-15\",\n  \"name\": \"9796d3ef-f58c-4598-b948-4a15fbf11184\",\n  \"status\": \"Failed\",\n  \"error\": {\n    \"code\": \"Url validation\",\n    \"message\": \"Webhook validation handshake failed for https://mywebgateway.com/dapr-eventgrid/myapplication/api/events. Http OPTIONS request failed with response code ServiceUnavailable. For troublehooting, visit https://aka.ms/esvalidationcloudevent. Activity id:2c38bc14-9b23-4b35-92e7-e4adc00eb5af, timestamp: 10/11/2023 10:29:34 PM (UTC).\"\n  }\n}\n--------------------------------------------------------------------------------\n" app_id=dapr-event-grid-test01 instance=dapr-event-grid-test01-6f645594c8-vm2pk scope=dapr.runtime type=log ver=1.11.4time="2023-10-11T22:29:42.071799593Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 12979ms" app_id=dapr-event-grid-test01 instance=dapr-event-grid-test01-6f645594c8-vm2pk scope=dapr.runtime type=log ver=1.11.4

**Azure Logs:**
> {\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"Url validation\",\"message\":\"Webhook validation handshake failed for https://mywebgateway.com/dapr-eventgrid/myapplication/api/events. Http OPTIONS request failed with response code BadGateway. For troublehooting, visit https://aka.ms/esvalidationcloudevent.

> {\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"Url validation\",\"message\":\"Webhook validation handshake failed for https://mywebgateway.com/dapr-eventgrid/myapplication/api/events. Http OPTIONS request failed with response code ServiceUnavailable. For troublehooting, visit https://aka.ms/esvalidationcloudevent.

### Issue 2 - 401 Unauthorized

Once Issue 1 was resolved, and the Dapr Sidecar was responding, I started to see an Unauthorized error.
Thanks to the logging, I zoned in on the JWT token by enabling the Debug logs on NGINX to capture the value and inspect it. The `iss` value was `https://sts.windows.net/{tenantId}/` however the component requires validation against `https://login.microsoftonline.com/{tenantId}/v2.0` 
As configured here: https://github.com/dapr/components-contrib/blob/v1.11.4/bindings/azure/eventgrid/eventgrid.go#L52C11-L52C11

This was a side effect of creating the App Registration using Terraform and not specifying `accessTokenAcceptedVersion` value of `2`. This is discussed further here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/575

Thankfully, simply updating the Application Registration Manifest to specify version `2` was enough to resolve this issue.
This is also configurable on the [azuread_application](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application) Terraform resource using the property `requested_access_token_version` in the `api` block.

**Dapr Sidecar Log:**
> level=error msg="Failed to validate JWT in the incoming webhook request: \"iss\" not satisfied: values do not match"

**Log message from Azure Event Grid:**
> {\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"Url validation\",\"message\":\"Webhook validation handshake failed for https://mywebgateway.com/dapr-eventgrid/myapplication/api/events. Http OPTIONS request failed with response code Unauthorized. For troublehooting, visit https://aka.ms/esvalidationcloudevent.

One other thing to mention while reverting the changes to get the failed log messages is that when I put everything back to the correct configuration and restarted the pods, I saw the same errors again. I simply restarted the pods again and then I saw 401 Unauthorized, invalid `iss`. So I restarted for a second time and it created the Event Subscription...

**Comment by ItalyPaleAle** [comment]
Thank you for sharing these issues.

Yes, we had to make a fairly large breaking change to the Event Grid binding in 1.10. This was a necessity for security reasons, as in Dapr 1.9 the endpoint did not authenticate calls and anyone could have invoked that to deliver messages to your Dapr. The "correct" way to add authentication is to use Azure AD, which works great but is not the easiest to set up.

For issue 1: this seems like something we should be able to fix. 

For issue 2: IIRC the default for new apps is to use version 2. This seems to be more of an issue with Terraform than Dapr. However, we can update the logs to explain that v2 must be used.

**Comment by joshwright10** [comment]
@ItalyPaleAle, thank you very much!

**Comment by berndverst** [comment]
Closing this because we should instead rewrite the component to poll for messages (which is new in EventGrid). See: #3322
