### ISSUE TITLE
Cors

### ISSUE THREAD

**Issue by pamav** [dapr/components-contrib#3180]
## Ask your question here

Hi,

I have question about Dapr Cors:

I have WebApi(in c# and swagger) and from this API I do Dapr service invocation over url:
http://localhost:3500/v1.0/invoke/testapi/method/x/y

and I got always Cors error because in response missing in item Header:Access-Control-Allow-Origin
How can I configure Dapr add to response header item Access-Control-Allow-Origin with defined values?

It is possible?

Thx

**Comment by yaron2** [comment]
Dapr service invocation is meant to be run in-cluster, not directly from the browser. Are you trying to use this from a client application?
