### ISSUE TITLE
Has anyone tried the Zeebe connector with self hosted Camunda Platform 8?

### ISSUE THREAD

**Issue by umerkle** [dapr/components-contrib#3185]
I wonder if the Zeebe connectors are working with Camunda Platform 8 (self hosted).
Since it is based on Zeebe, this should be possible...

**Comment by umerkle** [comment]
Is it even in use??

**Comment by berndverst** [comment]
Please ask that question in Discord. Way better chance someone will respond :)

**Comment by umerkle** [comment]
Found an answer to my question:
https://www.linkedin.com/pulse/dapr-zeebe-camunda-demo-robert-vejvoda
Thanks to Robert Vejvoda!
