### ISSUE TITLE
Contributing.md Should Add Info on How To Actually Test Changes Locally

### ISSUE THREAD

**Issue by cicoyle** [dapr/components-contrib#3192]
I think we should explictly spell out how to test your changes in components-contrib in the `contributing.md`.

A user might not know to go to the `go.mod` file in `dapr/dapr` and update the replace to reference their local `components-contrib`. Then to run: `go mod tidy`, then to build dapr with it.

**Comment by berndverst** [comment]
The contrib repo only needs to document:
- unit tests
- conformance tests (done here: https://github.com/dapr/components-contrib/tree/master/tests/conformance)
- certification tests

The issue filed here actually belongs in dapr/dapr, but we can certainly link to the documentation which must exist in dapr/dapr instead.

Here is what we can link to: https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md

That page is the source of truth and should be kept up to date.
