### ISSUE TITLE
Kafka PubSub offset loss in dapr 1.12

### ISSUE THREAD

**Issue by olitomlinson** [dapr/components-contrib#3234]
Starting with dapr 1.12 if all consumers leave the group, the offsets will be lost after a short duration of time (couple of minutes) which is very bad.

dapr 1.11.0 - 1.11.5 do NOT have this issue and work ok.

looks like this can be fixed by upgrading Sarama client, by this fix in Sarama 1.42.0

https://github.com/IBM/sarama/pull/2700

**Comment by yaron2** [comment]
Fixed with https://github.com/dapr/components-contrib/pull/3235

**Comment by olitomlinson** [comment]
@yaron2 @berndverst I've validated the fix works as expected in `1.12.2-rc.2`
