### ISSUE TITLE
Competing Consumers Pattern support for Azure ServiceBus Topics

### ISSUE THREAD

**Issue by maurice-freitag** [dapr/components-contrib#3268]
We require using topics rather than queues as we often have multiple services consuming the same event. However we require that each event is only ever successfully consumed by one instance of a consuming service, i.e. we need the [Competing Consumer Pattern](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#consumer-groups-and-competing-consumers-pattern) offered by Dapr for some components. We built a workaround with Dapr's distributed lock provider but ideally this is something that Dapr should handle for us. Is there a reason why this isn't implemented yet?

**Comment by jjcollinge** [comment]
IIRC by default each dapr sidecar that uses the [Azure Service Bus Topic component](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus-topics/) will use it's own app-id value as the `consumerID` and thus will only compete with other instances of the same app. You can change this by explicitly setting the `consumerID` on the component so all consumers use the same value and thus compete.

**Comment by maurice-freitag** [comment]
> IIRC by default each dapr sidecar that uses the [Azure Service Bus Topic component](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus-topics/) will use it's own app-id value as the `consumerID` and thus will only compete with other instances of the same app. You can change this by explicitly setting the `consumerID` on the component so all consumers use the same value and thus compete across app-ids.

The behavior you described is actually what I'm looking for - Dapr should route the event to only one instance of an app-id. Sadly this doesn't work and according to the [docs](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-overview/#consumer-groups-and-competing-consumers-pattern) it's not supposed to as only Azure ServiceBus Queues are currently supported. 

I think the consumer id on the component config is for setting up [namespace consumer groups](https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-namespace/), e.g. for using the same service bus with the same topics across multiple Kubernetes namespaces without interference. 

The consumer id of the application, i.e. the one used for competing consumers should be configured alongside the app itself which it is: 
![image](https://github.com/dapr/components-contrib/assets/21076995/671afdeb-4710-4ada-86a7-9025f98deb6a)
This setting does not seem to work for Azrue ServiceBus Topics however :/

**Comment by berndverst** [comment]
We are only adding support for features directly supported by the service and its SDKs.

The competing consumer pattern cannot be supported by all Dapr "PubSub" components. The behavior you are looking for is inherently a queue behavior.

The assumption that all Dapr components can and should support the competing consumer pattern is incorrect. Dapr does not add anything magical to enable the competing consumer pattern - but rather relies on this native feature from the SDK and service.

Instead, the long overdue issue is to classify our "PubSub" components into queues and topics (streams) and document the behavioral issues.
