### ISSUE TITLE
Create a JSON Secret Store

### ISSUE THREAD

**Issue by cmendible** [dapr/components-contrib#327]
## Describe the proposal

The idea is to create JSON secret store so developers can save secrets in a JSON file anywhere on their boxes and then use those secrets both in components and code.

This will:

- Simplify the experience for those who want to start using secrets or the secrets API without having to deploy a solution such an Azure Key Vault.
- Devs will have a full Dapr secrets API experience out of the box.
- Preparing demos will be much simpler.

The idea is inspired in what the [.NET Secret Manager](Secret Manager) enables in terms of dev experience.

### Features:

Given the following JSON:

```json 
   {
        "ConnectionStrings": {
            "MySQL": "super secret connection string"
        }
   }
```

- Since no one wants such a store enabled in production environments the store must be enabled explicitly setting an environment variable: (i.e. DAPR_ENABLE_JSON_SECRET_STORE = "1")
- JSON must be flattened into a map of key and values resulting in 
    - key: "ConnectionStrings:MySQL"
    - value: "super secret connection string"
- Note that in the previous sample a colon (':') was used as a separator for the JSON properties. That will be the default behavior unless a `nestedSeparator` param is set in the component metadata.

**Comment by amanbha** [comment]
@cmendible Thanks for sharing the proposal and PR, this will definitely be helpful in dev environments. As I understand user will have to set the env var DAPR_ENABLE_JSON_SECRET_STORE before running Dapr, do you think it would be good if cli can set this up?

**Comment by cmendible** [comment]
A switch for dapr run so any child process can access the env var? Once we add the component we can add an issue in the Dapr repo to discuss this feature right?

**Comment by amanbha** [comment]
Yes, this env is used by this component in dapr process to enable this json secret store, so cli can just set the env var before launching Dapr.

**Comment by cmendible** [comment]
> Yes, this env is used by this component in dapr process to enable this json secret store, so cli can just set the env var before launching Dapr.

@amanbha I just opened https://github.com/dapr/dapr/issues/1589 to track this.

**Comment by amanbha** [comment]
Thanks @cmendible I have moved it to dapr cli
