### ISSUE TITLE
Add event metadata as expected for beta and stable pubsub

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#3321]
## Describe the proposal

We uncovered a bug in runtime where `content-length` metadata was conflicting with the expected value for the payload delivered to pubsub subscriber. The issue happened only with Pulsar and could not be reproduced with Redis, uncovering lack of consistency in how pubsub components handle event metadata. Redis, as a stable component should not have an incomplete implementation - uncovering gap in coverage for conformance tests too.

Long story short, conformant pubsub components should handle metadata and not ignore it.

TODO: validate if there is any existing beta or stable pubsub component that does not handle event metadata and cannot implement it - this would be a blocker to close on this issue.

As an alternative, we can accept the behavior difference and document it just like we do in the state store table in Dapr Docs: https://docs.dapr.io/reference/components-reference/supported-state-stores/

Please, comment and vote:

👍 Make event metadata standard for beta and stable components.
🚀 Document that beta and stable components can optionally implement event metadata handling and which ones have this feature.
🎉 Metadata is for component-specific implementations and there cannot be a consistent implementation. Just document which metadata is handled by each component.
👎 Leave it optional and undocumented.

References:
https://github.com/dapr/dapr/issues/7413
https://github.com/dapr/components-contrib/pull/3320

**Comment by jjcollinge** [comment]
Just as an FYI, when I originally worked on pubsub metadata many moons ago it was to break the abstraction layer to support specific features of Azure Service Bus PubSub such as to allow a user to set the session ID or other attributes on an Azure Service Bus message to enable specific functionality. See the implementation https://github.com/dapr/components-contrib/blob/main/common/component/azure/servicebus/message.go. Therefore, it was not meant as a general purpose feature to attach common "metadata" to any message in a general way and was only documented in the specific components that supported it. So rather than saying a PubSub supports metadata I think of it as a PubSub supports a feature (such as ASB Sessions) by using metadata. This was a long time ago and I am not sure whether the use of pubsub metadata has evolved or the use has changed but thought I would share that if it helps.

**Comment by artursouza** [comment]
> Just as an FYI, when I originally worked on pubsub metadata many moons ago it was added to **break** the PubSub abstraction to support implementation specific features of Azure Service Bus PubSub such as to allow a user to set the session ID or other attributes on an Azure Service Bus message to enable specific functionality. See the implementation and notice there is explicit mapping to and from Message attributes that have meaning in ASB https://github.com/dapr/components-contrib/blob/main/common/component/azure/servicebus/message.go. Therefore, it was not meant as a general purpose feature to attach common "metadata" to any message in a general way and at the time was only documented in the specific components that explicitly used it. So rather than saying a PubSub supports metadata I think of it as a PubSub supports an implementation specific feature by using metadata; if it is not implementation specific then it should be part of the common request API to ensure consistency. This was a long time ago and I am not sure whether the use of pubsub metadata has evolved or how other components have implemented it but if there is a conflict due to the use of metadata that sounds implementation specific. Just thought I would share this in case it helps.
> 
> Also worth calling out that not all SDKs seem to implement this either. I recently added it to the go SDK.

This is a great point. Maybe there is no way to have a consistent implementation of event metadata since a simple passthrough is not the expected behavior for some of it.

**Comment by berndverst** [comment]
I made the same point in discord. Each component has a separate set of reserved metadata which will be used to tweak component behavior. That is what the metadata was originally created for. The passthrough of metadata came much later as a request.

You can only passthrough the metadata that is not a reserved keyword for the given pubsub component.

So absolute consistency won't be possible. I suggest that any user wishing to pass through custom data instead manually sends a cloud event using `application/cloudevent+json` to include cloud event extension attributes.

I have seen some folks with the requirement for Dapr to be sending the metadata as headers to the subscribing service. To me that's a completely separate request. It could be made part of the subscription metadata and we could say that such metadata would automatically be extracted from the cloud event envelope or some other place.
