### ISSUE TITLE
optimize kafka component to use a single sarama client

### ISSUE THREAD

**Issue by famarting** [dapr/components-contrib#3336]
## Describe the proposal

Currently the dapr components implementation instantiates two different sarama clients, one for the producer and another one for the consumer.

It should be possible to instantiate a single sarama client and then call `NewSyncProducerFromClient` and `NewConsumerGroupFromClient` instead of the current approach.

**Comment by berndverst** [comment]
Please do not open PRs before giving maintainers time to provide feedback on an issue.

@famarting some apps are only publishers while others are only subscribers.

**Comment by yaron2** [comment]
> Please do not open PRs before giving maintainers time to provide feedback on an issue.
> 
> @famarting some apps are only publishers while others are only subscribers.

Indeed, but in case they are both, they should be able to use the same client

**Comment by berndverst** [comment]
> > Please do not open PRs before giving maintainers time to provide feedback on an issue.
> > @famarting some apps are only publishers while others are only subscribers.
> 
> Indeed, but in case they are both, they should be able to use the same client

@yaron2 it doesn't matter anyway in this instance - I did some digging and under the hood the Sarama ProducerClient allocates a regular client first in its internal struct. So in that case we might as well explictly allocate it ourselves and just reuse that.
