### ISSUE TITLE
[PubSub Kafka] Dapr didn't reconcile missing subscription. Manual restart of dapr was required.

### ISSUE THREAD

**Issue by olitomlinson** [dapr/components-contrib#3350]
**runtime 1.12.2** (yes - I'm aware that 1.12.3 contains a subscriber fix, but I'm pretty sure that isn't the issue here)
**EKS**

---

1. On Feb 9th, I noticed that one of our Apps wasn't working as expected, upon further investigation we found that a particular Consumer Group (`ds-application.authz`) was missing 1 (out of 3) Topic subscriptions in Kafka.

`ds-application.authz` Consumer Group was expected to be subscribed to the following Topics

`ds-applicationdatabricks-created` - _subscribed as expected_ 
`ds-applicationrealm-created` - _subscribed as expected_ 
`ds-applicationrealm-user-created` - **missing** 

note : The consuming service only has 1 replica/pod, and there are only 1 partitions in the 3 Topics above, so its a really simple set-up.

---

**Just a note that the  `ds-applicationrealm-user-created` Topic hasn't always been missing from the Consumer Group**

I have logs from the 26th and 29th of January where I can see messages being processed from the `ds-applicationrealm-user-created` Topic as expected

time="2024-01-29T19:11:59.061442928Z" level=debug msg="**Processing Kafka message: ds-applicationrealm-user-created/0/3** [key=]" app_id=authz component="general-purpose-pubsub (pubsub.kafka/v1)" instance=sciplat-svc-authz-deployment-664d59564c-228hh scope=dapr.contrib type=log ver=1.12.2

---

2. My first thought was to check the sidecar logs to ensure that dapr was aware of the Topic (even if was missing in the Consumer Group in Kafka). **It did**. Many logs have all three Topics listed as expected, an example : 

time="2024-02-04T12:21:26.071093619Z" level=debug msg="**client/metadata fetching metadata for [ds-applicationdatabricks-created ds-applicationrealm-created ds-applicationrealm-user-created] from broker** luma-kafka-kafka-bootstrap.dotm-services:9092
" app_id=authz component="general-purpose-pubsub (pubsub.kafka/v1)" instance=sciplat-svc-authz-deployment-664d59564c-228hh scope=dapr.contrib type=log ver=1.12.2

---

3. Given that other Apps in the system which make use of the same PubSub component were operating correctly, there was little more I could do here. No point sending a canary message given that the Consumer Group had lost its subscription.

Therefore, I restarted the deployment at approx **11:47am on the 9th**

<img width="603" alt="image" src="https://github.com/dapr/components-contrib/assets/4224880/4f5bd6be-6f75-4ae1-8da5-7225b38c45c9">

**Immediately**, `ds-applicationrealm-user-created` Topic joined the Consumer Group, as expected

<img width="400" alt="image" src="https://github.com/dapr/components-contrib/assets/4224880/633b75b4-f113-4454-a024-0b43f9a5062c">

---

Attached below are **daprd** logs from the sidecar for the last 7 days. Therefore logs are present before and after the redeployment.

[extract-2024-02-10T20_29_06.226Z.csv](https://github.com/dapr/components-contrib/files/14230424/extract-2024-02-10T20_29_06.226Z.csv)

---

# Things of interest

## Thing 1

only after I did the redeployment (and normal service resumed), I see a specific log which says :

"Subscribed and listening to topics: [ds-applicationrealm-created ds-applicationrealm-user-created ds-applicationdatabricks-created]" 

This log does not appear in the days **before** the restart, which, in itself is not a problem, as my log retention doesn't go back far enough to when the sidecar started up earlier in January.

**However**, it does go to show that what ever code pathway generated this log is **essential** to recovering the subscription.

<img width="1447" alt="image" src="https://github.com/dapr/components-contrib/assets/4224880/7da2561d-467d-4c14-a09d-ee412156354d">

## Thing 2

[Broken Pipe](#broken-pipe)

_could be a red herring_

You will see lots of "broken pipe" and "timeout" errors coming from dapr related to kafka - However, even when I restarted the deployment, the errors continued, even though messages are now being processed. Therefor I'm 99% sure that this is red herring.

See graph below, which shows the broken "pipe errors" still occurring after restart.

<img width="1501" alt="image" src="https://github.com/dapr/components-contrib/assets/4224880/7a95d549-d8df-48ae-940e-bfb444fbe7ff">

**Comment by KrylixZA** [comment]
Is this potentially related to https://github.com/dapr/docs/issues/3707?

**Comment by KrylixZA** [comment]
I have seen this behaviour many times on my services that subscribe to multiple Kafka topics. We worked around the problem by creating a single Dapr component for each topic. This guaranteed that there was no misbehaviour of the consumer groups and running instances of the application.

**Comment by olitomlinson** [comment]
> Is this potentially related to [dapr/docs#3707](https://github.com/dapr/docs/issues/3707)?

Hmmm I don't think it is - On my Topics we only have 1 partition (for now), and just one replica of the consuming service, so the scenario is super super simple.

At first glance, the issue you raised in the Doc repo is touching on a more complex matter. I could be wrong of course!

**Comment by KrylixZA** [comment]
> > Is this potentially related to [dapr/docs#3707](https://github.com/dapr/docs/issues/3707)?
> 
> Hmmm I don't think it is - On my Topics we only have 1 partition (for now), and just one replica of the consuming service, so the scenario is super super simple.
> 
> At first glance, the issue you raised in the Doc repo is touching on a more complex matter. I could be wrong of course!

Nope, you're correct. If it's one replica and 1 partition, it's definitely not related.

**Comment by olitomlinson** [comment]
@KrylixZA Either way, I really appreciate you taking the time and effort to connect the dots!

**Comment by berndverst** [comment]
Are these dynamic subscriptions in code, or are these created declaratively (yaml)? That could make a huge difference for this issue. It might then be that the runtime does not consistently provide subscription information to each sidecar.

I'd encourage you to experiment with both approaches to see if this changes things for reproducing the problem.

My expectation is that declarative pubsub might be more error prone.

**Comment by olitomlinson** [comment]
I know we had the conversation on Discord, but I just want to add it here too for complete.

---

Yes, we are using declarative subscriptions, but I don't believe this is related to the issue, as I can see the missing Topic is echoed out in the logs, and those logs are emitted from component-contrib

example :

time="2024-02-04T12:21:26.071093619Z" level=debug msg="client/metadata fetching metadata for [**ds-applicationdatabricks-created ds-applicationrealm-created ds-applicationrealm-user-created**] from broker luma-kafka-kafka-bootstrap.dotm-services:9092
" app_id=authz component="general-purpose-pubsub (pubsub.kafka/v1)" instance=sciplat-svc-authz-deployment-664d59564c-228hh scope=dapr.contrib type=log ver=1.12.2

**Comment by olitomlinson** [comment]
Bump
