### ISSUE TITLE
Bump aws sdk version to support SQS over AWS JSON Protocol

### ISSUE THREAD

**Issue by Jossec101** [dapr/components-contrib#3354]
[SQS supports AWS JSON Protocol since last November](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-sqs-support-json-protocol/), but the project is using old sdk versions to support this.

Bumping the version to the following two would solve it:

Golang 1.x | aws/aws-sdk-go | v1.47.7 | AWS SDK for Go
-- | -- | -- | --
Golang 2.x | aws/aws-sdk-go-v2 | v1.28.0 | AWS SDK for Go V2

**Comment by yaron2** [comment]
Thanks for opening the issue. Feel free to submit a PR for this

**Comment by Jossec101** [comment]
> Thanks for opening the issue. Feel free to submit a PR for this

I've submitted it ;) #3355

**Comment by Jossec101** [comment]
#3355 was merged so closing this ;)
