### ISSUE TITLE
[State CosmosDB] SaveBulkStateAsync() throws context deadline exceeded exception

### ISSUE THREAD

**Issue by koumdev** [dapr/components-contrib#3399]
## Ask your question here
Hello,

I'm using Azure Cosmos DB state store and the SaveBulkStateAsync() to save bulk records, but an exception (`context deadline exceeded`) is thrown when the call takes more than 20 seconds(ish).

From [cosmosdb.go code](https://github.com/dapr/components-contrib/blob/cfee998aba0817ae07dc31bb53c34d21f6b9f4f2/state/azure/cosmosdb/cosmosdb.go#L83), it looks like there is a default timeout of 20 seconds.

All of the functions (`Get`, `Set`, `Delete`, ...) except `BulkGet` are using `defaultTimeout` to set the context timeout.

- Is that the reason why my call fails?
- Does that mean all the Azure Cosmos DB state store calls timeout after 20 seconds?
- Is there any way to change this timeout?
- It looks like all the bulk calls except `BulkGet` are actually processed as [single requests](https://github.com/dapr/components-contrib/blob/cfee998aba0817ae07dc31bb53c34d21f6b9f4f2/state/bulk.go#L127), so how come I am running into this timeout?

I'm using Dapr version `1.13.0`.

Thank you!

**Comment by berndverst** [comment]
Yes that would be why. It would need to be implemented as a new feature to make the timeout configurable.

The DotNet SDK making a single `SaveStateRequest` with multiple state items. The Dapr runtime notices whether this contains 1 or multiple items. If one item it calls the regular SaveState method, but if multiple - it calls the `Multi` method which is for batches.

Saving that batch times out of course.

FYI, CosmosDB has a limit of 100 operations per transactional batch - so you will not be able to save more than 100 items in a single SaveState operation.

https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/transactional-batch?tabs=dotnet

If you are saving no more than 100 items, then the only way to fix it will be by exposing a new feature that lets you control the timeout.

However, if you are attempting to save more than 100 items, then this cannot work anyway.

Hope this help. I'll tag this as a feature request for Dapr 1.14 so the configuration option can be exposed.
