### ISSUE TITLE
[State CosmosDB] Continuation token returned by QueryStateAsync() is invalid

### ISSUE THREAD

**Issue by koumdev** [dapr/components-contrib#3400]
Hi,

I'm using Azure Cosmos DB state store and the QueryStateAsync() method. I want to get all of my data and used `var query = "{\"filter\": {}}"`, but I run into an exception (`"state store statestorecosmos query failed: context canceled"`) if my database has more than 999 rows. I then tried to use pagination, but I'm having unexpected behaviors with the returned continuation token.

## Expected Behavior
If I have let's say 500 records in my container. I request 100 records. The token returned by QueryStateAsync() should allow me to read the next 100 records, and so on.

## Actual Behavior

The token returned by QueryStateAsync() after retrieving the first 100 records is empty, so if I supply that in the query I get the same exact 100 records as before. I can't continue reading the data.

## Steps to Reproduce the Problem
Using the .NET SDK:
```
var query = "{\"filter\": {}, \"page\": {\"limit\": 100}}";
var employeesResponse = await _daprClient.QueryStateAsync<Employee>(STORE_NAME, query, cancellationToken: cancellation);
// employeesResponse contains the first 100 records as expected

var paginationToken = employeesResponse.Token;
// Have to modify the token to escape the quotes first
...

query = $"{{\"filter\": {{}}, \"page\": {{\"limit\": 100, \"token\": {paginationToken}}}}}";
employeesResponse = await _daprClient.QueryStateAsync<Employee>(STORE_NAME, query, cancellationToken: cancellation);
// Should return the next 100 records, but doesn't because the token is empty. It returns the same 100 records returned previously
```
Or going directly to the API to just get 1 record at a time using this PowerShell script:

```
$firstResponse = Invoke-RestMethod -Method Post -ContentType 'application/json' -Body '{"filter": {}, "page": { "limit": 1}}' -Uri 'http://localhost:3500/v1.0-alpha1/state/statestorecosmos/query'

write-host "First results"
write-host $firstResponse.results

$token = $firstResponse.token
write-host "First results token: $token."

$query = '{"filter": {}, "page": { "limit": 1, "token": "' + $token + '"}}'
write-host "Next query: $query."

$secondResponse = Invoke-RestMethod -Method Post -ContentType 'application/json' -Body $query -Uri 'http://localhost:3500/v1.0-alpha1/state/statestorecosmos/query'

write-host "Second results"
write-host $secondResponse.results

$token2 = $secondResponse.token
write-host "Second results token: $token2."
```
You'll notice that the key in the result of the first query is the same as the one from the second query, so it's returning the same record.

## Additional Remarks
From the [component code](https://github.com/dapr/components-contrib/blob/cfee998aba0817ae07dc31bb53c34d21f6b9f4f2/state/azure/cosmosdb/cosmosdb_query.go#L257) it looks like there is a bug, the limit is never forwarded to Cosmos DB. It is only used to return a subset of the result. Therefore the component is actually reading the default page size. The token returned by the component, if returned, causes unexpected behaviors.

I'm using Dapr version `1.13.0`.

Thanks!

**Comment by berndverst** [comment]
Query API is Alpha and unsupported. We are not currently planning to advance the Query API. Additionally, the CosmosDB Go SDK we are using does not have native Query support and our attempt to implement this is extremely limited and error prone.

Please consider using the Cosmos DB SDKs directly for querying.
