### ISSUE TITLE
can we publish message to queue in rabbit mq instead of a topic?

### ISSUE THREAD

**Issue by isaacnikon93** [dapr/components-contrib#3402]
i am trying to use rabbit mq pubsub component and try to send a message to queue directly instead of using a topic
i have a few queues already created, i tried using bindings but it was causing some overflow when i was trying to define ttlInSeconds of "2592000" (30 days), according to RabbitMQ documentation if we pass a empty string as exchange and pass a routingKey 
https://www.rabbitmq.com/tutorials/amqp-concepts#exchange-default

i am trying to send it like below
`
d.client.PublishEvent(ctx, "rabbit-mq-pubsub", "", data.Message,
			client.PublishEventWithMetadata(
				map[string]string{
					"priority":   fmt.Sprint(data.Priority),
					"routingKey": queueName,
				},
			))
`

any pointers will be helpful

**Comment by berndverst** [comment]
I am not sure. I don't believe we currently have any active contributor with deep RabbitMQ knowledge (through I could be wrong). If you'd like to look through the code we have it's here. PRs welcome to improve things.

The SDK we use: github.com/rabbitmq/amqp091-go (currently on v1.8.1)

Dapr PubSub code:
https://github.com/dapr/components-contrib/tree/main/pubsub/rabbitmq/

and

Dapr Binding code
https://github.com/dapr/components-contrib/blob/main/bindings/rabbitmq/

**Comment by yaron2** [comment]
@isaacnikon93 see this: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-rabbitmq/#use-topic-exchange-to-route-messages
