### ISSUE TITLE
Make 'scopes' optional in oauth2clientcredentials middleware

### ISSUE THREAD

**Issue by anschoewe** [dapr/components-contrib#3406]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Not all OAuth2 token issuers require scopes during the client_credential token exchange.  For example, [Auth0 does not accept 'scopes'](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow/call-your-api-using-the-client-credentials-flow).  

Therefore, **I believe 'scopes' should be optional in the [oauth2clientcredentials](https://docs.dapr.io/reference/components-reference/supported-middleware/middleware-oauth2clientcredentials/) middleware component.**  It's currently required to have a value.

## Release Note

oauth2clientcredentials now supports optional scopes, making it compatible with token issuer's like Auth0.

RELEASE NOTE:

**Comment by berndverst** [comment]
Are you able to configure Auth0 using an empty value for the scopes today?

**Comment by anschoewe** [comment]
Yes. I’ve been using it for years without specifying a scope. By that I mean I don’t even pass the key “scopes” in the request. Totally absent.

**Comment by simulified** [comment]
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
