### ISSUE TITLE
process component sentinel error: [INIT_COMPONENT_FAILURE]: initialization error occurred for sentinel (middleware.http.sentinel/v1)

### ISSUE THREAD

**Issue by bunengxiu** [dapr/components-contrib#3408]
An error occurred following the [documentation tutorial](https://docs.dapr.io/reference/components-reference/supported-middleware/middleware-sentinel/), deploy context is [nodeapp.txt](https://github.com/dapr/dapr/files/15192595/nodeapp.txt)

error log:
process component sentinel error: [INIT_COMPONENT_FAILURE]: initialization error occurred for sentinel (middleware.http.sentinel/v1): [CREATE_COMPONENT_FAILURE]: initialization error occurred for sentinel (middleware.http.sentinel/v1): process component sentinel error: error creating HTTP middleware middleware.http.sentinel/v1: error to init sentinel with config '{\"Version\":\"v1\",\"Sentinel\":{\"App\":{\"Name .......

Dapr 
  Runtime -- version 1.13.2
kubectl
  Client Version: v1.28.3
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.28.2

**Comment by bunengxiu** [comment]
Sendtinel is alpha, I see
 Following the tutorial docs, sentinel not work, some errors occurred
 you means that the error will be fixed in the future, maybe for the 1.14 or more later

**Comment by berndverst** [comment]
@bunengxiu right now nobody is working on or investigating this component. It might not be fixed until 1.14 or later (probably later).
