### ISSUE TITLE
Enhance Dapr with RabbitMQ x-consistent-hash Exchange Support

### ISSUE THREAD

**Issue by rpersent** [dapr/components-contrib#3423]
## Describe the feature
This feature request proposes adding support for the RabbitMQ x-consistent-hash exchange type in Dapr.

## Business Value
* Improved scalability: x-consistent-hash distributes messages across multiple consumers in a consistent manner, even when adding or removing consumers. This leads to better load balancing and avoids message loss.
* Increased fault tolerance: Messages are routed based on a hash of the message key, ensuring messages with the same key are always delivered to the same consumer. This helps with handling consumer failures and retries.
* Simplified development: Developers can leverage the built-in functionality of x-consistent-hash exchanges for reliable message distribution without needing to implement custom logic.

## Release Note
RELEASE NOTE: ADD Support for RabbitMQ x-consistent-hash exchange type in Dapr.

**Comment by berndverst** [comment]
Can you provide any documentation on where / how this property must be used?

What do the publishers have to do? What do the subscribers have to do?

The official RabbitMQ SDK used by Dapr is this one: https://github.com/rabbitmq/amqp091-go
As a result Dapr will also be limited to the capabilities of that SDK.

**Comment by berndverst** [comment]
I briefly looked at the plugin article but it wasn't clear to me how that can be accomplished using the Rabbit MQ Go client SDK. Maybe it's possible, maybe not?

Anyone who wishes to pick up this work should first find a reference implementation using the RabbitMQ/amqp091-go client specifically.
