### ISSUE TITLE
fatal error: unlock of unlocked mutex

### ISSUE THREAD

**Issue by stefan-shredder** [dapr/components-contrib#3443]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.13.4

## Expected Behavior

When Dapr recovers from an unhealthy state, it shouldn't run into a fatal error while trying to unlock an unlocked mutex.

## Actual Behavior

We have different services that run into that behaviour from time to time. The dapr container enters an unhealthy state (for unknown reason) and after it enters the healthy state again, it runs into an fatal error: sync: unlock of unlocked mutex. I have attached the log.

[slotbooking-service-868d448f46-6kj59.log](https://github.com/user-attachments/files/15640117/slotbooking-service-868d448f46-6kj59.log)

The good part is, that the container successfully recovers from it.

## Steps to Reproduce the Problem

-

## Release Note

-

**Comment by yaron2** [comment]
@stefan-shredder can you confirm if this has been fixed in Dapr 1.14.x?

**Comment by yaron2** [comment]
Thanks, closing for now
