### ISSUE TITLE
Oracle Database state store as stable

### ISSUE THREAD

**Issue by magloriusmra** [dapr/components-contrib#3460]
Is something planned to certify the Oracle Database state store component as stable ?

**Comment by berndverst** [comment]
Nobody is actively working on writing the required conformance and certification tests for this. If someone wants to contribute this they can - which then would make the component stable. It's now too late for Dapr 1.14 however, so earliest release could be 1.15.

**Comment by berndverst** [comment]
By the way, the trickiest part here is finding someone who sponsors an Oracle Database server the Dapr project can run integration tests against very 8 hours, and also on demand at maintainer discretion.
