### ISSUE TITLE
error returned from app while processing pub/sub/ event xxxxx, Error while dialing dial top 127.0.0.1:6100: connect: cannot assian requested address  

### ISSUE THREAD

**Issue by tomatoqjq** [dapr/components-contrib#3461]
error msg:
pub/sub event, on consumer: (*pulsar.partitionconsumer) (0xc001b53c00), receivedrime:time.Time{wal1:0xc196b8e4e159ca33.

error returned from app while processing pub/sub/ event xxxxx, Error while dialing dial top 127.0.0.1:6100: connect: cannot assian requested address...

 uses: dapr run  application  and C++SDK。

**Comment by berndverst** [comment]
That means your app was not reachable via your configured app protcol (grpc or HTTP) on `127.0.0.1:6100` - this is not a component issue. Please troubleshoot the app is reachable on the app port. Closing this issue.
