### ISSUE TITLE
Redis statestore TTL is not atomically set

### ISSUE THREAD

**Issue by jjcollinge** [dapr/components-contrib#3482]
## Expected Behavior
When you set a key with a TTL it is applied atomically so that the key is never written without a TTL.  I'm assuming this is the intended behaviour.

## Actual Behavior
The Redis implementation of the statestore does not set the TTL to the key "atomically" therefore it is possible for a key to be set without a TTL during a partial failure. 

## Steps to Reproduce the Problem

Invoke a failure before [this line ](https://github.com/dapr/components-contrib/blob/beb3f8f456dbd6374ffc0c7edb542d0a80ee6456/state/redis/redis.go#L364) and check the key is written without a TTL.

## Release Note

RELEASE NOTE: **FIX** Bug in Redis statestore where TTL was not atomically applied

**Comment by berndverst** [comment]
This requires discussion - only if we are ok with **dropping Redis < 6.0 support** can we implement this.

https://redis.io/docs/latest/commands/set/

The SET command has a KEEPTTL feature in Redis 6 onward.

However, given that we technically offer Redis 5 support.. this is tricky. The Redis transaction feature is not a real atomic transaction with rollback by the way, so even using a transaction pipeline it is possible that a key gets saved while the TTL is never set!

Only definitive solution I see is to drop Redis 5 support, but this would be a breaking change we have to announce at least a release or two out.

For the time being I would consider this working as intended @jjcollinge.
