### ISSUE TITLE
SQS component prevents deploying pods without queue permissions, even when not using the queue

### ISSUE THREAD

**Issue by eraserhd** [dapr/components-contrib#3483]
## Expected Behavior

When service A has permission to an SQS queue and service B does not, and service B does not use the queue, we can deploy service B.

NOTE: In our EKS cluster, we grant `sqs:GetQueueUrl` permission only to pods that need it, scoped to specific queues.

## Actual Behavior

Service B fails because the sidecar calls `sqs:GetQueueUrl` with Service B's permissions when parsing metadata.  The pod enters CrashLoopBackoff.

## Steps to Reproduce the Problem

1. Create an SQS queue.
2. Create a Dapr input binding component for this queue.
3. Deploy Service A with a Service Role that can access this queue. This should work.
4. Deploy Service B without queue permissions or usage.
5. Observe Service B's pod fail to boot.

## Release Note

RELEASE NOTE: **FIX** SQS component defers GetQueueURL until Invoke or Read, allowing pods with different queue permissions to coexist.

## Other Notes

This is a repeat of #2721, which was closed due to being stale, and could be a repeat of #539.

**Comment by berndverst** [comment]
Expected behavior.

You should make sure to scope components such that apps / services that don't have permissions for the component do not load that component.

It's not clear to me why a failing component in one service hurts an entirely unrelated service (with a different Dapr app ID). That shouldn't be the case, but is besides the point.

Make sure to use distinct app IDs for distinct services and scope the components in the component.yaml.

https://docs.dapr.io/operations/components/component-scopes/

**Comment by berndverst** [comment]
This same behavior is true for any components that for example rely on AWS IAM or Azure Entra ID managed identity permissions, but where the given app / pod hasn't been granted the necessary permissions.

This is a configuration problem, not a code problem. Components should always be scoped for this very reason if you are working in restricted environments.

**Comment by berndverst** [comment]
Alternatively:
Edit the component spec and add `ignoreErrors: true` - that way the fact the component fails to init will not prevent the sidecar from crashing (and hence the pod from failing)

https://docs.dapr.io/reference/resource-specs/component-schema/

**Comment by berndverst** [comment]
If you don't scope a component to a specific app ID then the every sidecar of every app/service with load that component whether or not it is actually used. This is how Dapr works by design.

**Comment by berndverst** [comment]
As discussed in Discord - scoping is the right way to handle this. I think this issue can be closed!
