### ISSUE TITLE
Ability to Generate SAS url for Azure blob Storage 

### ISSUE THREAD

**Issue by bhagya05** [dapr/components-contrib#3484]
## Describe the feature

Users should be able to generate SAS url for their container or specific blob.
https://learn.microsoft.com/en-us/azure/ai-services/translator/document-translation/how-to-guides/create-sas-tokens?tabs=blobs
 
## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
@bhagya05 please use managed identity credentials or Azure CLI Credential instead. SAS tokens are inferior from a security perspective and their use is discouraged.

Dapr is also not a **access management** solution. The access to your storage account should be managed outside of Dapr. As such, you should create a SAS URL manually or via Azure Storage Management SDKs.

I'll defer to @ItalyPaleAle's opinion here, but my opinion (as a maintainer and Microsoft employee) is that we should not implement this feature.

**Comment by ItalyPaleAle** [comment]
I agree with Bernd on the security implications, however there _could_ be use cases where having a SAS token is required (legacy apps for example).

I'm happy to accept a PR to add this feature to the binding if someone wants to contribute it
