### ISSUE TITLE
Support ClientAuth with SSL for Kafka

### ISSUE THREAD

**Issue by karoldeland** [dapr/components-contrib#349]
## Describe the proposal
It seems that the ClientAuth SSL authentication is not supported in by the Kafka pubsub component. 

kafka.go :
```go
 func updateAuthInfo(config *sarama.Config, saslUsername, saslPassword string) {
	config.Net.SASL.Enable = true
	config.Net.SASL.User = saslUsername
	config.Net.SASL.Password = saslPassword
	config.Net.SASL.Mechanism = sarama.SASLTypePlaintext

	config.Net.TLS.Enable = true
	config.Net.TLS.Config = &tls.Config{
		//InsecureSkipVerify: true,
		ClientAuth: 0,
	}
}
```

We are using SSL with Client Certificate to authenticate a consumer or a producer. The sarama provider seems to support it. Is it possible to consider supporting this auth mecanism?

**Comment by yaron2** [comment]
Yes, that's a very plausible requirement.

**Comment by regul4rj0hn** [comment]
Sorry to necro this one, but is there any chance we could get this feature for Kafka pub-sub with SSL authentication?
