### ISSUE TITLE
Error net/http: invalid header field value for \"__key\ in Dapr version 1.13.5 on Windows machine

### ISSUE THREAD

**Issue by teachmeabhinav** [dapr/components-contrib#3503]
## Expected Behavior

 

When you run application on windows it should subscribe and forward the message to application route in version 1.13.5 of Dapr on windows machine

## Actual Behavior
When you run application on windows it is  subscribing  but not forwarding the message to application route in version 1.13.5 of Dapr however it was working perfectly fine in version 1.12.4 on windows machine.
Please refer to attached screen shot
![image](https://github.com/user-attachments/assets/f59e3a29-258b-433c-bee3-cff5b8fe0044)

It give the error **"net/http: invalid header field value for \"__key\""**
It don't see any issue in Linux

Machine configuration Windows 10

## Steps to Reproduce the Problem

- Upgrade the Dapr form version 1.12.4 to 1.13.5 on your windows machine
- Run you application
- you will the error

**Comment by rokrust** [comment]
I'm getting this issue on version 1.13.2 as well

**Comment by sandeepm1980** [comment]
I am having same issue. Kafka pubsub is not working on Windows platform. It's a blocker for us. It used to work in 1.12 verson and before. Please fix ASAP

**Comment by yaron2** [comment]
> I am having same issue. Kafka pubsub is not working on Windows platform. It's a blocker for us. It used to work in 1.12 verson and before. Please fix ASAP

Hi, I'm a Dapr maintainer. Please ping me on Dapr Discord. My handle is yaron2

**Comment by chetnamittal** [comment]
I am having the same issue 
It does not work in windows platform 
This used to work in previous versions 
Can you please help us by getting this fixed

**Comment by yaron2** [comment]
This issue is being worked on now and will be fixed for Dapr 1.14.2

**Comment by yaron2** [comment]
Hi all,

Dapr 1.14.2-rc.1 is out - please see if it fixes your issues and give feedback here

**Comment by teachmeabhinav** [comment]
@yaron2  We are able to get message after updating to 1.14.2-rc.1

**Comment by yaron2** [comment]
> @yaron2 We are able to get message after updating to 1.14.2-rc.1

Great validation, thanks!

**Comment by passuied** [comment]
@yaron2 we'll be testing this version shortly too

**Comment by passuied** [comment]
Validated the fix on our end and we're also good with it!

**Comment by yaron2** [comment]
> Validated the fix on our end and we're also good with it! Thanks a lot for the quick turnaround

Thanks! We'll now go ahead and release the patches

**Comment by passuied** [comment]
@yaron2 actually, I think we may have an issue. The additional encoding is breaking some code as it's encoding `=` for instance which is a valid ascii character.
So it is making the change non-bw compatible which may break many consumers...

**Comment by yaron2** [comment]
Hi all, we now have Dapr 1.14.2 out with the fix - please notice its OPT-IN: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/#receiving-message-headers-with-special-characters
