### ISSUE TITLE
Promote AWS Secrets Manager secret store component to Beta

### ISSUE THREAD

**Issue by smitterh** [dapr/components-contrib#3504]
## Describe the feature

The AWS Secrets Manager secret store component requires certification tests to be moved from Alpha to Beta.
This will accelerate Secret Store building block adoption for AWS Dapr users.

## Release Note

RELEASE NOTE:

**Comment by cicoyle** [comment]
[We need these requirements to be met](https://docs.dapr.io/operations/components/certification-lifecycle/#beta)

**Comment by elena-kolevska** [comment]
Successful run: https://github.com/dapr/components-contrib/actions/runs/11617637325/job/32353321405?pr=3588
