### ISSUE TITLE
Binding AWS Kinesis - reuse client credentials

### ISSUE THREAD

**Issue by soisyourface** [dapr/components-contrib#3508]
## Describe the proposal
Currently when creating a Kinesis binding, at least locally, you must pass in the "static credentials" for the secret(key, id, session?). This is not an ideal experience.

Propose that when creating the KCL for Kinesis that we use the existing AWS client credentials instead of remaking them.

If a complete replacement isn't wanted, then perhaps only using the existing client credentials will be used if the static credentials aren't defined in the config.

**Comment by yaron2** [comment]
This is definitely a good idea and we're doing the same for a lot of our other AWS components - please see how we reuse and handle authentication in AWS SQS for example

**Comment by sicoyle** [comment]
Hi, I'm working on improving our AWS IAM auth experience across all AWS components. We have a few different AWS Auth Profiles, and a new one that I'm adding for people to Assume an IAM Role. In some cases, we do allow you to load the default configuration for your AWS components here https://github.com/search?q=repo%3Adapr%2Fcomponents-contrib%20LoadDefaultConfig&type=code 

Is that more of what you're looking for here?

I would also urge you to look at the more temporary auth profiles that have rotating credentials as an improved security posture. That would include the new IAM Roles Anywhere profile with rotating creds every few minutes. https://github.com/dapr/components-contrib/blob/main/.build-tools/builtin-authentication-profiles.yaml
