### ISSUE TITLE
Allow consuming/producing Kafka tombstones when using Kafka PubSub with Avro

### ISSUE THREAD

**Issue by GregerTomas** [dapr/components-contrib#3510]
Currently, consuming/producing tombstones Kafka messages is not supported when using Avro schema validation. Null values should be treated specially and not be validated by a schema.

See also https://discord.com/channels/778680217417809931/901141467840524289/1276090536976973845

**Comment by passuied** [comment]
@GregerTomas as mentioned on discord, we were able to reproduce the issue but only on the produce. I have a fix and will submit a PR shortly

**Comment by GregerTomas** [comment]
@passuied  Yes, sounds good. I was able to recieve tombstones which were sent by non-Dapr producers (aka custom Dapr header were not present). When I sent a tombstone using Dapr, I recieved mentioned error.

**Comment by passuied** [comment]
@GregerTomas this should be resolved. Please confirm

**Comment by GregerTomas** [comment]
> @GregerTomas this should be resolved. Please confirm

confirmed
