### ISSUE TITLE
Need guidance on starting daprd built for component checking (OOM error)

### ISSUE THREAD

**Issue by alg** [dapr/components-contrib#3553]
I have dapr 1.14.1 installed into the system via nix. I've been working on the feature to support TAG type to the Redis State Query and was going to test how it works in the test app. So I followed the tutorial of building the custom `daprd`, replacing the version in the `~/.dapr/bin` etc. When I start, it immediately exists with the `killed` error. The exit code is `137` (OOM error).

I compared what old version displays when started:

```sh
→ ./daprd.bak help
INFO[0000] Starting Dapr Runtime -- version 1.14.1 -- commit 81cb1f5c4709535b03799e7e1826fbab0315b90b  instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.14.1
...
```

And the new one:

```sh
→ ./daprd help
zsh: killed     ./daprd help

→ echo $?
137
```

File type looks correct:

```sh
→ file daprd
daprd: Mach-O 64-bit executable arm64
```

Clearly something is wrong here. Can anyone suggest where to look next?

I'm on M1 so I took the dist binary from `dist/darwin_arm64/debug` obviously. There was no any other.

**Comment by yaron2** [comment]
Did you replace an earlier binary? If so, you must remove/delete the existing binary before copying over the new one

**Comment by alg** [comment]
You mean step 6 here? https://github.com/alg/components-contrib/blob/main/docs/developing-component.md

Yes, I've done that. After trying `dapr run ...` and seeing it reporting accidental kill of daprd on start I started looking into problem. Got to the point where I just ran `daprd` manually (notice "d") as described in the original message.
