### ISSUE TITLE
MQTT over TLS 

### ISSUE THREAD

**Issue by olegchorny** [dapr/components-contrib#357]
Hello @kumaya 
Is possible to leverage mqtt pubsub with enabled encryption on the server side?
It seems like I need to pass the tls flag somehow, but I didn't manage to find the right approach yet.

**Comment by kumaya** [comment]
@olegchorny Thank you for reaching out.

Currently, the pubsub mqtt implementation does not support tls configuration.

However, this can be done by enhancing the [mqtt metadata](https://github.com/dapr/components-contrib/blob/master/pubsub/mqtt/metadata.go) to accept relevant certificates and then setting `opts.SetTLSConfig()` while creating the connection.

@yaron2 If accepted, I can take it up.

**Comment by yaron2** [comment]
@kumaya can you take this?

**Comment by kumaya** [comment]
> @kumaya can you take this?

@yaron2 I can work on this.

**Comment by yaron2** [comment]
hey @kumaya, any update?

**Comment by kumaya** [comment]
> hey @kumaya, any update?

@yaron2 I am weighing on options to provide client certificate and key in metadata as string variable. Are there any better ways inbuilt/best practices to provide the cert and key variable as input parameters ?
