### ISSUE TITLE
[sql store] Reminder callbacks continue after reminder is unregistered

### ISSUE THREAD

**Issue by LMWF** [dapr/components-contrib#358]
From gitter.  SQL is being used as the actor store.  When redis is used the behavior is as expected.

## Expected Behavior

Unregistering a reminder should succeed and no subsequent callbacks for this reminder should occur.

## Actual Behavior

Unregistering a reminder succeeds but reminder callbacks continue happening.

This error - "items was not updated" appeared https://github.com/dapr/components-contrib/blob/b1c8dd5e3166cda5000c2bfe04b318554721c94a/state/sqlserver/sqlserver.go#L349

## Steps to Reproduce the Problem

Use sql as actor store.
Register a reminder.  
Unregister it.
Reminder callback still happens later

Note the user api calls are not happening quickly - there is time in between them.

**Comment by LMWF** [comment]
I can't repro this with the current master branch when using sql as the state store.  I tried some different reminder periods to see if that made a difference and still did not observe this - the reminder did not continue firing after it was unregistered, and the actual state for the corresponding reminder key in sql was correct. 

This issue https://github.com/dapr/dapr/issues/973 would cause the behavior described, but it would require registering the same reminder multiple times quickly.  It does not sound like that was done.

**Comment by amanbha** [comment]
closing as not repro.
