### ISSUE TITLE
HTTP error 500 context deadline exceeded when attempting to persist state to a MongoDB instance

### ISSUE THREAD

**Issue by simonrhart** [dapr/components-contrib#359]
## Expected Behavior

To invoke the Dapr sidecar directly i.e. http://localhost:3500/v1.0/state/mongostore to store state against a MongoDB database instance and return HTTP 201 return code in that the payload has persisted in the database.

## Actual Behavior

I continuously have a return code of HTTP 500 with a response text of:
`
{
    "errorCode": "ERR_STATE_SAVE",
    "message": "context deadline exceeded"
}
 `

## Steps to Reproduce the Problem

Create a MongoDB yaml file that looks similar to this:

`
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongostore  
spec:
  type: state.mongodb
  metadata:
  - name: host
    value: localhost:27017
  - name: username
    value: root
  - name: password
    value: <replace-with-your-password>
  - name: databaseName
    value:  
  - name: collectionName
    value:  
  - name: writeconcern
    value: 
  - name: readconcern
    value: 
  - name: operationTimeout
    value: 
`

Run an application using Dapr i.e. I am using a .NET core app here: 

`
dapr run --app-id myapp --port 3500 --app-port 5000 --components-path ./components dotnet run
`

Then post the following:

`
POST http://localhost:3500/v1.0/state/mongostore
[
        {
          "key": "2",
          "value": "value2"
          }
]
`

## Other useful information about this bug
Redis state store works ok within the same application/instance of Dapr. 
I can successfully communicate with the MongoDB instance using other applications outside of Dapr.
I have a user name and password configured in MongoDB because there is a bug in the C# SDK that requires it. I have not set the database collection or database name in the yaml for this component.

**Comment by shalabhms** [comment]
@simonrhart , 

Regarding - "I can successfully communicate with the MongoDB instance using other applications outside of Dapr."

What is the address that you are using in connecting the MongoDB instance?

**Comment by simonrhart** [comment]
@shalabhms 

In my Dapr app I have written my own repository instead of using the Dapr one and this is the connection string/ctor code that works ok:

`
mongodb://root:<mypassword>@localhost:27017
`

Where <mypassword> is my actual password of course.

The client code I am using this is:

`
  IMongoClient mongoClient = new MongoClient(connectionString);
`

In Robo 3T I am just using: localhost:27017

**Comment by jjcollinge** [comment]
I believe I saw this issue when writing the conformance tests for mongo (https://github.com/dapr/components-contrib/pull/336/commits/4492d887ff2e4ff53fce92e798ce87b3e800fa2d) <- this has fixes in.
- Firstly, there's an [issue on this line](https://github.com/dapr/components-contrib/blob/a6a0e3e3bc7639705641c31ab849d2b3a969ba1a/state/mongodb/mongodb.go#L279) where it is using `defaultTimeout` instead of the `operationTimeout` defined in metadata.
- Secondly, and critically, all other operations use `m.operationTimeout` which is never set so immediately fails on any operation. We need to add: `m.operationTimeout = meta.operationTimeout` to actually set it.

**Comment by shalabhms** [comment]
Thanks @jjcollinge for bringing the issue details.

#370 has fixed the issue now.

**Comment by simonrhart** [comment]
Thanks for fixing chaps, will test when it has been merged
