### ISSUE TITLE
Multi() transaction operations api for redis should use HSET or HDEL

### ISSUE THREAD

**Issue by youngbupark** [dapr/components-contrib#375]
## Steps to Reproduce the Problem

1. Set `key_for_hset` to `hset_value` using [set method](https://github.com/dapr/components-contrib/blob/a086a42f2b0af5e0416560b10cbed8d15743921b/state/redis/redis.go#L279)
2. Upsert `key_for_hset` to `set_value` using [multi method](https://github.com/dapr/components-contrib/blob/a086a42f2b0af5e0416560b10cbed8d15743921b/state/redis/redis.go#L296)
3. Get `key_for_hset` using [get method](https://github.com/dapr/components-contrib/blob/a086a42f2b0af5e0416560b10cbed8d15743921b/state/redis/redis.go#L218)

## Expected Behavior

return value is `set_value`

## Actual Behavior

return value is `hset_value`

Root case:
[multi method](https://github.com/dapr/components-contrib/blob/a086a42f2b0af5e0416560b10cbed8d15743921b/state/redis/redis.go#L296) uses `SET` and `DEL` operation but [set method](https://github.com/dapr/components-contrib/blob/a086a42f2b0af5e0416560b10cbed8d15743921b/state/redis/redis.go#L279) and [get method](https://github.com/dapr/components-contrib/blob/a086a42f2b0af5e0416560b10cbed8d15743921b/state/redis/redis.go#L218) use hash key operations.

How can actor state get api works ? it is because GET API tries to use `GET` as a fallback if HGETALL is failed - https://github.com/dapr/components-contrib/blob/a086a42f2b0af5e0416560b10cbed8d15743921b/state/redis/redis.go#L221

**Comment by youngbupark** [comment]
cc/ @yaron2 @amanbha

**Comment by yaron2** [comment]
cc @Haishi2016

**Comment by LMWF** [comment]
What's the problem in this issue?

**Comment by Haishi2016** [comment]
We use hash set operations because we need to attach a custom ETag field. This is critical to our concurrency control.
