### ISSUE TITLE
Client Sample - Serialization Error - (CosmosDB state store)

### ISSUE THREAD

**Issue by perokvist** [dapr/components-contrib#377]
Running the [client sample ](https://github.com/dapr/dotnet-sdk/blob/master/samples/Client/DaprClient/Program.cs)(with only the state calls), using the client nuget (instead of sdk project ref) **AND** the CosmosDB state component; 

Write, read and delete is expected to run.

But, on running the sample - it does write, then fails at read with the following ex;

```bash
== APP == Saved State!

== APP == Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to DaprClient.Program+Widget. Path: $ | LineNumber: 0 | BytePositionInLine: 46.
```

The item in cosmosDB looks like this after write;

```json
{
    "id": "demo||mykey",
    "value": "eyJzaXplIjoic21hbGwiLCJjb2xvciI6InllbGxvdyJ9",
    "_rid": "sLpTAOZXJvUBAAAAAAAAAA==",
    "_self": "dbs/sLpTAA==/colls/sLpTAOZXJvU=/docs/sLpTAOZXJvUBAAAAAAAAAA==/",
    "_etag": "\"0d00192c-0000-0c00-0000-5ee1cf2f0000\"",
    "_attachments": "attachments/",
    "_ts": 1591856943
}
```
Does this releate to dapr/dotnet-sdk#268 ?
Running with the default state store work just fine.

## Steps to Reproduce the Problem

- Remove the Client project ref from the sample
- Replace with nuget reference to 0.8 (client)
- Comment out all but the state calls in the sample
- Add the CosmosDB state component
- Run

**Comment by LMWF** [comment]
Transferred to components-contrib repo, this seems like an issue there.
