### ISSUE TITLE
Support separate Azure Service Bus subscriptions for same topic with different route

### ISSUE THREAD

**Issue by alexthissen** [dapr/components-contrib#378]
When creating subscriptions on the same topic, but with a different route, the component for Azure Service Bus should honor a separate ASB subscription per combination. 

Currently the implementation for the Azure Service Bus pub/sub component will only honor one of the topic/route combinations. It seems the AppID-topic tuple is used to register a subscription. This does not allow multiple subscriber on the same topic in the same application.

Example:
Topic: MyTopic
Route: RouteA

Topic: MyTopic
Route: RouteB

should give two subscriptions.

**Comment by jjcollinge** [comment]
@alexthissen thanks for raising this issue. @yaron2 I believe the current ASB implementation is consistent with the other pub sub on this; is this something we’d want to support? - I’m happy to add route to the subscription ID if so.

**Comment by alexthissen** [comment]
Any news on this?

**Comment by jjcollinge** [comment]
Nothing as of yet. I’m curious if the use case, could you expand it for me please? Why not have one handler that invokes 2 functions rather than dapr invoking 2 handlers with the same message?

**Comment by artursouza** [comment]
As of now, Azure Service Bus component in pubsub does offer a `ConsumerID` attribute. So, this can be achieved by having two separate pubsub components connecting to the same ASB endpoint but using a different `ConsumerID` each. This metadata attribute is not yet document, so I have created an issue to track that: https://github.com/dapr/docs/issues/1727

**Comment by sadgit** [comment]
> Nothing as of yet. I’m curious of the use case, could you expand it for me please? Why not have one handler that invokes 2 functions rather than dapr invoking 2 handlers with the same message?

This is an anti-pattern as the outcome of each event may differ. This would need a separate tally of which processors have completed and which need retrying.
