### ISSUE TITLE
Conformance Tests - Decide and finalize the list of components for GA

### ISSUE THREAD

**Issue by mukundansundar** [dapr/components-contrib#406]
## Describe the proposal
Decide and finalize the list of components for GA for v1.0. #404

**Comment by mukundansundar** [comment]
Initial set of components slated for GA:
Type | Component
-----|-------------
Binding | Azure Blob Storage
Binding | Azure Event Grid
Binding | Azure Storage Queue
Binding | HTTP/HTTPS
Middleware | OAuth2
Middleware | RateLimit
NameRes | Kubernetes
NameRes | mDNS
Pub/Sub | Azure Event Hubs
Secret Store | Kubernetes
State Store | Azure CosmosDB
State Store  | Redis

**Comment by mukundansundar** [comment]
@msfussell Based on the comments in #588 and #587 it seems that both middleware and name resolution does not come into the purview of conformance tests.

**Comment by mukundansundar** [comment]
@msfussell @artursouza @yaron2 Should I create a separate E2E task for the same in the dapr/dapr repo for the middleware and name resolution components?

**Comment by artursouza** [comment]
@mukundansundar  E2E tests are better fit for that. I don't think it belongs to M3 but we can expedite those in the last milestone if time allows.

**Comment by msfussell** [comment]
Binding | Azure Blob Storage
-- | --
Binding | Azure Event Grid
Binding | Azure Storage Queue
Binding | HTTP/HTTPS
Middleware | OAuth2
Middleware | RateLimit
Name Resolution | Kubernetes
Name Resolution | mDNS
Pub/Sub | Azure Service Bus Topics
Pub/Sub | Redis Streams
Secret store | Azure KeyVault
Secret store | Kubernetes
State | Azure CosmosDB
State | Mongodb
State | Redis
