### ISSUE TITLE
Conformance Tests - Implement API Tests for StateStore

### ISSUE THREAD

**Issue by mukundansundar** [dapr/components-contrib#407]
## Describe the proposal
Implement a sample test suite for Redis StateStore. #404 
Test the statestore interface completely.
Generate a report on test end. 
The redis setup is external to this for now. 
List and create issues for other tests that need to implemented as needed.
#404 

- [x] basic APIs init, set, get, delete, bulkset, bulkdelete
- [ ] transaction APIs

**Comment by mukundansundar** [comment]
The basic set is convered in the #586

**Comment by mukundansundar** [comment]
@artursouza Can you implement the tests for the transactions API once #586 is merged?

**Comment by artursouza** [comment]
@mukundansundar Yes, I can.

**Comment by mukundansundar** [comment]
@artursouza @yaron2 Please add a `breaking-change` label to this issue. 

The current label available is `breaking-changes`
