### ISSUE TITLE
Would this code cause vaultAddress empty without setting defaultVaultAddress?

### ISSUE THREAD

**Issue by silverjava** [dapr/components-contrib#421]
https://github.com/dapr/components-contrib/blob/65575593c1540ee75e0a9c5eeff6d0ceed52de1e/secretstores/hashicorp/vault/vault.go#L86

Hi guys,

I'm really interested in this project and thanks for building it. When I was reading the code, I feel whether the code line above would cause vaultAddress empty although the right behavior should set defaultVaultAddress other than empty strimg?

**Comment by silverjava** [comment]
Please check if the following test case makes sense:

```golang
funestInit(t *testing.T) {
	t.Run("with address empty", func(t *testing.T) {
		certBytes := getCertificate()
		properties := map[string]string{
			"caCert":        string(certBytes),
			"skipVerify":    "false",
			"tlsServerName": "vaultproject.io",
		}

		m := secretstores.Metadata{
			Properties: properties,
		}

		secretStore := vaultSecretStore{}
		secretStore.Init(m)

		assert.Equal(t, secretStore.vaultAddress, defaultVaultAddress)

	})
}
```

**Comment by DarqueWarrior** [comment]
You are correct. I just submitted a PR to fix it with tests that verified it was broken.
