### ISSUE TITLE
HTTP output binding to preserve tracing context

### ISSUE THREAD

**Issue by mchmarny** [dapr/components-contrib#424]
The HTTP binding right now does not preserve the request tracing context from user invocation. The output binding request doesn't include context so the parent trace ID would have to be predictably populated into the request metadata

```go
type InvokeRequest struct {
	Data      []byte            `json:"data"`
	Metadata  map[string]string `json:"metadata"`
	Operation OperationKind     `json:"operation"`
}
```

**Comment by shalabhms** [comment]
@mchmarny , this is known that we are currently not passing context to component code. Curious to know , are you tracing in binding component? 

/cc @youngbupark

**Comment by mchmarny** [comment]
I get that we are not doing it globally, the HTTP output binding could really benefit here as we are losing context in many workflow use-cases. Could predictable key in metadata be used for this?

**Comment by yaron2** [comment]
> I get that we are not doing it globally, the HTTP output binding could really benefit here as we are losing context in many workflow use-cases. Could predictable key in metadata be used for this?

That can work.

**Comment by shalabhms** [comment]
Have the tracing issue in dapr/dapr repo. closing this issue and using other one as reference https://github.com/dapr/dapr/issues/1913
