### ISSUE TITLE
Rename package name?

### ISSUE THREAD

**Issue by thinkerou** [dapr/components-contrib#43]
## Describe the proposal
now the name is `components-contrib`, but it's too long.
I suggest that rename to `common` or `base` or `components`, ok?
thanks!

**Comment by thinkerou** [comment]
update? before release v1.0.0.

**Comment by yaron2** [comment]
> update? before release v1.0.0.

Some of the components will get renamed/restructured, the repo name might change too.

We followed naming conventions for similar projects and repos on this, but can re-examine.

**Comment by amanbha** [comment]
@yaron2 while we have renamed the components within the repo, do we plan to consider repo rename or can this be closed?

**Comment by yaron2** [comment]
I think we can close this now.

**Comment by thinkerou** [comment]
ok
