### ISSUE TITLE
Provide the dev document for component (especially, testing)

### ISSUE THREAD

**Issue by youngbupark** [dapr/components-contrib#44]
## Describe the proposal

This is the issue to track the [gitter conversation](https://gitter.im/Dapr/community?at=5dacb87d3e33a9652a04ac61)

Need to provide the dev document to build and test component-contrib for developing new component.

- [x] : Create document to build component-contrib with dapr runtime
- [x] : Create document to test component-contrib with dapr runtime

**Comment by youngbupark** [comment]
cc/ @robertojrojas @amanbha @yaron2

**Comment by abhirockzz** [comment]
I am assuming this will include guidance for integration testing with the `dapr` runtime as well?

**Comment by youngbupark** [comment]
@abhirockzz Yes right. I updated description :)

**Comment by sayboras** [comment]
+1 for this issue.

Currently, I am testing for https://github.com/dapr/components-contrib/pull/142, it will be great to have some steps to follow :)

**Comment by youngbupark** [comment]
Closing this issue with PR #202 

@abhirockzz @sayboras I created the initial document for the component development. If you want to add more information, please improve it and create a pr.
