### ISSUE TITLE
Move bulk get to state store interface

### ISSUE THREAD

**Issue by Haishi2016** [dapr/components-contrib#447]
## Describe the proposal
Current state store interface doesn't have a bulk get method (though it has bulk set and bulk delete). Dapr API offers bulk get API, which loops through requested keys and invoke the underlying store as separate queries. This forbid us from implementing query optimizations based on a group of keys, which would be the common motivation of using bulk operations.

We should add bulk get to the state store interface and allow stores to implement possible optimizations when possible to reduce number of queries.

**Comment by LMWF** [comment]
This sounds like a good idea and should be discussed before bulk get is added on the sdk sides.

**Comment by yaron2** [comment]
> This sounds like a good idea and should be discussed before bulk get is added on the sdk sides.

This doesn't affect the SDKs at all, nor does it affect the existing implementation of Bulk Get. the API stays the same for the user.
This talks about adding an optional method for Bulk Get for state stores that support it, and where it isn't supported, the implementation behaves like it does today.

**Comment by skyao** [comment]
@Haishi2016  I opened a issue here and now we are working on this PR

https://github.com/dapr/dapr/pull/2467

**Comment by wcs1only** [comment]
This was closed via #2368
