### ISSUE TITLE
the natsstreaming has a nats logger but not a dapr logger

### ISSUE THREAD

**Issue by abserari** [dapr/components-contrib#448]
the natsstreaming has a nats logger but not a dapr logger. and there is no log.Info or log.Debug function call in code. it seems like that natsstreaming should have a pull-request first to convert logger and add log.Debug call like other components' realization.

https://github.com/dapr/dapr/issues/1996

so I update it and if it needs to update.

**Comment by yaron2** [comment]
Yes, this needs updating.
