### ISSUE TITLE
Add Qos to rabbitMQ binding

### ISSUE THREAD

**Issue by abserari** [dapr/components-contrib#455]
## Describe the proposal
make rabbitMQ input binding could configure the Qos of Consumer.

## task
- [x] update code
- [ ] update doc to notify the Qos arguments. I find no doc about the input binding Yaml so I don't know how to update it.

## Refer
https://github.com/rabbitmq/rabbitmq-server/pull/1408
https://www.rabbitmq.com/confirms.html#channel-qos-prefetch
https://www.rabbitmq.com/consumer-prefetch.html

## Reason
Yanzhi Li
@Li-Yanzhi
Sep 02 11:33
DAPR won’t distribute message from input binding to multiple instances of consumer?

I have the following scenario and issue:

1) External system publish 500 TODO job message to RabbitMQ
2) Consumer Pod use input binding (AMQP protocol) to receive messages from RabbitMQ, and Consumer Pod is running on demand (if no message, then no instances running)
2) KEDA scale the Consumer Pod from 0 to 5 based on custom metrics of RabbitMQ queueLength
3) Kubernetes create 5 instances of Consumer Pod based on scale rule (incoming 500 messages)
4) The daprd sidecar of first instances of Consumer Pod will get all 500 messages and processed them one by one, each message will use 20 seconds to complete, at meantime, the status of all messages in RabbitMQ changed from Ready to Unacked - UnAcknoledged
5) The other 4 instances of consumer Pod did NOT get any un-processed messages from RabbitMQ and free all time

I need all 5 instances of Consumer Pod parallelly process all non-complete messages in RabbitMQ, What configuration I missed or did wrong?

Yaron Schneider
@yaron2
Sep 03 01:50
What you are trying to accomplish should be supported. I'll look into the RabbitMQ binding

**Comment by abserari** [comment]
I completed the code here with two-line codes. https://github.com/abserari/components-contrib

**Comment by yaron2** [comment]
@abserari can you open a PR?

**Comment by abserari** [comment]
hello, I find no way to write the doc about how to set up an input binding component.

**Comment by yaron2** [comment]
> hello, I find no way to write the doc about how to set up an input binding component.

https://github.com/dapr/docs/blob/master/reference/specs/bindings/rabbitmq.md
