### ISSUE TITLE
[redis failover feature] add redis failover feature to redis state store Components

### ISSUE THREAD

**Issue by abserari** [dapr/components-contrib#458]
## Describe the proposal
![image](https://user-images.githubusercontent.com/32089134/92319851-2b6f0480-f04f-11ea-85fc-bc715b9df2bd.png)

I completed code here. https://github.com/abserari/components-contrib/tree/redis-failover-feature

**Comment by youngbupark** [comment]
@abserari Thanks for the contribution.

cc/ @mukundansundar @yaron2
