### ISSUE TITLE
Support of Azure Blob Metadata (for Blob state storage)

### ISSUE THREAD

**Issue by philliphoff** [dapr/components-contrib#462]
## Describe the proposal

Azure Blobs support both system (e.g. content type) and user-defined metadata.

This should also be supported within the Azure Blob state storage component, as [it currently is for the Azure Blob (output) binding component](https://github.com/dapr/components-contrib/issues/280).

**Comment by kdbeall** [comment]
@philliphoff This is an issue I'd like to work on.

- [blobstorage.go](https://github.com/dapr/components-contrib/blob/master/state/azure/blobstorage/blobstorage.go)

**Comment by philliphoff** [comment]
@kdbeall By all means!

**Comment by kdbeall** [comment]
@philliphoff I made a draft PR with some WIP code changes if you'd like to take a look.
https://github.com/dapr/components-contrib/pull/786

**Comment by philliphoff** [comment]
Thanks for the contribution!  It generally looks good to me.  However, as I'm not actually on the Dapr runtime team--I own VS [Code] tooling for Dapr--I'll leave it to them (@yaron2) to review.
