### ISSUE TITLE
support Get operation for Azure Blob Storage output binding

### ISSUE THREAD

**Issue by KaiWalter** [dapr/components-contrib#469]
Currently Azure Blob Storage output binding only supports `create` operation. We'd like to have also `get` operation supported by the output binding.

## background

We have a scenario with payloads >1MB which cannot be put on Azure Service Bus queues (not even with Premium plan). Instead we want to put payload in blob storage, some metadata into the queue, let the queue trigger a Dapr input binding and with the information in the metadata from there lookup payload from blob storage.

**Comment by mukundansundar** [comment]
not imported in dapr/dapr

**Comment by yaron2** [comment]
1. This is already imported, as it's an existing binding change.
2. Issues opened for components-contrib are closed in contrib, changes specific to the Dapr runtime should be opened in `dapr/dapr` repo.
3. During the release phase, the latest components-contrib is pulled and merged.
