### ISSUE TITLE
How is MQTT's will_set implemented in the dapr python sdk

### ISSUE THREAD

**Issue by moluzhui** [dapr/components-contrib#485]
## Ask your question here
Python's MQTT package provides the [will_set](https://www.eclipse.org/paho/index.php?page=clients/python/docs/index.php#option-functions) setting to implement that when the disconnect is to send a pre-set MQTT message

Now, project currently transferred to Dapr , which only supports `HTTP and GRPC` forms to connect to Dapr Sidecar, then whether the will_set function of Python MQTT will not be implemented under Dapr? 

If so, can you provide an instance? Thank you very much.

**Comment by youngbupark** [comment]
dupe https://github.com/dapr/dapr/issues/2135. Please look at my comment on the original issue.
