### ISSUE TITLE
Add dynamodb for state

### ISSUE THREAD

**Issue by sayboras** [dapr/components-contrib#49]
## Describe the proposal

To have support for dynamodb for state.

**Comment by sayboras** [comment]
If no one is working on this, I can pick up this.

**Comment by amanbha** [comment]
Sure, I have assigned it to you. 
 Thanks.

**Comment by yaron2** [comment]
@sayboras anything you need help with?

**Comment by sayboras** [comment]
> @sayboras anything you need help with?

I am just back from travelling this week, will plan sometime to wrap it up.

**Comment by sayboras** [comment]
@yaron2 need your input on how to handle `key` in dynamodb. Basically, we might need to have `key_col_num` during Set and Get methods. I can put this column name in `Metadata` of `GetRequest` or `SetRequest`, but feel like it's a hacky way.

``` golang
type GetRequest struct {
	Key      string            `json:"key"`
	Metadata map[string]string `json:"metadata"`
	Options  GetStateOption    `json:"options,omitempty"`
}
```
```golang
getItemInput := &dynamodb.GetItemInput{
		Key: map[string]*dynamodb.AttributeValue{
			"key_col_name": {
				S: aws.String(ID),
			},
		},
		TableName:      aws.String(ddb.cfg.DBTableProducts),
		ConsistentRead: aws.Bool(true),
	}
```

**Comment by yaron2** [comment]
> @yaron2 need your input on how to handle `key` in dynamodb. Basically, we might need to have `key_col_num` during Set and Get methods. I can put this column name in `Metadata` of `GetRequest` or `SetRequest`, but feel like it's a hacky way.
> 
> Another appoach is to use fixed key col num (e.g. `key`), however this will give very limited flexibility for consumer.
> 
> ```go
> type GetRequest struct {
> 	Key      string            `json:"key"`
> 	Metadata map[string]string `json:"metadata"`
> 	Options  GetStateOption    `json:"options,omitempty"`
> }
> ```
> 
> Code snippet on how to retrieve item.
> 
> ```go
> getItemInput := &dynamodb.GetItemInput{
> 		Key: map[string]*dynamodb.AttributeValue{
> 			"key_col_name": {
> 				S: aws.String(req.Key),
> 			},
> 		},
> 		TableName:      aws.String("table_name"),
> 		ConsistentRead: aws.Bool(true),
> 	}
> ```

We can use our own struct as the data object for DynamoDB which had two fields: Key and Data.

Then in GetItem requests we can select by the Key field.

**Comment by sayboras** [comment]
@yaron2 I think it would work as well, will spend sometime this weekend to wrap it up then :)

**Comment by gmusial-obj** [comment]
I would love to play around with DynamoDB as state store but I see that the issue here is outdated and PR has unreviewed changes from the last month. Is this feature blocked for some reason?

**Comment by yaron2** [comment]
@gmusial-obj I think at this point it would be OK for you to start a new PR.

@sayboras, if you still intend to address the comments and close the existing PR please let us know.
