### ISSUE TITLE
Azure Blob Storage Binding Expecting String for Data

### ISSUE THREAD

**Issue by lynn-orrell** [dapr/components-contrib#492]
The Azure blob storage binding now expects the data property to contain a string rather than accepting a nested json object. Unfortunately, the documentation isn't clear as to what the payload should be from an http perspective.

Notice here that the payload is represented as a string value: https://github.com/dapr/docs/blob/master/reference/api/bindings_api.md#payload

Notice here that the payload is represented as a nested json object:
https://github.com/dapr/docs/blob/master/reference/api/bindings_api.md#examples-1

This being said, which of these is correct? I'm assuming **_both_**. If that is the case, then we should attempt to see if the data is a valid json object and process it as such. If it's not, then we should assume that it is string data. 

Currently, the component attempts to strconv.Unquote() the data and throws an "Invalid syntax" error if non-quoted data is passed in the data property as seen here: https://github.com/dapr/components-contrib/blob/2c403ad238a576965767a5dd5581369cd0e76d46/bindings/azure/blobstorage/blobstorage.go#L140-L145

Obviously this needs to be fixed in the Azure blob storage binding but I'm wondering if this might be an issue for other bindings as well? Should we reason about a universal way to handle this so that it isn't up to each individual component (as that could lead to a very inconsistent developer experience)?

Thoughts?

/cc
@youngbupark @yaron2 @mchmarny @msfussell @orizohar

**Comment by youngbupark** [comment]
req.Data is bytes array ([]byte). before serializing data, we need to check if the data is bytes or the object. 

https://github.com/dapr/dapr/blob/3d21cd1df19a234a00ad072e3ddc96c9b4f3d1be/pkg/http/api.go#L305-L311

this issue is the same issue as what we have in state store in the last release.  We need to prioritize this issue as P1.

cc/ @yaron2 @msfussell @mukundansundar @artursouza

**Comment by yaron2** [comment]
This is now fixed in 1.0-rc1.
