### ISSUE TITLE
[Propasal] Add Ack wait and MaxInFlight Parameters to Nats Streaming Component

### ISSUE THREAD

**Issue by Admiralkheir** [dapr/components-contrib#505]
Hi, I think we need these parameters on component.yaml. According to the document these parameters are using in subscription code. [Source Link](https://docs.nats.io/developing-with-nats-streaming/acks#acknowledgements)
Default is like this,
- AckWait: 30 sec
- MaxInFlight: 1024

**Comment by yaron2** [comment]
@abserari can you comment here so I can assign this issue to you? thanks!

**Comment by yaron2** [comment]
Closes via #511
