### ISSUE TITLE
Dapr pub/sub publish is stripping Cloud Event fields

### ISSUE THREAD

**Issue by lynn-orrell** [dapr/components-contrib#506]
If an already created Cloud Event is sent to Dapr to be published via the pub/sub api, Dapr is recreating the Cloud Event and ignoring (failing to propagate) existing Cloud Event properties.

https://github.com/dapr/components-contrib/blob/5e9140f1dbba55581b6fe5d0fe0a0530af30411c/pubsub/envelope.go#L72-L92

**Comment by abserari** [comment]
What CloudEvent content is not good?

**Comment by abserari** [comment]
https://github.com/dapr/components-contrib/pull/509 I try one here. Could give me some advice to promote this change. I think code change is enough and should represent it in the doc.

**Comment by mchmarny** [comment]
Note, the CE extension names are unpredictable (`ce-*`) so this will have to include some form of parsing into map[string]interface{} and then adding one by one.
