### ISSUE TITLE
Enhance pub/sub to normalize all received messages to the Cloud Event spec

### ISSUE THREAD

**Issue by lynn-orrell** [dapr/components-contrib#507]
Currently, messages received via the pub/sub component building block are delivered to the application "bare". This proposal aims to normalize all messages to the Cloud Event spec that are sent from Dapr to the application.

For example, an existing, non-daprized application may be publishing simple json messages to a topic. I'll use an example coffee order for this discussion.

```json
"Bare" message example:

{
    "customerName": "Bruce Wayne",
    "loyaltyId": "1",
    "orderTotal": 35.91,
    "orderItems": [
        {
            "menuItemId": 3,
            "menuItemName": "Latte",
            "quantity": 5
        },
        {
            "menuItemId": 1,
            "menuItemName": "Americano",
            "quantity": 2
        },
        {
            "quantity": 2,
            "menuItemId": 2,
            "menuItemName": "Caramel Macchiato"
        }
    ],
    "orderId": "294111f8-0551-48a3-a48f-c3363c4116ad",
    "orderDate": "2020-10-07T19:42:27.513+0000",
    "storeId": "Redmond"
}
```

Let's assume we have existing, ***non-daprized*** publisher and a newly created ***daprized*** subscriber. The publisher publishes the above payload to the `orders` topic. Dapr will deliver this message "bare" to the ***daprized*** subscriber.

![image](https://user-images.githubusercontent.com/2810722/96938372-d583de00-148f-11eb-9f01-ff4d2247cfc2.png)

Here is where the first issue lies: ***Dapr only pays mind to the payload of the message. Existing metadata properties (Enqueue Time, Retry Count, etc.) are not delivered to the application as part of the message.***

Now, we decide to introduce a new microservice into the equation that will also publish order messages to the `orders` topic. This microservice utilizes Dapr pub/sub to accelerate the development lifecycle. Currently, when using Dapr to publish messages via the pub/sub building block, the message payload will be wrapped in a Cloud Event (assuming it's not already in this form). 

```json
Cloud Event example:

{
    "id": "da0a9f47-ce94-4eff-82d7-58c85191cccc",
    "source": "order-service",
    "type": "com.dapr.event.sent",
    "specversion": "1.0",
    "datacontenttype": "application/json",
    "data": {
        "customerName": "Bruce Wayne",
        "loyaltyId": "1",
        "orderTotal": 35.91,
        "orderItems": [
            {
                "menuItemId": 3,
                "menuItemName": "Latte",
                "quantity": 5
            },
            {
                "menuItemId": 1,
                "menuItemName": "Americano",
                "quantity": 2
            },
            {
                "quantity": 2,
                "menuItemId": 2,
                "menuItemName": "Caramel Macchiato"
            }
        ],
        "orderId": "294111f8-0551-48a3-a48f-c3363c4116ad",
        "orderDate": "2020-10-07T19:42:27.513+0000",
        "storeId": "Redmond"
    },
    "subject": "00-255e8a7387f468d7c80a34172b0c3ad1-f1f5a0f0d1c68078-00",
    "topic": "order",
    "pubsubname": "dapr-workshop.pubsub"
}
```

Here is where the second issue lies: ***the subscriber will now need to be updated to check whether the message was delivered "as is" or if it was delivered as a Cloud Event. This has a high potential to introduce runtime bugs into business logic code that leverages Dapr.***

![image](https://user-images.githubusercontent.com/2810722/96938434-fcdaab00-148f-11eb-8b43-cef9984759da.png)

> **Proposal: Dapr should wrap any messages that are received "bare" in a Cloud Event. This needs to be done and, if possible, enforced by each pub/sub component implementation, as each messaging provider will potentially be different. In addition, Dapr should ensure preservation of all existing message metadata via standard Cloud Event fields and Cloud Event Attribute Extensions.**

**Comment by abserari** [comment]
According to https://github.com/cloudevents/spec/blob/master/primer.md#creating-cloudevents, I suggest that all received messages be directly nested in CloudEvent as data while ensuring that the external event is encoded as JSON instead of cloudevent+json. In this way, according to the CloudEvent primer, the internal data can be arbitrarily coded, so that the internal data can be parsed through the customization of each component to add its own defined fields and other operations.

I just try to realize it with my project yesterday according to daprized origin realized, https://github.com/silverswords/pulse/blob/master/pkg/message/envelope.go
 just remove the transform action and wrap every received message in CloudEvent.

**Comment by lynn-orrell** [comment]
I'm not sure I agree with that based on this paragraph in the [Creating Cloud Events](https://github.com/cloudevents/spec/blob/master/primer.md#creating-cloudevents) section:

> As mentioned above, whether the entity that generated the initial event is the same entity that creates the corresponding CloudEvent is an implementation choice. ***However, when the entity that is constructing/populating the CloudEvents attributes is acting on behalf of the event source, the values of those attributes are meant to describe the event or the event source and not the entity calculating the CloudEvent attribute values.*** In other words, when the split between the event source and the CloudEvents producer are not materially significant to the event consumers, the spec defined attributes would typically not include any values to indicate this split of responsibilities.

Based on the way I read the spec, if we receive a "bare" message, we should do our best to construct a new Cloud Event and retain the original metadata about the actual event source. We can also add additional metadata to the new Cloud Event where it makes sense - such as tracing information.

**Comment by abserari** [comment]
> I'm not sure I agree with that based on this paragraph in the [Creating Cloud Events](https://github.com/cloudevents/spec/blob/master/primer.md#creating-cloudevents) section:
> 
> > As mentioned above, whether the entity that generated the initial event is the same entity that creates the corresponding CloudEvent is an implementation choice. _**However, when the entity that is constructing/populating the CloudEvents attributes is acting on behalf of the event source, the values of those attributes are meant to describe the event or the event source and not the entity calculating the CloudEvent attribute values.**_ In other words, when the split between the event source and the CloudEvents producer are not materially significant to the event consumers, the spec defined attributes would typically not include any values to indicate this split of responsibilities.
> 
> Based on the way I read the spec, if we receive a "bare" message, we should do our best to construct a new Cloud Event and retain the original metadata about the actual event source. We can also add additional metadata to the new Cloud Event where it makes sense - such as tracing information.

I agree with you, that's right. What I want to express is to include bare information directly on one layer of CloudEvent. We can also add some extra information for other purposes in our outer EventenVolope.

and sorry for my Vague expressions, I refer to the last paragraph of this cloud events section.  So I think this section indeed express our discuss the subject and guide a technical standard  of CloudEvent

> However, if this entity is performing some type of semantic processing of the CloudEvent, typically resulting in a change to the value of the data attribute, then it may need to be considered a distinct "event source" from the original event source. And as such, it is expected that CloudEvents attributes related to the event producer (such as source and id) would be changed from the incoming CloudEvent.

>There might exist special cases in which it is necessary to create a CloudEvent that contains another CloudEvent. Although the specification does not define nesting explicitly, it is possible. While the inner event will always be encoded in a stand-alone event format, the outer event can be either binary or structured mode. The datacontenttype attribute of the outer event must not be set to application/cloudevents+json or any other media type that is used to denote the usage of structured mode. A correct example of event nesting would be:

>Content-Type: application/json
ce-specversion: 1.x-wip
ce-type: myevent
ce-id: 1234-1234-1234
ce-source: example.com

>{
  "specversion": "1.x-wip",
  "type": "coolevent",
  "id": "xxxx-xxxx-xxxx",
  "source": "bigco.com",
  "data": { ... }
}

**Comment by abserari** [comment]
https://github.com/dapr/components-contrib/pull/509

**Comment by artursouza** [comment]
This has been addressed as part of the "raw message" feature in pubsub, not? @lynn-orrell ?
