### ISSUE TITLE
Remove Exporter Components now OpenTelemetry is adopted. 

### ISSUE THREAD

**Issue by msfussell** [dapr/components-contrib#508]
The exporter components can be removed since these are redundant when OpenTelemetry forwarded is used. The exporter are now all available here https://github.com/open-telemetry/opentelemetry-collector/tree/master/exporter

**Comment by yaron2** [comment]
hey @ShaileshSurya  can you pick this up? should be fairly simple

**Comment by ShaileshSurya** [comment]
Hey @yaron2 let me have a look at this. I will come up with more questions if I have any.

**Comment by ShaileshSurya** [comment]
Hey @yaron, 

I could not find any exporter component in the repository. I also found this PR merged https://github.com/dapr/components-contrib/pull/553 . Do you think this bug is already handled? If not can you please help me understand more.
