### ISSUE TITLE
Rename the 'native' exporter component 

### ISSUE THREAD

**Issue by tcnghia** [dapr/components-contrib#512]
## Describe the proposal

The `native` exporter is actually our OpenTelemetry exporter. The name is a bit non-descriptive (and maybe confusing) so it could benefit our users if we rename this to something else.

A few ideas:

- If we also switch metrics to OpenTelemetry (tracked [here](https://github.com/dapr/dapr/issues/2296)), then we can just rename `native` to `opentelemetry-collector` or even `opentelemetry`.
- If we deprecate all exporter components (like [this proposal](https://github.com/dapr/components-contrib/issues/508)), we could rename `native` to `exporter`. However, the configurations will be somewhat OpenTelemetry-specific so `exporter` will probably be a bit too generic.

**Comment by tcnghia** [comment]
cc @yaron2 @msfussell @youngbupark WDYT

**Comment by yaron2** [comment]
If we are only keeping one exporter, it should move out of contrib and into `dapr/dapr`.

**Comment by youngbupark** [comment]
We decided to deprecate exporters in components and move to opentelemetry collector.  @tcnghia can you change this issue's title?

**Comment by tcnghia** [comment]
The exporter components are deprecated (see dapr/dapr#2337). So this can be closed.
