### ISSUE TITLE
Have Dapr support multiple instances registered with same app-id and load balance requests across them

### ISSUE THREAD

**Issue by nrjohnstone** [dapr/components-contrib#514]
Currently looking at using Dapr in our data center to provide a transparent way for a legacy worker process to access a REST API.

Proposal was to deploy the REST API to each of the nodes where the worker process also runs, and then use Dapr as a side car process registering the app with the same service name on each node.

This does not work however as there is no native concept of load balancing in the Dapr system and what actually happens is that each time you start the Dapr side car the local instance of the REST API becomes the "latest" known service, and when that REST API stops, further calls to Dapr fail as it does not round robin to the other running instances of that service name.

It would be nice if you could have multiple registrations of the same app-id and Dapr would do simple round robin load balancing around them. 

When any instance of a Dapr side car was terminated, it should immediately remove that instance from the pool of services of that app-id within the Dapr system.

With this functionality you can potentially remove the need for complicated service discovery/load balanced mechanisms like Consul, and go with a much simpler Dapr native approach when you are dealing with legacy systems running on servers (as long as the network supports multicast for Dapr discovery ;-) )

Another thing I noticed is that if you try to register the same app-id locally with different ports you get a specific error complaining that the app-id is already used, but if you register the same app-id on different hosts (as I was doing experimenting with this) then it suceeds, you just don't get any type of "load balancing" behavior.

So in developing the load balancer logic, you should probably also allow multiple app-ids to be registered on the same host (as long as they go to different app-ports)

**Comment by yaron2** [comment]
@skyao can you help with this?

**Comment by skyao** [comment]
> @skyao can you help with this?

Ok, let me check what happens.

**Comment by yaron2** [comment]
@skyao here's some context:

See [here](https://github.com/dapr/components-contrib/blob/a27e486ef91407586a10630a9a22c91e9d389d60/nameresolution/mdns/mdns.go#L105), this is where Dapr searches the network for the given app ID in Self Hosted service discovery. This method needs to change to keep a map of instances per app ID, as today this function only handles a single instance of an app-id. Once there's a list of instances, there needs to be a basic round robin logic around them.

**Comment by jjcollinge** [comment]
@yaron2 do you think we should include basic load balancing capabilities in Dapr as described above for mDNS or do we delegate that to the external networking i.e. in Kubernetes it's handled by a service not Dapr - locally it can be handled by a Daprized load balancer or proxy if required. Just wondering if it's a core capability if it's different between environments.

**Comment by jjcollinge** [comment]
On second thoughts - not sure the above matters as it doesn't affect the runtime.

**Comment by yaron2** [comment]
> @yaron2 do you think we should include basic load balancing capabilities in Dapr as described above for mDNS or do we delegate that to the external networking i.e. in Kubernetes it's handled by a service not Dapr - locally it can be handled by a Daprized load balancer or proxy if required. Just wondering if it's a core capability if it's different between environments.

The mDNS implementation should have basic load balancing capabilities, yes.

**Comment by jjcollinge** [comment]
So just looking at the implementation of this, @yaron2 does your comment above suggest having a background goroutine periodically browse mDNS and maintain an in memory map of appId to address list whilst keeping an index of the currently returned address, then in the `ResolveID` call we use some algo (i.e. round robin) to select the next address and update the index? We'd need to be careful to set a reasonable timeout in browse as we can't cancel early anymore when we've received a response for a matching ID, we'd need to get all responses in a time window and maintain that as the list. Checking for updates often enough to not return a stale address. If we kept it as is and did browse in `ResolveID` we'd need to keep that time window for responses very short in order to not introduce perf issues.

**Comment by yaron2** [comment]
> So just looking at the implementation of this, @yaron2 does your comment above suggest having a background goroutine periodically browse mDNS and maintain an in memory map of appId to address list whilst keeping an index of the currently returned address, then in the `ResolveID` call we use some algo (i.e. round robin) to select the next address and update the index? We'd need to be careful to set a reasonable timeout in browse as we can't cancel early anymore when we've received a response for a matching ID, we'd need to get all responses in a time window and maintain that as the list. Checking for updates often enough to not return a stale address. If instead we kept it as is and did browse in `ResolveID` we'd need to keep that time window for responses very short in order to not introduce perf issues.

The way I see it:

the mDNS implementation should periodically check all the appIDs on the network and keep a map of an ID and it's address list.
When a new invocation request comes in, Dapr checks if there are any entries for the given ID. If none are present, an mDNS browse will happen. If no new entries are discovered, an error is returned for address not found. If entries are discovered, the map is updated and the call continues.

Requests should follow round-robin when multiple entries for an app ID exist.

**Comment by yaron2** [comment]
@jjcollinge I took the liberty of assigning this to you. This is important to get in for the nearest RC2 milestone..

**Comment by jjcollinge** [comment]
@yaron2 np - I can look into this.

> > So just looking at the implementation of this, @yaron2 does your comment above suggest having a background goroutine periodically browse mDNS and maintain an in memory map of appId to address list whilst keeping an index of the currently returned address, then in the `ResolveID` call we use some algo (i.e. round robin) to select the next address and update the index? We'd need to be careful to set a reasonable timeout in browse as we can't cancel early anymore when we've received a response for a matching ID, we'd need to get all responses in a time window and maintain that as the list. Checking for updates often enough to not return a stale address. If instead we kept it as is and did browse in `ResolveID` we'd need to keep that time window for responses very short in order to not introduce perf issues.
> 
> The way I see it:
> 
> the mDNS implementation should periodically check all the appIDs on the network and keep a map of an ID and it's address list.
> When a new invocation request comes in, Dapr checks if there are any entries for the given ID. If none are present, an mDNS browse will happen. If no new entries are discovered, an error is returned for address not found. If entries are discovered, the map is updated and the call continues.
> 
> Requests should follow round-robin when multiple entries for an app ID exist.

I'm going to implement this as an address cache, so the first request to a new appId will always be a browse but subsequent requests will use the cache. The cache will store ipv4 and ipv6 entries (separately) and have a TTL on them. New requests for existing appIds will renew the TTL but once expired a new browse will be required on the next request. I'll then just use a simple round robin selection to return the address from the list.

**Comment by jjcollinge** [comment]
@yaron2 np, will look at getting this done asap. "periodically check all the appIDs on the network" - this is the interesting bit. If we implement this as an address cache - then when we see an appId, we check if it's in the cache, if it has addresses in the cache, we select the appropriate one using round robin. If it is not in the cache we need to browse the network for the appId - we don't know how many responses we might get so this has to be a fixed window (which will introduce a bigger cost for cache miss requests) - we then add each response we receive in the window to the cache, then select the suitable one using round robin. We could optimize this to reduce the cache miss cost by returning early from browse on the first response (as it done now) so only a single address is in the cache for that appId, and then a background goroutine scans the network for more addresses for all appIds in the cache periodically and add any new addresses to that entry list. Entries in the address cache will have a TTL. The TTL we then be extended each time we see the same address for the associated appId and expired entries will be removed.

**Comment by shuiyunwudi** [comment]
Is there any method to configurate dapr to register service which have multiple instance on consul. we now found the configuration only support service name, not support argument "id", that means we can't register multiple service instance for one app. there is the website I refer: [https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/#configuration-format](url)
