### ISSUE TITLE
Service discovery and invocation not working reliably on Dapr self host mode on windows.

### ISSUE THREAD

**Issue by pattisapu01** [dapr/components-contrib#520]
## Expected Behavior
I am using project tye + dapr to orchestrate dapr side cars as processes in self host mode. I should be able to do service invocation.

## Actual Behavior
Service Invocation is not happening. Getting an error "{"errorCode":"ERR_DIRECT_INVOKE","message":"couldn't find service: orders"}"
Windows  10 version: 18362.1139,
Net core 3.1
Dapr: CLI version: 0.11.0, Runtime version: 0.11.3
Tye version: 0.6.0-alpha.20556.1+90d3e4e480bde4533dc9709a5d3ce9b7190a73b1

## Steps to Reproduce the Problem
a) Get the code from https://github.com/dotnet/tye/tree/master/samples/dapr
b) Watch video @ https://youtu.be/Ff2eq2a6xB0

## Release Note

RELEASE NOTE:

**Comment by msfussell** [comment]
@pattisapu01   _ can you try with the RC2 issue and reopen this issue if you are still having issues
