### ISSUE TITLE
Remove consumerID from pub/sub sample configs

### ISSUE THREAD

**Issue by amolenk** [dapr/components-contrib#521]
For the pub/sub building block components, the consumerID is always set to the application id (https://github.com/dapr/dapr/blob/baed8143e2251a6fd2095925308e9c8b5ec1cfe8/pkg/runtime/runtime.go#L962):

``` go
properties := a.convertMetadataItemsToProperties(c.Spec.Metadata)
properties["consumerID"] = a.runtimeConfig.ID
```

This means that the user can never override it in config. If this is the intended behavior,  the `consumerID` property should be removed from the configuration samples. Right now, both the NATS streaming and RabbitMQ components still show `consumerID` in the sample configs:

https://docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/setup-nats-streaming/
https://docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/setup-rabbitmq/

**Comment by yaron2** [comment]
You are correct, consumer groups should be removed.

Could you submit a PR to docs to fix this please?

**Comment by amolenk** [comment]
Sure
