### ISSUE TITLE
Add CVE information

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#527]
CVE is a public record of security vulnerabilities.

We want to add a section that details how an CVE entry for Dapr looks like, including but not limited to version of the runtime, version of the API and component, and SDK version.

**Comment by daixiang0** [comment]
Is it in process?

**Comment by CodeMonkeyLeet** [comment]
@yaron2 CVEs are generally issued by CVE Numbering Authorities (CNA) of which GitHub is one. Obtaining a CVE number (and publication to CVE tracking lists) can be done by [publishing a security advisory through GitHub](https://docs.github.com/en/code-security/security-advisories/publishing-a-security-advisory).
