### ISSUE TITLE
Getting a weird error when trying to log more

### ISSUE THREAD

**Issue by trondhindenes** [dapr/components-contrib#529]
## Ask your question here
I'm trying to add a bit more logging to the aws-related components. Most of them have a "getClient" func which returns an authenticated session, and I thought it would be helpful to debug-log the authenticated user/identity

However:
(snipped from https://github.com/dapr/components-contrib/blob/master/bindings/aws/sqs/sqs.go#L134)

Given this code:
```go
func (a *AWSSQS) getClient(metadata *sqsMetadata) (*sqs.SQS, error) {
	fmt.Println("hello")
	a.logger.Debugf("hello")
```
I get a runtime error on the `Debugf` call:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3500139]
```

The `a` object contains a logger, so I'm unable to see why this happens (comparing it to other modules). 
I am _very_ new to Golang and there's tons of stuff around references etc that I really haven't read up on so there might be a very real reason why this call is failing.

**Comment by yaron2** [comment]
@youngbupark can you assist here?

**Comment by mukundansundar** [comment]
@yaron2 I think the logger is not initialized properly for sqs. https://github.com/dapr/components-contrib/blob/master/bindings/aws/sqs/sqs.go#L36-L38

For reference see https://github.com/dapr/components-contrib/blob/master/bindings/aws/sqs/sqs.go#L36-L38

**Comment by trondhindenes** [comment]
@mukundansundar thanks for pointing me in the right direction - it turns out that https://github.com/dapr/components-contrib/blob/master/bindings/aws/sqs/sqs.go#L36 is the culprit, the return statement should be
`return &AWSSQS{logger: logger}` to properly wire up the logger.
Thanks again! closing this.

**Comment by mukundansundar** [comment]
@trondhindenes can you add a fix PR for this issue and link it to this issue?

**Comment by trondhindenes** [comment]
@mukundansundar yup! Doing it now
