### ISSUE TITLE
RabbitMQ Pub/Sub Missing QoS Initialization? 

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/components-contrib#536]
I am currently having an issue that I am not able to receive messages on +1 consumer (only one receives the messages). My consumer id is the same and everything is coming on the same queue.

When reading through RabbitMQ documentation, it appears that I have to set the prefetch count (https://www.rabbitmq.com/tutorials/tutorial-two-go.html) but it appears that this is not being set in the Dapr RabbitMQ component? https://github.com/dapr/components-contrib/blob/686b42fd1850705801a0660ac1df76c6551ae35c/pubsub/rabbitmq/rabbitmq.go#L88

When I look at the binding however, I am able to see it being set: https://github.com/dapr/components-contrib/blob/f647d9eedbfd98ec8fb297d18cee9ceb3c332dc2/bindings/rabbitmq/rabbitmq.go

Am I missing something here?

**Comment by yaron2** [comment]
This is by design, as in Dapr Pub/Sub an app ID acts as a consumer ID, which means that only one instance within a consumer group will get a copy of a message.

Ad you correctly mentioned, the binding can be used if you need to change this behavior.

**Comment by XavierGeerinck** [comment]
Thanks for your fast response @yaron2 will change it to a binding then! 😊 might it be interesting to update the documentation to include this btw?

**Comment by yaron2** [comment]
> Thanks for your fast response @yaron2 will change it to a binding then! 😊 might it be interesting to update the documentation to include this btw?

Yes, feel free to submit a PR for this where you see fit in the docs repo.
