### ISSUE TITLE
can't load oauth2 middleware in dapr1.0-rc1 kubernetes

### ISSUE THREAD

**Issue by sd797994** [dapr/components-contrib#537]
## Ask your question here
env: 
win10+docker desktop + kubernetes 1.18.8  + dapr 1.0-rc1
question:
follow this guide:(https://v1-rc1.docs.dapr.io/operations/security/oauth/),when i set an oauth2 component like this
`
apiVersion: dapr.io/v1alpha1`
`kind: Component`
`metadata:`
`  name: oauth2`
`  namespace: default`
`spec:`
`  type: middleware.http.oauth2`
`  version: v1`
`  metadata:
`
when i reload my deployment, the  pod's sidercar's logs print error "process component oauth2 error, incorrect type middlewares.http.oauth2"
how can i set yaml to right load oauth2 middleware in component?

**Comment by yaron2** [comment]
Closed with https://github.com/dapr/dapr/pull/2667
