### ISSUE TITLE
Question: how to get object from s3

### ISSUE THREAD

**Issue by haibingzhao** [dapr/components-contrib#538]
## Ask your question here
put object to s3 can use output [binding.s3](https://github.com/dapr/components-contrib/blob/f647d9eedbfd98ec8fb297d18cee9ceb3c332dc2/bindings/aws/s3/s3.go)

how to get object from s3? which API can I use?

**Comment by yaron2** [comment]
Currently there's no support for getting S3 objects, however Dapr has a way to support that using Bi-directional bindings.

If you want to add support for this, we (maintainers) will support you and welcome this addition. You can see an example of the Azure Blob Storage binding support for GET blob: https://github.com/dapr/components-contrib/blob/686b42fd1850705801a0660ac1df76c6551ae35c/bindings/azure/blobstorage/blobstorage.go#L196

**Comment by yaron2** [comment]
Also, if you don't have the time to contribute a PR for this but are blocked by this for using Dapr, we can try and assign a community member to do this.

**Comment by ksivamuthu** [comment]
@yaron2 Can you please assign this to me? I'll work on it, if it's not done yet.
