### ISSUE TITLE
Add prefetch count to RabbitMQ pub/sub

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#560]
Dapr today has prefetch count implemented for the RabbitMQ binding. The same functionality should be applied to the RabbitMQ pub/sub implementation.

/cc @trondhindenes

**Comment by trondhindenes** [comment]
I'll try my hand at this one.

**Comment by trondhindenes** [comment]
sweet! I'll get on the doc PR this week.

**Comment by yaron2** [comment]
Closed via #562
