### ISSUE TITLE
Exclusive Queues for RabbitMQ

### ISSUE THREAD

**Issue by eibrunorodrigues** [dapr/components-contrib#577]
## Describe the proposal
I'm using a lot this feature for RabbitMQ exclusive queues, and I think we can enable this option on Dapr bindings...

Something like, if the flag ```exclusive``` is passed, then we use the flag, if is not declared, `false` should be the default value.

**Comment by yaron2** [comment]
That makes sense. Would you be interested in submitting a PR?

**Comment by eibrunorodrigues** [comment]
@yaron2 sure! I'll submit the PR right away.

**Comment by eibrunorodrigues** [comment]
@yaron2 I created the PR... But I was thinking, maybe we can extend this to the subscribe method... So when the subscriber stops consuming, the queue dies... What do you think?

**Comment by yaron2** [comment]
Closed by https://github.com/dapr/components-contrib/pull/580
