### ISSUE TITLE
No CI pipeline (either azure or github actions)

### ISSUE THREAD

**Issue by sayboras** [dapr/components-contrib#58]
Not sure if any plan to do so for this repo.

**Comment by sayboras** [comment]
As other repo dapr/dapr just migrated from azure pipeline to github action, I will proceed with github action then, please help to review #59

**Comment by youngbupark** [comment]
@sayboras Can you please add badge to README.md ? I think you can find the reference in dapr repo.

**Comment by sayboras** [comment]
@youngbupark Good point 💯

**Comment by sayboras** [comment]
All items are addressed, closing PR :)
