### ISSUE TITLE
App able to subscribe to one GCP Pub/Sub topic only

### ISSUE THREAD

**Issue by sergey-komarov** [dapr/components-contrib#583]
## Expected Behavior

App should be able to subscribe to all required GCP Pub/Sub topics

## Actual Behavior

App subscribed to one GCP Pub/Sub topic only

## Steps to Reproduce the Problem

1. Use quickstart/pub-sub sample for reproducing (https://github.com/dapr/quickstarts/tree/master/pub-sub)
2. Use GCP Pub/Sub component instead of Redis according instructions (https://docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/setup-gcp/). Please notice that names of topics should be updated for following naming requirements (https://cloud.google.com/pubsub/docs/admin#resource_names)
3. Deploy to k8s cluster
4. Check subscriptions for A,B,C topics
5. Notice that only one topic (in my case topic A) has a subscriptions. Other topics don't have.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Will take a look at this

**Comment by yaron2** [comment]
@sergey-komarov I found the issue, and this will be fixed for the upcoming release.
