### ISSUE TITLE
Conformance tests - Implement API tests for NameResolution

### ISSUE THREAD

**Issue by mukundansundar** [dapr/components-contrib#587]
## Describe the proposal
Implement API tests for the Name resolution component.
Test the name resolution interface completely.
Generate a report on test end. 
List and create issues for other tests that need to implemented as needed.
#404

**Comment by mukundansundar** [comment]
@artursouza @yaron2 @tcnghia  Please add your thoughts on whether this is possible as conformance test or not.

**Comment by yaron2** [comment]
As there's no component model for name resolution, being platform specific, I think we should exclude name resolution from conformance tests.

**Comment by artursouza** [comment]
I agree, we can remove this from conformance test. It looks more like E2E test to me.

**Comment by mukundansundar** [comment]
closing this issue based on comments above.
