### ISSUE TITLE
Conformance tests - Implement API tests for Middleware component

### ISSUE THREAD

**Issue by mukundansundar** [dapr/components-contrib#588]
## Describe the proposal
Implement a sample test suite for HTTP middleware/OAuth2 middleware component.
Test the middleware interface completely.
Generate a report on test end. 
List and create issues for other tests that need to implemented as needed.
#404

**Comment by mukundansundar** [comment]
@artursouza @yaron2 @tcnghia  Please add your thoughts on whether this is possible as conformance test or not.

**Comment by artursouza** [comment]
This looks more like E2E test to me. Conformance test is for components that are pluggable and replaceable.

**Comment by mukundansundar** [comment]
closing this issue based on comment above.
