### ISSUE TITLE
SecretStore BulkGetSecret method flattens all of secrets into a single map

### ISSUE THREAD

**Issue by cmendible** [dapr/components-contrib#590]
## Expected Behavior

Should BulkGetSecret responses return a `map[string]map[string]string`?

## Actual Behavior

BulkGetSecret responses returns a `map[string]string` instead of  `map[string]map[string]string` which means that when using Kubernetes we are losing the original secret key / name cause the method is flattening the results.

Should we keep the method as is? Or should we change it to return `map[string]map[string]string`?

Check: https://github.com/dapr/dotnet-sdk/pull/511#discussion_r554204277 for more details.

## Release Note

RELEASE NOTE:

**Comment by cmendible** [comment]
@yaron2, @rynowak what are your thoughts on this one?

**Comment by yaron2** [comment]
`map[string]map[string]string ` is the more flexible data structure for returning multiple secrets, not just for Kubernetes but going forward for additional secret stores too. So I recommend we make that change.

**Comment by cmendible** [comment]
> `map[string]map[string]string ` is the more flexible data structure for returning multiple secrets, not just for Kubernetes but going forward for additional secret stores too. So I recommend we make that change.

@yaron for secrets stores that do not hold multiple secrets per key I'll create a key per secret and return a map with the same key and the secret value:

["my secret 1"][my secret 1]"secret value 1"
["my secret 2"][my secret 2]"secret value 2"

thoughts?

**Comment by yaron2** [comment]
> > `map[string]map[string]string ` is the more flexible data structure for returning multiple secrets, not just for Kubernetes but going forward for additional secret stores too. So I recommend we make that change.
> 
> @yaron for secrets stores that do not hold multiple secrets per key I'll create a key per secret and return a map with the same key and the secret value:
> 
> ["my secret 1"][my secret 1]"secret value 1"
> ["my secret 2"][my secret 2]"secret value 2"
> 
> thoughts?

Looks fine, but needs to be properly documented. SDKs can create custom, more typed structures on top of this.

**Comment by yaron2** [comment]
hey @cmendible please remember to update docs regarding the new structure. thanks!
