### ISSUE TITLE
Error while running `go mod tidy`

### ISSUE THREAD

**Issue by sayboras** [dapr/components-contrib#62]
## Expected Behavior

No error for `go mod tidy`

## Actual Behavior
The below error is happening
```
github.com/dapr/dapr/pkg/components/bindings imports
        github.com/dapr/components-contrib/bindings/kubernetes imports
        github.com/kubernetes-client/go/kubernetes/config tested by
        github.com/kubernetes-client/go/kubernetes/config.test imports
        k8s.io/client/kubernetes/config/api: git ls-remote -q https://github.com/kubernetes/client in /Users/XXX/go/pkg/mod/cache/vcs/1873572271fcf325ad32062ccf6aee165fdb6b2229b714b40050d6bf3d599824: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/kubernetes/client/' not found
```

```bash
$ go version
go version go1.13.3 darwin/amd64
```

## Steps to Reproduce the Problem
Just run `go mod tidy`

**Comment by sayboras** [comment]
@youngbupark @yaron2 need your input on this. 

There might be bigger conversation on why we checked in vendor folder as well. I am aware that this approach is quite common, but we might need to take extra steps to make sure following points:
- no unintended changes in files in vendor (this could be developer mistake), reviewer will not be able to spot this one due to large number of changes.
- how to keep vendor folder and `go.mod`, `go.sum` consistent

**Comment by yaron2** [comment]
Yeah, this issue covers it:
https://github.com/kubernetes/kubernetes/issues/83847

Looks like it will be resolved soon. If not, we should probably fall back to the previous Kubernetes Go client.

**Comment by sayboras** [comment]
@yaron2 thanks. Not sure here is the good one to discuss about my other question 

> @youngbupark @yaron2 need your input on this.
> 
> There might be bigger conversation on why we checked in vendor folder as well. I am aware that this approach is quite common, but we might need to take extra steps to make sure following points:
> 
> * no unintended changes in files in vendor (this could be developer mistake), reviewer will not be able to spot this one due to large number of changes.
> * how to keep vendor folder and `go.mod`, `go.sum` consistently in sync
