### ISSUE TITLE
GetBulkSecrets map duplicates the key in the submap

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#633]
## Expected Behavior

For keyvalue stores that do not support map as the secret, use a different solution to create the unary map:

```json
"mysecretkey": {
   "value": "secret content"
}
```

Documenting that "value" is used for secret stores that don't support map. This is better to address now than to break later.

## Actual Behavior

Instead of:

```json
"mysecretkey": {
   "mysecretkey": "secret content"
}
```

## Steps to Reproduce the Problem

Use local or env secret store.

## Release Note

RELEASE NOTE: N/A

**Comment by cmendible** [comment]
Hi @artursouza that was the previous behavior of the GetSecrets API and was changed a while ago by @yaron2 

https://github.com/dapr/components-contrib/commit/21853a1182250620ab985b61661f638ff64bceb8#diff-2ecf37fd044ed8183e8fe82389aed24f1549edebeb95b09f8ae4ba5c639b9c8d

For consistency we return the secret name on the GetBulkSecrets API.

Should we change both?

**Comment by artursouza** [comment]
@cmendible This was discussed within the maintainers and there was no sense that one way is better than the other. We will keep the current behavior to avoid breaking changes for V1 release.

Thanks.
