### ISSUE TITLE
Restrict environment variables in env local store

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#634]
Exposing all env variables from daprd into the app might expose unwanted secrets for some scenarios. To reduce attack surface, I propose the env requires the list of env variables allowed to be defined in the Component metadata.

**Comment by msfussell** [comment]
What secrets are you referring to? Can we have an example of this that may matter? 
It would be good to have a list of all the Dapr env variable so that we are clear which ones we are referring to.

**Comment by artursouza** [comment]
I am not referring to any Dapr environment variable specifically. I am referring that users might have environment variables in the container that runs Dapr but do not want to have all of them exposed to apps.

**Comment by artursouza** [comment]
Apps running in standalone mode already has access to all env variables, so this restriction is not adding any protection.
