### ISSUE TITLE
Undocumented cron "delete" operation never returns

### ISSUE THREAD

**Issue by withinboredom** [dapr/components-contrib#639]
## Expected Behavior

For the cron to be disabled

## Actual Behavior

The endpoint never returns

## Steps to Reproduce the Problem

Create a cron component with the name `cron` that calls the app every second, call:

`http://localhost:3500/v1.0/bindings/cron` with the body 

```json
{
	"operation": "delete"
}
```

Never receive a response causing the client to hang.

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Can you run Dapr with `log-level` set to `debug` and print any logs you see?
