### ISSUE TITLE
Add NATS as pubsub component

### ISSUE THREAD

**Issue by abhirockzz** [dapr/components-contrib#64]
## Describe the proposal

Add support for [NATS](https://github.com/nats-io/nats-server) as a pubsub component in Dapr. To be specific, the intention is to use [NATS queue groups](https://docs.nats.io/nats-concepts/queue) such that consumer Dapr apps can share the workload in a load-balanced way

**Comment by abhirockzz** [comment]
I have started working on this - https://github.com/dapr/components-contrib/pull/65

**Comment by amanbha** [comment]
@abhirockzz feel free to assign the issues to yourself when you start working on the,

**Comment by yaron2** [comment]
Closed via #65
