### ISSUE TITLE
Improve DynamoDB state store implementation: Support sort keys, handle batch errors, add transactions

### ISSUE THREAD

**Issue by cuongvo** [dapr/components-contrib#648]
# DynamoDB state store improvements

I ran into a few areas that could use improvement before I'm comfortable using the DynamoDB store in production. Happy to send in a PR if we agree on the improvements.

## Add sort key support

The current DynamoDB state store implementation is missing support for `sort keys`. Sort keys allow users more flexibility in querying the store directly. Per the state API key schema [here](https://docs.dapr.io/reference/api/state_api/#key-scheme-1) we can use the delimit character to store the data with a sort key. 

DDB doesn't support conditional expressions on partition keys. Sort keys, however, support a range of conditional expressions ([docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.KeyConditionExpressions)). This would allow users to query only items belonging to a service, only items belonging to an actor type, etc.

We allow callers to provide  a `partitionKey` and `sortKey` value as part of the request metadata. We fall back to a default key strategy similar to that implemented in TableStore [here](https://github.com/dapr/components-contrib/blob/master/state/azure/tablestorage/tablestorage.go#L230-L237) if those values don't exist. 

## Add error handling to batch writes / deletes

DDB has a 25 item limit (as well as 16MB of data, but that's outside this scope) per batch write / delete call. The current implementation lacks this [error checking](https://github.com/dapr/components-contrib/blob/master/state/aws/dynamodb/dynamodb.go#L121-L141) and would fail to write any item when more than 25 items are passed into the batch write call. 

We should support breaking batches greater than 25 items into separate calls.

## Add support for transactions

DynamoDB supports transactions ([docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis.html)) and should be able to support the API defined in [state transactions](https://docs.dapr.io/reference/api/state_api/#state-transactions).

**Comment by yaron2** [comment]
I agree on these improvements, a PR will be most welcomed.
