### ISSUE TITLE
Azure Service Bus Couldn't renew all active message lock(s) for topic

### ISSUE THREAD

**Issue by jjcollinge** [dapr/components-contrib#649]
## Expected Behavior
Azure Service Bus pubsub works reliably and consistently over time.

https://github.com/Azure/azure-service-bus-go/issues/155
## Actual Behavior
A bug in the underlying Azure Service Bus Go SDK is causing the connection to expire silently which is causing this issue to appear in Dapr. The upstream issue is tracked here: https://github.com/Azure/azure-service-bus-go/issues/155

This appear to occur after the ASB pubsub has been running successfully for some time (reports currently indicate after 11 hours, but this might be environment specific).

The maintainers of the Azure Service Bus Go SDK are currently investigating and we will use this issue to track progress. If this problem isn't resolved before we wan't to GA this component we should implement a workaround that periodically renews the connection to ensure we don't experience this issue.

**Comment by jjcollinge** [comment]
Root causes identified in SDK and fixed in v0.10.10. I will update the component tomorrow and validate the fix.

**Comment by alex-doerfler** [comment]
Is this fix already available in a Dapr release? We keep having whole service downtimes due to this issue.

**Comment by thoemmi** [comment]
I do see the fix is in master, but not in 1.0.2. Do you have an ETA for when the fix is will be released?

**Comment by yaron2** [comment]
> I do see the fix is in master, but not in 1.0.2. Do you have an ETA for when the fix is will be released?

March 30th: https://github.com/dapr/dapr/issues/2843

If you want to test it out, you can use the `:edge` image that already contains the fix.

**Comment by paulgyro** [comment]
Note I am still having occurrences of this issue in Dapr 1.6.1.    time="2022-04-08T17:31:26.9681729-07:00" level=debug msg="Couldn't renew all active message lock(s) for topic svcADemoEvent1, %!(EXTRA common.Retryable=unhandled error link 4e49caaa-e882-4f8c-9ad5-997f61039e44: status code 401 and description: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://***REMOVED***. TrackingId:3a355e91-7278-4a30-ad25-5c50e4a86fb1_G14, SystemTracker:NoSystemTracker, Timestamp:2022-04-09T00:31:25)" app_id=ServiceB instance=***REMOVED*** scope=dapr.contrib type=log ver=1.6.1

**Comment by yaron2** [comment]
> Note I am still having occurrences of this issue in Dapr 1.6.1.
> 
> Situation: Long running pub/sub operations on a service that is running for hours followed by hours of no new messages to process. Then dozens of messages that trigger long running events are fired off successfully but lock renewal fails causing the messages to be re-delivered repeatedly. Result: Massive increase in service load due to re-delivery.
> 
> time="2022-04-08T17:31:26.9681729-07:00" level=debug msg="Couldn't renew all active message lock(s) for topic svcADemoEvent1, %!(EXTRA common.Retryable=unhandled error link 4e49caaa-e882-4f8c-9ad5-997f61039e44: status code 401 and description: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://_**REMOVED**_. TrackingId:3a355e91-7278-4a30-ad25-5c50e4a86fb1_G14, SystemTracker:NoSystemTracker, Timestamp:2022-04-09T00:31:25)" app_id=ServiceB instance=_**REMOVED**_ scope=dapr.contrib type=log ver=1.6.1

There were several improvements in 1.7.0 worth testing out.

**Comment by paulgyro** [comment]
> > Note I am still having occurrences of this issue in Dapr 1.6.1.
> > Situation: Long running pub/sub operations on a service that is running for hours followed by hours of no new messages to process. Then dozens of messages that trigger long running events are fired off successfully but lock renewal fails causing the messages to be re-delivered repeatedly. Result: Massive increase in service load due to re-delivery.
> > time="2022-04-08T17:31:26.9681729-07:00" level=debug msg="Couldn't renew all active message lock(s) for topic svcADemoEvent1, %!(EXTRA common.Retryable=unhandled error link 4e49caaa-e882-4f8c-9ad5-997f61039e44: status code 401 and description: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://_**REMOVED**_. TrackingId:3a355e91-7278-4a30-ad25-5c50e4a86fb1_G14, SystemTracker:NoSystemTracker, Timestamp:2022-04-09T00:31:25)" app_id=ServiceB instance=_**REMOVED**_ scope=dapr.contrib type=log ver=1.6.1
> 
> There were several improvements in 1.7.0 worth testing out.

I will upgrade and re-test then report back.

**Comment by paulgyro** [comment]
> > Note I am still having occurrences of this issue in Dapr 1.6.1.
> > Situation: Long running pub/sub operations on a service that is running for hours followed by hours of no new messages to process. Then dozens of messages that trigger long running events are fired off successfully but lock renewal fails causing the messages to be re-delivered repeatedly. Result: Massive increase in service load due to re-delivery.
> > time="2022-04-08T17:31:26.9681729-07:00" level=debug msg="Couldn't renew all active message lock(s) for topic svcADemoEvent1, %!(EXTRA common.Retryable=unhandled error link 4e49caaa-e882-4f8c-9ad5-997f61039e44: status code 401 and description: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://_**REMOVED**_. TrackingId:3a355e91-7278-4a30-ad25-5c50e4a86fb1_G14, SystemTracker:NoSystemTracker, Timestamp:2022-04-09T00:31:25)" app_id=ServiceB instance=_**REMOVED**_ scope=dapr.contrib type=log ver=1.6.1
> 
> There were several improvements in 1.7.0 worth testing out.

I have re-tested with Dapr 1.7 and the issue remains.  How do you recommend I proceed?

**Comment by niclasrothman** [comment]
Hi everyone, we are starting to see this issues as well on dapr 1.7.2 with the exact same behaviour, starting to process messages but after a while it "halts" with the following message;

`{"app_id":"x-backgroundtasks","instance":"x-backgroundtasks-bc4dcbcb6-jn8wz","level":"debug","msg":"Trying to renew 2126 active message lock(s) for topic x-client","scope":"dapr.contrib","time":"2022-06-26T05:56:05.407093931Z","type":"log","ver":"1.7.2"}`

Should we reopen this issue?

Nic

**Comment by sumanthpopuri** [comment]
We are also getting the same issue with version 1.9.5

time="2023-03-13T14:52:29.797904841Z" level=debug msg="Couldn't renew all active message lock(s) for topic <Redacted>, %!(EXTRA *fmt.wrapError=failed to send message with ID <Redacted>: context deadline exceeded)" app_id=<Redacted> instance=<Redacted> scope=dapr.contrib type=log ver=1.9.5
