### ISSUE TITLE
[Question] Pubsub semantics

### ISSUE THREAD

**Issue by abhirockzz** [dapr/components-contrib#66]
## Ask your question here

As per [pubsub docs](https://github.com/dapr/docs/blob/master/concepts/publish-subscribe-messaging/README.md) "Dapr guarantees At-Least-Once semantics for message delivery". Does this imply that means that pubsub component does not depend on the underlying messaging implementation semantics? e.g. if the "implementation A" supports (or is configured to support) "at-most-once" (no duplicates), Dapr might still end up re-trying and sending duplicate messages?

Let me know if this is posted/detailed elsewhere

**Comment by yaron2** [comment]
The Dapr runtime is written to return an error into the pubsub component in case of an unsuccessful delivery into user code.

In addition, Dapr runtime will not make use of pubsub components (implementation) which do not guarantee at least once semantics.

Hope this clarifies.
