### ISSUE TITLE
State - Inconsistent use of json/byte[] - (Cosmos state store)

### ISSUE THREAD

**Issue by perokvist** [dapr/components-contrib#665]
## Expected Behavior

When storing an object using StateTransactionRequest, it should be able to retrieve the same object using GetStateAsync<MyObject> or any generic GetState operation.

When using cosmos I expect all data to be stored as json.

This affects;
- Consistent API for the SDK
- Being able to query my collection (json expected)
- Using change feed (json expected)

(running this [http transaction sample](https://docs.dapr.io/reference/api/state_api/#examples)  with the cosmos state store - stores data as json).

## Actual Behavior

- StateTransactionRequest stores data as byte[]
- GetStateEntryAsync<MyObject> throws since it expects json

## Steps to Reproduce the Problem

- Save an object (MyObject) using StateTransactionRequest
- Fetch it using GetStateEntryAsync<MyObject> or any generic GetState operation

**Comment by yaron2** [comment]
This was fixed, I'm closing this for now as it'll come out with the next release.

Please re-open if you encounter this after using the next release.

**Comment by perokvist** [comment]
This solves the problem, when working with Api/SDK.

But using bytes in stores catered for json is not "optimal".

In the Cosmos case this affects;

- Being able to query my collection (json expected)
- Using change feed (json expected)

Is there a future where avoiding bytes could be an option ?

**Comment by perokvist** [comment]
@rynowak is it the .NET SDK that is forcing state in cosmos to be stored as bytes.
To my understanding, the cosmos component just honors what is sent, buy checking if its an byte[].
(or am I reading https://github.com/dapr/components-contrib/blob/master/state/azure/cosmosdb/cosmosdb.go#L338 wrong?) 😕 

Even if the state now is byte[] is consistent. 

 ```
        [Fact]
        public async Task SavingStateAsync()
        {
            await client.SaveStateAsync("localcosmos", "storage-test-1", new TestEventRecord("hello there"));
            await client.ExecuteStateTransactionAsync("localcosmos", new[] {
                new StateTransactionRequest("storage-test-2", JsonSerializer.SerializeToUtf8Bytes(new TestEvent("hello there")), StateOperationType.Upsert) });
        }
```

It would be preferable if it where json (or an option for json).

**Comment by rynowak** [comment]
@perokvist - can you please either take this feedback to dapr/dotnet-sdk (new issue) or open a new issue here? Comments on closed issues are not likely to result in a follow-up.

**Comment by perokvist** [comment]
@rynowak sound like a plan!
I've created an new [issue](https://github.com/dapr/dotnet-sdk/issues/614) in the SDK repo, lets see if it should stay there...
