### ISSUE TITLE
To rename StateStore interface in state package

### ISSUE THREAD

**Issue by sayboras** [dapr/components-contrib#67]
## Describe the proposal

As discussed in https://github.com/dapr/components-contrib/pull/59#discussion_r339658021, the `StateStore` interface can be renamed to `Store` for simplicity.

**Comment by youngbupark** [comment]
cc/ @yaron2 @Haishi2016 @amanbha @shalabhms @LMWF

**Comment by yaron2** [comment]
I edited the title and body to reflect interface and not struct.
