### ISSUE TITLE
Proposal: Metadata/Configuration decoding package

### ISSUE THREAD

**Issue by pkedy** [dapr/components-contrib#707]
There are several areas in the code where metadata/configuration in the form of `map[string]string` or `map[string]interface{}` are manually converted into Go structs. While this works, the code is inconsistent across implementations (components and conformance tests). This type of code could be greatly simplified and made less error-prone. It could and also benefit from consistent error messages and decoding functions. An example decoding function would be parsing a `time.Duration` as either milliseconds `5000` or string `"5s"`. You should also be able to use an interface to handle custom decoding for enums or where names equate to numeric values (e.g. `infinite -> -1`)

To accomplish this would involved is a fairly simple wrapper around the [mapstructure](https://github.com/mitchellh/mapstructure) package which we already use. It could be applied initially to the conformance tests and to make retries the pubsub components configurable.

**Comment by artursouza** [comment]
Let's start with conformance tests here.

Regarding making the change in components, just remember not to make breaking changes. Breaking change here means that applications should not need to change their component yaml for anything and the behavior of the components should not change either since this is more like a refactoring.

**Comment by pkedy** [comment]
💯 Agree. I've got the code ready to go but it relies on #702. Please assign this to me and add it to the 1.1 Milestone.

Note on the breaking changes. Once we are comfortable using it, it should not required components to change their YAML. It's a pure refactoring.
