### ISSUE TITLE
MongoDB State Store should throw an exception if an etag is set on the request

### ISSUE THREAD

**Issue by stephenaggett** [dapr/components-contrib#708]
## Expected Behavior

When setting a value for an etag when using a MongoDB state store, an exception should be thrown indicating that this is not supported.

## Actual Behavior

The etag is ignored. In cases of etag mismatches data is overwritten with no exceptions thrown.

## Steps to Reproduce the Problem

Call `DaprClient.TrySaveStateAsync` when using a MongoDB State Store (it will always return true regardless of the value of the etag).

## Release Note

RELEASE NOTE: **FIX** MongoDB State Store now throws an exception if the caller passes an etag (which not supported by this state store).

**Comment by halspang** [comment]
MongoDB received ETag support in this issue: https://github.com/dapr/components-contrib/issues/726

Tests verifying ETags were added here: https://github.com/dapr/components-contrib/issues/711

**Comment by artursouza** [comment]
Closing issue.
