### ISSUE TITLE
Add ETag to Statestore Conformance Testing

### ISSUE THREAD

**Issue by halspang** [dapr/components-contrib#711]
## Describe the proposal
ETags play a critical role in concurrency. Statestores are not required to support ETags directly but are expected to provide a similar level of functionality through whatever the underlying store provides. Currently, some statestores list that they support ETags directly. The proposal here is to add this as an optional operation in the conformance tests. Any statestore that wants to implement ETags directly can now have a simple proving ground to show that it meets what we expect.

[Note on ETags](https://docs.dapr.io/developing-applications/building-blocks/state-management/state-management-overview/#concurrency)
[Supported Stores](https://docs.dapr.io/operations/components/setup-state-store/supported-state-stores/)

The actual tests would be simplistic and not try and perform non-deterministic threading but rather would test the following:

- ~~Set with ETag takes given ETag~~
- Upsert with wrong ETag fails
- Upsert with correct ETag succeeds
- Delete with wrong ETag fails
- Delete with correct ETag succeeds

**Comment by mukundansundar** [comment]
`Set with ETag takes given ETag` I think this is not possible. Redis starts with version 1 always if I remember correctly and cosmosDB also has server side auto generated Etag https://docs.microsoft.com/en-us/azure/cosmos-db/database-transactions-optimistic-concurrency#optimistic-concurrency-control
```
Every item stored in an Azure Cosmos container has a system defined _etag property. The value of the _etag is automatically generated and updated by the server every time the item is updated. 
```

I think the rest look ok.

**Comment by halspang** [comment]
Yeah, it looks like that was just a coincidence with how I was testing where my chosen ETag was the first ETag that Redis chose. I'll remove that ask.
