### ISSUE TITLE
Enhance Kafka bindings to support SASL auth

### ISSUE THREAD

**Issue by abhirockzz** [dapr/components-contrib#72]
## Describe the proposal

Kafka brokers can be configured to support SASL authentication. The Dapr Kafka binding can be enhanced to provide this. This will allow integration with any Kafka broker including managed ones (where auth is mandatory) such as Azure Event Hubs, Confluent etc.

This authentication is optional and can be disabled using Dapr config e.g. `authRequired: "false"`

**Comment by abhirockzz** [comment]
I plan to work on this. Let me know if this sounds like a reasonable proposal. Thanks!

**Comment by yaron2** [comment]
Sounds great, thanks!

**Comment by yaron2** [comment]
closed via #77
