### ISSUE TITLE
Azure Service Bus Topics

### ISSUE THREAD

**Issue by alanwales** [dapr/components-contrib#73]
Hello,

Is there a way to subscribe to a topic? I have tried the sample and can connect to a queue successfully but not to a topic (even with the /dapr/subscriptions endpoint added):

https://github.com/dapr/docs/blob/master/concepts/bindings/specs/servicebusqueues.md

Also I traced the http response and can't seem to get the message properties from the service bus message, just the content. I would like at least to get the CorrelationId from the message headers if that is supported? Thanks

**Comment by yaron2** [comment]
Hey @alanwales , Azure Service Bus is a binding, meaning that in order to get events as input bindings there's no topic subscription needed, as you'd have with Pub-Sub.

**Comment by alanwales** [comment]
Thanks for the reply, it's a little bit confusing the separation between a Binding and PubSub since most of the bindings have a pub-sub flavour to them, but I see that there is a pr open for Azure Service Bus PubSub added a few days ago so that will be really useful when it lands.

https://github.com/dapr/components-contrib/issues/92

Cheers
