### ISSUE TITLE
[Proposal] Add Azure Event Grid for Pub-Sub 

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/components-contrib#74]
## Describe the proposal

Using [custom topics](https://docs.microsoft.com/en-us/azure/event-grid/event-sources#custom-topics) as event source and [WebHooks](https://docs.microsoft.com/en-us/azure/event-grid/event-handlers#webhooks) as event handlers

**Comment by yaron2** [comment]
Yeah that's a good proposal, only question is which IP do you give Event Grid when running on Kubernetes/local dev machine?

**Comment by RicardoNiepel** [comment]
### Local
not nice, but in line with other docs - using ngrok as tunnel.

Look at [Event Grid Trigger Local Debugging](https://docs.microsoft.com/en-us/azure/azure-functions/functions-debug-event-grid-trigger-local#allow-azure-to-call-your-local-function)

### K8s
Is adding auth to service invocation on the roadmap?  
If, this would be something we can also leverage for securing the sub endpoints?

Using a pubsub (or binding) broker which is outside of K8s (or only available in the cloud) is a common scenario and not specific to Event Grid, thus we need an overall design for this.

**Comment by yaron2** [comment]
> Is adding auth to service invocation on the roadmap?

Yes, but I don't want to tie it to this particular issue..
Authentication with cloud pub-sub infrastructure is tied to the specific implementation, whether its certificate/token based.

**Comment by RicardoNiepel** [comment]
For reference - PR for EventGrid as Binding: https://github.com/dapr/components-contrib/pull/290

I think the same questions apply here too:

> Yeah that's a good proposal, only question is which IP do you give Event Grid when running on Kubernetes/local dev machine?

**Comment by msfussell** [comment]
https://github.com/dapr/components-contrib/pull/290

**Comment by tomkerkhove** [comment]
Would love to have Event Grid as well - Either in-cluster or custom topic!

**Comment by tomkerkhove** [comment]
Looks like this was merged and done but not documented on https://github.com/dapr/components-contrib/blob/master/pubsub/Readme.md, is that correct?

**Comment by yaron2** [comment]
There's an Event Grid binding, not Pub/Sub.

**Comment by horros** [comment]
I too would love to have this.
