### ISSUE TITLE
How to give vaultTokenMountPath in Multinode Cluster

### ISSUE THREAD

**Issue by kamesh1677** [dapr/components-contrib#741]
Hi Team,

I am exploring on Dapr Secret management with Hashicorp Vault  in Multi node CLuster in K8S env.. 

How to pass vaultTokenMountPath in Mutlinode cluster or any Cluster . 

Component yaml .

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: vault:8270 # Optional. Default: "https://127.0.0.1:8200"
  - name: skipVerify # Optional. Default: false
    value : true
  - name: vaultTokenMountPath # Required. Path to token file.
    value : ??? (/root/Desktop/vaulttoken)

/root/Desktop/vaulttoken --do we need to create manually this file and refer in vaultTokenMountpath. 
PLease help me how to provide the path.

**Comment by kamesh1677** [comment]
> Hi,
> 
> Were you able to find the way to mount the path?

Hi 

Haven't tried this scenario again . Currently we are proceeding with the K8S secret loading mechanism.

**Comment by frvasquezjaquez** [comment]
> > Hi,
> > Were you able to find the way to mount the path?
> 
> Hi
> 
> Haven't tried this scenario again . Currently we are proceeding with the K8S secret loading mechanism.

Just to let you know, in the version 1.2, i was able to doint using the vaultToken param instead vaultTokenMountPath. Here is the documentation:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: [vault_address] # Optional. Default: "https://127.0.0.1:8200"
  - name: caCert # Optional. This or caPath or caPem
    value: "[ca_cert]"
  - name: caPath # Optional. This or CaCert or caPem
    value: "[path_to_ca_cert_file]"
  - name: caPem # Optional. This or CaCert or CaPath
    value : "[encoded_ca_cert_pem]"
  - name: skipVerify # Optional. Default: false
    value : "[skip_tls_verification]"
  - name: tlsServerName # Optional.
    value : "[tls_config_server_name]"
  - name: vaultTokenMountPath # Required if vaultToken not provided. Path to token file.
    value : "[path_to_file_containing_token]"
  - name: vaultToken # Required if vaultTokenMountPath not provided. Token value.
    value : "[path_to_file_containing_token]"
  - name: vaultKVPrefix # Optional. Default: "dapr"
    value : "[vault_prefix]"
```

**Reference**: https://docs.dapr.io/reference/components-reference/supported-secret-stores/hashicorp-vault/
