### ISSUE TITLE
StateStore - Storing Value as byte[] - (cosmos state component)

### ISSUE THREAD

**Issue by perokvist** [dapr/components-contrib#745]
Prior there was an [issue ](https://github.com/dapr/components-contrib/issues/665) with inconsistent use of json/byte[] for the cosmos component. 

State is now stored as byte[] on all operations, using cosmos (see test below).

But using bytes in stores catered for json is not "optimal".

In the Cosmos case this affects;

Being able to query my collection (json expected)
Using change feed (json expected)

Is this a concern for the SDK or on component level ?
To my understanding the [component checks](https://github.com/dapr/components-contrib/blob/master/state/azure/cosmosdb/cosmosdb.go#L338) the value, if its byte[]. 

```
      [Fact]
       public async Task SavingStateAsync()
       {
           await client.SaveStateAsync("localcosmos", "storage-test-1", new TestEventRecord("hello there"));
           await client.ExecuteStateTransactionAsync("localcosmos", new[] {
               new StateTransactionRequest("storage-test-2", JsonSerializer.SerializeToUtf8Bytes(new TestEvent("hello there")), StateOperationType.Upsert) });
       }
```

**Comment by artursouza** [comment]
Until there is a centralized approach to content-type in Dapr API, we can have a component level metadata for CosmosDB that can change the current behavior for text-only scenarios or to force a single content-type:

* Option 1: `textOnly` boolean - so everything is considered text, so byte[] becomes string.
* Option 2: `defaultContentType` string - so there is logic to determine how to try to convert byte[] into the defined content type. This has an advantage that can be reused later on when content-type is added as an optional attribute in the API.

**Comment by iayti** [comment]
I have the same issue [dapr/dotnet-sdk/issues/631](https://github.com/dapr/dotnet-sdk/issues/631) in Azure Cosmos DB component. I read [Practical-Microservices-with-Dapr-and-.NET](https://github.com/PacktPublishing/Practical-Microservices-with-Dapr-and-.NET) and look at the samples in this repository. I think this book and repository were published 4-5 months ago. There was no such problem back then. The image below is from the example in the book. 
<img width="643" alt="Screen Shot 2021-03-11 at 22 59 39" src="https://user-images.githubusercontent.com/30297580/110847097-8d8a1a00-82bd-11eb-9e6a-a908a2bdf62d.png">
