### ISSUE TITLE
Topic message lost if it is published before any subscriptions to the topic are registered, and a read attempt made

### ISSUE THREAD

**Issue by georgestevens99** [dapr/components-contrib#751]
## Expected Behavior

When I attempt to receive a message resident in an Azure Service Bus topic via the dapr ASB pubsub component I expect either the message to be delivered or an error message to result, notifying my app that the attempt to retrieve the message has failed.

## Actual Behavior
In one very specific situation, the dapr ASB pubsub component fails to retrieve a message resident in a topic, yet does not show any indication of error either in the dapr log (--loglevel debug) or by throwing an exception in the service code that is using the component.  Thus, this **silent failure losses a message** and no one has a clue this happens unless they examine the Topic logs (activity logs in the Azure Portal), where upon they will find a "User Error" logged each time this happens.  

This happens when using the .NET SDK with a gRPC service.

This only happens when the Topic has NO SUBSCRIPTIONS and >= 1 messages are sent to the topic while in that "no subscriptions" state.  Then, still with no subscriptions, when a service using the ASB topic component  creates a subscription. and then attempts to read the messages from the topic, a User Error will be generated in the Topics activity log, but will not be visible  to the service or dapr.   It appears the Topic has not been able to associate the messages in the topic with the new just made subscription.

## Steps to Reproduce the Problem

Here is a log of the actions I used to recreate this.  The log below shows 2 attempts, the first without dapr running withOUT --loglevel debug and the second with it.  NOTE QTC is the Test Client, a simple console app.

The first few lines are a note to myself for future reference.  Then my log follows:

![image](https://user-images.githubusercontent.com/6517661/110561047-feda9900-8114-11eb-8ae0-0da060eacbfe.png)

For a quick and dirty fix, all that is necessary is to **put a WARNING notice in the component documentation that all Subscriptions must be created BEFORE items are published to a topic**.

A longer term and cleaner fix would be to have the .NET SDK or Dapr runtime throw an exception so that the service would be able to detect this condition.  Perhaps there some way around this, but at minimum a clear error needs to show up in an obvious place since lost messages are a bad thing.

## Release Note

RELEASE NOTE:

**Comment by lynn-orrell** [comment]
@georgestevens99, if I understand you correctly, you have created a topic in Service Bus but haven't created any subscriptions to that topic. You then publish a message to said topic. If there are no subscriptions to the topic when the message is published, the message is "lost". 

This is how Service Bus works. If you publish a message to a topic in which there are no subscriptions, the message will get dropped on the floor as there is nowhere to deliver it to.

Please let me know if I missed something.

**Comment by georgestevens99** [comment]
What you said is true.  However since using the Service Bus is so simple
with Dapr bindings, I'll bet that a lot of people that use this binding do
not have a clue how the Service Bus Topic works and what the minimum
requirements are.  And at least they deserve a WARNING in the Service Bus
Topic binding component instructions, if not an error message from Dapr so
as to make their mistake easier to detect and to fix.  Indeed, I looked at
the Azure Service Bus Topic documentation and it did not say that an error
would happen under these conditions.  So how is a naive use supposed to
know these things?  And the polyglot nature of Dapr ensures there will be
plenty of developers unfamiliar with various chunks of technology.  Let's
be nice to them and make their job easier.

My goal is to save people from making easy-to-make mistakes and having to
know all the quirks of supported technologies so they come away being
happy, rather than being frustrated by having to wrestle with the
technology for hours to get it to work properly.  A user (developer)
friendly point of view that generally makes for satisfied customers.

Thanks,
George

**Comment by jjcollinge** [comment]
@georgestevens99 thanks for raising this issue. I think the best we could do here is to add a note to the documentation as you suggested. As is expected with pubsub, the publisher is firing and forgetting without knowledge of whether there is any subscribers at any point in time which means it'd be very difficult to provide a warning when this is the case and providing a warning always seems overkill. Would this be a change to the docs you'd be happy to make? Cheers

**Comment by georgestevens99** [comment]
@jjcollinge Putting a warning in the ASB PubSub Component document seems like it will work.  I'll have time to write up the wording and put it in the component documentation next week.  Is that OK.  And what next?  I am unfamiliar with the process.

**Comment by georgestevens99** [comment]
This was marked stale but is too important to let go of.  Loosing messages is never good, even if that is the default behavior of the underlying messaging backbone.  In effect, this tightly couples the publisher and subscriber in that the publisher has to know a subscriber has completed its subscription process successfully.  PS I would tag it as pinned but the description of how to do that in the Git Labels documentation does not match up with the way the Issue UI behaves?
