### ISSUE TITLE
Passing Service Bus Properties

### ISSUE THREAD

**Issue by mladedav** [dapr/components-contrib#755]
## Describe the proposal

Probably when converting from Service Bus' AMQP message to CloudEvent, all properties (application properties in AMQP 1.0 spec) are lost. This metadata may have vital business value in some cases and as such should be passed (it should probably enrich the data portion of the cloud event).

**Comment by yaron2** [comment]
Your app can compose it's own Cloud Event and there you can pass all of the AMQP fields as custom fields on the Cloud Event itself.

Here's how to send a custom Cloud Event: https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/#Content-Types

https://docs.dapr.io/reference/api/pubsub_api/#headers

**Comment by yaron2** [comment]
Another way to do it would just be to send the AMQP message in the `.data` field and it'll retain it's properties.

**Comment by mladedav** [comment]
When we have direct control over the messages we could use cloud events, but sometimes we are consuming messages from sources that use properties for Service Bus messages or it is undesirable to change the systems to not use the properties.

I believe scenarios where developers have to integrate with messages from other sources will be very common and therefore I believe this feature should be addressed in dapr (potentially as an option in the pubsub). But I would first like to know the stance of dapr developers, if this is a direction that the team wouldn't want to pursue, I would understand and this issue can be closed.

**Comment by mike-reynolds-savient** [comment]
I concur with this as I suspect it affects 'bindings' as well. Most of our data will not come from a system we control, but message headers are set to describe the user, provenance and routing information.
These headers need to be available when received in our application's code.
