### ISSUE TITLE
DaprException INTERNAL error when publish to topic

### ISSUE THREAD

**Issue by javageek79** [dapr/components-contrib#770]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
We encounter an increasing amount of exceptions during runtime when publishing messages to azure service bus, which we use for pubsub component. Nearly all of them are timeout exceptions.

Is there a way to configure timeouts when connecting to azure service bus in a pubsub component to avoid timeout exceptions?
![image](https://user-images.githubusercontent.com/3714921/111774307-911a3400-88af-11eb-9deb-a96e5ff29d6b.png)
Maybe it would also be possible, to configure retries in case of timeouts.

**Comment by javageek79** [comment]
Hi @artursouza, do you have any documentation on how the timeout settings are for gRPC connections from / to the sidecar?
We not only having problems to publish, but also to subscribe to topics.

A short sidenote,
we lately reduced the [kubernetes_cluster idle timeout](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#idle_timeout_in_minutes)   down to 4min, while the default used to be 30min.

**Comment by artursouza** [comment]
> Hi @artursouza, do you have any documentation on how the timeout settings are for gRPC connections from / to the sidecar?
> We not only having problems to publish, but also to subscribe to topics.
> 
> A short sidenote,
> we lately reduced the [kubernetes_cluster idle timeout](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#idle_timeout_in_minutes) down to 4min, while the default used to be 30min.

Subscribe does not happen over gRPC usually, unless you start a gRPC server and implement the Dapr callback proto API (please, confirm if this is the case). Daprd will invoke an HTTP endpoint on your app to deliver each pubsub message. Where is the timeout message showing up on the subscriber end?

In the meantime, I am looking into the timeout issue in publish.

**Comment by artursouza** [comment]
@javageek79 We just had a PR addressing your concern regarding timeout and reconnection in Azure Service Bus: https://github.com/dapr/components-contrib/commit/ca62139f473c4c879c984471cb154fbb86894ad9#diff-8f0a750f05222eb118aded3b8c6c3a926a2564220b5a9c2fd06e6e75c7180aaf

This issue seems to be a duplicate of #692. Please, try this out in 1.1 (once released) to confirm it is addressed. I will keep the issue open until then.

**Comment by javageek79** [comment]
@artursouza cool, thanks for the response.

I also took a more closer look and it somehow seems, that those are two different timeout situations.

1. error on startup, when connecting to pubsub causes a timeout (#692)
![image](https://user-images.githubusercontent.com/3714921/112274080-5c76f580-8c7e-11eb-80f8-f9611b6fdedd.png)
here, logs look different and would also prevent startup of sidecar.

2. the issue described above. Timeout occurs during runtime of a sidecar. Here sidecar tries to publish a message to a topic

3. Similar to 2., Timeout also occurs during runtime of a sidecar. Here sidecar tries to receives a message from a topic due to a subscription.
