### ISSUE TITLE
pubsub using eventhub with multiple consumer groups

### ISSUE THREAD

**Issue by msjiaxie** [dapr/components-contrib#773]
## Ask your question here
We are using EventHub as a message broker, we created a EventHub instance(topic). We have two subscribers with different dapr app id, so we created two consumer groups using two app id. Then we published 10 messages to the EventHub instance, but one consumer group A received 4 messages and the other one consumer group B received 6 messages. From our understanding, consumer group A and B should receive 10 messages separately.

[Setup Azure Eventhubs](https://docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/setup-azure-eventhubs/)
```
Create consumer groups for each subscriber
For every Dapr app that wants to subscribe to events, create an Event Hubs consumer group with the name of the dapr id. For example, a Dapr app running on Kubernetes with dapr.io/app-id: "myapp" will need an Event Hubs consumer group named myapp.
```

The official document says that each consumer group should maintain its own meta data. 

[Consumer Groups](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features)
```
The publish/subscribe mechanism of Event Hubs is enabled through consumer groups. A consumer group is a view (state, position, or offset) of an entire event hub. Consumer groups enable multiple consuming applications to each have a separate view of the event stream, and to read the stream independently at their own pace and with their own offsets.
```

Do I misunderstand the usage of pubsub eventhub? Anyone could help?

**Comment by CodeMonkeyLeet** [comment]
@msjiaxie This does seem to be unintuitive behavior, let me take a look and get back to you.

**Comment by CodeMonkeyLeet** [comment]
@msjiaxie it seems like there are a couple of overlapping issues here, and the gist is that the alpha EventHub pubsub component has Dapr semantics which are at odds with the Event Hubs semantics. Dapr pubsub in general provides a [competing consumers pattern](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/dn568101(v=pandp.10)) for consuming events, and the behavior you observe is consistent with that pattern.

However, as you note, EventHubs was designed explicitly for throughput using the partitioned consumers pattern, and that is not properly handled through the Dapr pubsub interface. The EventHubs _bindings_ component does let you use the partitioned consumer pattern, though I've not tested its behavior with respect to consumer groups.

Independent of the broader question of whether Dapr pubsub should implement fan-out consumption (see https://github.com/dapr/dapr/issues/3332), the implementation of the EventHubs pubsub component itself seems to depend on an old version of the EventProcessorHost to handle checkpointing, and it is sharing the storage for checkpoints between consumer groups. Given that the EventHubs pubsub component has other critical challenges (such as no support for topics, #964), there might need to be a rework of the alpha EventHubs pubsub  component.
