### ISSUE TITLE
[PROPOSAL] - Standardise on supported metadata for Storage bindings

### ISSUE THREAD

**Issue by bhummerstone** [dapr/components-contrib#777]
## In what area(s)?

> /area runtime
/area operator
> /area placement
> /area docs
> /area test-and-release
## Describe the proposal

Per PR https://github.com/dapr/docs/pull/1329, there is no standardisation on the metadata passed to a Storage binding, which means that a different JSON payload must be constructed each time; see here for an example: https://gist.github.com/bhummerstone/92420db52c499f2e4e7a131240354cc2

I propose standardising on the metadata that a binding of each type (e.g. Storage) can accept. For Storage, this could be as simple as using "name" for each binding of that type to refer to the destination file name.

As a practical example, this would require only minor changes to e.g. the AWS S3 binding (https://github.com/dapr/components-contrib/blob/master/bindings/aws/s3/s3.go):
- In the Invoke function (line 61) change all reference to "key" to "name"
- For line 73, keep this as "Key:    aws.String(name)" as this is what the AWS SDK expects

As a tangential issue, the Azure Storage binding supports base64 encoding whilst AWS/GCP do not: I appreciate that these are all in Alpha, but it would be great to have a standard set of functionality that the bindings implement.

**Comment by yaron2** [comment]
Moved the issue to components-contrib.

We can make these changes backward compatible, so I'm not overly worried here.

@bhummerstone can you create a table that shows the current metadata names and suggested metadata names for storage bindings?

**Comment by bhummerstone** [comment]
Binding | Current Value | Proposed Value
------------ | ------------ | ------------
Alibaba Cloud Object Storage | key | name
AWS S3 | key | name
Azure Blob | blobName | name
GCP Storage Bucket | name | name

Not the most exciting table ever, but it will do :)

Azure Blob also supports base64 encoding which the others do not, so that's a potential thing to add to any schema

**Comment by bhummerstone** [comment]
Happy to use "key" or "fileName" instead of "name" for everything, but as long as it is consistent it doesn't make much difference imo

**Comment by bhummerstone** [comment]
Just seen the new Local Storage binding that implements things slightly differently again: it uses "fileName" in the metadata, and also supports automatic base64 decoding
