### ISSUE TITLE
Hashicorp Vault - accept root token as string instead of file

### ISSUE THREAD

**Issue by Banchio** [dapr/components-contrib#794]
I'm trying to setup Hashicorp Vault as secret store and have an issue on how to pass the token file to the component while running in the sidecar in the Kubernetes cluster. 
My proposal is to introduce another configuration parameter (vaultToken?) which is required if vaultTokenMountPath is not supplied. This way I would be able to pass the token using standard kubernetes secretRef syntax.
Thanks!

**Comment by DarqueWarrior** [comment]
I am willing to update the component if everyone agrees to this change. I think we support the current file-based method as well as a `vaultToken` that can be read from a K8s secret.
