### ISSUE TITLE
Where can I find component maturity level - alpha, beta, GA?

### ISSUE THREAD

**Issue by maulik-modi** [dapr/components-contrib#795]
Where can I find component maturity level - alpha, beta, GA?

**Comment by mukundansundar** [comment]
For the lifecycle see https://docs.dapr.io/operations/components/certification-lifecycle/
For the individual components: 
https://docs.dapr.io/operations/components/setup-state-store/supported-state-stores/
https://docs.dapr.io/operations/components/setup-pubsub/supported-pubsub/
https://docs.dapr.io/operations/components/setup-secret-store/supported-secret-stores/
https://docs.dapr.io/operations/components/setup-bindings/supported-bindings/
https://docs.dapr.io/developing-applications/middleware/supported-middleware/
