### ISSUE TITLE
Add Kafka for Pub-Sub

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#8]

**Comment by robertojrojas** [comment]
@yaron2 I'm going to work on this issue and I was planning to use the [Sarama](https://github.com/Shopify/sarama) package.

**Comment by yaron2** [comment]
Thats great, thanks!

**Comment by yaron2** [comment]
@robertojrojas are you actively working on this?

**Comment by robertojrojas** [comment]
@yaron2 Any suggestions on how to integration test the pubsub component?

**Comment by yaron2** [comment]
Add the following line at the bottom of `go.mod` in the `dapr` repo:
`replace github.com/dapr/components-contrib => ../components-contrib`

This assumes your modified components-contrib code resides in the same directory that has the `dapr` repo in it.

Open a terminal in the `dapr` repo and run `go mod vendor`.

This should pull all the dependencies including components-contrib from your local copy into `dapr`.

Then, update the loader in the Dapr runtime under `/pkg/components/pubsub/loader.go`:

```
import "github.com/dapr/components-contrib/pubsub/kafka"

RegisterMessageBus("kafka", kafka.NewKafka)
```

You can then build the daprd binary locally, copy it to your PATH and test it with the [pub-sub sample
](https://github.com/dapr/samples/tree/master/4.pub-sub)

**Comment by robertojrojas** [comment]
@yaron2 Thanks for the instructions.

**Comment by rohitshrivastava04** [comment]
quite interested in having a look at kafka pub sub, just wanted to know would it support Schema registry for AVRO schema?

**Comment by mihaimyh** [comment]
Is AVRO schema registry supported?

**Comment by mukundansundar** [comment]
> Is AVRO schema registry supported?

@mihaimyh please create a separate issue for this question.
