### ISSUE TITLE
Wrong command

### ISSUE THREAD

**Issue by DarqueWarrior** [dapr/components-contrib#808]
## Expected Behavior

Step 6 of developing-component.md states this.

6. Replace the installed daprd with the test binary (then dapr cli will use the test binary)
\# Back up the current daprd
_mv /usr/local/bin/daprd /usr/local/bin/daprd.bak_
cp ./dist/darwin_amd64/debug/daprd ~/.dapr/bin

## Actual Behavior

I think it should be this.

6. Replace the installed daprd with the test binary (then dapr cli will use the test binary)
\# Back up the current daprd
**mv ~/.dapr/bin/daprd ~/.dapr/bin/daprd.bak**
cp ./dist/darwin_amd64/debug/daprd ~/.dapr/bin

On my machine I don't have `/usr/local/bin/daprd`. Is that a typo or is my machine to setup correctly?

It is also odd to say backup a file in one location (/usr/local/bin/daprd) and to copy the new version to a different location (~/.dapr/bin). 

## Release Note

RELEASE NOTE:

**Comment by akkie** [comment]
@DarqueWarrior On different machines the file is located in a different location. I think this serves only as an example.

**Comment by DarqueWarrior** [comment]
OK. Even as an example the source of the backup should also be the target of the new file right? To your point, you can change the first or second line. Just seems silly to backup one file and then copy a different file somewhere else. :)

**Comment by pkedy** [comment]
This was fixed by #843 after I saw someone on Discord run into this problem.
