### ISSUE TITLE
Add support for HashiCorp Vault as a secret store

### ISSUE THREAD

**Issue by anubhavmishra** [dapr/components-contrib#81]
Implement HashiCorp [Vault](https://vaultproject.io) as a secret store.

**Comment by anubhavmishra** [comment]
@yaron2 can you help me test the secret store by giving me an example like [this](https://github.com/dapr/docs/blob/master/concepts/components/secrets.md#examples) one?

I am building the Dapr project by following these instructions:

```bash
DEBUG=1 make build
```

This creates a binary in `dist/darwin_amd64/debug`

```bash
mkdir -p dist/darwin_amd64/debug/components
```

I am defining the secretstore component using the following configuration.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.hashicorp.vault
  metadata:
  - name: vaultAddr
    value: http://127.0.0.1:8200
  - name: vaultTokenMountPath
    value: /tmp/.vault-token
  - name: skipVerify
    value: true
```

I am able to register the secretstore when I run `daprd` but I can't use the API to retrieve secrets. 

```bash
./daprd --dapr-id vaulttest --placement-address localhost:50005
INFO[0000] starting Dapr Runtime -- version edge -- commit b019bfa-dirty
INFO[0000] log level set to: info
INFO[0000] standalone mode configured
INFO[0000] dapr id: vaulttest
INFO[0000] loaded component secretstore (secretstores.hashicorp.vault)
INFO[0000] loaded component statestore (state.consul)
WARN[0000] failed to init input bindings: app channel not initialized
INFO[0000] actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s
INFO[0000] actors: starting connection attempt to placement service at localhost:50005
INFO[0000] http server is running on port 3500
INFO[0000] gRPC server is running on port 50001
INFO[0000] local service entry announced
INFO[0000] dapr initialized. Status: Running. Init Elapsed 4.702594ms
INFO[0000] actors: established connection to placement service at localhost:50005
INFO[0000] actors: placement order received: lock
INFO[0000] actors: placement order received: update
INFO[0000] actors: placement tables updated
INFO[0000] actors: placement order received: unlock
```

Can you provide me an example of how one would go about registering a secret store using a component and how one would test retrieval of secrets?

**Comment by anubhavmishra** [comment]
Also, my HashiCorp Vault implementation is [here](https://github.com/anubhavmishra/components-contrib/commit/fbc985c29a6c737d54fcb3e46fb744dcefc9e0f6#diff-3552039d6a28e41ef6db7de38f17e07e). Hopefully, that helps!

**Comment by anubhavmishra** [comment]
I found an example for Azure KeyVault here: https://github.com/dapr/docs/blob/master/howto/setup-secret-store/azure-keyvault.md

**Comment by youngbupark** [comment]
@anubhavmishra Thanks for your contribution! 

> I found an example for Azure KeyVault here: https://github.com/dapr/docs/blob/master/howto/setup-secret-store/azure-keyvault.md

Here's an example to use secret from hashicorp vault in redis component.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: hashicorp_vault
spec:
  type: secretstores.hashicorp.vault
  metadata:
  - name: vaultAddr
    value: http://127.0.0.1:8200
  - name: vaultTokenMountPath
    value: /tmp/.vault-token
  - name: skipVerify
    value: true
```

Ensure that `redisPassword` secret should be in the vault and auth.secretStore should be metadata.name value. (`hashicorp_vault`)
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: "[redis]:6379"
  - name: redisPassword
    secretKeyRef:
      name: redisPassword
auth:
    secretStore: hashicorp_vault
```

**Comment by anubhavmishra** [comment]
@youngbupark thanks for the help. I figured it out using the Azure example, it was pretty straight forward. Looking forward to submitting the PR soon! 🚀

**Comment by yaron2** [comment]
Looking forward to this PR

**Comment by gunniwho** [comment]
I have a question about vaultTokenMountPath: so given that I configure the Vault component with the vaultTokenMountPath /tmp/.vault-token like in the example above, where exactly (which pod) should the token be mounted? Thanks!

**Comment by anubhavmishra** [comment]
@gunniwho the Vault token is usually mounted in the home directory like "~/.vault-token" but you can change it to any location of your choice. Read more: https://www.vaultproject.io/docs/commands#token-helper

**Comment by gunniwho** [comment]
@anubhavmishra but wouldn't it have to be mounted in the daprd sidecar container? How would I go about getting a token in there?

**Comment by anubhavmishra** [comment]
I would expect something to perform a Vault login using the [Kubernetes Auth Method](https://www.vaultproject.io/docs/auth/kubernetes). This can be done by an init container or a sidecar. You can also do this by using the [Vault Agent]() and here is the guide: https://learn.hashicorp.com/tutorials/vault/agent-kubernetes. The secret can be mounted using a shared mount between containers that is accessible by the dapr sidecar container.

**Comment by frvasquezjaquez** [comment]
@anubhavmishra can you please provide any doc about how to create the token file? i created it in the app path, but the sidecar is not able to get that path. how could i create that file in the sidecar?
