### ISSUE TITLE
Plan to add etcd components back

### ISSUE THREAD

**Issue by skyao** [dapr/components-contrib#818]
## Describe the proposal

Last year we removed etcd components because etcd can't support the new version of grpc. As in this PR: 

https://github.com/dapr/components-contrib/pull/499

Now etcd is changed to support the latest grpc version in this master branch: 

https://github.com/etcd-io/etcd/blob/master/go.mod

```
	google.golang.org/grpc v1.36.1
```

We can plan to add etcd components back now,  and later after etcd new version is released we can do it quickly.

Seems the first thing is that we should upgrade our grpc version from v1.34 to v1.36.1.

**Comment by jiaanguo** [comment]
> ## Describe the proposal
> Last year we removed etcd components because etcd can't support the new version of grpc. As in this PR:
> 
> #499
> 
> Now etcd is changed to support the latest grpc version in this master branch:
> 
> https://github.com/etcd-io/etcd/blob/master/go.mod
> 
> ```
> 	google.golang.org/grpc v1.36.1
> ```
> 
> We can plan to add etcd components back now, and later after etcd new version is released we can do it quickly.
> 
> Seems the first thing is that we should upgrade our grpc version from v1.34 to v1.36.1.

Hello, May I ask how that adding back procedure goes? When will Etcd support available again? That will be great help, many thanks!
