### ISSUE TITLE
 Can't use Redis cluster as statestore

### ISSUE THREAD

**Issue by abogdanov37** [dapr/components-contrib#851]
## Expected Behavior

I expect that Dapr can work with the Redis cluster as it works with a single instance

## Actual Behavior

Now I get an error

```
Unhandled exception. Dapr.DaprException: State operation failed: the Dapr endpoint indicated a failure. See InnerException for details. ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="fail to get statehistory from state store statestore: MOVED 7470 10.30.28.237:6379") at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken) --- End of inner exception stack trace --- at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken) at Zyfra.Cm.Dapr.StateStore.Provider.Core.DaprStateStoreProvider.GetHistoryState() at Zyfra.Cm.History.Manager.Core.HistoryManager.Up() at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state) at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() at System.Threading.ThreadPoolWorkQueue.Dispatch() at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

## Steps to Reproduce the Problem

Create the Redis cluster with 6 nodes. For example use bitnami the Redis helm chart https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster

## Release Note

RELEASE NOTE:  **FIX**  Can't use Redis cluster as statestore

**Comment by abogdanov37** [comment]
I find some time to investigate the issue and found that current behavior is normal. To add the ability to work with the Redis cluster we need to use another Redis client type. See https://github.com/go-redis/redis/blob/master/cluster.go#L24. I suggest add new state store named `redis-cluster`.

**Comment by abogdanov37** [comment]
How can I change the label? After investigating I understand that this is improvment

**Comment by yaron2** [comment]
> How can I change the label? After investigating I understand that this is improvment

Done

**Comment by abogdanov37** [comment]
> > How can I change the label? After investigating I understand that this is improvment
> 
> Done

Thank you!

**Comment by abogdanov37** [comment]
> > How can I change the label? After investigating I understand that this is improvement
> 
> Done

Thank you!
