### ISSUE TITLE
Redis subscriber stops receiving messages after TCP reset.

### ISSUE THREAD

**Issue by wcs1only** [dapr/components-contrib#852]
## Expected Behavior

If a TCP connection goes away without the redis subscriber receiving a TCP FIN or RST, the subscriber should timeout and reconnect.

## Actual Behavior

There is an issue with our E2E tests on Windows that is causing TCP connections to be dropped with a RST whenever a public IP address is added to a service. We have yet to root cause why this is happening, but this is definitely a case that Dapr should handle gracefully.

Here is how the Dapr redis subscriber component operates today:

|redis|  message direction|                           Dapr|
| -- | -- |--|
|                                    |<-| xreadgroup block:0 (forever)|
|waits for message | | |
|new message | -> | process message |
|                                  | <- | xack|

If some intermediary (like a stateful firewall or LB) looses context on the connection while Dapr is blocked, Dapr may hang indefinitely not realizing that the connection has gone away. 

|redis|  message direction|                           Dapr|
| -- | -- |--|
|                                    |<-| xreadgroup block:0 (forever)|
|waits for message | | |
|new message | -> <- X RST | Does not get message or RST |
| connection closed| | Connection still open, waiting for xreadgroup response |

Eventually, TCP keepalive will come along and detect that connection is actually gone vs just waiting for data and surface a connection close to Dapr. After which Dapr will recover. This can take several minutes or even hours depending on OS behavior.

## Steps to Reproduce the Problem

This can be reproduced using any simple pubsub setup (like the pubsub quickstart). All you need to do is trigger a connection
RST temporarily. 

Assuming your redis server is running on Linux, all you have to do is drop outbound traffic with a RST for 5s or so:
```
sudo iptables -I OUTPUT -p tcp --sport 6379 -j REJECT --reject-with tcp-reset && sleep 5 && sudo iptables -D OUTPUT -p tcp --sport 6379 -j REJECT --reject-with tcp-reset
```

## Release Note

RELEASE NOTE: **FIX** Redis subscriber should not block infinitely on XReadGroup

**Comment by rtrindvg** [comment]
Are you sure this bug is fixed? I am using 1.6.0 and as reported on issue https://github.com/dapr/dapr/issues/4302, the problem still seems to exist.

Since my redis lives inside the same k8s cluster as daprd, it may be recreated with another IP when restarted. I am not sure if this changes anything related to this fix.

**Comment by yaron2** [comment]
@rtrindvg we will be working on better handling connection failures for all components in a generic manner, so when components disconnect from the underlying implementation `daprd` will try to reconnect for a while and if it can't, will panic the process (and cause a container restart on k8s).

**Comment by MaticDiba** [comment]
Hi @yaron2 is there any update regarding this issue? We are experiencing the same as @rtrindvg on k8s.

**Comment by kalprajkakani** [comment]
Facing this issues in DAPR version 1.8.4.

**Comment by cciobanu98** [comment]
Facing these issues in DAPR version 1.9.4

**Comment by worldofgeese** [comment]
Hi @yaron2 another +1 here. Are there any workarounds you can suggest to avoid running into this?
