### ISSUE TITLE
Dapr CLI commands take ~5 seconds to execute

### ISSUE THREAD

**Issue by jkotalik** [dapr/components-contrib#865]
I'm trying to run dapr commands locally, and every command (even `dapr --version` and `dapr`) take 5 seconds to execute. 

https://user-images.githubusercontent.com/8302101/117346362-823a1180-ae5c-11eb-8bf6-825f221d54c7.mp4

## Steps to Reproduce the Problem

I can't repro this on WSL2, only on Windows. I tried uninstalling and reinstalling dapr which didn't help.

## Versions

CLI version: 1.1.0
Runtime version: 1.1.2

**Comment by wcs1only** [comment]
With aerospike v2.7.0:
```
$ time dapr --version
CLI version: edge
Runtime version: 1.1.2

real    0m8.827s
user    0m0.000s
sys     0m0.015s
```

With aerospike v4.5.0:
```
$ time dapr --version
CLI version: edge
Runtime version: edge

real    0m0.531s
user    0m0.000s
sys     0m0.046s

```
