### ISSUE TITLE
Add NATS JetStream pubsub component

### ISSUE THREAD

**Issue by ipfans** [dapr/components-contrib#870]
## Describe the proposal

Add support for [NATS Stream](https://docs.nats.io/jetstream/jetstream) (NATS new generation persistence engine) as a pubsub component in Dapr. It's more powerful than NAST Streaming and add more functional to NATS.

**Comment by rumblefrog** [comment]
Also, note that Nats Streaming is being deprecated, users are to moved to Jetstream: https://github.com/nats-io/nats-streaming-server#warning--deprecation-notice-warning
