### ISSUE TITLE
Move retry and config packages to dapr/kit for reuse

### ISSUE THREAD

**Issue by pkedy** [dapr/components-contrib#893]
## Describe the proposal

The `retry` and `config` package now seem to have some traction. In order to leverage these patterns in dapr/dapr, we need to move these packages to `dapr/kit` and update the imports in this repo accordingly.

**Comment by daixiang0** [comment]
Does it mean we need remove `internal/retry` and `internal/config` as well?

If so and possible, I would like to do it.
