### ISSUE TITLE
Azure EventHubs binding: Remove "close by interrupt signal" logic

### ISSUE THREAD

**Issue by pkedy** [dapr/components-contrib#894]
## Expected Behavior

This component has a client to cleanup.  The Dapr runtime now calls `Close() error` on any component that implements `io.Closer`. Logic to cleanup should be moved there.

## Actual Behavior

Currently it uses a signal channel to wait to close itself.

RELEASE NOTE: **FIX** Azure EventHubs binding implements `Close()` for cleanup

**Comment by CodeMonkeyLeet** [comment]
Closing this issue as the addition and the move of logic into `Close() error` is handled by #1093.

Using https://github.com/dapr/dapr/issues/3555 to track the broader question of replacing wait on SIGTERM with appropriate cancellation contexts.
