### ISSUE TITLE
Introduce Dependabot to automate package upgrade

### ISSUE THREAD

**Issue by daixiang0** [dapr/components-contrib#943]
## Describe the proposal

Introduce [dependabot](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-dependabot-security-updates) to  automate package upgrade.

It would reduce upgrade by hand like #942 

If accepted, I would like to do this.

**Comment by CodeMonkeyLeet** [comment]
It's a good idea, and dependabot should be [enabled by default](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates#supported-repositories) already, but it looks like the Go package ecosystem is [not included by default](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph#supported-package-ecosystems) and [needs to be enabled](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem)

**Comment by daixiang0** [comment]
Still available.

**Comment by CodeMonkeyLeet** [comment]
@artursouza might be something to track for 1.5 ... just needs a bit of investigation and config perhaps.
