### ISSUE TITLE
Certify Azure Table Storage as Stable in state store

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#950]
## Describe the feature
Certify Azure Table Storage as GA in state store

## Release Note

RELEASE NOTE:

**Comment by tanvigour** [comment]
## Test Plan Draft

### Existing tests (Conformance test)
- Test for mixed data types
- Test for init
- Test for ping
- Test for operations  :  get , set delete, bulkdete, transaction, etag, first-write

###  Proposed tests 
-  Test for existing  table name vs new table handling (functional)
-  Test for authentication using Azure auth layer : https://github.com/dapr/components-contrib/issues/1103
-  Test for consistency in behavior of Partition and Row key with non-Dapr consumers (conformance)
-  Test for data persistence : write with dapr and read natively should have consistent data (data validation) , vice versa?

**Comment by berndverst** [comment]
@tanvigour @artursouza important update:

This component should switch to the new / current Track 2 SDK for Table Storage.

This SDK supports BOTH the Azure Table Storage (as part of a Storage Container) as well as the Cosmos DB Table API.

https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/data/aztables

IMO we should not GA this component using the existing outdated SDK

**Comment by berndverst** [comment]
From recent Discord activity is clear that customers expect this component to connect to **both** Azure Blobstorage Tables as well as Cosmos DB Tables API. That can be facilitated by using the new Track 2 SDK and exposing the relevant options as component metadata.

Tracking the Track 2 migration work separately at https://github.com/dapr/components-contrib/issues/1528

**Comment by tanvigour** [comment]
> From recent Discord activity is clear that customers expect this component to connect to **both** Azure Blobstorage Tables as well as Cosmos DB Tables API. That can be facilitated by using the new Track 2 SDK and exposing the relevant options as component metadata.
> 
> Tracking the Track 2 migration work separately at #1528

Do we have an estimate  on migration of table storage state store to track 2 sdk?

**Comment by tanvigour** [comment]
## Test Plan Draft

### Proposed tests (Certification)

- Test handing the  "TableName" for existing vs new table 
   -  Create a table "ExistingTable" and specify that in the metadata tablename field
   -  Confirm "ExistingTable" is being used as table for azure table storage
   -  Don't create a table before hand and specify name "NewTable" in metadata field
   - Confirm new table named "NewTable" is created and used by Azure Table storage

- Test for data persistence
   - Write data using Dapr
   - Read data natively
   - Confirm the persistence in data

- Test for consistency of keys with non-Dapr consumers
   - Confirm Partition key and row key have consistent behavior

- Test reconnection/retries
   - Interrupt the network 
   - Confirm reconnection happens
   
- Test for authentication using Azure Auth layer (available in sdk 2)

**Comment by tanvigour** [comment]
@artursouza  Please review the test plan when you get a chance. Thanks!

**Comment by mukundansundar** [comment]
@tanvigour 
- Add tests for concurrency 
- Add tests for etag support 
- Test all CRUD operations ... as in add in tests for update and delete as well 
- Add tests for the negative scenarios as well, like deleting or reading non-existent keys etc.
