### ISSUE TITLE
Certify MQTT as GA in pubsub

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#952]
## Describe the feature
Certify MQTT as GA in pubsub

## Release Note

RELEASE NOTE:

**Comment by shivamkm07** [comment]
# MQTT certifcation testing

This project aims to test the MQTT Pub/Sub component under various conditions.

## Test plan

### Basic Test

* Bring up a MQTT cluster
* Start 1 sidecar/application(App1)
    * Publishes 1000+ unique messages 
    * App: Simulate periodic errors
    * Component: Retries on error
    * App: Observes successful messages
    * Test: Confirms that all expected messages were received (in order) 

### Multiple Publishers-Subscribers

* Start second sidecar/application(App2)
    * Each of the publishers publish a fixed number of messages to the topic
    * Test: Confirms that both applications receive all published messages

### Persistent Session

* Start a constant flow of publishing and subscribing
    * Start a sidecar/application with persistent session
    * Stop the sidecar, wait for sometime and re-connect
    * Test: Confirms that all published messages were received and no messages were lost

### Network Test
* Simulate network interruption
    * Test: Begins trying to reconnect & publish
    * Component: Begins trying to reconnect & re-subscribe

**Comment by shivamkm07** [comment]
MQTT messages are still always Acked even if handler returns an error. But it seemingly requires change in paho.mqtt.golang lib and there already is an issue opened potentially addressing this.

See #1234 for more details.

**Comment by mukundansundar** [comment]
The certification plan looks good to me.

> MQTT messages are still always Acked even if handler returns an error. But it seemingly requires change in paho.mqtt.golang lib and there already is an issue opened potentially addressing this.
> 
> See #1234 for more details.

With this in mind ... I am not comfortable with certifying this as Stable without a fix or a workaround for this as this basically breaks Dapr PubSub API conformance at that point.

**Comment by artursouza** [comment]
Please, add a new network scenario where the publisher is also validated that can recover from a reconnection.

**Comment by artursouza** [comment]
> MQTT messages are still always Acked even if handler returns an error. But it seemingly requires change in paho.mqtt.golang lib and there already is an issue opened potentially addressing this.
> 
> See #1234 for more details.

Can this be addressed in the dependency too? I am OK if we cut a PR against the dependency's repository.

**Comment by artursouza** [comment]
Please, compare this test with the plan from RabbitMQ and Kafka. You might take more scenarios from those here.

**Comment by shivamkm07** [comment]
> Please, add a new network scenario where the publisher is also validated that can recover from a reconnection.

Updated test plan accordingly

**Comment by XavierGeerinck** [comment]
Question: will MQTT v5 be supported? According to the implementation (https://github.com/dapr/components-contrib/blob/29848e1ff68a56bdf0272513e3af9c925ab56535/pubsub/mqtt/mqtt.go#L286) Dapr uses https://github.com/eclipse/paho.mqtt.golang while as this repository states that for MQTT v5 this library should be used: https://github.com/eclipse/paho.golang

P.S. MQTT v5 is needed for Azure IoT Hub Broker MQTT v5 support :) (@artursouza) main issue here is that username:password is not used but it requires SAS token setting... (more info: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-5#connection-lifecycle & https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-5#authentication)

**Comment by yaron2** [comment]
> Question: will MQTT v5 be supported? According to the implementation (
> 
> https://github.com/dapr/components-contrib/blob/29848e1ff68a56bdf0272513e3af9c925ab56535/pubsub/mqtt/mqtt.go#L286
> 
> ) Dapr uses https://github.com/eclipse/paho.mqtt.golang while as this repository states that for MQTT v5 this library should be used: https://github.com/eclipse/paho.golang
> P.S. MQTT v5 is needed for Azure IoT Hub Broker MQTT v5 support :) (@artursouza) main issue here is that username:password is not used but it requires SAS token setting... (more info: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-5#connection-lifecycle & https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-5#authentication)

We should make sure v5 is used, based on what I've seen.

**Comment by rabollin** [comment]
> > Question: will MQTT v5 be supported? According to the implementation (
> > https://github.com/dapr/components-contrib/blob/29848e1ff68a56bdf0272513e3af9c925ab56535/pubsub/mqtt/mqtt.go#L286
> > 
> > ) Dapr uses https://github.com/eclipse/paho.mqtt.golang while as this repository states that for MQTT v5 this library should be used: https://github.com/eclipse/paho.golang
> > P.S. MQTT v5 is needed for Azure IoT Hub Broker MQTT v5 support :) (@artursouza) main issue here is that username:password is not used but it requires SAS token setting... (more info: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-5#connection-lifecycle & https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-5#authentication)
> 
> We should make sure v5 is used, based on what I've seen.

MQTT v5 support is being assessed and in consideration as it has multiple enhancements over the current version.

**Comment by shivamkm07** [comment]
@XavierGeerinck @yaron2 [MQTT v5](https://github.com/eclipse/paho.golang/releases) is still in beta release, so it can't be used till it gets to stable.
As per latest discussion with @artursouza , the plan is to get the current mqtt component to GA using MQTT3 and once MQTT v5 gets to stable, we can either upgrade thereafter or have a different component supporting v5. Let me know if it's good.

**Comment by XavierGeerinck** [comment]
Azure IoT Hub is going with MQTT v5 as well so I think Dapr should follow. But I would check this off with the Microsoft IoT Hub team? in the end they will benefit from this.

**Comment by shivamkm07** [comment]
Seemingly MQTT doesn't guarantee ordering of messages(https://stackoverflow.com/questions/30955110/is-message-order-preserved-in-mqtt-messages) and so removed order part from test plan. Also verified the same while running tests.
