### ISSUE TITLE
Certification tests for RabbitMQ pubsub

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#954]
## Describe the feature
Certify RabbitMQ as GA in pubsub

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
Issue #826 must be fixed for this component to be GA-ed.

**Comment by dmitsh** [comment]
Proposed plan:

Run pubsub with 2 pods, each for a distinct consumerID.

[test 1]: consistency
 - verify number of published messages equals to number of received messages per consumerID
 - verify that consumers don't receive messages from unsubscribed topics

[test 2]: scaling
 - scale up one of the pubsub pods (one of the consumerIDs)
 - verify consistency (as in test 1)
 
[test 3]: reconnect
- simulate network interrupt
- verify the number of pub/sub messages keeps growing
- verify consistency (as in test 1)

**Comment by artursouza** [comment]
Reopening since there were new issues uncovered during testing.

**Comment by berndverst** [comment]
@dmitsh can this be closed now since 1.5.1 release?

**Comment by dmitsh** [comment]
> @dmitsh can this be closed now since 1.5.1 release?

I think we will close it in 1.6.
There were issues #1371 and #1372 that I've addressed, but the fix for them is not in 1.5.1

**Comment by artursouza** [comment]
Changed scope to certification tests as claiming component to stable will now require a "grace period" of 1 release.
