### ISSUE TITLE
Certification tests for Kafka binding

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#955]
## Describe the feature
Certify Kafka as GA in input/output binding

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
Fix #1006 should be a pre-req for this component to be GA-ed.

**Comment by artursouza** [comment]
Changed scope to certification tests as claiming component to stable will now require a "grace period" of 1 release.

**Comment by skyao** [comment]
PR done, please help to review @artursouza
