### ISSUE TITLE
Certification tests for Azure Blob Storage binding

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#956]
## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
This component is in good shape. All conformance tests pass and the authentication logic has already been updated to support all Azure auth mechanisms.

Will revisit this once we have determined our definition of GA.

**Comment by artursouza** [comment]
Changed scope to certification tests as claiming component to stable will now require a "grace period" of 1 release.
