### ISSUE TITLE
Certify Azure CosmosDB as GA in output binding

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#958]
## Describe the feature
Certify Azure CosmosDB as GA in output binding

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment]
## Component test plan

- [ ] Conformance tests passing
- [ ] Integration / E2E test verifying data sent to output binding is written to Cosmos DB
- [ ] Integration test -- expected failure for invalid partition key specified, or partition key missing from document
Possibly
- [ ] Graceful handling of connection resets / interruption
