### ISSUE TITLE
Certification tests for Azure Event Hubs binding

### ISSUE THREAD

**Issue by artursouza** [dapr/components-contrib#960]
## Describe the feature
Certify Azure Event Hubs as GA in input/output binding

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
The IoT hub from "integration test" needs to move to conformance test because the "integration tests" are not officially supported in a GitHub pipelines and it overlaps in objective with our certification tests.

Instead of retry, let's validate reconnection. Add a scenario where the connection to EvenHubs is stopped for a few seconds and validate that publish and subscribe continues to work after connection is recovered.

For AAD authentication, validate one of the authentication options is fine but verify that the code is using the "shared" code for Azure auth.

**Comment by tanvigour** [comment]
@artursouza  Added a scenario covering reconnection, auth testing and IoT migration from integration. Does this look good?

**Comment by berndverst** [comment]
@artursouza FYI -- this component cannot be certified until pending open issues are resolved, especially https://github.com/dapr/components-contrib/issues/1598

It would be very helpful to have a certification test that verifies this very situation. There may be required updates to this component as a result.
