### ISSUE TITLE
Azure EventHubs pubsub component doesn't handle topics correctly

### ISSUE THREAD

**Issue by ecaisse** [dapr/components-contrib#964]
## Expected Behavior
With Azure EventHubs as a pubsub component, when publishing an event with Dapr to a specific topic, the event should be sent to the endpoint configured for that topic as configured via the /dapr/subscribe endpoint.

## Actual Behavior
Events can be sent to the wrong endpoint, resulting in the wrong handler being called. When combined with the .NET SDK, the wrong controller is called without raising errors despite the failed deserialization.

Tested with Dapr standalone on Windows 10.

## Steps to Reproduce the Problem
Code sample: [DaprEventHub.zip](https://github.com/dapr/components-contrib/files/6669801/DaprEventHub.zip)

1. In the Azure Portal, create an Event hub and storage container as per the [instructions in the Dapr docs](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/#create-an-azure-event-hub)
    - Create the Event Hubs namespace in a resource group
    - In the Event Hubs namespace, create a new Event Hub
      - In my tests, I was using 4 partitions with 1 day of retention. Capture was off.
    - In the Event Hub _overview_, add a consumer group with the ID of the app supplied to the `dapr run` command
    - In the Event Hub _shared access policies_, add a new policy with Send and Listen for claims.
2. Create a [pubsub component yaml file](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/#component-format) in the components folder (%UserProfile%\.dapr\components\ in Windows) with the connection string from the Event Hub and storage account information
3. Compile the code sample (.NET) and start the application with Dapr
    - `dapr run -a my-app --app-port 5000 --dapr-http-port 55502 --dapr-grpc-port 55501 --log-level debug dotnet run`
4. In the browser (or using curl/iwr), access http://localhost:5000/api/topic1 around 10 times to generate events
    - All events using that endpoint will be generated with a "Name" property of "Topic1"
5. In the console, you should see the event handlers being triggered. Note that they should all be handled by Topic1Controller, but some of them are not.
    - This issue is intermittent, there is a chance that all events will be properly handled by Topic1Controller. If that is the case, in the components yaml file, change the storageContainerName to another name and restart the application. This will replay all events generated at step 4.

Sample output: 
![image](https://user-images.githubusercontent.com/1854279/122391584-2d9cb280-cf41-11eb-8dcf-d049a5208484.png)

## Potential cause
In the [Subscribe method](https://github.com/dapr/components-contrib/blob/1ac87d93c5ec816bd130215ec4d3dd6bbaefc29e/pubsub/azure/eventhubs/eventhubs.go#L126) for the Azure Event Hubs pubsub component, a processor is created but has no knowledge of the topic for which it should be subscribed.

In the sample, we subscribe to 2 topics, "topic1" and "topic2". However, we have created 2 processors for the events that are identical except for the Topic property of `pubsub.NewMessage`. There is no guarantee that the event for Topic1 will be handled by the processor that was created for Topic1.

When looking at other pubsub components like [rabbitmq](https://github.com/dapr/components-contrib/blob/1ac87d93c5ec816bd130215ec4d3dd6bbaefc29e/pubsub/azure/eventhubs/eventhubs.go#L126) or [natsstreaming](https://github.com/dapr/components-contrib/blob/1ac87d93c5ec816bd130215ec4d3dd6bbaefc29e/pubsub/azure/eventhubs/eventhubs.go#L126), handlers are registered by topic. Azure Event Hubs does not seem to have that concept when registering handlers. The only solution I can see is for the component to check the received event's topic before executing the handler.

## Release Note
RELEASE NOTE: **FIX** Azure Event Hub pubsub component properly handles topics.

**Comment by CodeMonkeyLeet** [comment]
@ecaisse Thanks for the issue, I think it illustrates one of the challenges when trying to abstract over components that have different internal semantics. As you observe, an Azure Event Hub doesn't have an internal notion of a topic, because the expectation is that [each Event Hub represents a topic](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview#kafka-and-event-hub-conceptual-mapping) so in the use case, I think the expected configuration is to have two Event Hubs under the same namespace and treat each as a separate topic.

@yaron2 Is this something that Dapr pubsub should overlay as an abstraction on top of Event Hubs?

**Comment by ecaisse** [comment]
Personally, I think that Dapr should adds the concept of topics on top of an Event Hub (from Event Hubs perspective, it's like a "sub-topic" handled by the application) since one of the goal of using Dapr is the ability to switch components without change in functionality.

If, for whatever reason it's decided to not implement the fix, the component should be deprecated and the docs should recommend using the Azure Event Hubs binding component.

**Comment by ecaisse** [comment]
I see that https://github.com/dapr/components-contrib/issues/951 is planned for the 1.4 release, however, I don't think this component should be GA certified until this current issue has been looked into, as no matter which solution is chosen, it will most likely introduce breaking changes to the component.

**Comment by berndverst** [comment]
@ecaisse both @CodeMonkeyLeet and I have spent significant time investigating ways to support topics in EventHubs -- even going as far as treating individual Event Hubs as topics under one shared Event Hubs namespace. This not only requires a very complex implementation that may be hard to maintain but also requires a lot of additional Azure resources to be provisioned by someone wishing to use Event Hubs for PubSub. The user experience would be terrible and there is too much risk for operational errors. We would not be able to GA that component in good conscience.

Unfortunately we have decided that we must deprecate the Event Hubs PubSub component as it is not possible to handle Dapr's PubSub paradigm correctly given how Event Hubs is designed.

The following issue has been updated to now track the deprecation work:
https://github.com/dapr/components-contrib/issues/951

**Comment by tanvigour** [comment]
Should this be closed?

**Comment by berndverst** [comment]
@tanvigour let's close this when the deprecation is announced in the 1.4 release notes and docs.

**Comment by artursouza** [comment]
This will be fixed as part of #951
