### ISSUE TITLE
Added confluent kafka support for alibaba cloud kafka service

### ISSUE THREAD

**Issue by cshi0** [dapr/components-contrib#968]
## Describe the proposal
The current kafka component is implemented by using sarama. However, it does not support the legacy versions used by alibaba cloud kafka service, and it is not tested against alibaba cloud's kafka service. Therefore, a new component is implemented by using confluent kafka sdk to support the kafka service on alibaba cloud.

Ref: dapr/docs#1582

**Comment by cshi0** [comment]
@pkedy The version I was testing on is 2.2, and I cannot connect to brokers with ssl enabled. I have contacted the kafka team at Alibaba cloud, and they told me that sarama has compatibility problem with kafka 2.2. 

Or maybe the configuration of my client is incorrect, so I attached my testing codes here. Please tell me how I can fix the configuration to enable ssl. The error given is ` client has run out of available brokers to talk to (Is your cluster reachable?) `. It I can connect to the brokers with confluent kafka sdk with the same settings. Thank you!

```golang
package main

import (
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"io/ioutil"
	"os"
	"strings"

	"github.com/Shopify/sarama"
)

type KafkaConsumerConfig struct {
	Brokers  []string
	Topic    string
	consumer sarama.Consumer
	client   sarama.Client
}

func main() {
	config := KafkaConsumerConfig{}
	config.Brokers = strings.Split(os.Getenv("KAFKA_ENDPOINTS"), ",")
	config.Topic = "dapr_test"

	consumerConfig := sarama.NewConfig()
	consumerConfig.Version = sarama.V2_2_0_0

	consumerConfig.Net.SASL.User = os.Getenv("KAFKA_SASL_USERNAME")
	consumerConfig.Net.SASL.Password = os.Getenv("KAFKA_SASL_PASSWORD")
	consumerConfig.Net.SASL.Handshake = true
	consumerConfig.Net.SASL.Enable = true
	consumerConfig.Net.SASL.Mechanism = sarama.SASLTypePlaintext

	consumerConfig.Net.TLS.Enable = true

	caCertPool := x509.NewCertPool()

	b, _ := ioutil.ReadFile(os.Getenv("KAFKA_CA_LOCATION"))
	caCertPool.AppendCertsFromPEM(b)

	tlsConfig := &tls.Config{
		RootCAs:    caCertPool,
		ClientAuth: tls.RequestClientCert,
	}
	consumerConfig.Net.TLS.Config = tlsConfig

	var err error
	config.client, err = sarama.NewClient(config.Brokers, consumerConfig)
	if err != nil {
		fmt.Println("Unable to create kafka client " + err.Error())
		return
	}

	config.consumer, err = sarama.NewConsumerFromClient(config.client)
	if err != nil {
		fmt.Println("Unable to create new kafka consumer", err, config.client)
		return
	}

	partitions, err := config.client.Partitions(config.Topic)

	if err != nil {
		fmt.Println("Unable to fetch partition IDs for the topic", err, config.client, config.Topic)
		return
	}

	fmt.Println("Partitions:", partitions)

	topics, err := config.client.Topics()
	if err != nil {
		fmt.Println("Unable to fetch topics", err, config.client)
		return
	}

	fmt.Println("Topics:", topics)

}
```

**Comment by cshi0** [comment]
The above code works when ` InsecureSkipVerify` in the tls.config is set to true, so I guess it is the problem with the ssl.

**Comment by cshi0** [comment]
It turns out that the problem might be associated with the ca certificate, and I am contacting the kafka team at Alibaba Cloud.

**Comment by cshi0** [comment]
@pkedy Hi！After talking with the kakfa team, they told me that no matter whether the certificate is valid or not, they are going to force their consumers to use confluent kafka sdk instead of sarama because they have experienced the situation that some clients are not able to consume messages after upgrading. So, it seem I cannot work on the current sarama component for supporting Alibaba cloud's kafka service.

**Comment by pkedy** [comment]
@cshi0 Thanks for the update! That sounds unfortunate. Were the clients not able to consume messages after upgrading Sarama or when Alibaba updated their Kafka service? I'd like to understand this better because like I said, using the C wrapper would require CGO and I'm not sure we want to make that leap. It might be that the component using confluent's library is not included in the `daprd` build and you would need to do a custom build/container to include it.

While I'd really like to see Sarama work, another alternative that does not require CGO is https://github.com/segmentio/kafka-go. Have you looked at that?

I'm cc'ing a few Abibaba people in case they have more information.
/cc @skyao @daixiang0

**Comment by daixiang0** [comment]
@pkedy thanks for cc. I would like to accept confluent kafka into dapr, confluent kafka is a well-used kafka version. It would be perfect if its lib is pure go implement. If not, maybe a plugin(not build as default) is a choice. Also, should we consider make kafka interface more common for more kafka client?

btw, I am from Intel.

**Comment by daixiang0** [comment]
Still available.

**Comment by greenie-msft** [comment]
@artursouza , dapr-bot closed this PR due to it being stale. There is still a docs issue/pr open for it. Should this be reopened?

**Comment by artursouza** [comment]
@pkedy @yaron2 do we want to allow CGO in dapr?

**Comment by greenie-msft** [comment]
@pkedy @yaron2 @artursouza  pinging again. Are we going to close this PR? We have a associated docs PR that's very out of date.

**Comment by msfussell** [comment]
@artursouza @berndverst @yaron2 - Following up here on @greenie-msft comment

**Comment by berndverst** [comment]
We should close this. We do not want to allow CGO. Pluggable components will help here and allow Alibaba to provide a Confluent Kafka component.

Objections @artursouza @yaron2 ?

(We should also close https://github.com/dapr/docs/pull/1669 https://github.com/dapr/docs/issues/1582)

**Comment by artursouza** [comment]
We should close this as "won't fix" and recommend using pluggable components after 1.9 release.
