### ISSUE TITLE
Client Credentials authN & authZ is supported by all Dapr components having an Azure implementation

### ISSUE THREAD

**Issue by georgestevens99** [dapr/components-contrib#970]
At the minimum, all dapr components having an implementation as an Azure service need to support authentication and authorization to Azure via the Client Credentials flow (not on behalf of, please) which is supported for most Azure services (i.e. external services from Dapr's point of view).   This feature may also apply to dapr components that implement services provided by other non-Azure providers via the Client Credential flow, but I use only Azure herein so I am not familiar with these.

Azure Client Credential flow involves the developer registering a daprized service (which needs to use some Azure service via a dapr component) with an Azure Active Directory tenant.  This gives the service a Service Principal which has a unique ClientId, plus either a ClientSecret or the key to a Certificate.  Then the Service Principal is registered by the developer with each Azure service that the daprized service needs to access. Plus, fine grained authorization permissions are also specified at this point for the daprized service as well.  This allows the running service to obtain a Client Credential access token from Azure Active Directory, and use that token (via the dapr component) to access the external Azure resource and perform the operations on the resource that the previously set fine grained authorization allows, all via the dapr feature being requested here.

Please note that **the above scenario applies to both Managed Identities** (system assigned and user assigned) **and non-managed identities as well**.  _Managed Identities_ are Azure located services, whose AAD identities are either assigned  by Azure (system assigned) or by a developer (user assigned). A _non-managed identity_ is some service that may or may not be located on Azure which has a Service Principle (as described above).  All these types of identities have Service Principals and thus the ability to get fine grained access authorization to many different Azure resources and services.  A main difference between Managed Identities and unmanaged identities is that Managed Identities always have a certificate which is managed and renewed automatically by Azure.  Unmanaged identities require the developer to furnish either a ClientSecret or certificate, plus renew it manually as well.

Long-story-short -- If dapr can support Managed Identities to allow a daprized service to access "external" Azure services, then (probably with little or no extra work) it can also support unmanaged identities!  

Here is the business value:  

1. Unmanaged identities are important to support since they allow services located on-prem or on-edge to use Azure AD as an identity provider and thus fully participate in the first class authentication Azure AD provides, adding another level to the recommended defense-in-depth strategy.  Note that this allows the use of Dapr to propagate far beyond the cloud and Kubernetes clusters, increasing the breadth of adoption of Dapr.

2. The Client Credentials flow via Azure Active Directory also allows a service to utilize the fine grained access authorization provided by most Azure  services.  Such fine grained access permissions often offer a radically smaller attack surface, compared to the previous generation of Shared Access Signatures. 

3.  Microsoft recommends that Shared Access Signatures now be used only if one wants permissions to automatically expire after a fairly short period of time.    For most services Microsoft now recommends that they use Service Principles to authenticate instead of Shared Access Signature, and also to use fine grained authorization that is available via Azure Active Directory for each Azure Service.  **Therefore, the key business value here is having the capability for daprized services to use Azure Best Practices for security, thereby reaping the great increase in protection they provide.**

For example, a daprized service needs to read from an Azure Service Bus Topic then save the result in an Azure Storage Blob.  In this case the daprized service needs a Service Principal obtained from registering the service with Azure Active Directory, or by getting it from a Managed Identity.  Then the developer needs to register the Service Principal with the Azure Service Bus Topic and Azure Storage Blob they intend to use so as to specify that the Service Principal has only permission to read from the Topic and write to the Blob.  

Then the developer will provide the information required to obtain a Client Credentials flow access token from Azure AD while the service is running to the Dapr Pubsub and State components it will use.  Perhaps this can be done via something like a SecretRef, call it an AccessTokenRef.  In other words, put the info required to obtain an access token in a AccessToken component that is referenced by both the pubsub and state components.  This is like a Secret in concept.  Note that an AccessToken component info (some of which is highly confidential) should also be stored in a SecretStore (most likely a Key Vault).

Once all the information is in the proper places the daprized service can run and access the Topic and Blob via dapr components as necessary without having to do anything in the developer-written-code.  However, please note that caching access tokens is absolutely necessary to provide excellent performance.  The Azure SDK provides "automatic" (or at least in a number of secnarios) access token caching.  Please see Azure Identity client library for .NET - Version 1.4.0 at https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme for details on the most recent capabilities of AAD client SDK.  The dapr components need to implement token caching so as to make it transparent to the developer.

Note that another acceptable implementation would be to have a Dapr Access Token Utility service (app) that runs with its own Dapr sidecar, and which is utilized by all other dapr instances in a Dapr Mesh to retrieve the security access tokens their services (apps) need.  This further increases the separation of concerns by not mixing security token code with dapr component code.  Such a token utility might, in concept, be somewhat like the existing Actor Placement Service or Zipkin.  

This approach could also greatly leverage the use of existing cloud service provider SDKs in developing the code for the Access Token Utility and shortening development time.  This approach could also easily lead to using existing Security Token service code that is now in use in legacy scenarios being used in daprized services, thus providing the ability to bring some legacy services into the Dapr Mesh.  In short, such an approach would allow developer written Access Token Utility services to be written.  Such things may need a separate utility-contrib repository.

Thanks.  Please let me know if you have any  questions.

For background on this, plus links to related Microsoft documentation please see https://github.com/dapr/components-contrib/issues/938.

@artursouza -- This is the result of #938. Thanks for your assistance

## Release Note

RELEASE NOTE:

**Comment by ItalyPaleAle** [comment]
@georgestevens99 I agree with you, and had the same need: essentially, being able to use Azure AD and RBAC to authenticate the app rather than relying on "access/master keys", connection strings, etc.

I have stated some work on a "common Azure authentication logic" in the PR linked above. There are 12 components to update and I only have updated 2 so far, but if maintainers agree with the base approach I can look into the others (or if someone wants to help, that would be great!)

**Comment by georgestevens99** [comment]
Ale -- That is good to hear that you have the same need and are making progress on implementing it!  Thanks for your interest and support.  I may be available to write and run integration tests on some of your modifications once you get maintainer approval, if that would help you.

**Comment by artursouza** [comment]
Thanks @ItalyPaleAle. We are following it.

**Comment by berndverst** [comment]
FWIW This is also necessary to truly GA the Azure components in my opinion. I looked at @ItalyPaleAle's PR -- the switch of components to the common auth logic can be done gradually in the future -- better to incrementally get things out there. The approach looks good to me.

Note that some Azure services will still require SAS tokens / connection strings as no alternatives exists for these services.
